### ISSUE TITLE
环境安装问题

### ISSUE THREAD

**Issue by liushui0712** [neolee/wop-community#1]
![image](https://user-images.githubusercontent.com/54479298/85250171-69b14a80-b488-11ea-9c2e-99238746dc72.png)
老师好，请问这种情况应该如何解决啊，试了好多次，也可以科学上网，就是不行呢，。。。

**Comment by neolee** [comment]
用浏览器试试能否打开 `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` 这个地址？如果不能就是网络问题，可以考虑换个网络或者用网络代理试试。

如果浏览器可以打开上面地址（可能因为你浏览器用了科学上网），那么就把打开的那个页面保存为 `install.sh`，放在你的 Downloads 目录下，然后运行：

```shell
/bin/bash ~/Downloads/install.sh
```

或者，也可以尝试下 Homebrew 的国内镜像，比如下面这个（Homebrew 的国内镜像不少，搜索一下这类方案挺多的）：

https://gitee.com/cunkai/HomebrewCN

按照这个页面上的命令安装即可使用国内的镜像。此方法我自己没用过，如果你成功了可以反馈到这里，以后别的同学就可以放心用了。

**Comment by neolee** [comment]
另外，科学上网很多是针对浏览器的，要在命令行发挥作用需要执行一些操作，可以咨询你的服务提供者。

**Comment by liushui0712** [comment]
谢谢老师，回家后晚上11点多再试，同样的命令，流畅运行～应该就是网络问题了

**Comment by runningscott** [comment]
李老师您好，按照上面的操作运行 ‘ /bin/bash ~/Downloads/install.sh’  之后，终端反馈和我之前按照教程里的反馈一样，如图
<img width="565" alt="截屏2020-06-24 14 41 00" src="https://user-images.githubusercontent.com/42107780/85512118-1d067480-b62c-11ea-9ff4-341809e33e85.png">
<img width="558" alt="截屏2020-06-24 14 41 11" src="https://user-images.githubusercontent.com/42107780/85512221-390a1600-b62c-11ea-8ded-cd51cae0ef64.png">
<img width="573" alt="截屏2020-06-24 14 51 28" src="https://user-images.githubusercontent.com/42107780/85511030-bd5b9980-b62a-11ea-8441-d964dff9c2a2.png">
<img width="694" alt="截屏2020-06-24 15 08 27" src="https://user-images.githubusercontent.com/42107780/85512555-9dc57080-b62c-11ea-8105-0cd106925228.png">

我上网搜的解决方案和您 的也差不多，有人说多试几次，我也试了，还是一样。
是需要命令行FQ才能安装Homebrew吗？为什么可以打开它的官网却不能下载呢，只能通过命令行下载吗？国内镜像版本和这个有区别吗？
望回复，谢谢！

**Comment by runningscott** [comment]
> 谢谢老师，回家后晚上11点多再试，同样的命令，流畅运行～应该就是网络问题了

你是装的镜像版本吗？

**Comment by runningscott** [comment]
> 用浏览器试试能否打开 `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` 这个地址？如果不能就是网络问题，可以考虑换个网络或者用网络代理试试。
> 
> 如果浏览器可以打开上面地址（可能因为你浏览器用了科学上网），那么就把打开的那个页面保存为 `install.sh`，放在你的 Downloads 目录下，然后运行：
> 
> ```shell
> /bin/bash ~/Downloads/install.sh
> ```
> 
> 或者，也可以尝试下 Homebrew 的国内镜像，比如下面这个（Homebrew 的国内镜像不少，搜索一下这类方案挺多的）：
> 
> https://gitee.com/cunkai/HomebrewCN
> 
> 按照这个页面上的命令安装即可使用国内的镜像。此方法我自己没用过，如果你成功了可以反馈到这里，以后别的同学就可以放心用了。



> 李老师您好，按照上面的操作运行 ‘ /bin/bash ~/Downloads/install.sh’ 之后，终端反馈和我之前按照教程里的反馈一样，如图
> <img alt="截屏2020-06-24 14 41 00" width="565" src="https://user-images.githubusercontent.com/42107780/85512118-1d067480-b62c-11ea-9ff4-341809e33e85.png">
> <img alt="截屏2020-06-24 14 41 11" width="558" src="https://user-images.githubusercontent.com/42107780/85512221-390a1600-b62c-11ea-8ded-cd51cae0ef64.png">
> <img alt="截屏2020-06-24 14 51 28" width="573" src="https://user-images.githubusercontent.com/42107780/85511030-bd5b9980-b62a-11ea-8441-d964dff9c2a2.png">
> <img alt="截屏2020-06-24 15 08 27" width="694" src="https://user-images.githubusercontent.com/42107780/85512555-9dc57080-b62c-11ea-8105-0cd106925228.png">
> 
> 我上网搜的解决方案和您 的也差不多，有人说多试几次，我也试了，还是一样。
> 是需要命令行FQ才能安装Homebrew吗？为什么可以打开它的官网却不能下载呢，只能通过命令行下载吗？国内镜像版本和这个有区别吗？
> 望回复，谢谢！


额，没等老师回复，我已经按照您的链接安装了国内镜像版本了，应该是成功了，是不是可以直接用了？
<img width="1048" alt="截屏2020-06-24 15 23 22" src="https://user-images.githubusercontent.com/42107780/85515365-9d7aa480-b62f-11ea-92d3-af7efe9130f5.png">
<img width="989" alt="截屏2020-06-24 15 25 42" src="https://user-images.githubusercontent.com/42107780/85515375-a0759500-b62f-11ea-93fc-e6f2b67c9a0e.png">

之后想换成原版的话应该也有方法吧？

**Comment by neolee** [comment]
@runningscott 不要在别人的问题下提自己的新问题，重开一个 issue 比较好。

你这个问题是下载安装（从苹果的服务器） Xcode Command Line Tools 失败了，比较像是网络问题。

**Comment by TurtleNinja42** [comment]
> @runningscott 不要在别人的问题下提自己的新问题，重开一个 issue 比较好。
> 
> 你这个问题是下载安装（从苹果的服务器） Xcode Command Line Tools 失败了，比较像是网络问题。

抱歉，没注意，我另开一个吧

**Comment by runningscott** [comment]
> 用浏览器试试能否打开 `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` 这个地址？如果不能就是网络问题，可以考虑换个网络或者用网络代理试试。
> 
> 如果浏览器可以打开上面地址（可能因为你浏览器用了科学上网），那么就把打开的那个页面保存为 `install.sh`，放在你的 Downloads 目录下，然后运行：
> 
> ```shell
> /bin/bash ~/Downloads/install.sh
> ```
> 
> 或者，也可以尝试下 Homebrew 的国内镜像，比如下面这个（Homebrew 的国内镜像不少，搜索一下这类方案挺多的）：
> 
> https://gitee.com/cunkai/HomebrewCN
> 
> 按照这个页面上的命令安装即可使用国内的镜像。此方法我自己没用过，如果你成功了可以反馈到这里，以后别的同学就可以放心用了。

**Comment by TurtleNinja42** [comment]
> 用浏览器试试能否打开 `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` 这个地址？如果不能就是网络问题，可以考虑换个网络或者用网络代理试试。
> 
> 如果浏览器可以打开上面地址（可能因为你浏览器用了科学上网），那么就把打开的那个页面保存为 `install.sh`，放在你的 Downloads 目录下，然后运行：
> 
> ```shell
> /bin/bash ~/Downloads/install.sh
> ```
> 
> 或者，也可以尝试下 Homebrew 的国内镜像，比如下面这个（Homebrew 的国内镜像不少，搜索一下这类方案挺多的）：
> 
> https://gitee.com/cunkai/HomebrewCN
> 
> 按照这个页面上的命令安装即可使用国内的镜像。此方法我自己没用过，如果你成功了可以反馈到这里，以后别的同学就可以放心用了。

我可能是因为网络问题无法直接下载Homebrew，然后就下载了上面的国内镜像版本，安装很顺利，暂时没有什么问题。
