### ISSUE TITLE
Jupyter Lab 应该安装在主目录里还是 Code 子目录里比较好？

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#10]
**jupyterlab应该安装在主目录里好呢？还是安装在Code子目录里比较好？**. 还有一个是nteract.

><img width="263" alt="image" src="https://user-images.githubusercontent.com/52586220/85926160-008a6680-b8d0-11ea-8161-3a5de56aa7f2.png">

><img width="325" alt="image" src="https://user-images.githubusercontent.com/52586220/85926176-18fa8100-b8d0-11ea-931b-2012a83cb60d.png">

**Comment by neolee** [comment]
不明白这个问题。Jupyter Lab 是 Python 的扩展程序，用 `pip install jupyterlab` 安装，会自动安装在 Python 环境指定的地方。

**Comment by coolcoollc** [comment]
> 不明白这个问题。Jupyter Lab 是 Python 的扩展程序，用 `pip install jupyterlab` 安装，会自动安装在 Python 环境指定的地方。

我确实用pip命令安装完了jupyterlab 但是指定的地方在哪里呢 怎么运行呢？电脑里找不到

**Comment by neolee** [comment]
这是一个命令行程序，在命令行里执行 `jupyter lab` 就可以运行。当然你应该在你下载的学习用书或者教材所在的目录里运行这个命令比较好。

在课程配套资源里的附录2“如何使用配套学习用书”里有说明。

关于 Jupyter Lab 还有个支线课程可以看看。

**Comment by coolcoollc** [comment]
谢谢李老师，但是这个命令回车后出现问题
![image](https://user-images.githubusercontent.com/54808095/85947371-db076680-b97c-11ea-85f7-3b3a090312b5.jpg)

**Comment by coolcoollc** [comment]
> 这是一个命令行程序，在命令行里执行 jupyter lab 就可以运行。当然你应该在你下载的学习用书或者教材所在的目录里运行这个命令比较好。
> 在课程配套资源里的附录2“如何使用配套学习用书”里有说明。
> 关于 Jupyter Lab 还有个支线课程可以看看。

好像图片显示不了，就是出现 无法将jupyter项识别为cmdlet   等等

**Comment by Shawnnn** [comment]
我觉得可以先确定一下，jupyter lab是否安装成功？
在命令行输入
>`pip list`
用来查看pip已经安装过的包列表
![image](https://user-images.githubusercontent.com/15227825/85947631-39682100-b94c-11ea-8f63-f733576aaa81.png)
如果列表找不到jupyterlab相关的包的话，可能安装失败了
![image](https://user-images.githubusercontent.com/15227825/85947652-4f75e180-b94c-11ea-8964-0522c1b600a5.png)

**Comment by coolcoollc** [comment]
> 我觉得可以先确定一下，jupyter lab是否安装成功？
> 在命令行输入
> 
> pip list
> 用来查看pip已经安装过的包列表
> 
> 如果列表找不到jupyterlab相关的包的话，可能安装失败了

谢谢，搞定了，不容易啊。就是没下载成功，我以为成功了。在清华的站点比较快

**Comment by neolee** [comment]
@coolcoollc 运行任何命令都要关注返回的信息，确定是不是顺利执行成功了。我一直说编程就是把计算机当朋友，和计算机聊天——你不可能和朋友聊天但是不看自己和对方说了啥吧？如果没看明白对方说了啥，也不会就不管它滑过去吧？
