### ISSUE TITLE
运行作业报错

### ISSUE THREAD

**Issue by cx123456-cx** [neolee/wop-community#100]
<img width="937" alt="微信图片_20200711160020" src="https://user-images.githubusercontent.com/57081376/87219662-b43f2c00-c38f-11ea-97e9-fa2ce484da30.png">

**Comment by neolee** [comment]
你的 Runtime 下面选的 kernel 是啥啊？这个出错信息显然不是 Python kernel 而是 nodejs 的。你之前提的那个 issue #98 也是同样的问题，为啥把那个关了又重新开了一个呢……

**Comment by cx123456-cx** [comment]
![image](https://user-images.githubusercontent.com/57081376/87219775-cd94a800-c390-11ea-9899-9e5d670f147e.png)

**Comment by neolee** [comment]
你没有安装 nteract 运行 Python 代码所需要的 kernel。下面截图是《准备学习用书》指南里的一段：

<img width="778" alt="nteract kernel" src="https://user-images.githubusercontent.com/24796/87219822-1fd5c900-c391-11ea-9f1a-97590dd3c98c.png">

所以你是没看到这段话，还是忘了做，还是不知道该如何做？

**Comment by cx123456-cx** [comment]
家里的网络搞不定，用外面的网络，有些步骤在家里操作过，有点凌乱了
