### ISSUE TITLE
请教：万物皆为布尔值，是真的吗？？

### ISSUE THREAD

**Issue by yyd841122** [neolee/wop-community#101]
万物皆为布尔值
数字 0 “相当于”假，而其他数字都相当于真；
空字符串“相当于”假，非空的字符串“相当于”真。

print(type("" and True))
这句返回值是  <class 'str'>

如果从”空字符串“相当于”假，非空的字符串“相当于”真。“  这一句来理解那，我们返回值应该是bool ，不应该是str，不是吗？

**Comment by neolee** [comment]
表达式 `"" and True` 求值的结果是 `''`，即空字符串。

这个原因解释起来很麻烦，目前也没太大用处，一般情况下坚决不要写这种代码就对了。

**Comment by yyd841122** [comment]
好的！谢谢老师！！！

**Comment by tyler1zhang** [comment]
非常喜欢你提的两个问题。人才！

我找了一下， 这个 [Python Reference Manual/5.10 Boolean Operations](https://docs.python.org/2.0/ref/lambda.html)的链接应该会了解到一些东西，在这个问题里，`and` 和`or` 的return是类似的，但是与`not` 不同。 还有一些python的发明者的设定，比如PEP [285](https://www.python.org/dev/peps/pep-0285/)，蛮有意思的。

对了，人才，加个微信吧。 我的微信号是“christlzh".
