### ISSUE TITLE
第二课 演示 函数-数学公式 LaTeX语法问题

### ISSUE THREAD

**Issue by lgqbee** [neolee/wop-community#102]
按流程操作应该显现为：
<img width="317" alt="image" src="https://user-images.githubusercontent.com/57405578/87221016-66c8bc00-c39b-11ea-8ecf-db9564678cfe.png">
但我的notebook没有自动如上渲染：
![image](https://user-images.githubusercontent.com/57405578/87221050-bad3a080-c39b-11ea-8dfa-a10fef849f9b.png)

**Comment by neolee** [comment]
把你的 notebook 保存然后作为附件发上来。

**Comment by lgqbee** [comment]
关闭后重新打开notebook，是显示公式的，不清楚为什么今天下午Shift+Enter运行Cell时，没有显示公式，就直接是语句。
[WoP 第二节 练习.ipynb.zip](https://github.com/neolee/wop-community/files/4906644/WoP.ipynb.zip)

**Comment by neolee** [comment]
可能你没有执行那个单元格。现在解决了就好。

**Comment by lgqbee** [comment]
已解决，后面再试类似语句，运行会出现公式。
