### ISSUE TITLE
Windows 上 jupyter 安装出错

### ISSUE THREAD

**Issue by brarcher214** [neolee/wop-community#103]
在Windows7上尝试多次用命令pip install jupyter  一直安装出错，不知该如何解决，
![jupyter1 0](https://user-images.githubusercontent.com/24749111/87226263-2d0cab00-c3c5-11ea-87f8-7aad9702134e.png)
也试过命令pip3 install jupyter仍旧出错
![jupyter1](https://user-images.githubusercontent.com/24749111/87226228-f898ef00-c3c4-11ea-9594-4f16cda71da8.png)

**Comment by neolee** [comment]
网络问题，可以尝试使用国内的镜像站点，比如清华这个（其实指南里有说）：

https://mirror.tuna.tsinghua.edu.cn/help/pypi/

另外，课程官方不支持 Windows 7，虽然有些系统也能搞定，但你自己斟酌。

**Comment by brarcher214** [comment]
谢谢李老师，明确是网络原因，问题已解决
