### ISSUE TITLE
异常处理中 finally 语句随机输出

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/wop-community#104]
我将 finally 语句放在循环体最后，并使用循环内的变量，以为会报错，但是发现可以正常运行，测试后发现在一个循环内，无论输入什么数值，都会有一个固定的整数输出；在重启另一个循环后，会随机出现另一个整数；这种情况可以解释么？还是  finally 语句最好不这样使用呢？
![图片](https://user-images.githubusercontent.com/57054269/87222687-6da9fb80-c3a8-11ea-8ec2-c4727522874f.png)
![图片](https://user-images.githubusercontent.com/57054269/87222691-7569a000-c3a8-11ea-84d8-61ce1859da76.png)

**Comment by neolee** [comment]
首先这个输出很正常，没啥问题，在 `x = int(input(...))` 这一句没成功的情况下，x 的值还是它之前就拥有的那个值，`finally` 下面的代码块是无论如何都会执行的。比如你第一次运行最后成功输入的是 3，那么下一次执行整个单元格时，x 就是 3，如果 try 后面出异常，x 还是 3。至于第一次为啥 x 是 5，我估计是你之前就运行过这个代码。

顺便说下，notebook 背后是一个 Python 解释器，从你打开 notebook 开始这个解释器就启动了，然后你运行的所有代码，哪怕运行之后被你删了改了，其运行过的效果都留在这个 Python 解释器里，它记得你运行过的所有变量及其值。

另外 `finally` 子句是用来执行一些无论如何都必须执行的代码的，比如清理用过的资源之类的。

**Comment by wenwen-shan** [comment]
好的，明白了，确实是上次最后成功的输入数值，因为我每次最后都是随机输入的数字，导致我以为语句随机输出了。我以为重新启动单元格，就会重新赋值，其实这个程序里的变量要重新启动解释器才是真正的重新赋值，因为这个语句是在执行过的程序上更改的，变量 x 已经被赋值，我重新启动 kernal 后，出现 nameError ,`x` 未被定义。谢谢老师解答。
