### ISSUE TITLE
写完了一行代码，要运行它，有没有快捷键

### ISSUE THREAD

**Issue by jiangminghe** [neolee/wop-community#105]

**Comment by neolee** [comment]
你猜？

**Comment by tyler1zhang** [comment]
你想问的是在什么地方写的代码呢？ 是Terminal，VS Code， JupyterLab，还是别的? 等你清楚了位置，然后就可以读读相关的说明书了（行话叫RTFM）。 
建议你抽时间打开老师建议阅读的这篇文章 [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)，或者它的[中文版](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)。这样可以把问题说的更清楚。
