### ISSUE TITLE
JupyterLab 里面代码行运行的顺序和前后代码运行关系如何衔接或打断？

### ISSUE THREAD

**Issue by jinnami** [neolee/wop-community#107]
在jupyterlab里完成编程作业练习。问题1：运行写完代码的时候从中间的代码开始运行了，发现之后从头开始运行，但是代码行前面的数字顺序是接在中间的代码行运行的数字后面，无奈只好将错就错运行完一遍，但是第一行编码前面的数字不是1。问题2：前面有赋值的代码，后面写运算代码行的时候可能无意中操作了增加和删除代码行的动作，后面继续写的运算代码行不认前面的赋值代码，变成另一个新的代码开始。要怎么重新连接前面的赋值代码行？
![作业问题1](https://user-images.githubusercontent.com/68197601/87252769-4e929300-c4a8-11ea-8aff-8da0685e3335.png)
![作业问题](https://user-images.githubusercontent.com/68197601/87252772-581bfb00-c4a8-11ea-945d-89b475810337.png)

**Comment by neolee** [comment]
Jupyter Lab 里的 notebook 就是一份文档，里面有些代码，仅此而已。运行的顺序完全由你来控制，notebook 的 kernel（你可以理解为一个独立的 Python 解释器，和文档是分离的）会记住你执行的代码。

所以并没有“衔接”“打断”这样的概念，文档是文档，解释器是解释器。这个需要理解，从你的文字表述来看可能有些误解，所以表达的也不太好懂。

至于你遇到的一些具体问题，倒是很好解决：

1. 如果执行顺序乱了，可以选择 Kernel 菜单下的 Restart kernel and clear all outputs，这样会清掉所有执行序号及输出，并重启底下的 Python 解释器，一切都恢复到干净状态，你可以重新按照正确的顺序执行代码。

2. 第二个截图里明显你执行 `a < b` 那一个格子之前没执行过任何代码（因为那个格子前序号是 1），所以 `a` 和 `b` 都没定义过，自然会出错了。

3. 有时候其实不需要序号都正确整齐漂亮，有时候你只是想执行一个单元格试试，和其他部分都没有关联，那就试就好了，这样才能发挥 notebook 灵活实验的优势。真要写比较长的、前后相关的代码，以后我们会更多使用 Visual Studio Code。
