### ISSUE TITLE
为啥两段代码完全等价

### ISSUE THREAD

**Issue by cx123456-cx** [neolee/wop-community#108]
![image](https://user-images.githubusercontent.com/57081376/87262823-f2526200-c4ed-11ea-9de9-8b412eedbf30.png)
这种“相当于‘的逻辑是指什么，’”怎么理解这两段代码完全等价，是形式上等价吗

**Comment by neolee** [comment]
这是课上讲了的内容。当 `if` 后面放的不是 bool 值的时候，Python 会尝试把它转换为 bool 值，比如放了一个整数 n，Python 会根据它是不是 0 来将其变成 bool 值。

所以 `if n:` 和 `if n != 0:` 是严格等价的，是一回事。
