### ISSUE TITLE
在作业本中抄写课程内容如何操作才能保证跟原文的格式一致？

### ISSUE THREAD

**Issue by Amanda-6789** [neolee/wop-community#109]
<img width="1396" alt="截屏2020-07-13 下午12 57 24" src="https://user-images.githubusercontent.com/53425091/87272931-4c612080-c50a-11ea-8033-a1fbe4f7cfdf.png">

下载本周作业，用nteract将课本抄写一遍，是否能在作业本中修改文档格式？

**Comment by neolee** [comment]
系统检查作业的时候不会看文本单元格的内容，但你**千万不要增加或者删除任何单元格**。

教材中的文本都是使用 Markdown 格式书写的，比如你截图中下方的引文样式是用 `> ` 开头的段落。你双击源文本，可以看到其 Markdown 源代码。

建议学习一下 Markdown，支线课程有一讲说的就是这个，自己网上搜索一些资料学习也很快。

**Comment by Amanda-6789** [comment]
<img width="791" alt="截屏2020-07-13 下午3 07 18" src="https://user-images.githubusercontent.com/53425091/87283092-868ceb00-c527-11ea-8c1d-ee51b067292c.png">

探索了一下nteract，我第一次是用Insert Code Cell Below，添加了单元，抄写了教材。

老师答疑后，发现有Insert Text Cell Below，又抄写了一段，并查看了教材源代码，抄写的内容格式跟教材一致了。

课后再学习一下Markdown。

**Comment by neolee** [comment]
再强调一次：上传的作业千万不要改动原版的任何结构，也就是不要增加和删除任何单元格，只在已有的代码单元格里填入正确的代码并执行就好。
