### ISSUE TITLE
Windows 10 下安装 git 失败

### ISSUE THREAD

**Issue by jiaobufan** [neolee/wop-community#11]
![1593316155(1)](https://user-images.githubusercontent.com/63732336/85937474-77f2e100-b936-11ea-8720-3170ea5ae123.png)

**Comment by neolee** [comment]
网络问题，换个网络或者换个时间再试试（可能需要先 scoop uninstall git 清理残余），也可以考虑用网络代理。

**Comment by jiaobufan** [comment]
> 网络问题，换个网络或者换个时间再试试（可能需要先 scoop uninstall git 清理残余），也可以考虑用网络代理。

谢谢老师答复，我是换了好几个网络，也用了vpn还没解决，晚上回家里试试去。

**Comment by neolee** [comment]
如果你用了代理是一定可以的，但是要注意很多代理不能直接支持命令行里的操作，需要在命令行做一些操作才能生效，可以咨询下你的服务商。

**Comment by jiaobufan** [comment]
> 如果你用了代理是一定可以的，但是要注意很多代理不能直接支持命令行里的操作，需要在命令行做一些操作才能生效，可以咨询下你的服务商。

Ok

**Comment by jiaobufan** [comment]
> > 如果你用了代理是一定可以的，但是要注意很多代理不能直接支持命令行里的操作，需要在命令行做一些操作才能生效，可以咨询下你的服务商。
> 
> Ok

会不会我之前就使用安装包自己安装过git，我卸载重装试试。

**Comment by neolee** [comment]
其实如果装过 git 并且可以在命令行用 `git --version` 正常运行显示版本号，其实不需要重装，继续安装 Python 就可以了。

但如果可能还是搞定命令行环境下的网络代理最好，因为不定啥时候就用得上……

**Comment by jiaobufan** [comment]
> 其实如果装过 git 并且可以在命令行用 `git --version` 正常运行显示版本号，其实不需要重装，继续安装 Python 就可以了。
> 
> 但如果可能还是搞定命令行环境下的网络代理最好，因为不定啥时候就用得上……

哈哈，我用另外的方式解决了：
1. 下载安装包 https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z 下载回来的安装包名称是 ProtableGit-2.27.0-64-bit.7z.exe；
2. 复制这个安装包到 scoop 的 cache 目录后改文件名为 git#2.27.0.windows.1#https_github.com_git-for-windows_git_releases_download_v2.27.0.windows.1_PortableGit-2.27.0-64-bit.7z.exe_dl.7z；
3. 执行scoop install git命令——成功了。

![1593321850(1)](https://user-images.githubusercontent.com/63732336/85938773-b5f60200-b942-11ea-86ff-89550f4116f3.jpg)

**Comment by jiaobufan** [comment]
> > 其实如果装过 git 并且可以在命令行用 `git --version` 正常运行显示版本号，其实不需要重装，继续安装 Python 就可以了。
> > 但如果可能还是搞定命令行环境下的网络代理最好，因为不定啥时候就用得上……
> 
> 哈哈，我用另外的方式解决了：1.[https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z下载安装包，安装包名称是ProtableGit-2.27.0-64-bit.7z.exe;2.复制这个安装包到scoop的cache目录后改文件名为：git#2.27.0.windows.1#https_github.com_git-for-windows_git_releases_download_v2.27.0.windows.1_PortableGit-2.27.0-64-bit.7z.exe_dl.7z；3.执行scoop](https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85%E5%8C%85%EF%BC%8C%E5%AE%89%E8%A3%85%E5%8C%85%E5%90%8D%E7%A7%B0%E6%98%AFProtableGit-2.27.0-64-bit.7z.exe;2.%E5%A4%8D%E5%88%B6%E8%BF%99%E4%B8%AA%E5%AE%89%E8%A3%85%E5%8C%85%E5%88%B0scoop%E7%9A%84cache%E7%9B%AE%E5%BD%95%E5%90%8E%E6%94%B9%E6%96%87%E4%BB%B6%E5%90%8D%E4%B8%BA%EF%BC%9Agit#2.27.0.windows.1#https_github.com_git-for-windows_git_releases_download_v2.27.0.windows.1_PortableGit-2.27.0-64-bit.7z.exe_dl.7z%EF%BC%9B3.%E6%89%A7%E8%A1%8Cscoop) install git命令；成功了。
> ![1593321850(1)](https://user-images.githubusercontent.com/63732336/85938773-b5f60200-b942-11ea-86ff-89550f4116f3.jpg)

看起来就是代理不支持命令行安装的原因。

**Comment by jiaobufan** [comment]
问题已解决
