### ISSUE TITLE
运行 jupyter lab 命令有错误提示

### ISSUE THREAD

**Issue by kekeyumuku** [neolee/wop-community#110]
运行jupyter lab命令，浏览器界面如下：
<img width="1301" alt="截屏2020-07-13 下午2 36 20" src="https://user-images.githubusercontent.com/25841942/87278251-93eda980-c516-11ea-9444-538930f11ef0.png">

命令行的界面如下：

<img width="1665" alt="截屏2020-07-13 下午2 39 19" src="https://user-images.githubusercontent.com/25841942/87278412-f8106d80-c516-11ea-86dc-d086c11c3135.png">

复制命令行里的命令：
`http://localhost:8888/?token=8e3f03b19a9b6c99e6a8b461c64bcb14c24a2f5880f49428`
在浏览器粘贴，可以正常打开jupyter lab。

如何执行命令jupyter lab就可以直接正常打开呢？

**Comment by neolee** [comment]
命令行出现的提示大概是说某个 kernel 无效，这个不算大问题——除非反复出现。

一般来说运行 `jupyter lab` 命令是会自动打开争取的网址的，你截图中浏览器里这个错误提示一般是说你已经在一个浏览器里打开了这个 Jupyter Lab 页面，现在想再次打开，这是不被支持的，一个 `jupyter lab` 命令只能打开一个 Lab 页面。

建议你关掉所有浏览器窗口，在命令行 Control+C 终止 `jupyter lab` 运行，然后重新运行 `jupyter lab` 命令看看。

**Comment by Yi-chenglong** [comment]
老师，我在执行jupyter lab命令后也出现了这样的提示，而且是反复出现，重启电脑、重启终端、重启浏览器都不管用，反复出现该问题，之前都没有这样的现象
