### ISSUE TITLE
for 循环显示关于换行的疑惑

### ISSUE THREAD

**Issue by kekeyumuku** [neolee/wop-community#112]
```
count = 0
while count < 5:
    print(count)
    count += 1
    
print('Loop ends.')
```

执行程序显示结果如下：
```
0
1
2
3
4
Loop ends.
```

什么显示结果不是这样呢？

`01234Loop ends.`

**Comment by neolee** [comment]
因为 `print()` 这个函数就是这么设计的，输出完你要它输入的东西之后会自动换行。

如果你想把一组值都输出显示在同一行里，就要手动把它们串成一个字符串，然后调用 `print()` 一次显示出来。

正好在需要你们自学的第九章“字符串”里介绍相关的方法，你可以自己试试。

**Comment by kekeyumuku** [comment]
> 因为 `print()` 这个函数就是这么设计的，输出完你要它输入的东西之后会自动换行。
> 
> 如果你想把一组值都输出显示在同一行里，就要手动把它们串成一个字符串，然后调用 `print()` 一次显示出来。
> 
> 正好在需要你们自学的第九章“字符串”里介绍相关的方法，你可以自己试试。

明白了，谢谢李骏老师
