### ISSUE TITLE
for 循环作业时遇到的疑问

### ISSUE THREAD

**Issue by ly0721** [neolee/wop-community#113]
1，False是时候时候输入或者输出时都首字母需大写的么，有没有可以小写的时候呢？
2，下图2中同样的命令语句中为什么第一行1 是缺省值，第二行3是公差
<img width="414" alt="111" src="https://user-images.githubusercontent.com/67821088/87284748-4e86a780-c529-11ea-9032-5ef2471892e4.png">
<img width="412" alt="222" src="https://user-images.githubusercontent.com/67821088/87284773-55adb580-c529-11ea-88e2-929ea05c0a3b.png">

**Comment by neolee** [comment]
1. Python 是区分大小写的语言，所有名字都是区分大小写的，也就是说 False 和 false 是完全不同的东西。

3. 第三个参数就是指定序列的公差，前一个例子公差是 1，这和不指定第三个参数效果一样，后一个例子公差为 3，就有明显效果了。

**Comment by ly0721** [comment]
好的，老师～
