### ISSUE TITLE
nteract 中 input 输入框无法提交

### ISSUE THREAD

**Issue by keepgrowing27** [neolee/wop-community#114]
在 nteract 中执行含 input 语句的代码块，
然后在跳出的 input 输入框中录入字符，再点击【提交】发现无反应，
尝试点击 Enter 键以及其他一些组合键，也没有反应，见下方截图：
![input_wonnot_excute](https://user-images.githubusercontent.com/25919260/87294286-176ac300-c536-11ea-9446-2f7f1c48977b.png)
希望得到提示。

**Comment by neolee** [comment]
看你截图，这个单元格前面的 [] 里显示的是 `...`，似乎是你的 kernel 正在运行中，很可能是你多按了几次执行，其中有某次没有输入提交，输入界面这个细节 nteract 做的不太好，有时候会让人迷惑。

你可以在 Runtime 菜单里选择 Restart，等重启 kernel 完成再试。

**Comment by keepgrowing27** [comment]
老师好，我在 Runtime 菜单里选择 Restart，等重启 kernel 完成再次测试，input输入框依然无法提交，即点击提交按钮没有任何反应，不论输入框里填写什么内容：
![input_image](https://user-images.githubusercontent.com/25919260/87368395-25f5c080-c5b0-11ea-8558-401c9090a1dd.png)
 而且在重启 kernel 的过程中，有时候会跳出错误提示：
![restart_error](https://user-images.githubusercontent.com/25919260/87368447-43c32580-c5b0-11ea-988e-32910ebcf4d2.png)

**Comment by neolee** [comment]
这个情况比较罕见，你用 Jupyter Lab 试试？

**Comment by keepgrowing27** [comment]
Jupyter Lab 中 input 语句执行和运行正常。

**Comment by neolee** [comment]
那就先继续用 Jupyter 吧，最近好像 nteract 的 bug 有点多，之前比较简单还挺好的……

**Comment by keepgrowing27** [comment]
好的
