### ISSUE TITLE
输入 code . 无法打开 Visual 程序

### ISSUE THREAD

**Issue by cunzai2020** [neolee/wop-community#115]
![image](https://user-images.githubusercontent.com/67787893/87295995-aa0c6180-c538-11ea-9911-cabe8378a641.png)

**Comment by cunzai2020** [comment]
visual  studio code 程序我也安装好了，但是无法用code . 命名打开，是地址不对吗？

**Comment by neolee** [comment]
一般来说 Visual Studio Code 装好你就可以用 code 命令了，现在的出错信息说找不到 code 这个命令，你可以重启下 Windows 试试。

**Comment by cunzai2020** [comment]
软件装错了，重新安装软件后，就可以了。谢谢李老师。
