### ISSUE TITLE
用手机或电脑打开课程配套资源教材特别慢或显示无法打开网页

### ISSUE THREAD

**Issue by banshibao** [neolee/wop-community#116]
电脑是win7，手机是一加7，网络是移动宽带wifi和移动4G。
鼠标点第二章程序的基本结构(一)：值与变量蓝色进度条走一半，或出现空白情况，或显示无法打开网页。换电脑或手机也是同样情况，不过有时等一会会出现课程内容，打开的次数极少。电脑和手机打开课程配套资源教材附录1.编程环境配置指南和附录2.如何使用配套学习用书特别快，其他有代码的课程特别慢或显示无法打开网页，应该是用jupyter notebook viewer加载内容慢的问题。
手机截图拼图如下：
![未标题-1](https://user-images.githubusercontent.com/24274761/87320793-f5853680-c55d-11ea-8ce1-c10b26accdf3.jpg)
电脑截屏如下：
![wenti](https://user-images.githubusercontent.com/24274761/87321387-c0c5af00-c55e-11ea-9276-0cc568e2a7ca.JPG)
请教老师如何解决，无法显示课程内容特别着急，谢谢。

**Comment by neolee** [comment]
两个指南在我们的系统自己的服务中，而教材是使用 nbviewer 对 notebook 进行渲染。我刚才试了下，在我这里还是挺快的，所以应该是网络方面的问题，可以换个时间或者换个网络试试，或者尝试网络代理。
