### ISSUE TITLE
实例后的对象们可以直接生成一个列表或者集合吗？

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#117]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/52586220/87372807-01ebac80-c5bb-11ea-9837-b42f7e29e3eb.png">

上图实例化了三个对象a c d后，在下面的for循环中却直接组合成了一个列表[a, c, d]，这个是什么原理？还是说本来就可以这样操作的？

比如我生成了10个对象，然后随便找出其中5个又组成另外一个列表，只要变量不同就可以了吗？

**Comment by tyler1zhang** [comment]
当你准备好三个对象a, c, d之后，你可以把它们组合成一个列表。 这是一次性使用的方法。如果你要复用，最好还是给这个列表一个变量名。 比如下面的代码：
```python
animals = [a, c, d]
for animal in animals:
    print(animal.name, ':', animal.voice())
```

这样不管你有多少个新的对象，你都可以通过命令`animals.append(new_obj)`来把新的对象添加到animals的list里面（这个方法之后会学到）。 像你最后讲的，你可以任意选择几个对象放到方括号里面，组成一个新的list数据，并使用它。

**Comment by Liujiale02** [comment]
我看得懂了，谢谢
