### ISSUE TITLE
附录 git 教程中的 q 键

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#119]
![image](https://user-images.githubusercontent.com/57065555/87392134-961b3b00-c5de-11ea-85fc-4ea0dc65faa1.png)
附录git与github简明入门中，有上面截图中这一段描述，在执行`git log`命令之后，需要按`q`键退回到命令行界面。
但我在命令行中执行`git log`命令之后，怎么不需要`q`键退回到命令行界面，而是直接是命令行界面？见如下截图？
![image](https://user-images.githubusercontent.com/57065555/87392523-425d2180-c5df-11ea-90da-b946aa5d00c5.png)

**Comment by neolee** [comment]
`git log` 命令会自动检查你的系统里有没有 `less` 之类的翻页控制程序，有的话就会用，那么你就会进入 less 的界面，需要按 q 来退出。

如果你的系统里没有这类软件，就直接显示了，就不需要 q 了。但这种情况下，如果你的 log history 很长，体验就会有点差。

**Comment by Amy20191** [comment]
哦，那翻页控制程序是怎么装呢，用软件包管理工具scoop可以装吗？

**Comment by neolee** [comment]
Windows 10 下，如果 Scoop 安装配置好了的话，应该 `scoop install busybox` 就有了。

**Comment by Amy20191** [comment]
我busybox有装的，但是`less`之类的翻页控制程序，还是没有。

**Comment by neolee** [comment]
如果你装了 busybox，那么就有 less 程序，你可以在命令行运行 `less` 看看。

如果可以运行这个命令，那么可能是你的 git 配置的关系，运行 `git config --list` 试试。

**Comment by Amy20191** [comment]
运行`less`后，代码如下：
![image](https://user-images.githubusercontent.com/57065555/87424184-1efd9b00-c60e-11ea-8a97-88e23ec384a5.png)

`git config --list`这个命令也是可以运行的，运行后代码如下：
![image](https://user-images.githubusercontent.com/57065555/87424344-5f5d1900-c60e-11ea-8265-709e5a6b929f.png)

**Comment by neolee** [comment]
试试用这个配置：`git config --global pager.log true`

以后如果你想关掉翻页器（pager），就执行 `git config --global pager.log false`

**Comment by Amy20191** [comment]
运行`git config --global pager.log true`后，运行`git log`命令，还是直接退回到命令行。

**Comment by neolee** [comment]
先别管这个了，按理来说只要你的 log 多一点就会有 pager 出来的。

**Comment by Amy20191** [comment]
嗯嗯，好的。
