### ISSUE TITLE
关于课程资源中《编程环境配置指南》的两个小问题

### ISSUE THREAD

**Issue by jiaobufan** [neolee/wop-community#12]
> 1. 此处的描述运行以下几个命令，命令表述不明确，到底是哪几个命令，我是靠猜的才明白是，scoop list；scoop install git；scoop update三个命令的。
![image](https://user-images.githubusercontent.com/63732336/85937828-acb46780-b939-11ea-95a8-d01454f582d6.png)

> 2.此处的ComEmu窗口不清楚是什么，搜索了一下发现是另外一个命令行工具。
![image](https://user-images.githubusercontent.com/63732336/85937874-29dfdc80-b93a-11ea-9f8a-995aa1706feb.png)

**Comment by neolee** [comment]
非常感谢为课程纠错！

第一个问题是文件转换时格式出错了，第二个是我更新文档时漏了。这就去修改和发布，再次感谢！

**Comment by neolee** [comment]
线上文档已更新修复这两个问题。

**Comment by jiaobufan** [comment]
> 线上文档已更新修复这两个问题。

看到了，补充一个问题：
![image](https://user-images.githubusercontent.com/63732336/86514905-f1636580-be47-11ea-8609-22b03da5d0a0.png)
应为^ +空格。

**Comment by neolee** [comment]
这个快捷键似乎不同系统配置有差别……

**Comment by jiaobufan** [comment]
> 这个快捷键似乎不同系统配置有差别……

是可以自定义设置的，默认是这样的。

**Comment by jiaobufan** [comment]
> > 这个快捷键似乎不同系统配置有差别……
> 
> 是可以自定义设置的，默认是这样的。

![image](https://user-images.githubusercontent.com/63732336/86515131-87e45680-be49-11ea-9147-d1e00dc91d88.png)

**Comment by neolee** [comment]
但是也有系统这里缺省是我写的那个。

https://support.apple.com/guide/mac-help/spotlight-keyboard-shortcuts-mh26783/mac

**Comment by jiaobufan** [comment]
嗯嗯，我倒是拿另一台mac试验了一下，可能我们系统是一样的，所以设置也一样，一般切换输入法用command➕空格，别的系统没见过，😄

**Comment by neolee** [comment]
我怀疑中国区域设置下就是你那种，美国区域设置下就是我写的那种。我去改改说明吧。

**Comment by jiaobufan** [comment]
> 我怀疑中国区域设置下就是你那种，美国区域设置下就是我写的那种。我去改改说明吧。

没毛病～也是个小问题。
