### ISSUE TITLE
关于P1-4作业第20和21题运行结果疑问

### ISSUE THREAD

**Issue by azheng526** [neolee/wop-community#120]
如图所示示情况：条件都输入后运行了一步，弹出了输入框，（不填入内容）继续运行第二步后结果与课件的标准答案为什么不同？
![批注 2020-07-14 211236](https://user-images.githubusercontent.com/50059311/87431123-c7b0f800-c618-11ea-927e-7e3a69d19887.png)

**Comment by neolee** [comment]
从截图看你最后一个单元格前面还是 [*]，所以可能你还没在输入框里按回车提交吧？

**Comment by azheng526** [comment]
因为之前已重复了几次。我又跑了一次，确认在输入框里按的回车。20和21的结果还是一致。
![批注 2020-07-14 214152](https://user-images.githubusercontent.com/50059311/87432675-e6b08980-c61a-11ea-8422-e3ccb248cbde.png)

**Comment by neolee** [comment]
这结果不是挺对的么，问题是啥？

**Comment by azheng526** [comment]
李老师，我以为这两道题的意思是：如果没有在姓名栏里输入‘姓名’的话就要求print“姓名不可为空，请重新输入”。（开始我还以为是输入的字符、标点、空格不规范）

**Comment by neolee** [comment]
`if not s:` 就是判断 s（用户输入的字符串）是不是空字符串，如果是空的就提示用户输入不合法，但因为这段代码没有放到循环里，所以并不会重试。如果想在用户输入空字符串时重试，要在外面套一个循环，并在循环里正确使用 `break`，你可以自己试试。

**Comment by azheng526** [comment]
明白了，谢谢老师！我这就去试试。
