### ISSUE TITLE
变量前加__

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#121]
老师，__init__ 用双下划线开头和结尾的方法，属于特殊方法。有的地方在变量之前也有__，《自学是门手艺》上解释为私有变量，这个怎么理解？
如果我定义一个类变量，这种变量整个类共有，然后再定义一个私有变量，这个变量不是整个类共有的吗？什么时候会用到私有变量呢？
###

class Dog:

    kind = ''
    __life_span = 10
       

###

**Comment by neolee** [comment]
Python 没有“私有”的概念，但是约定俗成 `_` 开始的变量不推荐给外部使用；而 `__` 开始的变量通常是 Python 内置具有特殊用途的接口。

**Comment by wangcong-creator** [comment]
谢谢老师。
