### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ghost** [neolee/wop-community#122]
源代码：
from random import randrage
n = randrage(1,100)

if n % 2 == 0:
    print(f"{n} is even")
else:
    print(f"{n} is odd")

运行结果报错：

![image](https://user-images.githubusercontent.com/67884048/87439096-efa55900-c622-11ea-8204-c101f343b9b6.png)
![image](https://user-images.githubusercontent.com/67884048/87439108-f46a0d00-c622-11ea-8cfd-12a95d020d5c.png)

Traceback (most recent call last):
  File "suijishu.py", line 1, in <module>
    from random import randrage
ImportError: cannot import name 'randrage'

我是照着书上来的……求问老师问题出哪了？

**Comment by neolee** [comment]
因为你拼错了呀，练练自己的眼力，看看你是哪里写错了（其实解释器的出错信息告诉你了）。
