### ISSUE TITLE
在 JupterLab 中运行下列代码出错

### ISSUE THREAD

**Issue by shuimu0579** [neolee/wop-community#123]
在mac Terminal里面运行了 pip install termcolor 之后

在vsCode里面运行是正常的。
<img width="1075" alt="success" src="https://user-images.githubusercontent.com/27910661/87442135-81629580-c626-11ea-9ca4-b07f413e6026.png">

但是在JupterLab里面运行显示如下报错：
<img width="1440" alt="issue" src="https://user-images.githubusercontent.com/27910661/87441188-6a6f7380-c625-11ea-94d3-bef6cfa17b72.png">

**Comment by neolee** [comment]
看上去你的 Jupyter Lab 用的 Python 环境和 VSCode（以及命令行环境）不一样。

**Comment by shuimu0579** [comment]
那我再去检查一下。

**Comment by shuimu0579** [comment]
Close the issue.
