### ISSUE TITLE
bark=voice 为什么 voice 后面不加括号？

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#125]
![WechatIMG5](https://user-images.githubusercontent.com/52586220/87629658-056f6700-c766-11ea-9bad-acb80d437470.jpeg)

例子截图中的最后一行，bark = voice。voice是一个函数，关于函数的调用后面要加个括号（），但是在这里却不用加。这种情况在昨晚课程的后面部分也有出现过。

- 是不是本来这样的bark() = voice(), 两个都是函数，可以简写成bark = voice？
- 如果不是上面的描述，那又是什么原因可以不写上括号？
- 难道在这里voice不是一个函数，而是一个值，然后赋值给bark吗？

劳烦老师和同学帮忙解答一下我的问题，谢谢

**Comment by jiaobufan** [comment]
1. 这个是给voice函数起别名的语法，不是调用语法。
2. 你可以理解为函数也是在内存中占用一块空间，这块儿空间使用一个名字引用他，即函数名称“voice”,使用这个名称可以找到函数的代码段去执行。
3.  bark = voice,则是定义一个变量，名称为bark，让他也指向这块空间，也可以使用这个名称去调用这段代码（函数体）。
4. 如果用了voice()，则为函数调用语法了，因此，这是不同的。

**Comment by jiaobufan** [comment]
> 1. 这个是给voice函数起别名的语法，不是调用语法。
> 2. 你可以理解为函数也是在内存中占用一块空间，这块儿空间使用一个名字引用他，即函数名称“voice”,使用这个名称可以找到函数的代码段去执行。
> 3. bark = voice,则是定义一个变量，名称为bark，让他也指向这块空间，也可以使用这个名称去调用这段代码（函数体）。
> 4. 如果用了voice()，则为函数调用语法了，因此，这是不同的。
> 补充一点，bark = voice(),如果这样写了，代表了voice函数的返回值赋值给bark

**Comment by neolee** [comment]
这真是一个好问题，观察力和逻辑都很好，逼得我不得不剧透后面的内容了。

昨天讲课时提了一句，说后面会学到，其实函数也是对象，这里就是一个例子。

其实函数就是对象（其类型为 `func`），所以 `bark = voice` 就是个一般的赋值语句，建立了一个新的对象 `bark` 并把 `voice` 的值赋给了它，它们从此指向了同一个函数对象。

函数这种对象的独特之处在于它们是“可以被调用的（_callable_）”，而调用函数的语法就是在函数对象后面加上一对小括号 `()` 并传递必要的输入参数进去。

所以函数本身就是一种对象，可以被赋值被传递被返回，而在函数名后面加括号是调用这个函数的语法。

还有另外一种理解角度，就是从表达式求值的角度理解：`voice` 这个表达式求值的结果是一个函数对象，也就是我们用 `def voice():...` 定义的那段代码；而 `voice()` 这个求值的结果则是调用函数 `voice()` 的返回值，具体是啥由函数具体定义。

所以 `bark = voice` 和 `bark = voice()` 都是合法的代码，但含义完全不同，而且看了前面的解释你应该知道他们分别是啥意思了吧。

**Comment by Liujiale02** [comment]
还是不好理解，只能慢慢消化或者提前学习后面的内容了。

**Comment by neolee** [comment]
哪里不好理解？

**Comment by Liujiale02** [comment]
这两个意思我明白了。

那我还可以这样理解吗--

`bark=voice`发生在**定义类的过程**当中（`class Dog...`），所以这种场景中可以直接当作赋值；

而当需要调用`.voice()`时，这种场景主要发生在**执行代码和生成对象**的时候。

**Comment by yyd841122** [comment]
bark = voice  这个值，是把voice()这个函数看作一个对像，赋值给bark，那在类以外调用，我的理解应该，直接    变量名.dark 就应该是调 voice()这个函数方法。

如果再写上一个（），那我理解的就是dark,也就是变成了一个函数方法，只是执行的语句是void()里面的。
变量名.dark 是不是相当于一个指针的含义？？？

**Comment by neolee** [comment]
@Liujiale02 和代码发生在哪里没有关系，在类定义的外面也可以写下面这样的代码：
```python
d = Dog('Snoopy')
my_dogs_bark = d.bark
print(my_dogs_bark())
```
上面的代码也会输出 `woof-woof`。在上面的代码中，`d.bark` 就是 `d` 对象的一个属性，也就是个变量，可以赋值给另外一个外部的变量 `my_dogs_bark`，于是 `my_dogs_bark` 也指向了我们在 `Dog` 类里定义的函数，给 `my_dogs_bark` 后面加个括号就能调用这个函数了。

实际上关键规律是：`bark` 是一个函数对象，如果你要操作这个函数对象（把它赋值给别的变量，或者把它作为输入参数送给别的函数），那就直接使用 `bark` 这个变量就好了；如果你要调用这个函数那就在后面加上括号 `bark()`。

@yyd841122 你的理解也不准确，参见上面的解释。

**Comment by yyd841122** [comment]
是不是可以这样理解，要把dark当作一个值来理解，类比为    int   float   ,  但是要用dark这个函数的时候，一定要加上（）。这样才能去调用真正的函数。

**Comment by neolee** [comment]
> 是不是可以这样理解，要把 dark 当作一个值来理解，类比为 int float，但是要用 dark 这个函数的时候，一定要加上 ()。这样才能去调用真正的函数。

这个基本上对了。

**Comment by gaoteng-pro** [comment]
1. `bark = voice`这是一个赋值语句，其中左边`bark`是变量，右边 **一定必须** 是个值。

2. 值是数据在计算机中的存在形式，且值有好多类型。有基本的数据：**整数**、**小数**、**布尔**、**字符与字符串**；也有高级的数据：**对象**、**数据容器**、**函数**。

3. 所以，**函数** 也是值。

4. `voice`是 **函数**，它是值；`voice（）`是 **函数的调用**，也是值，两者都可以通过赋值语句赋值给变量。

5. 既然，上述两个都是值，都可以赋值给左边的变量。所以`bark = voice`和`bark = voice（）`都是合法的，都是python解释器认可的。区别仅在于赋值语句 **右边的值** 的类型不同。

6. `bark = voice（）`就是把 **函数调用后的值** 赋值给变量；而`bark = voice`就是把 **函数** 赋值给变量，那么`bark`这个变量就被赋值为一个 **函数** ，因为被 **函数** 赋值了，而不是被 **函数调用的返回值**  赋值，所以被 **函数** 这种值类型赋值后的`bark`就是一个 **函数**  。
