### ISSUE TITLE
TypeError、ValueError 和 IndentationError 的区别和抛出场景

### ISSUE THREAD

**Issue by jiaobufan** [neolee/wop-community#126]
今日在做数据容器续作业时发现，教材中多处提到在某种情况下会抛出TypeError，但实际运行后不太一样，以下是截图：
### IndetationError
![image](https://user-images.githubusercontent.com/63732336/87637149-6605a080-c774-11ea-9d7a-beebdb699dbd.png)

### ValueError
![image](https://user-images.githubusercontent.com/63732336/87637289-8fbec780-c774-11ea-8786-a929113a0270.png)

### 疑问：

- IndentationError是在人为改变tuple的元素时抛出的，还有哪些场景下会抛出IndentationError，why？
- ValueError是在将tuple的值赋值给多于或者少于tuple本身元素的个数时抛出的，还有哪些场景下会抛出ValueError，why？
- TypeError会在什么场景下抛出呢？
- 教材这块写抛出TypeError是否是笔误还是TypeError是IndentationError和ValueError的父类？

**Comment by neolee** [comment]
* `TypeError` 表示你对某个对象的操作和它的类型不符，比如想调用某个方法，但那个对象其实没那个方法；试图改变 tuple 的某个元素也属于这种情况（因为 tuple 不支持这个操作）。

* `ValueError` 一般是你提供的值不符合要求，比如该给数字的时候给了个字符串，该给4个值的时候给了5个（你截图里的 unpacking 出错就是这种情况）。

* `IndentationError` 比较简单，就是代码缩进有问题，比如不该缩进的缩进了，改缩进的没缩进等等。

**Comment by jiaobufan** [comment]
> * `TypeError` 表示你对某个对象的操作和它的类型不符，比如想调用某个方法，但那个对象其实没那个方法；试图改变 tuple 的某个元素也属于这种情况（因为 tuple 不支持这个操作）。
> * `ValueError` 一般是你提供的值不符合要求，比如该给数字的时候给了个字符串，该给4个值的时候给了5个（你截图里的 unpacking 出错就是这种情况）。
> * `IndentationError` 比较简单，就是代码缩进有问题，比如不该缩进的缩进了，改缩进的没缩进等等。

场景基本理解了，但仍然存在以下两个问题。
1. 试图改变tuple的元素，抛出的时IndentationError，见图1.
2.教材里的说明的是错误？

**Comment by neolee** [comment]
你试图改变 tuple 元素的那一行前面有个空格，这首先是缩进错啊！

关于 unpacking 那段是有问题，我去改改。

**Comment by jiaobufan** [comment]
> 你试图改变 tuple 元素的那一行前面有个空格，这首先是缩进错啊！
> 
> 关于 unpacking 那段是有问题，我去改改。

OK，搞定~
