### ISSUE TITLE
覆盖 hosts 文件的管理员权限如何使用呢？

### ISSUE THREAD

**Issue by yuxi0324** [neolee/wop-community#128]

**Comment by neolee** [comment]
你的问题也太简略了吧？不知道你的操作系统，也不知道你用什么方式编辑 hosts 文件，是要我去猜么？

好吧，那我就猜一下，假定你是 Windows 10，假定你用 Visual Studio Code 来编辑 hosts 文件（这是正确的方法），那么你需要：

1. 以管理员方式启动 Visual Studio Code（右键点该程序的图标有选项）；
2. 在 Visual Studio Code 中选择 File -> Open Files 菜单项，找到 `C:\Windows\System32\drivers\etc\hosts` 文件并打开；
3. 按照文档说明编辑该文件；
4. 保存，如果有提示是否用管理员权限覆写文件，选择是。

**Comment by yuxi0324** [comment]
对不起老师我的问题没有经过大脑就发了出来，这个问题解决了，但是覆盖之后，成功刷新 DNS 解析缓存之后，去安装scoop还是
![image](https://user-images.githubusercontent.com/68325748/87665076-e938ed80-c798-11ea-9902-945392e5af64.png)

**Comment by neolee** [comment]
你确定成功更新了么？你现在的 hosts 文件长啥样？用 VSCode 打开截图给我看看。

**Comment by yuxi0324** [comment]
![image](https://user-images.githubusercontent.com/68325748/87665562-b17e7580-c799-11ea-8857-43c09d8e872a.png)

**Comment by neolee** [comment]
所以你只加了一个域名的解析，注意看你命令行里出现的红字提示，计算机表示它找不到的域名是 `raw.githubusercontent.com`。

按照我在 https://github.com/neolee/wop-community 页面下方写的，你需要在 `hosts` 文件中加入所有 GitHub 有关的域名解析才行，你需要按照那个完整做一遍，再试着安装 Scoop。
