### ISSUE TITLE
在用 f-string 时让 print 出来的结果换行用 ''' 可以吗？

### ISSUE THREAD

**Issue by liushui0712** [neolee/wop-community#129]
<img width="602" alt="WeChatfecdd3c3490a32e1054260f4261e185e" src="https://user-images.githubusercontent.com/54479298/87666834-ec81a880-c79b-11ea-8cb5-53b951c2e441.png">
试了一下，\n是没问题的，如果输出结果很多的话，有些麻烦。
试着用  '''  ，却不行，是用法错误还是真的不可以呢？

**Comment by neolee** [comment]
如果你用三个引号括起来的形式，那么 `f` 要写在外面啊，正确的大致这样：

```python
a = 42
b = 74
s = f'''我试一下，
你的分数是{a}，
我的分数是{b-a}'''
print(s)
```

**Comment by liushui0712** [comment]
啊，明白了，我也在f后面试过，居然囫囵吞枣的在 ‘ 又额外加了 '''。谢谢老师
