### ISSUE TITLE
关于实例化对象调用问题

### ISSUE THREAD

**Issue by feifei3333** [neolee/wop-community#130]
![图片](https://user-images.githubusercontent.com/68018321/87672184-22775a80-c7a5-11ea-9768-344e7de15e55.png)
老师请问这个程序为什么可以运行？
![图片](https://user-images.githubusercontent.com/68018321/87672432-8a2da580-c7a5-11ea-8278-839710e869c3.png)
按照课程例子应该这样写，是吗

**Comment by neolee** [comment]
如果只看第一张截图，`p.printName(...)` 这一句是会出错的，因为 `p` 这个变量没有初始化过——它能执行肯定是你之前执行过实例化 `p` 的代码。

p.s. Python 里变量和函数等名字的命名习惯是 `print_name` 这样的，而不是 `printName` 这样的，后者是 Java 等语言的风格。
