### ISSUE TITLE
__init__ 传参数 None 的疑惑

### ISSUE THREAD

**Issue by yyd841122** [neolee/wop-community#131]
![提问](https://user-images.githubusercontent.com/67271134/87735730-f1307600-c808-11ea-9ad2-98a3ced3a007.png)

**Comment by neolee** [comment]
name 这个属性是对象的属性，Animal 类确实没这个属性呀。

**Comment by tyler1zhang** [comment]
这里面有太多的`name`，可能是导致你混乱的原因。你可以尝试把你写出来的`name`换成`color`，就不容易乱了。

```python
class Animal:
    kind = ''
    
    def __init__(self, skin_color):
        self.color = skin_color
``` 
这里面很容易乱的是各个名字的本质是什么。 `skin_color`是你初始化时输入的参数， `color`是将来的对象object的属性。而在这个类的定义code中，并没有一个`类属性`是`color`。 所以当你调用`Animal.color`一定会出错。 

另外，建议你学习使用markdown的文本方式提问，请看这个[链接](https://www.bilibili.com/video/BV1wE411i7Ve)。

**Comment by yyd841122** [comment]
老师的解释我明白了，Animal,这个类里面本身就是没有name 这个属性，name 这个属性是属于实例化的那个对像的。

**Comment by gaoteng-pro** [comment]
如果已经解决了，可以关闭掉issue。如果想就这个问题重新发问，在关闭状态下，依然可以重新发问，不用担心漏掉类似疑问。
