### ISSUE TITLE
同样都是函数赋值 : 号和 = 号都有些什么区别

### ISSUE THREAD

**Issue by jinnami** [neolee/wop-community#132]
比如在写这段代码里：
```python
class Cat:

    kind = 'felidae'

    def __init__(self, name):
        self.name = name
        
    def mew(self):
        return 'meow-meow'

c = Cat('Garfield')
```
我能将里面的
```python
def mew(self):
    return 'meow-meow'
```
改写成 `def mew(self) = return 'meow-meow'`

或改写成 `def mew(self) = 'meow-meow'`  吗？

**Comment by neolee** [comment]
不能。

定义函数只有一种语法，就是：
```python
def f():
    ......
```

上面这叫函数的“定义”，不是赋值。

如果写 `g = f` 这才是把函数对象 f 赋值给了变量 g，函数定义和赋值完全是两个东西。

关于这个概念可以参考另外这个 issue #125 。

p.s. 问题里的程序代码可以使用 Markdown 标签，否则会很乱，具体参见 https://github.com/neolee/wop-community/ 。我也帮你改了，你可以点 Edit 看看我咋改的。

**Comment by jinnami** [comment]
好像有点明白了，定义下面可以有很多，可以是类名称，可以是类属性，可以没有具体的值。而赋值等号两边是直接1对1对应的关系。

**Comment by neolee** [comment]
在编程语言里定义一个东西都有很严格的语法，不能混，比如 Python 里 `class XXX:` 是定义一个类，`def xxx():` 是定义一个函数，你要定义什么就要用它特定的语法。

而赋值语句是通用的，左边是个变量，右边是个值（或者可求值）就可以。
