### ISSUE TITLE
TypeError: Dog() takes no arguments

### ISSUE THREAD

**Issue by congboqiu** [neolee/wop-community#134]
着课本，操写代码，对了一遍，老是出错：
![批注 2020-07-17 202119](https://user-images.githubusercontent.com/32408593/87787662-9893c400-c86e-11ea-869d-81d19fba3dd9.png)

TypeError: Dog() takes no arguments
如果复制课堂代码就能过？

**Comment by neolee** [comment]
这就是我上课说的容易出现的错误：`__init__()` 方法的名字拼错，前后都是两个下划线，不是一个。因为拼错，Python 认为你没有自己写 `__init__()` 方法，也就相当于用了一个缺省的 `__init__(self)` 方法，那么实例化的时候就不该有输入参数。

p.s. 如果发现自己的问题需要增加内容或者修改，直接修改标题和正文就行了，不需要另外开一个。仔细读读 https://github.com/neolee/wop-community/ 吧。

**Comment by congboqiu** [comment]
> 这就是我上课说的容易出现的错误：`__init__()` 方法的名字拼错，前后都是两个下划线，不是一个。因为拼错，Python 认为你没有自己写 `__init__()` 方法，也就相当于用了一个缺省的 `__init__(self)` 方法，那么实例化的时候就不该有输入参数。
> 
> p.s. 如果发现自己的问题需要增加内容或者修改，直接修改标题和正文就行了，不需要另外开一个。仔细读读 https://github.com/neolee/wop-community/ 吧。

谢谢，老师。还是没有只字不差的阅读，忏愧。
