### ISSUE TITLE
成功安装 Visual Studio Code 后运行 code. 提示 command not found

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#135]
使用mac OS 10.15.5 Catalina

内容：第一讲：进入编程的世界

1.输入python3 -V, 指向Python 3.7.4版本
2.成功安装并运行Visual Studio Code
3. 第一种方式成功，第二种方式输入jupyter lab, 成功。
4. 使用第三种方式失败：输入touch  hello.py , 没有任何提示
继续输入code. 提示command not found. 
尝试关机重启，问题仍然存在。

**Comment by xuzhengfu** [comment]
1. 是 `code .`，注意中间那个 “空格”。（`.` 表示当前工作目录，这条命令的意思就是：使用编辑器 VSCode 打开当前工作目录。）

2. 我们应该遵循李骏老师的建议：把（至少开始试着把）计算机当作我们的朋友。在这里，你会发现：计算机其实已经回应我们了。你让计算机做一件事儿 —— 使用编辑器 VSCode 打开当前工作目录，计算机回应你说：“没有 `code.` 这个命令啊！”

    > ```shell
    > code. command not found.
    > ```

3. 请复习支线课程（在新生大讲堂中）第一讲、第四讲以及第五讲。

**Comment by jomi0820** [comment]
我有看到code后面有空格，我输入对是“code .”
然后提示“command not found”， 我也明白计算机提示的意思是“没有code”这个命令
我的问题是：成功安装Visual Studio Code， 也在正确目录下，输入的命令也正确，为什么会出现这个提示？

**Comment by neolee** [comment]
有点好奇，为啥时隔 28 天突然又想起这问题了呢？

按照安装配置指南在 Visual Studio Code 中进行设置了么？macOS 下必须手工安装 code 命令，具体方法指南里有。

另外 Visual Studio Code.app 需要拖到 Applications 目录下才行。

**Comment by jomi0820** [comment]
老师，我的情况是这么回事儿：
1.我在7月份第一次提出问题后，自己重启了几次电脑，然后再输入code命令以后，发现可以在终端进入Visual Studio Code里面了。虽然当时并不知道，为什么之前输入正确会提示command not found， 但是问题是解决了，可以正常使用。

2. 随后一直正常使用操作，即在终端输入code可以打开，没有发生过问题。

3. 再返回这个issue， 是因为这几天我使用时又出现了和之前一样的问题，就是终端里输入code命令以后，又提示“command not found”。我反复重启了电脑，问题还是没有解决。

按照您的提醒，我进行了如下的操作解决了问题
1. 把Visual Studio Code拖入Application （之前没有），在启动台里直接进入Visual Studio Code来使用它。这点我之前没注意到.
2. 在Visual Studio Code安装code：
重新打开VSCode –> command+shift+p –> 输入shell command –> 点击提示Shell Command: Install ‘code’ command in PATH运行。

这个问题，我自己是今天根据您提到的2点才算真正明白了原因。
如上的描述，留给和我一样的在起初会因为小问题很迷惑的伙伴。
