### ISSUE TITLE
为什么迭代器里要定义 `__iter__()`？

### ISSUE THREAD

**Issue by chhyuan** [neolee/wop-community#136]
老师，迭代器里给出一个取下一个元素`__next__()`就好了，为啥要定义一个`__iter__()`对象自己返回自己呢？

**Comment by neolee** [comment]
就这么规定的，任何可迭代对象需要一个用 `__iter__()` 方法返回一个迭代器，否则无法被 `for...in` 循环迭代。到讲这课时会有更详细的说明。

另外，逻辑上 `__iter__()` 方法可以不返回自己，而是返回另外一个实现了 `__next__()` 方法的对象，也就是这两个方法的实现可以分离，实现 SoC 和更精细化的复用，只是目前阶段不太用得到罢了。

**Comment by chhyuan** [comment]
Got it.
