### ISSUE TITLE
课程大练习一 - 集中区

### ISSUE THREAD

**Issue by neolee** [neolee/wop-community#137]
希望参与大练习一的 _社交化大作业_ 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：

1. 本帖回复只需要贴出 gist 链接，**不要**写任何其他东西；
2. 要对某个 gist 进行评论的请在该 gist 下面回复，**不要**写在这里。

**Comment by shuimu0579** [comment]
https://gist.github.com/shuimu0579/657679638790430e0499b9ba6a26336e

**Comment by blueeyezhy** [comment]
https://gist.github.com/blueeyezhy/7987b7925316d07ff1e3507657b86ce1

**Comment by jiaobufan** [comment]
https://gist.github.com/jiaobufan/0cb75753c4426dbbb5d9607165b51171

**Comment by doriawq** [comment]
https://gist.github.com/doriawq/e5d71f7600fd5b1e19602d08b685521a

**Comment by hendasheng** [comment]
https://gist.github.com/N1U/ba4790e1567a63c9779903a4437aa243

**Comment by xuzhengfu** [comment]
https://gist.github.com/Xuzhengfu/c7ecb126334c04a7ee6c752da8fa8660

**Comment by Shawnnn** [comment]
https://gist.github.com/Shawnnn/015f6d1e28bae5158fe0b8f4069eac0a

**Comment by lgqbee** [comment]
https://gist.github.com/lgqbee/ae05bcba34b71591d5c95815d386c35b

**Comment by wang-yulin** [comment]
https://gist.github.com/wang-yulin/2e54189e57619875b3958c85bda05266

**Comment by 1043-nw** [comment]
https://gist.github.com/1043-nw/c0de0c86b9b3eca4fa6c1e486b1ee4b3

**Comment by wenwen-shan** [comment]
https://gist.github.com/wenwen-shan/7d880ebfe51980912a0e7309f4ff135d

**Comment by sujuxiaoren** [comment]
https://gist.github.com/sujuxiaoren/69c6c3dd1eb2edb157fe1aefb0cbd68c

**Comment by Amanda-6789** [comment]
https://gist.github.com/Amanda-6789/4499244632f8e538db02757c989f870d

**Comment by wongpu** [comment]
https://gist.github.com/wongpu/04573e1cad44e5b209538118e146ed41

**Comment by zhangSen1987** [comment]
https://gist.github.com/zhangSen1987/7e7a0d91930b0620af1198687d89ec9f

**Comment by gaoteng-pro** [comment]
https://gist.github.com/gaoteng-pro/bcc30349cba7a002a51bf7e5820db076

**Comment by yyd841122** [comment]
https://gist.github.com/yyd841122/32c0a412af02fa670ff7ae9a75842517

**Comment by muyuzhu** [comment]
https://gist.github.com/muyuzhu/14fca259e290fdbf6511ff9b60a49624

**Comment by cunzai2020** [comment]
https://gist.github.com/cunzai2020/36af2fdbc76af44cc3c81f28105c939f

**Comment by liushui0712** [comment]
https://gist.github.com/liushui0712/8751b4da3b4896a6abd850f69bce9d83

**Comment by tyler1zhang** [comment]
https://gist.github.com/tyler1zhang/c476632dd442bb92555e54b1a5483442

**Comment by girlfriendandme** [comment]
https://gist.github.com/girlfriendandme/9190813024a3fe97ade808f4451f4db0

**Comment by catynchyna** [comment]
https://gist.github.com/catynchyna/b1b5757276c557ec7b553157c852e8f0

**Comment by kekeyumuku** [comment]
https://gist.github.com/kekeyumuku/b929f80e5747ab60bded00979194b31a

**Comment by HSChloe** [comment]
> 希望参与大练习一的 社交化大作业 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：
> 
> 本帖回复只需要贴出 gist 链接，不要写任何其他东西；
> 要对某个 gist 进行评论的请在该 gist 下面回复，不要写在这里。

https://gist.github.com/HSChloe/64bab4906c182ec0a7caaa8d524ea6a3

**Comment by Liujiale02** [comment]
https://gist.github.com/Liujiale02/daf5d35ca0fa36ca9c878eea26c43e61

**Comment by xiaoatang** [comment]
https://gist.github.com/xiaoatang/310c0fc98a164a68fa414083550a6a50

**Comment by iamjinlei0312** [comment]
https://gist.github.com/Zhang-Jinlei/1b969a048f2498e4920d22185699f920

**Comment by Yongheng2020** [comment]
https://gist.github.com/Yongheng2020/ad5267ce73b69f1ca0a337017932d543

**Comment by Royhowtohack** [comment]
https://gist.github.com/Royhowtohack/289b7f28fdb81b8e349f143a68854270

**Comment by muse1171** [comment]
https://github.com/muse1171/learn-git/blob/master/garfield.py

**Comment by muse1171** [comment]
https://github.com/muse1171/learn-git/blob/master/garfield.py

**Comment by ccaaxx77** [comment]
https://gist.github.com/ccaaxx77/4196820658c0b9ae877dad982c32d57a

**Comment by congboqiu** [comment]
> 希望参与大练习一的 _社交化大作业_ 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：
> 
> 1. 本帖回复只需要贴出 gist 链接，**不要**写任何其他东西；
> 2. 要对某个 gist 进行评论的请在该 gist 下面回复，**不要**写在这里。
https://gist.github.com/congboqiu/311b75ea2ac5e9d6a82a02ddeeea16fc

**Comment by blackoutwhb** [comment]
https://gist.github.com/blackoutwhb/952dd972be5310eae6cadba2d5248d5b

**Comment by Wangbicong** [comment]
https://gist.github.com/Wangbicong/230aa8016c36bdfc98997576fc0d87df

**Comment by wangcong-creator** [comment]
https://gist.github.com/Wangbicong/1764b0b425ac3bbcab37026e8b2c6c68

**Comment by DamonNiu** [comment]
https://gist.github.com/DamonNiu/caa24ab60a48705cbd8defd0cd800aa3

**Comment by liangfeng3** [comment]
gist.github.com/liangfeng3/4c4620a52d70c6ba4047982e7003b060

**Comment by liangfeng3** [comment]
https://gist.github.com/liangfeng3/4c4620a52d70c6ba4047982e7003b060

**Comment by sai2008** [comment]
https://gist.github.com/sai2008/6b3996510fc9cbae43fa2dd5e04d5c35

**Comment by aqinmode** [comment]
https://gist.github.com/aqinmode/da4a6b2b28a4afa2a997110128928c64

**Comment by azheng526** [comment]
https://gist.github.com/azheng526/274d948f416239f1b3977efa939d1647

**Comment by Rick-Zo** [comment]
https://gist.github.com/DerickZo/b8cd17a1475cd0b0ac6ab5f9fe518627

**Comment by Yi-chenglong** [comment]
https://gist.github.com/Yi-chenglong/1cc3242e3c5ca7274fa95da29d6ac55d

**Comment by keepgrowing27** [comment]
https://gist.github.com/keepgrowing27/29a134965e8ed8443bce79543c313cf1

**Comment by wangBoZhengJuan** [comment]
> 希望参与大练习一的 _社交化大作业_ 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：
> 
> 1. 本帖回复只需要贴出 gist 链接，**不要**写任何其他东西；
> 2. 要对某个 gist 进行评论的请在该 gist 下面回复，**不要**写在

> 希望参与大练习一的 _社交化大作业_ 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：
> 
> 1. 本帖回复只需要贴出 gist 链接，**不要**写任何其他东西；
> 2. 要对某个 gist 进行评论的请在该 gist 下面回复，**不要**写在这里。

[https://gist.github.com/wangBoZhengJuan/8d7af5c500547a010e119a49174ea27b](url)

**Comment by wangBoZhengJuan** [comment]
[https://gist.github.com/wangBoZhengJuan/8d7af5c500547a010e119a49174ea27b](url)

**Comment by wangBoZhengJuan** [comment]
[https://gist.github.com/wangBoZhengJuan/8d7af5c500547a010e119a49174ea27b](url)

**Comment by wangBoZhengJuan** [comment]
https://gist.github.com/wangBoZhengJuan/fe8221477f4cc2bcb7fb14cd595f0f66

**Comment by BlackSocrates** [comment]
https://gist.github.com/BlackSocrates/ff9147882cdecab4805d812e0ea775da
