### ISSUE TITLE
函数 s.rindex() 返回值问题

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#138]
```python
s = 'Perform a string formatting operation. The string on which this method is called can contain literal tex...'
s.rindex('string')
43
```
这段代码，是从字符串 s 中查找 string的位置，是从右往左找。字符串 s 中共有2个string，从右往左数，找到第一个string的位置，返回值应该是58，怎么是43呢？

**Comment by neolee** [comment]
这也是很多同学会问的问题。

`str.rindex(substr)` 这个方法，它会在 `str` 中从右向左搜索 `substr` 子串，找到之后返回找到的子串的第一个字母的下标。

这里面的几个要点是：
1. 从右向左找；
2. 找到后返回匹配子串的**第一个**字母的**下标**（*index*）；
3. 下标永远是从左向右从 0 开始的。

所以在你的例子里返回的是字符串里第二个 `string` 中的 `s` 的下标，是 43。

**Comment by Amy20191** [comment]
哦，明白了。
