### ISSUE TITLE
字体颜色、加粗问题

### ISSUE THREAD

**Issue by cx123456-cx** [neolee/wop-community#139]
![image](https://user-images.githubusercontent.com/57081376/87846505-fa9e0900-c902-11ea-9988-c8e67cd420da.png)
重新复习前面的课，老师说这个None字体绿色加粗是Python内置的保留字，特殊的符号。del也是绿色加粗。print、type也是绿色，但是没有加粗。2020普通数值也是绿色不加粗
问题：在Python里面，输入不同的东西显示不同的颜色和字体是有专门的代表意思吗，比方说是内置的，还是普通数值？还是仅仅因为在notebook上运行才会显示不同的颜色，字体的颜色粗细没人任何指向？

**Comment by neolee** [comment]
你提到的这个“程序里不同的内容被显示为不同颜色和样式”的功能叫做 *syntax highlighting*，是程序编辑器提供的一种友好功能，让你可以在视觉上识别出程序里的不同元素。

这个功能在不同的编辑器里的实现可能不一样，功能的精细程度和定制都会有细微差异。Jupyter Lab 里的代码单元格、Visual Studio Code、还有 PyCharm 这样比较重型的 IDE，本质上核心都是一个代码的编辑器，它们对 *syntax highlighting* 的实现都有些差别。

这个东西的实现基于下面几个组件：
1. 对程序的分析，识别出不同的元素：这个部分差异最大，比较强大的编辑器会对代码做完整系统的语法分析，和 Python 解释器执行程序代码的过程几乎一样，可以非常精确地辨别出诸如全局变量和局部变量、不同数据类型、有用没用的名字等等；有些轻量级的编辑器则只做非常简单的分析，只能大致区分几类基本元素。
2. 对不同元素可以定义不同的显示样式，常见的是颜色和粗体斜体；
3. 允许定制多种多样的主题，也就是不同的样式组合，你在 Jupyter Lab 的菜单里选 Settings - Text Editor Theme 可以选择自己喜欢的样式方案。

所以，回到你的问题：这些特殊样式显示是程序编辑器提供的功能，程序本身只是普通的文本（Python 解释器才不管你是啥颜色粗体斜体呢，只认字儿）；至于某个样式是啥意思，需要去查看这个颜色主题的具体说明，不同环境不同样式主题里可能不一样。
