### ISSUE TITLE
Jupyter Lab 问题

### ISSUE THREAD

**Issue by coolcoollc** [neolee/wop-community#14]
李老师，我报了7月4号的编程课。按照视频和文档配置了环境，jupyterlab我安装了，但是不知道装哪了，怎么在电脑上看到，怎么启动？像其他软件我都能看到
![image](https://user-images.githubusercontent.com/54808095/85947255-12c1de80-b97c-11ea-98e2-e321250cd421.jpg)

**Comment by neolee** [comment]
我在你的另一个问题里回答了。

**Comment by Shawnnn** [comment]
![image](https://user-images.githubusercontent.com/15227825/85947337-5bf93a80-b94a-11ea-84e4-4c3e12263ba6.png)
打开CMD， 在控制台里面输入jupyter lab
就能打开
![image](https://user-images.githubusercontent.com/15227825/85947368-8945e880-b94a-11ea-87c7-8a3fe7919ded.png)
