### ISSUE TITLE
这句没弄明白 self._prompt("This is Garfield...")

### ISSUE THREAD

**Issue by congboqiu** [neolee/wop-community#140]
预习第一个大作业中：
 def run(self):
        **self._prompt("This is Garfield dialog system. Let's talk.")**
        for bot in self.bots:
            bot.run()
定义的run方法self._prompt("This is Garfield dialog system. Let's talk.")1.这句语法是实现直接显示圆括号里边的字符吗？2.如果是显示字符，为什么不是self._prompt = "This is Garfield dialog system. Let's talk."，然后再print(self._prompt)呢？

**Comment by neolee** [comment]
这个问题，你首先要搞清楚 `self._prompt` 是个啥？它是一个属性还是一个方法（函数）？

想明白这件事之后，看看 #125 可以升华一下。

**Comment by congboqiu** [comment]
> 这个问题，你首先要搞清楚 `self._prompt` 是个啥？它是一个属性还是一个方法（函数）？
> 
> 想明白这件事之后，看看 #125 可以升华一下。

感谢老师，知道了。我怎么又犯了断章取义，直接忽视它的上面那段代码的毛病：
>def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()
self._prompt（） 是调用上面那段方法（函数)！

**Comment by neolee** [comment]
对哒！

另外建议你去看看 https://github.com/neolee/wop-community 主页上的文档，学会在问题和讨论中使用 Markdown 标签来标注代码段，会好看很多。
