### ISSUE TITLE
学习用书的使用遇到困难

### ISSUE THREAD

**Issue by yuxi0324** [neolee/wop-community#141]
Win10 的学习用书是如何安装的，然后如何用 jupyter lab 打开，我的方式是压缩到用户里，但是打不开。

![image](https://user-images.githubusercontent.com/68325748/87849681-ed8e1380-c91c-11ea-993b-ad4efefd4b42.png)
![image](https://user-images.githubusercontent.com/68325748/87849690-fda5f300-c91c-11ea-87b4-136da8828f2f.png)

**Comment by neolee** [comment]
首先你要自己创建一个空的目录，**比如**在 `C:\Users\{你的用户名}\Code`，注意这是打个比方，实际上的路径是在你的用户目录下的，然后把你下载（或者下载解压出来）的学习用书（*.ipynb 文件）放到这个目录里，然后在命令行里用 `cd` 命令进入上述目录，然后执行 `jupyter lab`，就好了。课程的指南里是**假定**你建立的目录位于 `C:\Users\username\Code\my-student-book`，所以是执行：

```shell
cd C:\Users\username\Code\my-student-book
jupyter lab
```

其中 `C:\Users\username\Code\my-student-book` 要替换成你实际创建和存放学习用书的那个目录。

你可能需要先看一下支线课程里的第一讲，理解一下目录、文件和命令行的“当前工作目录”概念。

p.s. 问题的标题不要太长，详细说明放到正文里吧。
