### ISSUE TITLE
第一阶段大作业要求 & 社会化大作业

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#143]
## 作业&要求
* <img width="1440" alt="截屏2020-07-18 下午9 47 33" src="https://user-images.githubusercontent.com/57254889/87854211-e4b03880-c942-11ea-84d1-d4703e8de7cf.png">
* <img width="1440" alt="截屏2020-07-18 下午9 49 37" src="https://user-images.githubusercontent.com/57254889/87854239-22ad5c80-c943-11ea-98b1-a7c67042f297.png">

---

## 社会化大作业操作流程
-  <img width="1440" alt="截屏2020-07-18 下午9 54 11" src="https://user-images.githubusercontent.com/57254889/87854278-6902bb80-c943-11ea-980d-7b92b3ee0b14.png">
-  <img width="1440" alt="截屏2020-07-18 下午9 55 35" src="https://user-images.githubusercontent.com/57254889/87854284-71f38d00-c943-11ea-9dd5-42826f331948.png">
-  <img width="1440" alt="截屏2020-07-18 下午9 55 42" src="https://user-images.githubusercontent.com/57254889/87854298-8fc0f200-c943-11ea-99a0-8b8892d24ed3.png">

---

### 137#issue
* <img width="1440" alt="截屏2020-07-18 下午9 56 15" src="https://user-images.githubusercontent.com/57254889/87854310-a9fad000-c943-11ea-91fc-1081e82d19bc.png">

**交作业**地址，请打开下面👇的issue。
#137

**Comment by Shawnnn** [comment]
https://gist.github.com/Shawnnn/015f6d1e28bae5158fe0b8f4069eac0a

**Comment by neolee** [comment]
@Shawnnn 你贴错地方啦
