### ISSUE TITLE
已安装 termcolor 运行时依然报错

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/wop-community#145]
![Uploading 87867649...]()![Uploading 87867652...]()

尝试了重启kernel，重新运行代码问题依旧。

**Comment by Royhowtohack** [comment]
![image](https://user-images.githubusercontent.com/52094557/87867683-26cc8f00-c9c2-11ea-8260-19f0d2792299.png)![image](https://user-images.githubusercontent.com/52094557/87867686-2c29d980-c9c2-11ea-94d4-0539dbcccc7c.png)

**Comment by neolee** [comment]
这一般是因为你安装 termcolor 和 Jupyter Lab 运行的 Python 环境不一致导致的。

检查一下你的 Jupyter Lab 运行的 kernel 是哪一个，并执行下面的命令看看：

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by Royhowtohack** [comment]
> 这一般是因为你安装 termcolor 和 Jupyter Lab 运行的 Python 环境不一致导致的。
> 
> 
> 
> 检查一下你的 Jupyter Lab 运行的 kernel 是哪一个，并执行下面的命令看看：
> 
> 
> 
> ```shell
> 
> which python

> ![image](https://user-images.githubusercontent.com/52094557/87892220-1d4d3080-ca6f-11ea-9132-fb199d32e2cc.png)
> which python3
> 
> python -V
![Uploading 87892262...]()
> 
> python3 -V
![Uploading 87892270...]()
> 
> pip -V
> 
> pip3 -V
> 
> ```

**Comment by Royhowtohack** [comment]
python -V
![image](https://user-images.githubusercontent.com/52094557/87892380-8634a880-ca6f-11ea-8b05-029e3ba5f94a.png)
> 
> python3 -V
![image](https://user-images.githubusercontent.com/52094557/87892420-a06e8680-ca6f-11ea-9ebb-e21186dcd330.png)
> 
> pip -V
> 
Command not found:pip 
> pip3 -V
![
> 
> ```

我的系统里存在两个版本的python， python 3.74是用离线安装包装的。我不知道怎么卸载2·X的版本。那个好像是系统自带的

**Comment by Royhowtohack** [comment]
截图上传了好几次才成功。我用的iPad客户端，老是说上传失败。

**Comment by neolee** [comment]
你输入的命令错了，那个 `-V` 要大写的。

从前面两个命令的结果看，你的 python 和 python3 都不是按照课程的指南安装的。你的环境咋准备的？

**Comment by Royhowtohack** [comment]
<img width="893" alt="Screen Shot 2020-07-20 at 11 40 44" src="https://user-images.githubusercontent.com/52094557/87898605-2f37cf00-ca81-11ea-9565-1f4f9bf99d18.png">
<img width="867" alt="Screen Shot 2020-07-20 at 11 52 50" src="https://user-images.githubusercontent.com/52094557/87898609-31019280-ca81-11ea-9daf-1d12da977b88.png">
我重新看了一遍环境配置，我homebrew和pip都重装了。问题没解决。
<img width="931" alt="Screen Shot 2020-07-20 at 12 05 59" src="https://user-images.githubusercontent.com/52094557/87898661-6312f480-ca81-11ea-8b15-0273252f9837.png">

**Comment by neolee** [comment]
你跟着我的思路走，不要自己乱走，OK？

打开一个干净的命令行窗口，按顺序一个个执行下面的命令，千万不要输错命令，然后截**一个**图给我看就行了，别的什么也别做，也别多截别的图。

```shel
echo $PATH
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by Royhowtohack** [comment]
<img width="587" alt="Screen Shot 2020-07-20 at 14 13 42" src="https://user-images.githubusercontent.com/52094557/87905474-38ca3280-ca93-11ea-82fb-8b23fa4f419b.png">

好的

**Comment by neolee** [comment]
还有一个呢？`echo $PATH` 这个？

**Comment by Royhowtohack** [comment]
<img width="639" alt="Screen Shot 2020-07-20 at 14 51 04" src="https://user-images.githubusercontent.com/52094557/87908104-75e4f380-ca98-11ea-948e-8daa3065d201.png">

**Comment by neolee** [comment]
所以你安装在 `/Library/Frameworks/Python.framework/Versions/3.7` 目录下的 Python 环境是怎么装的？你现在缺省的 Python 环境是这个，而不是你在 Homebrew 装的。

如果你确定用这个环境，也没问题，注意几点：
1. 永远用 `pip3 install xxx` 来安装 Python 的第三方软件包，用 `python3 xxx.py` 来运行你的 Python 程序；
2. 在 Jupyter Lab 或者 nteract 或者 Visual Studio Code 中注意确认也配置使用这个 Python 环境，比如 Jupyter Lab，在你打开的 notebook 的右上角有你目前使用的 Python 环境，点击可以确认和切换。

**Comment by Royhowtohack** [comment]
> 所以你安装在 `/Library/Frameworks/Python.framework/Versions/3.7` 目录下的 Python 环境是怎么装的？

>


在环境配置的的视频里有说可以直接去Python的官网下载，我是那样安装的。
<img width="1677" alt="Screen Shot 2020-07-20 at 18 02 39" src="https://user-images.githubusercontent.com/52094557/87925705-4099cf00-cab3-11ea-9e79-4ae532894ef9.png">




> 2. 在 Jupyter Lab 或者 nteract 或者 Visual Studio Code 中注意确认也配置使用这个 Python 环境，比如 Jupyter Lab，在你打开的 notebook 的右上角有你目前使用的 Python 环境，点击可以确认和切换。
>

只有一个可选，python3
<img width="1322" alt="Screen Shot 2020-07-20 at 18 03 43" src="https://user-images.githubusercontent.com/52094557/87925786-5e673400-cab3-11ea-8c19-e07d95e6ad4e.png">


现在怎么办呢

**Comment by Royhowtohack** [comment]
> 1. 永远用 `pip3 install xxx` 来安装 Python 的第三方软件包，用 `python3 xxx.py` 来运行你的 Python 程序；
<img width="572" alt="Screen Shot 2020-07-20 at 18 06 34" src="https://user-images.githubusercontent.com/52094557/87926090-c6b61580-cab3-11ea-84a0-c1160d90ec45.png">

termcolor 是用pip3 安装的，Jupyter lab 也是用的 python3的kernel。 是因为terminal 默认用的是python2.X吗。 下一步不知道怎么办了。

**Comment by neolee** [comment]
你的 Jupyter Lab 也是用 `pip3 install jupyterlab` 安装的吧？如果不是需要执行前面这句来安装。如果是的话——

首先关闭 Jupyter Lab，在命令行执行 `python3 -m ipykernel install`，然后在重新执行 `jupyter lab` 试试。

**Comment by Royhowtohack** [comment]
> 
> 首先关闭 Jupyter Lab，在命令行执行 `python3 -m ipykernel install`，然后在重新执行 `jupyter lab` 试试。

搞定了，终于不报错了。多谢李老师耐心指导。不过我运行之后字体颜色并没有改变。
<img width="594" alt="Screen Shot 2020-07-20 at 21 17 30" src="https://user-images.githubusercontent.com/52094557/87942465-32f24280-cacf-11ea-9fcf-4677f6313121.png">
<img width="1199" alt="Screen Shot 2020-07-20 at 21 21 28" src="https://user-images.githubusercontent.com/52094557/87942481-3a195080-cacf-11ea-81ff-141481bfc88e.png">

尝试了restart kernel and clear all outputs。

**Comment by neolee** [comment]
这个变色在 notebook 里是看不出的，你要按照我上课的操作，把代码集中到一个 xxx.py 文件中，然后在命令行用 `python xxx.py` 才会有效果啊。

**Comment by Royhowtohack** [comment]
哦对， being an idiot.
