### ISSUE TITLE
print 函数里再嵌套一个函数

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#146]
错误的代码：
###
class Bot:

    wait = 1

    def __init__(self):
        self.q = ''
    
    def _think(self, s):
        return s

    def _say(self, s):
        time.sleep(Bot.wait)
        print(s)
    
    def run(self):
        print(_say(self.q))
        self.a = input()
        print(_say(self._think(self.a)))
###

正确的代码：
###
class Bot:

    wait = 1

    def __init__(self):
        self.q = ''
    
    def _think(self, s):
        return s

    def _say(self, s):
        time.sleep(Bot.wait)
        print(s)
    
    def run(self):
        self._say(self.q)
        self.a = input()
        self._say(self._think(self.a))
###

老师，我理解的print函数里再嵌套一个函数是可行的，为什么这里运行会报错_say这个函数没有定义呢？

**Comment by neolee** [comment]
要用 `self._say()`。

不过你这个嵌套有问题，因为 `_say()` 里面已有 `print()` 了，为啥外面还要套一个呢？
