### ISSUE TITLE
怎样安装 termcolor? 

### ISSUE THREAD

**Issue by onthebus98** [neolee/wop-community#148]

**Comment by neolee** [comment]
在命令行执行 `pip install termcolor`

**Comment by onthebus98** [comment]
同样的命令试过几次,都没有成功.提示:SyntaxError: invalid syntax
查看可用的modules也没有找到termcolor. 我可能是在python2 的目录下操作的. 
重启电脑,进到code 目录下,安装才成功了供大家参考.谢谢老师.

**Comment by tyler1zhang** [comment]
这个命令的使用，并不局限于在哪个目录下。你是不是最开始命令输入的不对，比如单词写错了。

**Comment by YunHang1010** [comment]
> 同样的命令试过几次,都没有成功.提示:SyntaxError: invalid syntax
> 查看可用的modules也没有找到termcolor. 我可能是在python2 的目录下操作的.
> 重启电脑,进到code 目录下,安装才成功了供大家参考.谢谢老师.

尝试执行下pip3 install termcolor 试试
