### ISSUE TITLE
案例学习之三 Web 服务 - 关于云服务和域名

### ISSUE THREAD

**Issue by Shawnnn** [neolee/wop-community#15]
我在看案例学习之三 Web服务，看到需要有云服务器，还用到了域名。

![image](https://user-images.githubusercontent.com/15227825/85947422-e477db00-b94a-11ea-94de-5a3355975d0f.png)

为了跟着课程走，是不是要买云服务、购买域名并备案？

我大概搜索了一下，有如下参考
[配置域名和服务器-如何搭建个人网站](https://blog.csdn.net/liqing0013/article/details/82898804)
[注册好域名了，怎样开始做网站？](https://www.zhihu.com/question/30041027)

**Comment by neolee** [comment]
你这个也太超前了吧？

**Comment by zed-wong** [comment]
> 我在看案例学习之三 Web服务，看到需要有云服务器，还用到了域名。
> 
> ![image](https://user-images.githubusercontent.com/15227825/85947422-e477db00-b94a-11ea-94de-5a3355975d0f.png)
> 
> 为了跟着课程走，是不是要买云服务、购买域名并备案？
> 
> 我大概搜索了一下，有如下参考
> [配置域名和服务器-如何搭建个人网站](https://blog.csdn.net/liqing0013/article/details/82898804)
> [注册好域名了，怎样开始做网站？](https://www.zhihu.com/question/30041027)

助教上场
国内的服务器和域名才需要备案，国外的就不用备案
[vultr服务器](https://www.vultr.com/?ref=7738352)
[免费的Tk后缀域名](http://www.dot.tk/)

**Comment by tyler1zhang** [comment]
可以试试一些免费的云试用。我用过华为云来跑老师给的示范程序。但是因为我在新加坡，所以也不清楚国内有没有别的要求。如果有，就改一下你的ip对应的地址应该可以解决吧。
