### ISSUE TITLE
关于大作业中的两个问题

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#150]
- **问题1**

![1595178036698](https://user-images.githubusercontent.com/52586220/87880846-890bab00-ca27-11ea-8b2d-33ff17c1416b.jpg)
     Bot类的init方法里有一个参数`self.q`，q是个参数为什么不写进括号里？即`def __init__(self, q):`
     这个又是什么回事？
·
·
·
·

- **问题2**

<img width="171" alt="image" src="https://user-images.githubusercontent.com/52586220/87880866-b5bfc280-ca27-11ea-9031-6a20344910f8.png">  

<img width="280" alt="image" src="https://user-images.githubusercontent.com/52586220/87880874-c839fc00-ca27-11ea-94b5-d73d29bd4e46.png">

   在Bot类里已经定义了一个类变量 `wait = 1`,那为什么还要在Garfield类的init方法中还要添加一个参数wait=1?——   (`def __init__(self, wait=1):`)
   子类bot不是已经使用了父类Bot中的变量和方法了吗？

**Comment by neolee** [comment]
1. `self.q` 不是参数，而是对象属性，是隶属于 Bot 类型对象的，而 `self` 就指代那个对象，所以写成 `self.q` 的样子，和普通的变量 `q` 是两回事。

2. 第一个 `wait = 1` 定义的是 Bot 类的一个类属性，可以用 `Bot.wait` 来访问；第二个（函数输入参数表里的） `wait=1` 是个输入参数，`=1` 表示这个参数是可选的，如果调用函数时不提供这个参数则其取缺省值 `1`。看着一样的东西放在不同地方含义可能完全不同。

**Comment by gaoteng-pro** [comment]
## 问题1
1. `self.q = ' '`这是一个 **赋值语句**，左侧是一个变量，所以`self.q`是一个变量，而不是参数。
2. 个人理解，参数其实是一个值。
3. 参数在函数的参数列表里的时候，还像一个变量；但在函数体内，参数是已经被赋值，是一个**值**。如：
```python
def add(a,b):
    c = a + b
    return c
```
4. 函数体内 `c = a + b`这句是一个**赋值语句**，左边的**c**是变量，右边的**a**和**b**是一定得是值。**a**和**b**在参数列表的时候是参数，一旦到函数体内，就是值。
5. 两种形式的函数：
```python
def __init__(self):
    self.q = '...'
```
和
```python
def add():
    q = '...'
```
6. 普通函数的变量，就是直接写变量；类定义函数中的**变量**，要在变量的前面加上**self.**。两者都是变量，只不过格式不一样。

**Comment by tyler1zhang** [comment]
首先你对**参数**和**属性**两个词在程序里面的定义有点混淆。每个类定义的模块，或者函数定义的模块都可以想象成一个黑箱子。**参数**是指那些输入到**黑箱**的**变量或值**。 属性是这个黑箱里面的一些黑箱固有的**变量或值**。 这些**变量或值**具体出现的位置，非常依赖你当初的设计初衷。 如果它非常稳定，基本上不会需要外部修改**值**， 那么它通常是个**属性**。如果它比较稳定，但我们希望可以给用户赋予修改值的权利，那我们通常是让它是个**缺省（也就是默认）输入参数**， 如果它非常不稳定，完全需要依赖外部的输入，那么它一般需要是个**输入参数**。 

* 问题1 

这里的 `self.q` 的 `q` 是这个Bot类将来会产生的对象object的一个属性，它并不是从外部输入的值，所以它不是个参数。 由于我们在从子类HelloBot和GreetingBot抽象成父类Bot的过程要保证结构的一致性， `self.q` 本来是**类的对象的属性**，而不是个初始化时输入的参数，所以父类Bot最终是你给的图中的样子。

<img width="986" alt="Screenshot 2020-07-20 at 11 52 51 AM" src="https://user-images.githubusercontent.com/49228317/87898151-f8ad8480-ca7f-11ea-87ea-7c2bf2aa9b32.png">

对于每个子类， `self.q` 都非常稳定，不需要进行变化，不同的机器人给出的第一个问题是固化的。所以我们把这些固化的值，可以写成一个**属性**。（补充一下，如果这个属性是所有的类共有的，它才应该是个**类属性**，否则一般是**对象的属性**）。

* 问题2

Garfield 类和Bot类是个从属关系，有点像老板和员工。首先 `Bot.wait` 是个类属性，是我们用各种子类（HelloBot, GreetingBot,....)的时候都共同用到的，所以是个类属性。我们在定义Bot的时候，先给这个类属性一个缺省（也就是默认）值 `1` 。 

```python
class Bot:

    wait = 1
```

然后，作为老板，Garfield在使用这些机器人的时候，我们想赋予Garfield更改 `Bot.wait` 的权利，虽然大部分情况下默认值足够用了，谁叫他是老板呢。基于上面的思考和设计，Garfield初始化的时候给了一个缺省参数，这个缺省参数默认值是1。 你完全可以使用Garfield的时候给他一个2的值，正如课程视频里演示的。 

这时候，你可能会问：“那我如果需要修改 `Bot.wait` ，直接修改它不就可以了？为什么还要加在Garfield里面？” （这个应该是问题2的思考逻辑）。这主要是为了**高内聚，低耦合**，Bot类和其他的子类的所有的参数都是封装好的，并不是面向用户的；真正面向用户的是他们的老板Garfield。基于这种原因，用户一般不直接修改Garfield使用的那些类的各种变量和值。用户只需要使用Garfield就好，不需要去管Garfield怎么去修改这个参数。 

老师在设计这些代码的时候，很多**变量和值**的位置都已经进行了设计（可能已经肌肉记忆），它出现在这个位置，确实是有原因的。

**Comment by gaoteng-pro** [comment]
> 每个类定义的模块，或者函数定义的模块都可以想象成一个黑箱子。参数是指那些输入到黑箱的变量或值。 属性是这个黑箱里面的一些黑箱固有的变量或值。 这些变量或值具体出现的位置，非常依赖你当初的设计初衷。 如果它非常稳定，基本上不会需要外部修改值， 那么它通常是个属性。
1. 如果函数或类是一个黑箱，那么传入黑箱的只能是值，变量不可以传入黑箱吧。
2. 属性和稳定不稳定没关系吧。

**Comment by neolee** [comment]
> 1. 如果函数或类是一个黑箱，那么传入黑箱的只能是值，变量不可以传入黑箱吧。
> 2. 属性和稳定不稳定没关系吧。

关于函数的调用和传参补充一下：
- 函数的作用是通过输入计算出输出；
- 函数的输入和输出都是值；
- 定义函数时还不知道输入的值具体是什么，就用参数变量来指代。

**Comment by Liujiale02** [comment]
@tyler1zhang @neolee 谢谢老师和同学，你们的回答真是超量级的。可能我的问题表达得不够清晰，但是你们帮我理顺了概念，太棒了。
