### ISSUE TITLE
把引号去掉，返回的是变量吗？

### ISSUE THREAD

**Issue by girlfriendandme** [neolee/wop-community#151]
[](url)
![image](https://user-images.githubusercontent.com/48598963/87898275-58a42b00-ca80-11ea-99f6-52757ae21964.png)

如题，不太明白，问一下老师

**Comment by neolee** [comment]
`bool` `int` `float` `str` 这些其实都是“值”，是 Python 自带的表示数据类型的一些固有的值，它们的类型是 `type`。

**Comment by girlfriendandme** [comment]
懂了懂了，我一开始还以为能返回一个字母组合，原来是返回一个“值”，谢谢老师呀！！
