### ISSUE TITLE
print() 的作用在哪里？

### ISSUE THREAD

**Issue by liushui0712** [neolee/wop-community#153]
def _prompt(self,t):
    print(t)
    print()         #  **这个print是干嘛的?**删除后依然可以成功运行
  def run(self):
    self._prompt(''' This is Garfield dialog system.
    Let's talk! ''')

**Comment by tyler1zhang** [comment]
这里`print()`的作用是打印一个空行。 为了和之后的对话分开，表示为两个部分。

**Comment by liushui0712** [comment]
> 这里`print()`的作用是打印一个空行。 为了和之后的对话分开，表示为两个部分。
啊哈，好吧～～谢谢。
