### ISSUE TITLE
大作业中 Bot.wait 值的问题

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#155]
```python
import time

class Bot:
    
    wait = 1
    
    def __init__(self):
        self.q = ''
        self.a = ''
        
    def _think(self, s):
        return s
    
    def run(self):
        time.sleep(Bot.wait)
        print(self.q)
        self.a = input()
        time.sleep(Bot.wait)
        print(self._think(self.a))


class Garfield:
    
    def __init__(self, wait=5):
        Bot.wait = wait
        self.bots = []

    def add(self, bot):
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()
```
这两个类的代码都执行后，为什么 `Bot.wait` 的值还是1呢？`class Garfield:` 的类中，不是已经把5赋值给`Bot.wait` 了吗？

**Comment by neolee** [comment]
`def __init__(self, wait=5):` 这是一个定义函数时的特殊语法（我们很快就会讲到），它的意思是：这个函数有个叫 `wait` 的参数，但这个参数是可选的，如果调用时传了这个参数的值那么就用传进来的值，如果调用时没传这个参数的值那就用缺省值 `5`。

所以这里并没有给 `wait` 赋值，也还没执行 `Bot.wait = wait`。

**Comment by Liujiale02** [comment]
如果我要将时间变成5，最好的办法是把外面的代码改成--`garfield = Garfield(5)`，括号里输入5就行了？

是这样理解吧？

**Comment by sujuxiaoren** [comment]
> garfield = Garfield(5)



> 如果我要将时间变成5，最好的办法是把外面的代码改成--`garfield = Garfield(5)`，括号里输入5就行了？
> 
> 是这样理解吧？

不用输，直接`garfield = Garfield()` 就可以了吧

**Comment by neolee** [comment]
@Liujiale02 

@sujuxiaoren 同学说的对，如果你希望设置为 5，那就什么都不用输，直接 `garfield = Garfield()`，`__init__()` 会自动按照 `wait=5` 的缺省值执行；如果你希望设为其他数值，就需要提供这个参数的具体指，比如 `garfield = Garfield(1.5)` 或者 `garfield = Garfield(wait=1.5)`。
