### ISSUE TITLE
大作业中的函数抽象

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#156]
想问一下老师的心得，就是老师在演示大作业的时候，想到一个功能的时候，可以随手把函数进行拆解、组装。

比如当父类**run函数**需要加两个**time.sleep**的时候，老师构造了一个 **_say函数**；需要加颜色显示的时候，又创建一个 **_format函数** ，接着又把这个 **_format函数**  融入到 **_say函数**。感觉就是整套动作已经是肌肉记忆，行云流水。就是需要的时候拆、组装，**而且**不同函数的输入参数之间转换自由。

如何做到的，有什么心得没？自己感觉反应不过来。**如何进阶？**

**Comment by tyler1zhang** [comment]
我觉得老师在抽离并构建这两个函数的时候，主要的出发点是避免重复代码，便于迭代。 静等老师的解释

**Comment by neolee** [comment]
有兴趣可以去看看 *Refactoring - Improving the Design of Existing Code* 这本书，中译本大概叫《重构》。

你描述的这个操作叫 *method extraction*，就是把一段代码抽取出来做成一个函数，把它原来出现的地方替换成新函数的调用。

这个没啥花样，就是多做，技止熟尔。关键在于发现需要这么做的地方，我上课也说了，重复的代码是好程序员都会很敏感地厌恶的，一开始你们可能没这个感觉，那就按照自己的想法先做，当你发现你要在好多个地方加上一模一样的一句 `time.sleep(1)` 并感觉很烦的时候，就差不多是要悟了。

对了，上面说的那本书里的第三章专门列举了不少代码里的“不好的气味”，就算后面不仔细看，这个第三章都很值得看。
