### ISSUE TITLE
Visual Studio Code 的波浪线提示功能

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#158]
课程大练习#1的视频课程中，老师演示的 visual studio code ，如果前面没有 `import random` 的话，下面的代码，`random` 下会有波浪线，但我的 visual studio code 不会出现波浪线的提示，这个功能是需要安装什么插件的吗？

**Comment by neolee** [comment]
你第一次打开一个 .py 文件的时候 Visual Studio Code 会提示你安装官方的 Python 插件，那个就可以。

最近 Microsoft 又开发了一个叫 Pylance 的升级版插件，也可以试试。

**Comment by Amy20191** [comment]
老师说的是下面这个插件吗？打开 .py 文件的时候，电脑屏幕右下角跳出的。
![image](https://user-images.githubusercontent.com/57065555/88056306-ef610c80-cb92-11ea-952b-ecc309f3cb43.png)
我点击了安装后，出现下面这样的，是安装不成功吧？这是什么原因呢？我的是Windows 10 系统。
![image](https://user-images.githubusercontent.com/57065555/88056411-13245280-cb93-11ea-9995-95fec4674101.png)

**Comment by neolee** [comment]
这个是 Linter，不装也没啥，你打开 VSCode 侧边栏里插件那个按钮，在里面看看有没有 Python，有就可以了。

**Comment by Amy20191** [comment]
![image](https://user-images.githubusercontent.com/57065555/88058470-1836d100-cb96-11ea-899d-cb7eeafef237.png)
Python 这个插件有安装过的，但是波浪线的提示功能还是没有。
