### ISSUE TITLE
关于类 Animal 开头字母大小写的疑惑？

### ISSUE THREAD

**Issue by Kuo-Ran** [neolee/wop-community#159]
第一阶段：
    第四讲：面向对象·续

第一题作业：‘类定义与对象创建’ 中  ‘父类、子类、继承与多态’ 部分

for animal in [a, c, d]:
    print(animal.name, ':', animal.voice())

animal 开头字母为什么不大写？

**Comment by Kuo-Ran** [comment]
![1595340810626](https://user-images.githubusercontent.com/68600053/88065651-74522300-cb9f-11ea-8d1f-b6c174ae5011.jpg)

**Comment by neolee** [comment]
在那个例子里 `Animal` 是类名，而 `animal` 是在循环 `for animal in [a, c, d]:` 中定义的循环变量。

Python（以及大部分现代编程语言）都是区分大小写的，`Animal` 和 `animal` 是完全不同的名字。

**Comment by Kuo-Ran** [comment]
明白了，谢谢老师。
