### ISSUE TITLE
关于 VS Code 的一些问题

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#16]
老师，我发现一个问题：每次开机在终端里，通过输入命令想打开vs code失败，如下图。

<img width="346" alt="image" src="https://user-images.githubusercontent.com/52586220/86032889-a40f7e80-ba6a-11ea-88e2-7b53dd0c1f5b.png">

但是如果我在vs code软件内部设置一下，又可以通过终端输入命令可以打开，如下面两图

<img width="905" alt="image" src="https://user-images.githubusercontent.com/52586220/86033209-2ac45b80-ba6b-11ea-9821-44e176eb82b3.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/52586220/86033371-6c550680-ba6b-11ea-827a-09ac9b2aff4d.png">

这种情况正常吗？能不能设置一直可以打开vs code的？我用的是mac系统。

**Comment by neolee** [comment]
这个现象不正常，应该是一次设置就好了。

以前有同学碰到过这个问题，应该是你的 VS Code 没放进你系统的 /Applications 目录下导致的，Mac 系统里安装一个应用，要把那个应用拖到 /Applications 里才行。
