### ISSUE TITLE
对象中的属性

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#160]
```python
class HelloBot(Bot):
    def __init__(self):
        self.q = "What's your name?"
        
    def run(self):
        self.a = input()
```
毫无疑问，在`__init__`方法中的`self.q`是属性，那么在`run`方法中的`self.a`是什么呢？

进一步，如果想在其他类定义中，引用`HelloBot`的`q`属性，可以直接在其他类定义中写`HelloBot().q`即可，那如果想在其他类定义中引用`HelloBot`的`self.a`的值呢？

**Comment by neolee** [comment]
当然也是属性啦。Python 是高度动态化的语言，可以在任何时候随便给对象加属性，在类定义里任何方法里都可以定义属性，已经定义就能使用；在类定义外面也可以对特定对象实例增加属性。

**Comment by xuzhengfu** [comment]
我们的所有困惑或许都出自以下这点：

```python
x = HelloBot()
print(x.a)

--> AttributeError: 'HelloBot' object has no attribute 'a'
```

在对 HelloBot 进行实例化之后，解释器 "竟然" 还告诉我：'HelloBot' object has no attribute 'a'

这是咋回事？a 不是 x 的属性吗？

个中原因在于：HelloBot 已经对 Bot 的 `__init__` 方法进行了覆写。这即意味着说：在对 HelloBot 进行实例化之后，我们事实上有且仅有一个 `self.q` 的属性，并没有 `self.a` 这个属性。

如果想在其他类定义中使用 HelloBot 的 `self.a` 的值，我们必须先对 `self.a` 做初始化。

**Comment by gaoteng-pro** [comment]
1. 
```python
class HelloBot:
    def __init__(self):
        self.q = 'What is your name?'
        
    def run(self):
        self.a = input()

h = HelloBot()
print(h.q)
h.run()
print(h.a)
```
---
2. 
```python
class HelloBot:
    def __init__(self):
        self.q = 'What is your name?'
        
    def run(self):
        self.a = input()
        
print(HelloBot().q)
HelloBot().run()
print(HelloBot().a)
```
上述两个的区别，仅仅在于是否把实例化的对象赋值给一个变量。结果却大相径庭，把对象赋值给变量的，运行之后，可以把`self.a`的值打印出来；而没有把实例化的对象赋值给变量的，一样运行之后，会报错:`'HelloBot' object has no attribute 'a'`

我的初衷就是，想在其他的类中，使用`HelloBot`里面的**名字**，也就是`self.a`的值。但怎么构建，也没法引用`HelloBot`里的`self.a`的值。

**Comment by xuzhengfu** [comment]
那是因为第二段代码分别独立进行了三次实例化，互不相干。

所以，对于 “在其他的类中，如何使用 HelloBot 里面的 self.a 的值” 这个问题，你再想想？

**Comment by gaoteng-pro** [comment]
哦，对于第一个问题理解了。

基于上述的理解，对于如何在其他类中使用HelloBot的self.a的值，那只有先把对象实例化之后，赋值给一个变量。但这样做之后，还是一样的报错。

部分代码如下：
```python
stella = Stella()
h = HelloBot()
g = GreetingsBot()
f = FavoriteColorBot()
c = CalcBot()
ga = GamblingBot()
stella.add(h)
stella.add(g)
stella.add(f)
stella.add(c)
stella.add(ga)
Stella.run()
```
我想在GamblingBot()里一开始输出，`Hello 名字，Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit.`于是我这样写了：
```python
class GamblingBot(Bot):
    
    def __init__(self):
        self.q = f"Hello {h.a}.Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit."
```
结果还是报错：`AttributeError: 'HelloBot' object has no attribute 'a'`

实例化赋值给变量之后，仍然无法使用`HelloBot`里`self.a`的值？

**Comment by neolee** [comment]
其实对象的属性也是变量，`x.a` 和一个普通的变量 `foo` 没什么本质区别，唯一区别就是 `x.a` 说明这个变量“有主”，是隶属于对象 `x` 的。

既然是变量，那就必须符合我们一开始讲“值、变量和类型”时的通用规则：任何变量在使用前必须初始化。所以你必须在使用 `x.a` 前必须至少给它赋值一次。所以你在是用它之前要想想是不是在某处已经给它赋值过了，如果没有那就会出错。

另外一个要点是：你在类定义里写的类的方法（函数）的定义，它们只是定义，还没有被执行过。比如你在 `Bot` 类的 `run()` 方法里给 `a` 这个属性进行了第一次赋值，那么在你创建 `Bot` 类的实例对象 obj 并调用它的 `obj.run()` 方法之前 `obj.a` 就还没有初始化，自然无法使用。

所以一个良好习惯是：**对于外部可能使用的属性，最好在 `__init__()` 方法中进行初始化**，因为这个方法是创建实例对象时一定会被调用的，可以确保里面初始化的属性总是可用的。

**Comment by xuzhengfu** [comment]
> When a class defines an __init__() method, class instantiation automatically invokes __init__() for the newly-created class instance. [[1]](https://docs.python.org/3/tutorial/classes.html#class-objects)

你的代码事实上在运行到 `ga = GamblingBot()` 时就会报错（因为 self.a 还没有被初始化），根本不会执行后面的指令。

**Comment by gaoteng-pro** [comment]
一开始的时候，我就在`__init__`写了`self.a = input（）`，但这样的结果就是，在调用`Bot`类的`run（）`方法的时候，首先不是打印`What is your name？`，而是直接跳出对话框，让你输入。你输入之后，才打印`What is your name？`。
- - -
对于`self.a`没被运行？所有`bot`的`run`都是顺序执行的，先执行的是`HelloBot`的`run（）`，然后才运行其他的`Bot`的`run（）`。

所以，到底如何才能在其他类中用到`HelloBot`的**self.a**的值？

**Comment by neolee** [comment]
不是，你在 `__init__()` 里初始化 `self.a` 的话，不要用 `input()` 啊，这个函数是要用户输入的时候才需要调用的，应该用在 `run()` 方法里。如果你想在 `__init__()` 里初始化 `self.a` 的话，应该这么写：

```python
class Bot:
    def __init__(self):
        self.q = ''
        self.a = ''
        
    def run(self):
        print(self.q)
        self.a = input()
        ...
```

p.s. 其实并不需要这么做，因为按照我们的设计 `self.a` 这个属性也就只在 `run()` 里面需要用到，并不需要提前初始化；甚至把它做成了 `run()` 里面的临时变量都没问题（你可以自行验证）。

**Comment by xuzhengfu** [comment]
在不改变你其他代码的前提下，你可以往 GamblingBot 的 `__init__` 方法中添加一句：

```py
class GamblingBot(Bot):
    
    def __init__(self):
        h.run()
        self.q = f"Hello {h.a}.Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit."
```

需要提醒你的是，你上面代码的最后一句 `Stella.run()`，`Stella` 应该是小写。

当然，这样的代码运行起来会很乱。原因在于，你已经改变了 Bot 类最初定义时的执行逻辑。

**Comment by gaoteng-pro** [comment]
@Xuzhengfu 你这样岂不是还要再输入一遍**name**。

计算的那个`Bot`的`run`方法，因为要加入循环，不也得覆盖吗？加功能了，该覆盖也得覆盖吧。老师的做法相对更优雅，不用再输入一遍**name**。

**Comment by gaoteng-pro** [comment]
@neolee 如果`self.a`不做成属性，下面其他类引用起来会很麻烦，甚至都不知道如何引用这个`self.a`
值。如果只是在这个`HelloBot`类里使用无所谓。

**Comment by xuzhengfu** [comment]
所以，对于你最初的那个问题 “到底如何才能在其他类中用到HelloBot的self.a的值？”

把你的解决方法（完整代码）贴出来看看？

**Comment by neolee** [comment]
> 如果 `self.a` 不做成属性，下面其他类引用起来会很麻烦，甚至都不知道如何引用这个 `self.a`
> 值。如果只是在这个 `HelloBot` 类里使用无所谓。

这就要看你的具体设计了，在我原来的设计里这个 `a` 基本上不会被其他地方用到，更不会（也不该）被子类用到，是完全封装到 `run()` 内部的。

**Comment by gaoteng-pro** [comment]
**先说结论**：python解释器真奇怪，老师@neolee的方法居然不行。 @Xuzhengfu 你的方法可行，代价是需要两次输入姓名，你一定要看一看运行的结果。如何才能更优雅，两次跳出对话框，输入一样的名字，感觉有点。。。

中午的时候没在家，没用电脑演示，只是逻辑上演示了一下，下面是电脑演示的结果。

以下代码是老师给的那个在`__init__`方法里加`self.a = ''`，因为`self.a = ''`运行后打印是空，为了更好展示`self.a = ''`的运行结果，我把`self.a = ''`换成了`self.a = 'apple'`。

发现在别的类中引用的`self.a `的值，只能是`self.a `在`__init__`方法里初始的值，无论后面怎么被赋值，在其他类中引用`self.a `的时候，只能显示`self.a `在`__init__`方法里初始的值。这一点和其他的变量不同。

可以看到`GamblingBot`第一句打印的是`Hello apple`而不是`Hello gaoteng`。

## 老师的方法及运行结果。

```python
import random
import time
from termcolor import colored
from simpleeval import simple_eval


class Bot:
    
    wait = 1

    def __init__(self):
        self.q = ''
        
    def _think(self,s):
        return s

    def _format(self,s):
        return colored(s,'blue')

    def _say(self,s):
        time.sleep(Bot.wait)
        print(self._format(s) ) 
        
    
    def run(self):
        self._say(self.q)
        self.a = input()
        self._say(self._think(self.a))
        print()


class HelloBot(Bot):
    
    def __init__(self):
        self.q = 'What is your name?'
        self.a = 'apple'
        
    def _think(self,s):
        return f'Hello {s}!'        


class GreetingsBot(Bot):
    
    def __init__(self):
        self.q = 'How are you today?'
        
    def _think(self,s):
        if ("good" in s.lower() ) or ("fine" in s.lower()) or ("great" in s.lower()):
            return 'Great!'
        else:
            return 'Sorry to hear that.'


class FavoriteColorBot(Bot):
    
    def __init__(self):
        self.q = "What's your favorite color?"
        
    def _think(self,s):
        colors = ['red','orange','yellow','green','blue','indigo','purple']
        a = random.choice(colors)
        if a == s.lower():
            return f"You like {s.lower()}? Me too! "
        else:
            return f"You like {s.lower()}? That's a beautiful color! My favorite color is {a}."


class CalcBot(Bot):

    def __init__(self):
        self.q = "Through recent upgrade I've learnt how to calculate.Input some arithmetic expression to try.If you want to exit,please enter x or q or exit or quit."

    def _think(self,s):
        result = simple_eval(s)   
        return f"Done.Result = {result}" 
    
    def run(self):
        
        while True:
            self._say(self.q)
            self.a = input()
            if ('x' or 'q' or 'exit' or 'quit') in self.a:
                break
            else:                
                self._say(self._think(self.a)) 


class GamblingBot(Bot):
    
    def __init__(self):
        self.q = f"Hello {HelloBot().a}!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit."
        
        
    def _think(self,s):
        self.dice = random.choice(['big','small'])
        if s == self.dice:
            return f'Result is {self.dice},You Win!'
        else :
            return f'Result is {self.dice},You lose!'
    
    def run(self):
        
        while True:
            self._say(self.q)
            self.a = input()
            if ('x' or 'q' or 'exit' or 'quit') in self.a:
                break
            else:                
                self._say(self._think(self.a)) 

            
class Stella:
    
    def __init__(self,wait=1):
        Bot.wait = wait
        self.bots = []
        
    def add(self,bot):
        self.bots.append(bot)
        
    def run(self):
        print("This is Stella dialog system.let's talk.")
        print()
        
        for bot in self.bots:
            bot.run()


stella = Stella()
stella.add(HelloBot())
stella.add(GreetingsBot())
stella.add(FavoriteColorBot())
stella.add(CalcBot())
stella.add(GamblingBot())
stella.run()
```
#### 老师代码运行结果：
```python 
This is Stella dialog system.let's talk.

What is your name?
 gaoteng
Hello gaoteng!

How are you today?
 good
Great!

What's your favorite color?
 red
You like red? Me too! 

Through recent upgrade I've learnt how to calculate.Input some arithmetic expression to try.If you want to exit,please enter x or q or exit or quit.
 x
Hello apple!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit.
 big
Result is big,You Win!
Hello apple!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit.
 x
```
## 正福的方法及运行结果
```python
import random
import time
from termcolor import colored
from simpleeval import simple_eval


class Bot:
    
    wait = 1

    def __init__(self):
        self.q = ''
        
    def _think(self,s):
        return s

    def _format(self,s):
        return colored(s,'blue')

    def _say(self,s):
        time.sleep(Bot.wait)
        print(self._format(s) ) 
        
    
    def run(self):
        self._say(self.q)
        self.a = input()
        self._say(self._think(self.a))
        print()


class HelloBot(Bot):
    
    def __init__(self):
        self.q = 'What is your name?'
        
    def _think(self,s):
        return f'Hello {s}!'        


class GreetingsBot(Bot):
    
    def __init__(self):
        self.q = 'How are you today?'
        
    def _think(self,s):
        if ("good" in s.lower() ) or ("fine" in s.lower()) or ("great" in s.lower()):
            return 'Great!'
        else:
            return 'Sorry to hear that.'


class FavoriteColorBot(Bot):
    
    def __init__(self):
        self.q = "What's your favorite color?"
        
    def _think(self,s):
        colors = ['red','orange','yellow','green','blue','indigo','purple']
        a = random.choice(colors)
        if a == s.lower():
            return f"You like {s.lower()}? Me too! "
        else:
            return f"You like {s.lower()}? That's a beautiful color! My favorite color is {a}."


class CalcBot(Bot):

    def __init__(self):
        self.q = "Through recent upgrade I've learnt how to calculate.Input some arithmetic expression to try.If you want to exit,please enter x or q or exit or quit."

    def _think(self,s):
        result = simple_eval(s)   
        return f"Done.Result = {result}" 
    
    def run(self):
        
        while True:
            self._say(self.q)
            self.a = input()
            if ('x' or 'q' or 'exit' or 'quit') in self.a:
                break
            else:                
                self._say(self._think(self.a)) 


class GamblingBot(Bot):
    
    def __init__(self):
        h.run()
        self.q = f"Hello {h.a}!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit."
        
        
    def _think(self,s):
        self.dice = random.choice(['big','small'])
        if s == self.dice:
            return f'Result is {self.dice},You Win!'
        else :
            return f'Result is {self.dice},You lose!'
    
    def run(self):
        
        while True:
            self._say(self.q)
            self.a = input()
            if ('x' or 'q' or 'exit' or 'quit') in self.a:
                break
            else:                
                self._say(self._think(self.a)) 

            
class Stella:
    
    def __init__(self,wait=1):
        Bot.wait = wait
        self.bots = []
        
    def add(self,bot):
        self.bots.append(bot)
        
    def run(self):
        print("This is Stella dialog system.let's talk.")
        print()
        
        for bot in self.bots:
            bot.run()


stella = Stella()
h = HelloBot()
g = GreetingsBot()
f = FavoriteColorBot()
c = CalcBot()
ga = GamblingBot()

stella.add(h)
stella.add(g)
stella.add(f)
stella.add(c)
stella.add(ga)

stella.run()

```
#### 正福代码运行结果
```python
What is your name?
 gaoteng
Hello gaoteng!

This is Stella dialog system.let's talk.

What is your name?
 gaoteng
Hello gaoteng!

How are you today?
 good
Great!

What's your favorite color?
 red
You like red? That's a beautiful color! My favorite color is purple.

Through recent upgrade I've learnt how to calculate.Input some arithmetic expression to try.If you want to exit,please enter x or q or exit or quit.
 x
Hello gaoteng!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit.
 big
Result is big,You Win!
Hello gaoteng!Let's start comparing big and small.Please enter big or small.If you want to exit,please enter x or q or exit or quit.
 x
```

**Comment by neolee** [comment]
这个问题有点复杂了，我需要写一个长一点的回复来解释。

首先，我之前没搞懂你要做什么，所以我的建议是在大练习的基本设计框架下给出的，在这个基本设计中，`self.a` 只在 `Bot` 类的 `run()` 方法中使用，甚至都不需要是个属性，做个普通变量都 OK（我下面的代码会演示这个思路），而且从我们的基本设计出发，这样做最好；其实我之所以在课上把 `self.a` 设计为一个属性，其实是希望有人提出并改进，将其改为 `run()` 内部的一个局部变量。

然后，简单分析下你的需求。你的需求其实是希望后面运行的某个 bot 使用前面运行的某个 bot 的属性，这个需求是在目前的设计框架下无法实现的，因为目前我们设计的 bot 是一种“无状态（_stateless_）”的模块，通俗地讲就是用完就扔，彼此之间无法访问的，之所以这么设计是为了简单清晰，避免干扰大家理解和练习基本知识点。

但是，你的需求并不过分，是个很合理、很正常的需求，对它的实现也有很标准的方法，这个方法就是使用一个公共变量保存运行过的 bot 的有共享需要的数据。这个公共变量放在那里好呢？从各方面来讲，都应该放在负责聚合装载 bot 的那个类里（你这里的 `Stella`），因为这个变量的生命周期和 `Stella` 类相同，`Stella` 类作为负责管理所有 bot 的类职责上也匹配。

而 @Xuzhengfu 同学的解决方案思路与上面说的一样，但实现方面就不对了，因为在特定类里使用了不受管理的全局变量，这是大忌。试想如果我们创建 `HelloBot` 实例时用的变量不叫 `h`，甚至我们没有加入 `HelloBot` 的实例，你的 `GamblingBot` 都会出错，这就好像我们做了个组件，但是对使用它附加了很多麻烦的限定，这无疑是很糟糕的。

最后给出一个我的参考实现，它遵循前述解决方案的思路，代码后面有一些简要说明：

```python
from time import sleep
from termcolor import colored
import random
from simpleeval import simple_eval


class Bot:

    wait = 1

    def __init__(self, session=None):
        self.session = session

    def _think(self, s):
        return s

    def _format(self, s):
        return colored(s, 'blue')

    def _say(self, s):
        sleep(Bot.wait)
        print(s)

    def _q(self):
        self.q = ''

    def run(self):
        self._q()
        self._say(self.q)
        a = input()
        self._say(self._think(a))


class HelloBot(Bot):

    def _q(self):
        self.q = "Hi, what is your name?"

    def _think(self, s):
        self.session['name'] = s
        return f"Hello {s}"

class FavoriteColorBot(Bot):

    def _q(self):
        self.q = "What's your favorite color?"

    def _think(self, s):
        colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'purple']
        return f"You like {s.lower()}? My favorite color is {random.choice(colors)}"

class CalcBot(Bot):

    def _q(self):
        self.q = f"Hi, {self.session.get('name', 'you')}! Through recent upgrade I can do calculation now. Input some arithmetic expression to try:"

    def _think(self, s):
        result = simple_eval(s)
        return f"Done. Result = {result}"

class Garfield:
    
    def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = [] # a list container for bots in system
        self.session = {} # a dict container for session data from bots

    def add(self, bot_class):
        bot = bot_class(self.session)
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()


if __name__ == '__main__':
    garfield = Garfield()

    garfield.add(HelloBot)
    garfield.add(FavoriteColorBot)
    garfield.add(CalcBot)
    
    garfield.run()
```

说明：
1. 在 `Garfield` 类中增加了 `session` 这个属性，用于保存任何需要跨 bot 共享的数据，这是一个 `dict` 类型的容器；
2. 修改了向 `garfield` 对象中添加 bot 的机制，原先是创建好一个 bot 对象作为参数传给 `add()` 方法加入进去，现在改为直接把 某个 bot 的类传给 `add()` 方法，在 `add()` 内用这个类来初始化对象，以便在初始化时将 `garfield.session` 传给该 bot；
3. 修改了 `Bot` 基类的 `__init__()` 方法，增加了 `session` 这个属性，并可以在实例化时设置 `session` 属性的值；第 2 和第 3 点合起来，使得所有加入到对话系统的 bot 都可以读写 `garfield.session` 这个属性；
4. 将 `self.q` 的定制从 `Bot` 类的 `__init__()` 方法中移出，转移到 `run()` 方法中，并做成了一个独立的方法 `_q()`，便于派生类自行定制；之所以要放到 `run()` 中去，是因为需求中希望在设置 `q` 属性的值时使用其他 bot 运行过后才有的数据；这一修改的额外好处是，以后派生类都不再需要重写 `__init__()` 方法了，这本也是我期待大家做出的一个改进点；
5. 顺便移除了 `Bot` 类的 `a` 属性，改为 `run()` 方法中的局部变量；
6. 对 `session` 内数据的使用有一定容错，即使你没加入 `HelloBot`，后面也不会出错，只会使用一个缺省值代替。

这个参考实现唯一超纲的是对 `dict` 字典容器的读写，但并不难懂，有兴趣预习下数据容器的第二章就能了解。但要真正理解上述要点也并不容易，有自信的同学可以挑战下。

**Comment by tyler1zhang** [comment]
花了好久时间才看懂1到6的解释。但是感觉离可以写出这种代码还有很远的距离。去优化自己的code去。

有一个想法：_q()这个方法可以直接return 一个String，然后可以移除self.q这个变量。

```python
    def _q(self):
        return '' # edit it in relative Bot class

    def run(self):
        self._say(self._q())
        a = input()
        self._say(self._think(a))

```

**Comment by HSChloe** [comment]
老师，garfield.add()中实例化对象时传入的self.session，和函数调用时传入的argument类似吗？如果类似，按照昨天讲的作用域，garfield.session是不是不会被bot改变？

**Comment by neolee** [comment]
> @tyler1zhang 还有一个想法：_q() 这个方法可以直接 return 一个 str，然后可以移除 self.q 这个属性。

完全可以。

> @HSChloe garfield.add() 中实例化对象时传入的 self.session，和函数调用时传入的 argument 类似吗？如果类似，按照昨天讲的作用域，garfield.session 是不是不会被 bot 改变？

啊哈，又挖到超前的话题了。昨天我上课是不是提了一句，等我们讲容器的时候会补充关于 scope 的更深入的规则？其实这里传递的 `session` 数据确实是穿越了 scope 边界，并且 `bot.session` 和 `garfield.session` 都指向同一个容器对象，这里面的原理到时候听课吧。

**Comment by tyler1zhang** [comment]
> 老师，garfield.add()中实例化对象时传入的self.session，和函数调用时传入的argument类似吗？如果类似，按照昨天讲的作用域，garfield.session是不是不会被bot改变？

不同类型的数据传入函数或类方法的副作用不同。先看一段代码

```python
i = 1
f = 1.0
t = True
s = "aaa"
l = [1,2]
d = {"a":1}

def add_element(initial_data, added_data):
    if isinstance(initial_data, int):
        initial_data += added_data
    elif isinstance(initial_data, float):
        initial_data += added_data
    elif isinstance(initial_data, bool):
        initial_data = False
    elif isinstance(initial_data, str):
        initial_data += added_data
    elif isinstance(initial_data, list):
        initial_data.append(added_data)
    elif isinstance(initial_data, dict):
        initial_data["additional"] = added_data
        
def check_effect(original_data, additional_data):
    print(f"{type(original_data)} original value is {original_data}.")
    add_element(original_data, additional_data)  
    print(f"Finally it became {original_data}. ")
    print()
    
check_effect(i, 1)
check_effect(f, 0.01)
check_effect(t, 0)
check_effect(s, "bbb")
check_effect(l, 'a')
check_effect(d, 0)
```
输出是
```python
<class 'int'> original value is 1.
Finally it became 1. 

<class 'float'> original value is 1.0.
Finally it became 1.0. 

<class 'bool'> original value is True.
Finally it became True. 

<class 'str'> original value is aaa.
Finally it became aaa. 

<class 'list'> original value is [1, 2].
Finally it became [1, 2, 'a']. 

<class 'dict'> original value is {'a': 1}.
Finally it became {'a': 1, 'additional': 0}.
```
我尝试解释一下。可能我的解释不是特别精准。如果有说错的地方希望老师指正。
可能是基于对内存占用量的考量（我猜的），如果是简单的int，float，或者bool，当作为参数传给函数或者类的时候，计算机复制了它的值，直接给到函数或类里面。这样这个变量指向的值并没有发生变化。但是如果是list和dict，这类数据的数据量可能很大，所以计算机就不在内存里复制一份，而是直接对变量指向的值的位置进行操作。但是不知道为啥str，没有副作用。

**Comment by neolee** [comment]
@tyler1zhang 这里不是内存占用的问题，而是一个值是 mutable 还是 immutable 的问题。Python 中的变量就是一个指向值的标签，而赋值语句可以建立变量和值之间指向关系，并切断变量原先的指向关系；假如两个变量指向同一个值，而这个值本身是 mutable 的，也就是说这个值内部的内容是可以改变的，那么内容的改变就会影响到指向它的所有变量。具体来说 `int` `float` `str` 类型的值都是 immutable 的，而 `list` `dict` 等类型的值都是 mutable 的。

这个以后讲容器的时候会详细讲，现在不着急。

**Comment by gaoteng-pro** [comment]
>```python
>def add(self, bot_class):
>        bot = bot_class(self.session)
>        self.bots.append(bot)
>```
`bot_class`是`add`方法的输入参数，但在定义体内，居然还可以有`bot_class(self.session)`这样的操作，输入参数不是一个值吗？居然还可以这样操作？不理解这句语法背后是什么道理。

**Comment by neolee** [comment]
@gaoteng-pro 调用时 `bot_class` 确实会被替换为一个值，但这个值是一个“类对象”，类对象其实有点像“函数对象”，可以通过在它后面放一对括号来做类的实例化——就好像可以在函数对象的后面放一对括号来调用它一样。

**Comment by gaoteng-pro** [comment]
1. 哦，这一句其实就是类的实例化。因为类属性里只有`self.session`，所以这一句括号里就只有`self.session`。如果`self.q`没有改写成方法，那么这一句话括号里还要在`self.session`后面加上`self.q`。
2. 类的名字在其他类的方法中引用的时候就是写成`bot_class`，这个和`__init__`一样，是python解释器看到就知道是啥意思的单词，把这里的`bot_class`换成其他单词，python解释器就不知道是类名字了吧。

以上两个点理解对吧？

**Comment by neolee** [comment]
`bot_class` 就是个变量啊，名字是随便取的，是 `add` 方法的一个参数，调用时它就被换成 `HelloBot` `CalcBot` 这样具体的“类对象”了；而那句 `bot_class(...)` 就被替代为 `CalcBot(...)` 这样的，那么 `CalcBot` 的 `__init__` 方法有几个参数，你就需要传几个参数进去。

**Comment by gaoteng-pro** [comment]
如何有效阅读这种很多行很多行的源代码？

**Comment by neolee** [comment]
> 如何有效阅读这种很多行很多行的源代码？

沿着程序执行的轨迹看。

**Comment by Xuzhengfu** [comment]
这篇文章可能对你 @gaoteng-pro 有所帮助：[Everything Is an Object](https://linux.die.net/diveintopython/html/getting_to_know_python/everything_is_an_object.html)。

尤其下面这几段内容，解决了我不少关于 “对象” 这个概念的困惑：

> Everything in Python is an object, and almost everything has attributes and methods. All functions have a built-in attribute `__doc__`, which returns the doc string defined in the function's source code. The sys module is an object which has (among other things) an attribute called path. And so forth.
> 
> Still, this begs the question. What is an object? Different programming languages define “object” in different ways. In some, it means that all objects must have attributes and methods; in others, it means that all objects are subclassable. In Python, the definition is looser; some objects have neither attributes nor methods (more on this in Chapter 3), and not all objects are subclassable (more on this in Chapter 5). But everything is an object in the sense that it can be assigned to a variable or passed as an argument to a function (more in this in Chapter 4).
> 
> This is so important that I'm going to repeat it in case you missed it the first few times: everything in Python is an object. Strings are objects. Lists are objects. Functions are objects. Even modules are objects.
