### ISSUE TITLE
定义了的函数但无法调用

### ISSUE THREAD

**Issue by K8K0** [neolee/wop-community#161]
![图片](https://user-images.githubusercontent.com/67420321/88201006-81434500-cc79-11ea-92fb-1eef232628e0.png)

![图片](https://user-images.githubusercontent.com/67420321/88200927-6670d080-cc79-11ea-9772-a0e1a735586a.png)
老师我为什么报错；没有属性。
我确认过输入法

**Comment by neolee** [comment]
你的 `Animal` 类里定义的 `voice()` 方法的缩进错误，搞成和前面一个方法的定义体对齐了，这使得它会被当做前一个方法内部的一个内嵌函数，而不是 `Animal` 的方法——记住，缩进代表它属于上一层。

另外你的标题表述也不对，我改了，你比较下改之前和之后的表述，要充分理解为什么。
