### ISSUE TITLE
定义了函数但没有属性

### ISSUE THREAD

**Issue by K8K0** [neolee/wop-community#162]
![图片](https://user-images.githubusercontent.com/67420321/88201006-81434500-cc79-11ea-92fb-1eef232628e0.png)

![图片](https://user-images.githubusercontent.com/67420321/88200927-6670d080-cc79-11ea-9772-a0e1a735586a.png)
老师我是哪里错了？
 我确认过输入法。

**Comment by neolee** [comment]
Duplicate of #161
