### ISSUE TITLE
子类无法继承父类的属性

### ISSUE THREAD

**Issue by sujuxiaoren** [neolee/wop-community#163]
这个是我写的大作业的代码：
https://gist.github.com/sujuxiaoren/69c6c3dd1eb2edb157fe1aefb0cbd68c

其中，这个是父类的部分内容：
```python
class Bot:
    wait = 1
    def __init__(self):
        self.q = ''
        self.loop = 0
```
这个是子类的部分内容：
```python
class HelloBot(Bot):
    def __init__(self):
        self.loop = 0
        self.q = "Hi,what's your name?"
```
这里`self.loop`是我用来区分是否用做循环的，因为5个子类，有3个不需要循环，这里子类定义了自己的初始化函数。

但是我刚开始的时候，为了减少重复的代码使得更优雅些，我是这样写的：
```python
class HelloBot(Bot):
    def __init__(self):
        self.q = "Hi,what's your name?"
```
这时候就报错了：AttributeError: 'HelloBot' object has no attribute 'loop'。
在子类执行初始化函数的时候，__init__里面我没有写`self.loop = 0`，按理不是应该继承父类的初始化对象的属性么，只有`self.q`的值更改覆盖了父类，`self.loop`不应该跟着父类同样执行同样也是0么，为什么一定要写这句呢？

**Comment by neolee** [comment]
关于继承的规则是这样的：

1. 子类继承父类的一切，这叫 _inherit_；
2. 子类可以改写父类已有的实现，一旦改写就替换掉父类的实现，这叫 _override_。

所以当你的 `HelloBot` 实现了自己的 `__init__()` 方法，它就替换了父类中的 `__init__()` 方法，而不是“先运行父类版本再运行子类版本”的 `__init__()` 方法。

如果你需要在子类的实现中引用父类的实现，就需要用我们课上讲的 `super()` 函数了：

```python
class HelloBot(Bot):
    def __init__(self):
        super().__init__()
        self.q = "Hi, what's your name?"
```

**Comment by zhangSen1987** [comment]
子类对父类的定义不做任何改动才能继承。

**Comment by sujuxiaoren** [comment]
@neolee 老师，我尝试替换了，似乎不行。
会出现这个错误。
`TypeError: __init__() takes 1 positional argument but 2 were given`

**Comment by neolee** [comment]
你替换了啥？怎么改的？

**Comment by sujuxiaoren** [comment]
对不起，是我没说清楚。
```python
class HelloBot(Bot):
    def __init__(self):
        self.loop = 0
        self.q = "Hi,what's your name?"
```
我是把这个子类里面的`self.loop = 0` 替换成 `super().__init__()`，变成：
```python
class HelloBot(Bot):
    def __init__(self):
        super().__init__()
        self.q = "Hi, what's your name?"
```

然后我随便写了一个短点的代码进行测试，也是报错：
```python
class Bot:

    def __init__(self):
        self.q = 0
        self.loop = 0

    def run(self):
        print(self.q)
        print(self.loop)

class sonbot(Bot):
    def __init__(self):
        super().__init__(self)
        self.q = 1
        


test = sonbot(Bot)
test.run()
```

**Comment by sujuxiaoren** [comment]
是我搞错了代码敲错了，看了上一个同学的问题。。。谢谢老师
可以运行成功
```python
class Bot:

    def __init__(self):
        self.q = 0
        self.loop = 0

    def run(self):
        print(self.q)
        print(self.loop)

class sonbot(Bot):
    def __init__(self):
        super().__init__()
        self.q = 1
        


test = sonbot()
test.run()
```
