### ISSUE TITLE
如何让 input() 的返回值呈原来的类型？

### ISSUE THREAD

**Issue by adz6666** [neolee/wop-community#164]
python3中，input()的返回值全都变成了str类型，如何获得其原来的类型？
![d0825bd0087d9a01591b8bc8153c43b](https://user-images.githubusercontent.com/61263424/88216094-37655980-cc8f-11ea-8544-dbe4b7c3115c.png)

**Comment by zhangSen1987** [comment]
**原来的类型**是啥意思？刚理解错了，按你问的意思直接再把输出的字符串转原来的类型就行了。

**Comment by neolee** [comment]
什么是“原来的类型”呢？

当 `input()` 函数被调用，你在命令行输入了一些东西，Python 解释器怎么知道你输入的是整数还是浮点数还是还是别的什么呢？

实际上 `input()` 函数没法直接知道你输入的是什么，它只是把你输入的东西当做一串字符串返回。

然后你可以尝试把这串字符串转换为整数或者浮点什么的，比如：

```python
s = input()
try:
    n = int(s)
except ValueError:
    print('Invalid input.')
```

**Comment by adz6666** [comment]
比如开始的图片中，我建立了一个input()，然后用户输入了 2  ，我想知道用户输的这个2 是什么类型的值，于是我print()了他的tpye，结果这个2是一个str，可是他原本不是应该是int吗，于是我搜索了一下，他说python3中的
input()会自动返回一个str类型的值，所以我想知道如何能得出原本这个 2 （用户输入的值）应该是的类型。

**Comment by zhangSen1987** [comment]
> 比如开始的图片中，我建立了一个input()，然后用户输入了 2 ，我想知道用户输的这个2 是什么类型的值，于是我print()了他的tpye，结果这个2是一个str，可是他原本不是应该是int吗，于是我搜索了一下，他说python3中的
> input()会自动返回一个str类型的值，所以我想知道如何能得出原本这个 2 （用户输入的值）应该是的类型。

如果想确定input()原本输入的是什么值，只能用老师说的那个方式，用代码提前限定输入的是什么类型。

**Comment by adz6666** [comment]
sorry，请参考这篇文章：https://blog.csdn.net/qq_29883591/article/details/78177279
这篇文章我没看到最后所以自己试的时候我让input输入了一个变量，所以还是报错，以至于在issue上提问。
不过没太懂里面eval()的意思。

**Comment by neolee** [comment]
可能你还没理解我前面回复的意思。

关键在于理解：我们在命令行界面输入和输出的任何东西都是字符串，`print()` 显示出来的是字符串，而 `input()` 读取到的也是字符串。

你用键盘输入了比如说 `2`，你心里想的是个整数 2，但 `input()` 这个函数并不知道你心里的想法，它只知道你输入了一个字符 `'2'`，而判断这个 `'2'` 里面是个整数这件事需要用别的函数来实现，比如我给出的那个方案。

你给出的链接里说的一些话是带有误导性的。比如他说“无论我们的初衷是得到一个整数、小数或者其他的值，input 都会在我们的输入的值的左右两边加上一个引号”就属于本末倒置，后面还反复提到“input 强加的引号”，这就直接把你的理解带偏了。很多网上的文章（CSDN 格外多）都有这类问题，需要好好甄别。

事实是：我们输入的就是字符串，而 `input()` 就负责把这个字符串返回，至于字符串里面的内容应该如何理解（是个整数还是个别的什么东西），是另外的事情。而 `eval()` 这个函数就更复杂了，不建议现在去弄这个东西。

你可以预习一下课程配套资源里第二部分的《第六章 字符串数据》，应该就会有个更清晰的理解。
