### ISSUE TITLE
print 函数中的逗号问题

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#165]
```
def say_hi(*names):
    for name in names:
        print('Hi,', name)
say_hi('Neo')

Hi, Neo
```
这样的一段代码中，`print` 函数中，'Hi,'  和 name 之间的这个逗号，是起什么作用呢？
在字符和字符串这一章中，有下面这样一段代码，固定文字和变量之间要用+号这样连接，或者用f-string的方式，那上面代码中的'Hi,'  和 name 之间，怎么不需要+号或者f-string就可以了呢？
```
x = 62
y = 29
print('计算完毕，获胜概率为 ' + str(x) + '%，败北概率为 ' + str(y) + '%，平局概率为 ' + str(100-x-y) + '%。')
```

**Comment by neolee** [comment]
'Hi,' 和 name 之间的逗号表示这是送给 `print()` 函数的两个参数啊，函数的多个参数之间要用逗号隔开，这个记得么？

`print()` 这个函数可以有 0、1 或者多个输入参数：

- 如果不给它参数，它就输出一个空行；
- 如果给它一个参数，它就把这个参数转换为 str 然后显示出来（并换行）；
- 如果给它多于一个参数，它会把所有参数都转换为 str，然后一个个显示出来，两两之间加上空格，最后再加一个换行。

这些东西，官方文档里都有，但其实自己多试试马上就能得到答案，比如试试执行下面这些代码：

```python
print(3, 4, 'foo')
print('3' + '4' + 'foo')
print(f"{3} {4} {'foo'}")
print(f"{3} {4}\n{'foo'}")
```

学会自己探索是很有意思的。

**Comment by Amy20191** [comment]
学着学着混起来了。
