### ISSUE TITLE
New gist 总是显示“网页无法显示”

### ISSUE THREAD

**Issue by Yongheng2020** [neolee/wop-community#167]
![image](https://user-images.githubusercontent.com/67858621/88272839-e8113e80-cd0b-11ea-8b1d-d0bbbcbaf000.png)
我的Github 可以登录，issues也可以用，但是上传作业用的这个gist总是无法显示页面，请问怎么破

**Comment by Sincere-io** [comment]
1. 去试首页底部老师的方法。
2. 换个时间点。

**Comment by Yongheng2020** [comment]
搞不定，页面加载不了，老师首页底部说的是交作业的方法，但是交作业的前提是要用gist链接

**Comment by Sincere-io** [comment]
Issues前Code打开底部有关访问Github的一些方法试过了吗？

**Comment by tyler1zhang** [comment]
Sincere-io说的首页是这个
https://github.com/neolee/wop-community#附解决访问-github-的一些问题

**Comment by Yongheng2020** [comment]
已搞定
