### ISSUE TITLE
判断语句在第二次循环时生效

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#169]
我想写一个成语接龙游戏的程序，下图是我的代码：
![error1](https://user-images.githubusercontent.com/53089964/88289453-d342a400-cd27-11ea-9322-c6a3fa682fff.PNG)
在运行elif语句的时候报错，下图是报错：
![error2](https://user-images.githubusercontent.com/53089964/88289532-f4a39000-cd27-11ea-8d60-00b5b74bb28e.PNG)

两个问题：
1. `elif idiom.is_idiom(self.a) is False or idiom.is_idiom_solitaire(self._think(self.a), self.a) is False:`

这里有两个判断，第一个是判断用户输入是否是一个成语，第二个是判断用户输入的成语和程序输出的成语是否可以接龙。第一个判断运行没有问题，我尝试按照同样的思路去写第二个判断结果运行时报错typeerror。

2. 这个报错解决之后，还不能达到我想要的目的，因为循环开始时先是用户输入一个成语，之后机器人跟上，用户在机器人输出的成语基础上再次输入一个成语。这样就要求这个判断在第二次循环时生效，我没有思路，老师可以提示一下吗？

**Comment by neolee** [comment]
第一个问题，实际上是你使用第三方库的时候没有用对里面的方法。

你用的是 china-idiom 这个第三方包，我看了下这个包的文档，有几点你需要注意：

* `idiom.next_idioms_solitaire` 这个方法返回的是一个列表，哪怕只返回一个成语，也是放在一个列表中的，而你需要字符串类型的一条成语，所以你要取出其中第一个元素作为 `_think()` 的返回，比如 `return self.n[0]`（其实最好做一下容错，判断下 `self.n` 里面至少有一个元素）；
* `idiom.is_idiom_solitaire` 这个方法的两个输入参数都是字符串，由于你的上述错误，你调用它时的第一个参数 `self._think(self.a)` 不是字符串而是个列表，所以就报错了。

另外，你的 `elif` 逻辑判断写的不好，有更加简明的写法，例如下面这样：
```python
elif not idiom.is_idiom(self.a) or not idiom.is_idiom_solitaire(self._think(self.a), self.a):
```

第二个问题，你的需求是和 bot 玩接龙游戏，创意很好，但逻辑有点复杂，所以要好好设计一下，一个好诀窍是写代码前先用自然语言说清楚流程和算法，比如我们可以写出下面这样的“伪代码”——你可能会在这个过程中反复多次，你要写到你完全理顺思路且知道如何用程序去实现里面每一步为止：

```
计算机输出游戏说明
用户输入第一个成语 => 将这个成语保存到 idiom1 中（这里也可以判断下输入的是不是退出指令，以及是不是成语）
游戏开始 => while 循环：
    调用 next_idioms_solitaire(idiom1) 获得一个接龙成语并输出 =>  将该成语保存到 idiom2 中
    里层循环 => while 循环：
        读取用户输入 => 将该输入存入 idiom1 中
        如果 idiom1 是 x exit 等退出指令则直接退出里层循环 => break
        调用 is_idiom(idiom2) 和 is_idiom_solitaire(idiom2, idiom1) 判断用户输入的 idiom1 是否合格 => if 判断
            如果不是：输出提示让用户重新输入，继续里层循环
            如果是：结束里层循环 => break
    (从里层循环出来之后)检查下如果 idiom1 是 x exit 等退出指令则退出大循环结束游戏 => break，否则继续
```

上面是个例子，不一定完全对，你可以自己去尝试写写；之后还可以做一些抽象和模块化，比如书读取用户输入之后，判断输入是不是退出指令以及是不是个成语这件事，可能会在几处都用到，可以考虑做成个独立函数，你要设计下这个独立函数的输入输出。

**Comment by wangcong-creator** [comment]
以下是我的实现代码：
###

class IdiomBot(Bot):

    def _q(self):
        return "I know all Chinese idioms. Let's play a idiom solitaire game. You can input an idiom to have a try. "

    def _think(self, s):
        self.n = idiom.next_idioms_solitaire(s, count=1, heteronym=False)
        return self.n[0]

    def run(self):
        time.sleep(Bot.wait)
        self._say(self._q())
        self.idiom1 = input()
        while True:
            self.idiom2 = self._think(self.idiom1)
            self._say(self.idiom2)           
            while True:
                self._say("Try your best to follow or you can input 'q','x','Q' or'X' to quit the game.")
                self.idiom1 = input()
                if self.idiom1 in ['q', 'x', 'Q', 'X']:
                    break               
                elif not idiom.is_idiom(self.idiom1) or not idiom.is_idiom_solitaire(self.idiom2, self.idiom1):
                    self._say("You print an invalid idiom, please try again.")
                else:
                    break
            if self.idiom1 in ['q', 'x', 'Q', 'X']:
                self._say("Byebye. See you next time.")
                break

###

功能暂时实现了，但是有很多需要优化的地方。我有以下问题：
1. 在 run 方法里需要判断是否退出的地方有三个，第一个是循环之外，第二个是里层循环，第三个是外层循环。但是这三处用法都不一样，我尝试写了一个方法如下：

###
    def _quit(self, s):
        while True:
            if s in ['q', 'x', 'Q', 'X']:
                break

    def run(self):
        time.sleep(Bot.wait)
        self._say(self._q())
        self.idiom1 = input()
        while True:
            if self.idiom1 in ['q', 'x', 'Q', 'X']:
                self._say("Byebye. See you next time.")
            else:
                while True:
                    self.idiom2 = self._think(self.idiom1)
                    self._say(self.idiom2)           
                    while True:
                        self._say("Try your best to follow or you can input 'q','x','Q' or'X' to quit the game.")
                        self.idiom1 = input()
                        self._quit(self.idiom1)               
                        if not idiom.is_idiom(self.idiom1) or not idiom.is_idiom_solitaire(self.idiom2, self.idiom1):
                            self._say("You print an invalid idiom, please try again.")
                        else:
                            break
                    self._quit(self.idiom1)

###

结果运行的时候出现了灾难，根本运行不下去。老师能指点一下吗？

**Comment by neolee** [comment]
你后面写的这个 _quit 方法肯定不会工作啊，你想想它干了啥？它运行了一个循环然后退出了，对调用它的一端什么事也没做。

正确的做法应该是写一个函数对用户输入进行分析判断，先看它是不是退出指令，如果是的话返回比如说 -1，然后判断下它是不是个成语，是的话返回 1，不是的话返回 0，这个函数就是一个设计合格的模块（清晰地接口，从输入算出输出）；然后 `run()` 主方法里可以使用这个函数来对用户的输入进行判断，根据返回值来选择是退出循环还是告诉用户输入不是个成语要他重新输入。
