### ISSUE TITLE
git 装了二天还是一无进展

### ISSUE THREAD

**Issue by SZZ0722** [neolee/wop-community#17]
![image](https://user-images.githubusercontent.com/67678671/86314012-26f62c00-bc59-11ea-82b6-159fcaf7271f.png)

**Comment by SZZ0722** [comment]
![image](https://user-images.githubusercontent.com/67678671/86314701-de3f7280-bc5a-11ea-9166-f226c151c478.png)

**Comment by alphaho** [comment]
可以按照提示先试试运行：

 `scoope uninstall git` 来卸载安装失败的 git

然后再用 `scoop install git` 重新安装一下

看看这样能不能解决

**Comment by SZZ0722** [comment]
![image](https://user-images.githubusercontent.com/67678671/86315085-ce745e00-bc5b-11ea-9047-6ae4b034dde6.png)

**Comment by neolee** [comment]
无论遇到什么问题，不要“乱试”，要努力搞清楚自己在做什么以及计算机告诉你了什么。

首先，确定你目前的状态：Scoop 应该是装好了，但是通过 Scoop 安装 git 不成功。

那么首先需要清除安装失败的 git：`scoop uninstall git`，然后再重新尝试安装：`scoop install git`，根据安装时出现的问题有针对性的解决——这些其实计算机给你的反馈里就有，上面也有同学给你了建议，你试过了么？结果如何？

另外，通过搜索这个社区，你会发现其实有同学遇到安装 git 的问题，有的同学还自己找到了不错的解决方案，比如可以参考这个问题的内容： #11

**Comment by SZZ0722** [comment]
相关内容已经看了N遍了，GIT仍然安装不成功
按照#11中的方法，复制这个安装包到 scoop 的 cache 目录后改文件名为 git#2.27.0.windows.1#https_github.com_git-for-windows_git_releases_download_v2.27.0.windows.1_PortableGit-2.27.0-64-bit.7z.exe_dl.7z；我的cache中已经有安装文件了，执行命令scoop uninstall git时，仍会再次下载，网带极慢，无赖换成手机热点，ping命令一切正常
![image](https://user-images.githubusercontent.com/67678671/86316358-26609400-bc5f-11ea-92c4-bfbe5cb5e222.png)

**Comment by neolee** [comment]
你放进 cache 目录的那个文件的名字不对，最后多了个 .7z，所以当然就没被认出来，于是 Scoop 就尝试重新下载了。

如果你感觉现在很焦躁很愤怒，建议休息平静一下。

**Comment by SZZ0722** [comment]
应该是最后一步了，不知哪里出了问题

![image](https://user-images.githubusercontent.com/67678671/86325266-5bc2ad00-bc72-11ea-8580-7e06cbddeea2.png)

**Comment by zed-wong** [comment]
`scoop install python37@3.7.4`
这条命令的意思是：用scoop安装python3.7.4

可是我看之前的问题，是不能安装git吧？

装git的命令是 `scoop install git`

如果想要装python，不能用scoop，需要去官网[下载](https://www.python.org/downloads/release/python-383/)

**Comment by neolee** [comment]
@SZZ0722 你前面的 `scoop update` 没有成功，返回的信息里 `fatal` 是“严重（致命）错误”的意思，具体错误是从服务器获取软件包的数据失败了。你可能需要换个网络或者换个时间多试几次。从你前面的信息看，你所在的网络环境访问一些境外站点是有点不太稳定的。

实在不行的话，另一个办法是按照 @who3m1 所说的，直接到 Python 官网下载课程需要的 Python 3.7.4，不过他给出的链接不对，应该是下面这个： https://www.python.org/downloads/release/python-374/  在文件列表中选择下载 Windows x86-64 executable installer 那个然后安装就可以了。

**Comment by SZZ0722** [comment]
谢谢老师





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 下午5:31
收件人: "neolee/wop-community"<wop-community@noreply.github.com&gt;; 
抄送: "天马行空"<308271077@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [neolee/wop-community] git 装了二天还是一无进展 (#17)





 
@SZZ0722 你前面的 scoop update 没有成功，返回的信息里 fatal 是“严重（致命）错误”的意思，具体错误是从服务器获取软件包的数据失败了。你可能需要换个网络或者换个时间多试几次。从你前面的信息看，你所在的网络环境访问一些境外站点是有点不太稳定的。
 
实在不行的话，另一个办法是按照 @who3m1 所说的，直接到 Python 官网下载课程需要的 Python 3.7.4，不过他给出的链接不对，应该是下面这个： https://www.python.org/downloads/release/python-374/  在文件列表中选择下载 Windows x86-64 executable installer 那个然后安装就可以了。
