### ISSUE TITLE
绘图机器人需要老师指点

### ISSUE THREAD

**Issue by wangBoZhengJuan** [neolee/wop-community#170]
想利用turtle库做一个绘图机器人，卡住了，老师指条路，我继续干
![微信图片_20200723224651](https://user-images.githubusercontent.com/49601464/88300822-7f8b8700-cd36-11ea-9eb1-d5627d941d72.png)

**Comment by tyler1zhang** [comment]
请问你为什么选择了turtle，而不是matplotlib之类的更常用的库呢？

**Comment by neolee** [comment]
Turtle 这个库的灵感来自最早的 PC，也是我接触的第一部电脑，苹果的 Apple II。如果你想玩这个，需要自己研究下相关文档和例子。

然后你这个问题，“需要老师指点”，我指点啥啊？你想做什么？哪些成功了，又遇到了啥问题？

**Comment by wangBoZhengJuan** [comment]
老师，我死磕着解决了。
