### ISSUE TITLE
关于函数定义的两个问题

### ISSUE THREAD

**Issue by jinnami** [neolee/wop-community#171]
def Hello(self, name):中的self和def idiv(a, b):的a是同一个性质吗？

def __init__(self, n)中的__init__和def idiv(a, b):的idiv是同一个性质吗？

**Comment by neolee** [comment]
你觉得呢？

**Comment by tyler1zhang** [comment]
> def Hello(self, name):中的self和def idiv(a, b):的a是同一个性质吗？

self 是将来类初始化出来的对象，a是输入函数的参数。 

> def __init__(self, n)中的__init__和def idiv(a, b):的idiv是同一个性质吗？

`__init__`是python reserve的一个函数名，它有特殊的用途。 idiv应该仅仅是个函数名。

**Comment by neolee** [comment]
@jinnami 我前面问你自己觉得如何，具体说，就是你需要问自己一些问题：你这个问题中 “同一个性质”是什么含义？你实际上想问的是什么？你对自己的问题有没有一些猜想？有没有想过如何去验证自己的猜想？

**Comment by jinnami** [comment]
我就是觉得有些不一样，但它们又在相似的位置上。去来来回回爬学习资料，现在有点明白了，我这样理解对不对，self是类定义，好比是默认的类对象，如果没有其它地方去定义它，它就是self，除非其它地方定义它可以取代它成为一个类对象。而a是函数的变量，就是变量a。__init__看教材应该是和idiv函数名是有区别的，教材说是解释器在实列化对象后 自动调用的方法，__init__()是方法，是不是就是方法的一个约定的符号，没有更多的意义。我想知道__init__有没有别的知识，比如它在什么情况下有特别的用法作用或意义去帮助我理解，还是就是在类定义里的一个约定符号。

**Comment by neolee** [comment]
看问题首先看本质，然后再看附加的特性。

```python
class Foo:
    def __init__(self, name):
        self.name = name

def idiv(a, b):
    q = a // b
    r = a % b
    return q, r
```

`def __init__(self, name):` 和 `def idiv(a, b):` 都是定义函数的语法，`__init__` 和 `idiv` 都是函数，括号里的`self` `name` 和 `a` `b` 都是函数的输入参数；所有输入参数都是函数定义里的局部变量，仅在函数定义体内有效——这些就叫本质，是关键性的东西。

主要差别是 `__init__` 定义在一个类里面（在类定义 `class Foo:` 之下缩进），所以这个函数隶属于这个类的对象实例，这个函数没法直接用 `__init__(...)` 去调用，而必须先创建一个 `Foo` 类型的对象 `obj`，然后用 `obj.__init__(...)` 这样的语法来调用它。

上面这些属于“基本概念”，是要毫不含糊理解清晰的，是什么就是什么，没有模棱两可。

进一步需要理解的是 `self` 和 `__init__` 这两个特殊的名字。这两个并不属于“基本概念”，而是 Python 语言设计出的“语言工具”或者叫“规则”。
* `__init__` 是 Python 所有对象都拥有的一个函数，这个函数在对象被创建起来之后会被自动执行，我们定义自己的对象类型（class）时可以自定义这个函数的实现，因为它是对象创建之后自动运行的第一个函数，所以适合用来做一些对象初始化的工作；
* `self` 是一个特殊的变量，它只在类定义里面使用，代表该类的对象实例，类的所有方法的第一个参数必须是 `self`，确保它可以在方法定义内部使用。

虽然有这些特殊之处，但本质上，`__init__` 还是个函数，`self` 还是个变量。

最后，你提到“我想知道…有没有别的知识”，其实已经暗含了你潜意识里的一种认知，就是这东西似乎是个什么，但又有些特殊的地方。所以建议你仔细阅读上面的内容，努力学会“先认清一个事物的本质（是什么）然后再掌握其特殊规则”的思维方法。

p.s. 以上内容课上都是讲过的，但看你的表述，无论是一些关键概念的名词还是理解都不太对（比如：`self` 是对象不是类更不是“类定义”，`a` 不是函数的变量而是函数的“参数”），是没参加直播还是在什么地方理解上出现了问题呢？

**Comment by jinnami** [comment]
谢谢老师的解答和补充知识，很有帮助。直播课都是参加的，基本看两遍。也许是前面看的时候没理解到位或不够重视某个知识点就上过去了，在后面上课和练习遇到时问题就反应出来了。自己知道还没掌握好，羡慕很多同学，学习都跑到课程前面去了。
