### ISSUE TITLE
为什么这个函数 print 输出了两个”Hi“

### ISSUE THREAD

**Issue by jinnami** [neolee/wop-community#172]
我在自己练习熟悉函数，尝试各种开脑洞时出现的情况，不要在意这个函数的目的意义。我奇怪的是print时有两个Hi,多的一个Hi是哪一段代码或哪个逻辑关系产生的。
```
def say_hi(a, b):
    print('Hi!')
    c = a
    d = b
    return c, d
    
q, r = say_hi(3, 4)
print(say_hi(3, 4))

Hi!
Hi!
(3, 4)
而我删掉了一行代码q, r = say_hi(3, 4)，print时就只有一个Hi。
def say_hi(a, b):
    print('Hi!')
    c = a
    d = b
    return c, d
    
print(say_hi(3, 4))

Hi!
(3, 4)
```

**Comment by neolee** [comment]
你这不是已经自己试出答案了么……

**Comment by tyler1zhang** [comment]
强烈建议@jinnami 去看看Markdown怎么写，老师给了支线课程。这个issue写出来之后，没有读下去的动力。好在你写的短。你其实找到了那句代码。但是由于你还是有一定的疑问，估计你没有表述清楚你的问题，整理一下思路，说清楚到底哪里没有想明白吧。

加油💪

**Comment by neolee** [comment]
@jinnami 你问的问题，是上一次上课刚讲过的内容，不是不可以问，但至少应该有自己的一些思考，尤其是你自己的尝试已经非常接近答案了，这时候喂给你一个答案没啥意义，自己再思考下吧。

另外，建议仔细读一读 https://github.com/neolee/wop-community/ 首页的文档，对在这里高效交流非常重要。

**Comment by jinnami** [comment]
刚学编程，抓紧时间在复习练习上课，有时间就反复看课程回访和课程资料，各种状况出来，是没理解透，或者说就是在帮助理解的过程中。担心自己跟不上进度着急，很多小白的问题提出来。老师同学提示一下，自己然后才理解一些。不过编程这个过程挺有意思挺有趣的。q, r = say_hi(3, 4)是不是已经运行了say_hi函数里面的print，打印出了hi,只是没有外部打印命令，返回值3，4没有显示，而后面print(say_hi(3, 4))外部的打印命令，打印出了函数say_hi里面的hi，和打印出了返回值3， 4

**Comment by neolee** [comment]
> 刚学编程，抓紧时间在复习练习上课，有时间就反复看课程回访和课程资料，各种状况出来，是没理解透，或者说就是在帮助理解的过程中。担心自己跟不上进度着急，很多小白的问题提出来。老师同学提示一下，自己然后才理解一些。不过编程这个过程挺有意思挺有趣的。q, r = say_hi(3, 4)是不是已经运行了say_hi函数里面的print，打印出了hi,只是没有外部打印命令，返回值3，4没有显示，而后面print(say_hi(3, 4))外部的打印命令，打印出了函数say_hi里面的hi，和打印出了返回值3， 4

基本正确。你看，这不是挺好的么。学习的两个要诀：1. 上课认真听讲，对关键概念反复推敲；2. 下课勤动手，敢于猜想和验证，不懂就问。

```python
q, r = say_hi(3, 4)
```

这句程序的执行实际上是两层：
1. 对赋值语句等号的右边进行求值，也就是“调用 `say_hi(3, 4)` 函数获得其返回值”，而所谓“调用函数”就是用确定的输入参数值替换掉函数定义时的参数变量，然后执行函数定义体，`say_hi` 这个函数定义体里有一个 `print` 所以会输出 `Hi`；
2. `say_hi` 返回值是 3 和 4，分别赋值给了 q 和 r 这俩变量。

```python
print(say_hi(3, 4))
```

类似的，这句程序也分两层，先调用 `say_hi(3, 4)` 得到返回值，然后调用 `print()` 输出这个返回值。同上，调用 `say_hi` 时会输出第二个 `Hi`，而调用 `print()` 时会输出 `(3, 4)`。

**Comment by neolee** [comment]
顺便，前面 @tyler1zhang 同学的建议也很对，你需要认真阅读 https://github.com/neolee/wop-community/ 首页的文档（我前面也提了一次但你似乎没在意）。这个文档教你如何更有效地提问和讨论，其中最具性价比的就是如何标记你问题中的程序代码，让它们看上去更漂亮更清晰，不要小看了这些外观的问题，你看我给你的回答中的代码段落标记（无论是独立段落还是嵌在文本中间的），是不是清晰很多？你难道不想也写成这样么？

**Comment by jinnami** [comment]
嗯，谢谢老师和同学的解答。好的，我也想注意更多内容，现在有点手忙脚乱，顾头顾不了尾的感觉，目前内心还是知道有太多的东西在等我弄懂。老师同学在这次培训中真的是引导和督促到我。代码段落标记刚才试了，第一次试直接将···靠着要引用的代码，出来奇怪的状态，后来意识到···不能像文本一样靠着代码。刚才还不明白代码中间有文本要怎么分开，现在想到一样···要空开。

还有一个小疑惑，

```
q, r =say_hi(3, 4)
print(q, r)
3， 4
```

打印出来是不带括号的3， 4

```
print(say_hi(3, 4))
(3, 4)
```
打印出来的是带括号的（3， 4）。这个细微的差别是打印值和打印函数返回的值的区别吗？

**Comment by neolee** [comment]
这种带括号的 `(3,  4)` 其实是一种数据容器，等我们讲到数据容器你就懂了。

另外你可以在代码块标记第一行的三撇后面写上 `python` 这样可以有针对 Python 的语法高亮颜色显示。

**Comment by jinnami** [comment]
好，谢谢老师，很有兴趣尝试各种新的编程知识。
