### ISSUE TITLE
no module named  "keyword"

### ISSUE THREAD

**Issue by jianbian-zcx** [neolee/wop-community#174]
<img width="636" alt="截屏2020-07-24 上午11 30 36" src="https://user-images.githubusercontent.com/66012598/88358388-56eca700-cda1-11ea-86c4-78b26398aeb1.png">
这个错误何解？

**Comment by neolee** [comment]
我想问问你，你的标题里 “keyword” 和你程序里 “Keyword” 之间有什么差别？

**Comment by jianbian-zcx** [comment]
啊？不知道哎，大小写么？

**Comment by neolee** [comment]
所以你关闭了这个问题，我可以理解为是解决了么？
