### ISSUE TITLE
大作业改进 CalcBot 遇到难题

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/wop-community#175]
>作业一：改进最后这个 CalcBot，让它可以反复执行，用户可以一直输入算术表达式求值，直到用户输入 x q exit 或者 quit 为止，才跳到下一个 bot 执行。

我的思路是使用一个循环。不过我这样写，既不会循环，输入 x q exit 或者 quit 还会报错。请问李老师我的方向对吗？是用 while吗？可能我用错了。

<img width="1265" alt="Screen Shot 2020-07-24 at 13 57 36" src="https://user-images.githubusercontent.com/52094557/88364940-0c762500-cdb7-11ea-9eea-5a1767774eb6.png">

<img width="1269" alt="Screen Shot 2020-07-24 at 13 57 47" src="https://user-images.githubusercontent.com/52094557/88365129-a9d15900-cdb7-11ea-90c1-3c5a0ec77e46.png">

**Comment by neolee** [comment]
你的这段代码中有不少问题。

首先，为什么你用了两个 `input()` 调用呢？这就意味着你要用户输入两次，第一次输入的内容赋值给 `self.a`，第二次输入的内容赋值给了 m。

然后你的循环语句也有问题。

```python
while m in ['q', 'x', 'exit', 'quit']:
    print('See you next time')
else:
    ...
```

上面这段代码的意思是：只要 m 是 'q', 'x', 'exit', 'quit' 这几个值其中之一，就循环打印 'See you next time'，否则执行 `else` 后面代码段。这肯定不是你想表达的意思对吧？

我猜程序第一次提示输入时你输入了 x，所以 `self.a = 'x'`，第二次提示输入的时候不知道你输了什么，很可能直接回车了，所以很可能 `m = ''`（空字符串），于是到了 `while` 循环那里，条件不成立，于是执行 `else` 后面的，但 simple_eval 不知道怎么计算 `x` 这个表达式，这也不是个算术表达式，所以就出现了你看到的一大串出错信息——你运气还不错，如果你的 m 的值是 `'x'` 的话，就要出现死循环了。

分析完错误，再说说怎么做才对。正确的逻辑应该大致是这样的：

```
while True:
    self.a = input()
    if self.a 的值是 'q', 'x', 'exit', 'quit' 其中之一:
        break
    else:
        尝试调用 _think 计算 self.a 表达式的值并输出
```

你可以自行将这个思路编程可以运行的程序，还可以不断优化它。

**Comment by Royhowtohack** [comment]
>很可能直接回车了，所以很可能 m = ''（空字符串），


我确实是这么干的。😂。 我测试了老师的思路，所有的问题都解决了。 第二个任务，我的想法是去使用一些现成的模块。我尝试了去这个网站找素材 https://pypi.org。  找到的是project。我装了一个 https://pypi.org/project/hangthepyman/ 这个。我觉得我好像找错了。
请老师指教下哪里去找第三方库？

**Comment by neolee** [comment]
PyPi 确实就是 Python 第三方库的官方集中地，找到后用 `pip install xxxx` 就可以安装，安装后就可以导入和使用，具体用法就要看这些库自己的文档了。

**Comment by Royhowtohack** [comment]
搞定，多谢李师傅指点！
