### ISSUE TITLE
module 'myutil' has no attribute 'say_hi'

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/wop-community#177]
我自己打了一遍报错，我又复制粘贴了老师的代码，也报错。是为什么呢？

<img width="1388" alt="Screen Shot 2020-07-24 at 18 09 04" src="https://user-images.githubusercontent.com/52094557/88381471-13ae2a80-cdd9-11ea-9f5e-a90b04850363.png">
<img width="824" alt="Screen Shot 2020-07-24 at 18 10 57" src="https://user-images.githubusercontent.com/52094557/88381472-14df5780-cdd9-11ea-8a5d-3386123c16c7.png">

**Comment by neolee** [comment]
你这个 `myutil.py` 文件放在哪里？在前面截图那个 notebook 同一个目录下或者 `assets` 子目录下吗？如果不在是找不到的，而且看你的出错信息，可能在 notebook 同目录或 `assets` 子目录下有个叫 `myutil.py` 但没内容的文件。

**Comment by Royhowtohack** [comment]
搞定了，确实是地方没放对。
