### ISSUE TITLE
模块引入失败的问题

### ISSUE THREAD

**Issue by liushui0712** [neolee/wop-community#178]
1、已保存myutil.py 到code里，且终端 ls code 已显示。
2、把code添加到了sys.path
3、import myutil时依然出现问题，不知道问题出在了哪一步。

![image](https://user-images.githubusercontent.com/54479298/88450691-62180380-ce83-11ea-8708-e1724219ebcb.png)
![image](https://user-images.githubusercontent.com/54479298/88450707-8378ef80-ce83-11ea-8c69-f546fc7505fd.png)
![image](https://user-images.githubusercontent.com/54479298/88450716-98ee1980-ce83-11ea-93f7-27f8c06ba8a8.png)

**Comment by neolee** [comment]
比较简单的办法是：把 myutil.py 和你的 notebook 文件放在一起，放同一个目录下，然后就可以直接 import 了。

**Comment by liushui0712** [comment]
> 比较简单的办法是：把 myutil.py 和你的 notebook 文件放在一起，放同一个目录下，然后就可以直接 import 了。

果然。。。。立刻就行了，哎呀，折腾了我好久的一个问题，居然这么简单就解决了！谢谢老师
