### ISSUE TITLE
模块引用错误，找不出是什么原因

### ISSUE THREAD

**Issue by zhangshu-xiong** [neolee/wop-community#179]
在模块这节我把上面那个 myutil.py 放在C:\\Users\lenovo\文档\GitHub')子目录下，之后用‘sys.path.append('C:\\Users\lenovo\文档\GitHub')’放入 sys.path 中
sys.path 列表内容显示有C:\\Users\lenovo\文档\GitHub'，file:///C:/Users/Lenovo/Pictures/%E7%BC%96%E7%A8%8B%E9%97%AE%E9%A2%98/%E6%A8%A1%E5%9D%97%E5%BC%95%E5%85%A5%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%981%E5%9B%BE.png
但运行时显示错误file:///C:/Users/Lenovo/Pictures/%E7%BC%96%E7%A8%8B%E9%97%AE%E9%A2%98/%E6%A8%A1%E5%9D%97%E5%BC%95%E5%85%A5%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98.png

**Comment by xuzhengfu** [comment]
最好重新组织一下 issue（在新生大讲堂中学习支线课程第一讲、第四讲），因为一些关键信息看不到，要靠猜才行……

 另，`\` 有特殊用途[[1]](https://docs.python.org/2.0/ref/strings.html)。正确的写法是：

```py
sys.path.append(r'C:\Users\lenovo\文档\GitHub')
```

**Comment by neolee** [comment]
关于使用自己写的模块，最简单的办法是把你需要引入的 module 放到你的主 notebook 或者主 .py 文件一起，即同一目录下，然后就可以直接 import 了，`sys.path.append` 都不需要。

如果要学习使用 `sys.path.append`，那么要对文件的“绝对路径”和“相对路径”有个正确认识，这些在支线课程第一讲里有说。比如 `./code/` 表示当前目录（命令行的当前工作目录，或者你的 notebook 所在目录）下的 code 子目录；而 `~/code/` 表示用户根目录下的 code 子目录；等等。

你要确保你的 module 们放在某个目录下，然后用 `sys.path.append()` 把这个目录加到搜索路径里才行。

**Comment by zhangshu-xiong** [comment]
谢谢，问题已解决，重新看了支线课程，感觉受益匪浅





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neolee/wop-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上8:15
收件人:&nbsp;"neolee/wop-community"<wop-community@noreply.github.com&gt;;
抄送:&nbsp;"zsx27"<zsx27@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/wop-community] 模块引用错误，找不出是什么原因 (#179)





 
最好重新组织一下 issue（在新生大讲堂中学习支线课程第一讲、第四讲），因为一些关键信息看不到，要靠猜才行……
 
但是，“猜” 这种动作通常会让人感到沮丧和疲惫，比如：我猜你运行 sys.path.append('C:\Users\lenovo\文档\GitHub') 应该会报错，因为  \ 有特殊用途1。可是你说：
  
sys.path 列表内容显示有C:\Users\lenovo\文档\GitHub'
  
这让我感到矛盾。
 
无论如何，正确的写法应该是：
 sys.path.append(r'C:\Users\lenovo\文档\GitHub')
