### ISSUE TITLE
Mac 作业流程

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#18]
老师能录一个关于mac的作业下载提交的整个流程吗？

只能用VS code打开，没有jupyter选项。希望出一个mac的作业下载提交全流程。

<img width="1440" alt="截屏2020-06-30 上午11 10 05" src="https://user-images.githubusercontent.com/57254889/86373664-39528300-bcb6-11ea-96bb-228c514cccda.png">

**Comment by neolee** [comment]
你没装 nteract 自然没法直接打开……

**Comment by gaoteng-pro** [comment]
在哪下载来着？我记得老师在B站上有讲过nteract，找了一圈没找到。

还是想用jupyter来写作业。下载下来的文件，怎么能挪到指定的文件夹呢？比如挪到Code文件夹。

**Comment by neolee** [comment]
用 Jupyter Lab 也没问题。你问的问题课程资料里都有，去找找吧。

**Comment by gaoteng-pro** [comment]
OK了，直接在terminal里输入jupyter lab，在打开的jupyter lab里选Downloads，然后选择你下载的学习文件，一般是一串数字.ipynb，点开这个文件就好，在里面完成作业，并保存。

上传的话，点击上传，选择下载文件夹，选择你那个文件，点击上传，提交作业就OK了。


mac遇到这样问题的小伙伴可以参考。

**Comment by gaoteng-pro** [comment]
我再用图片的方式回答一下，这样比较直观。

前提条件：你已经按照老师给的教程，装好了编程环境以及jupyter lab；从**新生大讲堂**下载了学习文件。

**打开作业&写作业**
1.同时按： `command`+`空格`，会出现如下图的对话框
<img width="862" alt="截屏2020-07-05 上午11 42 12" src="https://user-images.githubusercontent.com/57254889/86525188-771dfa00-beb6-11ea-9bdf-0ab67700c8ad.png">
2.在对话框里输入`terminal`，然后`回车`；在出现的命令行，输入`jupyter lab`，然后`回车`，就会启动`jupyter lab`，如下两图
<img width="586" alt="截屏2020-07-05 上午11 43 57" src="https://user-images.githubusercontent.com/57254889/86525241-47232680-beb7-11ea-9ed2-59f5b459f8f8.png">
<img width="1268" alt="截屏2020-07-05 上午11 45 38" src="https://user-images.githubusercontent.com/57254889/86525263-9a957480-beb7-11ea-8b7f-28e3eedb28b9.png">
3.在上图中，点击红色箭头的文件，然后选择红框里的`Downloads`，然后选择你从**新生大讲堂**下载的文件。
4.好，你已经用jupyter lab打开了你的学习文件，可以在里面学习了，然后保存。

**上传作业**
在新生大讲堂里，点击上传作业，然后点**下载**，选择你保存的那**一个**名字的文件，如下图：
<img width="1434" alt="截屏2020-07-05 上午11 48 49" src="https://user-images.githubusercontent.com/57254889/86525345-9ae23f80-beb8-11ea-8308-e8d19b98f330.png">
