### ISSUE TITLE
module 引入

### ISSUE THREAD

**Issue by muse1171** [neolee/wop-community#180]
```python
import sys
sys.path

['/Users/baojuan/Downloads',
 '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '',
 '/Users/baojuan/Library/Python/3.7/lib/python/site-packages',
 '/usr/local/lib/python3.7/site-packages',
 '/usr/local/lib/python3.7/site-packages/IPython/extensions',
 '/Users/baojuan/.ipython',
 './pilot-student/',
 './pilot-student/',
 './pilot-student/',
 './assets/',
 './assets/',

sys.path.append('./pilot-student/') #179 
我的myutil.py文件是在pilot-student目录下，所以我执行这个命令，结果下面就报错了。

import myutil
myutil.say_hi('Neo', 'Trinity')

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-94b736aa9ac6> in <module>
----> 1 import myutil
      2 myutil.say_hi('Neo', 'Trinity')

ModuleNotFoundError: No module named 'myutil'
```
我的myutil.py文件是在pilot-student目录下，所以我执行这个命令sys.path.append('./pilot-student/')，结果下面就报错了。问题肯定在这里，但是我不知道错在哪里啦。

**Comment by xuzhengfu** [comment]
你的当前工作目录应该是 `'/Users/baojuan/Downloads'`，你确定这个目录下有 `pilot-student` 吗？

**Comment by muse1171** [comment]
> 你的当前工作目录应该是 `'/Users/baojuan/Downloads'`，你确定这个目录下有 `pilot-student` 吗？
/Users/baojuan/Downloads/code/pilot-student 是这样的顺序，那么我应该如何操作呢？

**Comment by xuzhengfu** [comment]
事实上，教材原文已经给出了非常详细的信息。所以，我觉得你肯定行——我相信你可以通过自己 ”反复阅读“ 抓住重点，这个过程可能有些不容易，但意义却足够重大，不是吗？

唯一需要提醒的是：`.` 表示 ”当前工作目录“ 的意思。如果对于这句话还有一些困惑，要记得学习支线课程第一讲。

以下是教材原文：

> sys 是 Python 管理系统环境的模块，而 sys.path 保存着一个列表，里面是所有解释器“认识”的目录，这些目录都是解释器会自动去找模块的地方，我们可以看到，运行 Python 解释器的当前目录是自动包含在里面的；然后就是 Python 环境的库所在目录，我们用 pip 安装的库都会放在这些目录下。
> 
> 注意：你的环境里显示出来的这个 sys.path 列表内容可能和我不一样，这没关系。
> 
> 由于我把上面那个 myutil.py 放在这些 notebooks 所在目录下的 assets 子目录下，这个子目录不在上面显示的 sys.path 中，但我们可以把它加进去：
> 
> ```py
> sys.path.append('./assets/')
> ```

如果你看到这里，心里暗想：别跟我废话了，我都看了多少遍了，这还用你说嘛！

那么，答案是：

```py
sys.path.append('./code/pilot-student/')
```

**Comment by muse1171** [comment]
> 事实上，教材原文已经给出了非常详细的信息。所以，我觉得你肯定行——我相信你可以通过自己 ”反复阅读“ 抓住重点，这个过程可能有些不容易，但意义却足够重大，不是吗？
> 
> 唯一需要提醒的是：`.` 表示 ”当前工作目录“ 的意思。如果对于这句话还有一些困惑，要记得学习支线课程第一讲。
> 
> 以下是教材原文：
> 
> > sys 是 Python 管理系统环境的模块，而 sys.path 保存着一个列表，里面是所有解释器“认识”的目录，这些目录都是解释器会自动去找模块的地方，我们可以看到，运行 Python 解释器的当前目录是自动包含在里面的；然后就是 Python 环境的库所在目录，我们用 pip 安装的库都会放在这些目录下。
> > 注意：你的环境里显示出来的这个 sys.path 列表内容可能和我不一样，这没关系。
> > 由于我把上面那个 myutil.py 放在这些 notebooks 所在目录下的 assets 子目录下，这个子目录不在上面显示的 sys.path 中，但我们可以把它加进去：
> > ```python
> > sys.path.append('./assets/')
> > ```
> 
> 如果你看到这里，心里暗想：别跟我废话了，我都看了多少遍了，这还用你说嘛！
> 
> 那么，答案是：
> 
> ```python
> sys.path.append('./code/pilot-student/')
> ```

```python
sys.path.append('./Code/pilot-student/')

import myutil
myutil.say_hi('Neo', 'Trinity')

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-94b736aa9ac6> in <module>
----> 1 import myutil
      2 myutil.say_hi('Neo', 'Trinity')

ModuleNotFoundError: No module named 'myutil'


baojuan@baojuandeMacBook-Pro pilot-student % ls
README.md
assets
learn-git
myutil.py
```
还是不行～～

**Comment by xuzhengfu** [comment]
注意 code 大小写，至于是大写还是小写，我也不知道——都是你告诉我的……

另，不用引用别人的回复（因为严重影响阅读），直接在 issue 下回复即可 —— 就像我这条回复，就没有引用你的话，是不是阅读体验好很多？

**Comment by muse1171** [comment]
我开始以为是大小写的问题，code Code 都试了，都不行。

**Comment by neolee** [comment]
首先，最简单的办法是把你需要引用的 module 放到你的主 notebook 或者主 .py 文件一起，即同一目录下，然后就可以直接 import 了，`sys.path.append` 都不需要。

然后，如果要学习使用 `sys.path.append`，那么要对文件的“绝对路径”和“相对路径”有个正确认识，这些在支线课程第一讲里有说。`./Code/pilot-student/` 表示当前目录（命令行的当前工作目录，或者你的 notebook 所在的目录）下的 Code 子目录下的 pilot-student 子目录下；而 `~/Code/pilot-student/` 表示用户根目录下的 Code 子目录下的 pilot-student 子目录下；等等。

你要确保你的 modules 放在上述目录下才行。

另外，为啥题主会用 pilot-student 这种子目录啊，这不是好久前的古董版本里的东西么。

**Comment by zilin19** [comment]
我也出现过同样的问题，建议认真阅读老师的答复，理解相对路径和绝对路径。可以试试sys.path.append('/Users/baojuan/Downloads./pilot-student/')，希望对你有用。加油。。。。。。

**Comment by xuzhengfu** [comment]
@muse1171 咋样啦…… 问题解决了吗？

**Comment by muse1171** [comment]
我刚刚用了楼上zilin19  说的的方法，已经成功了。谢谢大家的帮助。检讨：我没理解 ('./modules/')这里面哪个.的意思，直接学着老师用./xxx ，造成了失败。

**Comment by muse1171** [comment]
哈哈哈另外回复下老师的。另外，为啥题主会用 pilot-student 这种子目录啊，这不是好久前的古董版本里的东西么。回答：因为题主很懒！！
