### ISSUE TITLE
模块引入报错

### ISSUE THREAD

**Issue by zilin19** [neolee/wop-community#181]
* myutil.py放在notebooks下的assets文件中，为什么执行调用模块 import myutil 和调用其中的is_prime “from myutil import is_prime“时都报错：No modle named ‘myutil’ 。
![Annotation 2019-12-01 114454](https://user-images.githubusercontent.com/51396634/88482063-734f3600-cf91-11ea-9c37-65b0287b123b.png)

**Comment by neolee** [comment]
你这问题和截图有啥关联么？

关于引入自己写的 module，最简单的办法是把你需要引用的 module 放到你的 notebook 或者主 .py 文件一起，即同一目录下，然后就可以直接 import 了。

如果你把 module 文件放在主 notebook 所在目录的 assets 子目录下，需要先用 `sys.path.append("./assets/")` 才能找得到。

截图里的错误是，一般是因为你前面写了类似 `input = "Hello"` 这样的赋值，把 `input` 变成了一个字符串类型的变量，覆盖掉了系统自带的 `input` 函数。

**Comment by zilin19** [comment]
* 问题出在子目录，把assests的本地详细路径输入后运行正常。
*  描述问题的截图张贴错误，“input”错误赋值问题已got。
