### ISSUE TITLE
winsound.Beep 在 jupyter lab 中运行和在命令行中执行 .py 文件时均无声音

### ISSUE THREAD

**Issue by keepgrowing27** [neolee/wop-community#182]
在完成课程第一阶段大作业的过程中，需要用到提示音的功能，使用了类似下面的代码块：
``` python
import winsound

for i in range(5):
    winsound.Beep((i+1)*100,600)
    print(f"Beep: {i+1}")

print("Beep finished")
```
1. 上述代码在 nteract 中执行，可以听到声音，可以输出 `print` 语句，一切运行正常。
2. 上述代码在 jupyter lab 中执行，可以输出 `print` 语句，但没有声音。
3. 上述代码通过 Visual Studio Code 存为 .py 文件，然后在 ConEmu 中执行，可以输出 `print` 语句，但是也没有声音。

方式 1 可以正常出声音，说明电脑音响和代码本身应该都没有问题，而方式 2 和 3 都没有声音，就像是 `winsound.Beep `方法在此两种方式中不起作用一样。
自己已经尝试上网搜索 `winsound.Beep` 的相关说明和用法解释，依然没有找到方式 2、3 无声音的原因和解决方案，还请李老师给些提示和指导。

**Comment by neolee** [comment]
我在所有环境下测试下面的代码：

```python
import winsound

winsound.Beep(2000, 1000)
```

都没问题，无论在 Windows Terminal 下，或者 Jupyter Lab 里，或者 Visual Studio Code 的 Terminal 里。所以我猜可能是你的系统环境的问题？

当然这个 `winsound` 的包只能在 Windows 下使用，macOS 是不行的。

**Comment by keepgrowing27** [comment]
我使用的是 Win10 专业版操作系统。
那现在就确认不是代码的问题，而是我自己系统环境的问题了，
那我就再仔细检查测试下，看问题到底出在哪里？

**Comment by keepgrowing27** [comment]
又在 Windows Terminal 中进行了测试，声音正常。
问题就出在 jupyter lab 和 ConEmu 中，
算了，先不纠结这个问题了，现在就去提交大作业。

**Comment by neolee** [comment]
Jupyter Lab 的话，你的浏览器是啥？我用的是 Chrome。
