### ISSUE TITLE
引入 module 报错

### ISSUE THREAD

**Issue by whxzhou** [neolee/wop-community#184]
![image](https://user-images.githubusercontent.com/48576143/88530894-a1398680-d034-11ea-8755-b7ba96b6a30b.png)
![image](https://user-images.githubusercontent.com/48576143/88530510-1062ab00-d034-11ea-8a3c-8e6759dfdb0f.png)

我这是卡在哪里了？

**Comment by neolee** [comment]
不推荐在 Visual Studio Code 中编辑 `.ipynb` 文件，要么你就用 Jupyter Lab 来编辑运行 `.ipynb` 文件，要么你就在 Visual Studio Code 中编辑运行 `.py` 文件。

另外关于 `import` 已经有好多同样的问题了，请先搜索已有的 issues。

**Comment by xuzhengfu** [comment]
解决 模块路径 的问题之后，记得更正误拼的模块名。
