### ISSUE TITLE
Maximum recursion depth

### ISSUE THREAD

**Issue by HSChloe** [neolee/wop-community#186]
想使用try except 观察Maximum recursion depth，返回值是0，是递归到n=0就终止了吗？
```python
def f(n):
    try:
        return n*f(n-1)
    except:
        return n
f(5)
```

**Comment by neolee** [comment]
你这个思路不成功，因为运行时异常 `RecursionError` 并不会在函数内抛出，而是会在函数调用次数过多时抛出。所以你的代码会抛出异常然后上下文清空，返回一个 0。

其实你把异常处理的部分去掉，让 Python 抛出 `RecursionError`，它也会显示一个调用次数的。

**Comment by kekeyumuku** [comment]
> 想使用try except 观察Maximum recursion depth，返回值是0，是递归到n=0就终止了吗？
> 
> ```python
> def f(n):
>     try:
>         return n*f(n-1)
>     except:
>         return n
> f(5)
> ```

不是
 n等于0的时候，`n*f(n-1)`的结果始终是0
你可以用这个查深度`sys.getrecursionlimit()`

**Comment by HSChloe** [comment]
好像没有显示调用次数
![image](https://user-images.githubusercontent.com/48611079/88810068-72afdd00-d1e7-11ea-8fd4-2889ed8693e5.png)
而且有异常处理时，很快就会返回0，没有异常处理要等待一会儿才会抛出异常，所以感觉两种情况调用次数很不一样

**Comment by neolee** [comment]
在命令行下运行。
