### ISSUE TITLE
运行 print(t.tzinfo) 时出现乱码

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#187]
![image](https://user-images.githubusercontent.com/57065555/88896442-6cb80b80-d27c-11ea-974d-935fdbb6ef58.png)
我是windows 10的系统，运行时出现了乱码，怎么调整可以正确显示呢？

**Comment by neolee** [comment]
你的 Windows 应该设置了系统显示语言为中文，而你看到的乱码，本来应该是一段中文“中国标准时间”。

这是一个经典问题，根源是在 Windows 下 Python 底层使用的库没有正确的设置其语言编码。

为了确认，你可以运行下面的 Python 代码：

```python
import locale

locale.getlocale()
```

其返回很可能是 `(None, None)`，就是上面说的没有正确设置语言编码。解决方案是自己手动指定中文编码：

```python
import locale

locale.setlocale(locale.LC_ALL, "chinese")
```

然后再运行你的时区显示代码就可以了。

**Comment by Amy20191** [comment]
是的，设置后可以了。
