### ISSUE TITLE
P2-6字符串作业第20步的运行错误

### ISSUE THREAD

**Issue by azheng526** [neolee/wop-community#189]
![批注 2020-07-30 作业片段2](https://user-images.githubusercontent.com/50059311/88924686-2bd4ec80-d2a6-11ea-87e0-5d4184146206.png)
![批注 2020-07-30 作业片段1](https://user-images.githubusercontent.com/50059311/88924780-49a25180-d2a6-11ea-97c0-c44c44c09c40.png)

**Comment by neolee** [comment]
按照格式化串，月份该是 07 才行。

**Comment by xuzhengfu** [comment]
同学：说来奇怪，这样写在 macOS 上并不报错……

李骏老师：是的，这就是两个 OS 底层 C 语言库的实现差异导致的，Windows 的那个东西很有个性的……

**Comment by neolee** [comment]
@azheng526 你改了 07 之后就好了？我后来又测试了一下似乎不是这个问题，因为我用 7 在 Windows 下也可以……

**Comment by azheng526** [comment]
李老师，问题我已核实。是我这台机器不识别星期“Wed”（改成“周三”即正常运行）月份的07或7都没问题。Win10好神奇

**Comment by neolee** [comment]
> 李老师，问题我已核实。是我这台机器不识别星期“Wed”（改成“周三”即正常运行）月份的07或7都没问题。Win10 好神奇

Emmm 确实神奇啊……
