### ISSUE TITLE
Mac 安装 Python jupyterlab 问题

### ISSUE THREAD

**Issue by Jackgong1** [neolee/wop-community#19]
brew install python 
显示 3.7.7 already installed, it's just not linked.
请问怎样link？
pip install jupyterlab 
显示command not found

**Comment by neolee** [comment]
你提供的信息太少，有些东西只好猜了。

首先你需要 `brew link python`，这一步一般是不必要的，因为你 `brew install python` 的时候会自动进行，现在显示为已安装未 link，一般是有些问题的，但你没说，猜不出原因。

其次，macOS 的某些版本中有自带一个老的 Python 2.7，而命令 `python` 和 `pip` 都是指向这个老版本，你做一些处理就可以解决这个问题，在课程资源-附录1&2里有说明，仔细阅读：

<img width="793" alt="python" src="https://user-images.githubusercontent.com/24796/86439824-defc0580-bd3b-11ea-918e-c092f2d8fcba.png">

<img width="792" alt="pip" src="https://user-images.githubusercontent.com/24796/86439836-e4595000-bd3b-11ea-89b2-ee85cb9a3859.png">

**Comment by Jackgong1** [comment]
> 你提供的信息太少，有些东西只好猜了。
> 
> 首先你需要 `brew link python`，这一步一般是不必要的，因为你 `brew install python` 的时候会自动进行，现在显示为已安装未 link，一般是有些问题的，但你没说，猜不出原因。
> 
> 其次，macOS 的某些版本中有自带一个老的 Python 2.7，而命令 `python` 和 `pip` 都是指向这个老版本，你做一些处理就可以解决这个问题，在课程资源-附录1&2里有说明，仔细阅读：
> 
> <img alt="python" width="793" src="https://user-images.githubusercontent.com/24796/86439824-defc0580-bd3b-11ea-918e-c092f2d8fcba.png">
> 
> <img alt="pip" width="792" src="https://user-images.githubusercontent.com/24796/86439836-e4595000-bd3b-11ea-89b2-ee85cb9a3859.png">

**Comment by Jackgong1** [comment]
> > 你提供的信息太少，有些东西只好猜了。
> > 首先你需要 `brew link python`，这一步一般是不必要的，因为你 `brew install python` 的时候会自动进行，现在显示为已安装未 link，一般是有些问题的，但你没说，猜不出原因。
> > 其次，macOS 的某些版本中有自带一个老的 Python 2.7，而命令 `python` 和 `pip` 都是指向这个老版本，你做一些处理就可以解决这个问题，在课程资源-附录1&2里有说明，仔细阅读：
> > <img alt="python" width="793" src="https://user-images.githubusercontent.com/24796/86439824-defc0580-bd3b-11ea-918e-c092f2d8fcba.png">
> > <img alt="pip" width="792" src="https://user-images.githubusercontent.com/24796/86439836-e4595000-bd3b-11ea-89b2-ee85cb9a3859.png">

可以发运行码照片给您看下么？
我在新加坡，应该不应清华那个链接。

**Comment by neolee** [comment]
你在新加坡的话，网络应该没啥问题，不需要用别的镜像站。

简单说，你需要做几个事情：

* `brew link python` 完成 Python 安装；
* 按照附录1里的指引建立 python 命令指向你安装的 Python 3.7；
* 按照附录2里的指引，用 `pip3 install jupyterlab` 安装 JupyterLab。

这些操作，一步成功了再做下一步，如果遇到错误提示，尝试分析原因和解决，有问题可以补充到这里。

可以发截图，如何在这里贴图在这个 repo 的首页有说明： https://github.com/neolee/wop-community

**Comment by Jackgong1** [comment]
> 你在新加坡的话，网络应该没啥问题，不需要用别的镜像站。
> 
> 简单说，你需要做几个事情：
> 
> * `brew link python` 完成 Python 安装；
> * 按照附录1里的指引建立 python 命令指向你安装的 Python 3.7；
> * 按照附录2里的指引，用 `pip3 install jupyterlab` 安装 JupyterLab。
> 
> 这些操作，一步成功了再做下一步，如果遇到错误提示，尝试分析原因和解决，有问题可以补充到这里。
> 
> 可以发截图，如何在这里贴图在这个 repo 的首页有说明： https://github.com/neolee/wop-community
李老师，下面是输入brew link python 的error：麻烦帮忙看下怎么处理。

Warning: python 3.7.7 is already installed, it's just not linked
You can use `brew link python` to link this version.
chens-MacBook-Air:~ chenluheng$ 
chens-MacBook-Air:~ chenluheng$ brew link python
Linking /usr/local/Cellar/python/3.7.7... 
Error: Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python

**Comment by neolee** [comment]
嗯，果然，是有本来就存在的文件阻碍你配置你安装的 Python，似乎你以前用别的办法装过 Python 吧？

很简单，就按照它给你的提示，执行 `brew link --overwrite python` 就好了。

**Comment by Jackgong1** [comment]
> > 你在新加坡的话，网络应该没啥问题，不需要用别的镜像站。
> > 简单说，你需要做几个事情：
> > 
> > * `brew link python` 完成 Python 安装；
> > * 按照附录1里的指引建立 python 命令指向你安装的 Python 3.7；
> > * 按照附录2里的指引，用 `pip3 install jupyterlab` 安装 JupyterLab。
> > 
> > 这些操作，一步成功了再做下一步，如果遇到错误提示，尝试分析原因和解决，有问题可以补充到这里。
> > 可以发截图，如何在这里贴图在这个 repo 的首页有说明： https://github.com/neolee/wop-community
> > 李老师，下面是输入brew link python 的error：麻烦帮忙看下怎么处理。
> 
> Warning: python 3.7.7 is already installed, it's just not linked
> You can use `brew link python` to link this version.
> chens-MacBook-Air:~ chenluheng$
> chens-MacBook-Air:~ chenluheng$ brew link python
> Linking /usr/local/Cellar/python/3.7.7...
> Error: Could not symlink bin/2to3
> Target /usr/local/bin/2to3
> already exists. You may want to remove it:
> rm '/usr/local/bin/2to3'
> 
> To force the link and overwrite all conflicting files:
> brew link --overwrite python
> 
> To list all files that would be deleted:
> brew link --overwrite --dry-run python

输入 Python -V, 显示版本是2.7.10.
但是输入install
Last login: Fri Jul  3 16:36:46 on ttys000
chens-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
chens-MacBook-Air:~ chenluheng$ brew install python
Updating Homebrew...
Warning: python 3.7.7 is already installed and up-to-date
To reinstall 3.7.7, run `brew reinstall python`
chens-MacBook-Air:~ chenluheng$ pip install jupyterlab
-bash: pip: command not found
chens-MacBook-Air:~ chenluheng$ 



> 嗯，果然，是有本来就存在的文件阻碍你配置你安装的 Python，似乎你以前用别的办法装过 Python 吧？
> 
> 很简单，就按照它给你的提示，执行 `brew link --overwrite python` 就好了。

李老师，我重新开启了terminal：
brew install python, 
显示already installed 3.7.7
但是输入Python -V
显示2.7.10
pip install jupyterlab 
显示command not found .
请问什么问题？ 

Last login: Fri Jul  3 20:35:30 on ttys000
chens-MacBook-Air:~ chenluheng$ brew install python
Updating Homebrew...
Warning: python 3.7.7 is already installed and up-to-date
To reinstall 3.7.7, run `brew reinstall python`
chens-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
chens-MacBook-Air:~ chenluheng$ pip install jupyterlab
-bash: pip: command not found
chens-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
请你仔仔细细的把我上面的每个回复再读一遍，最好读出声来。然后把附录1和2也好好读一遍。

**Comment by Jackgong1** [comment]
> 请你仔仔细细的把我上面的每个回复再读一遍，最好读出声来。然后把附录1和2也好好读一遍。

谢谢李老师神速回复。
我强制执行了，貌似还是不可以，恕我愚笨。

Last login: Fri Jul  3 21:46:11 on ttys000
chens-MacBook-Air:~ chenluheng$ rm /usr/local/bin/python
rm: /usr/local/bin/python: No such file or directory
chens-MacBook-Air:~ chenluheng$ ln -s/usr/local/bin/python3 usr/local/bin/python
ln: illegal option -- /
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
chens-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
你这不是愚笨的问题，是没耐心。

> 简单说，你需要做几个事情：
> 
> * `brew link python` 完成 Python 安装；
> * 按照附录1里的指引建立 python 命令指向你安装的 Python 3.7；
> * 按照附录2里的指引，用 `pip3 install jupyterlab` 安装 JupyterLab。
> 
> 这些操作，一步成功了再做下一步，如果遇到错误提示，尝试分析原因和解决，有问题可以补充到这里。

这是我前面的答复，请问你有没有一步步做我这里列出的三件事？第一件成功了么？没成功的话遇到什么问题？

你上面写的是第二件事，然后你的命令输错了，`-s` 后面需要一个空格——自己想一想，这样的问题和智力有关么？没有吧……

**Comment by Jackgong1** [comment]
> 你这不是愚笨的问题，是没耐心。
> 
> > 简单说，你需要做几个事情：
> > 
> > * `brew link python` 完成 Python 安装；
> > * 按照附录1里的指引建立 python 命令指向你安装的 Python 3.7；
> > * 按照附录2里的指引，用 `pip3 install jupyterlab` 安装 JupyterLab。
> > 
> > 这些操作，一步成功了再做下一步，如果遇到错误提示，尝试分析原因和解决，有问题可以补充到这里。
> 
> 这是我前面的答复，请问你有没有一步步做我这里列出的三件事？第一件成功了么？没成功的话遇到什么问题？
> 
> 你上面写的是第二件事，然后你的命令输错了，`-s` 后面需要一个空格——自己想一想，这样的问题和智力有关么？没有吧……
第一步 Brew link python 做了。 附录1也做了，还是不可以，请指正

Last login: Fri Jul  3 21:55:14 on ttys000
Gong-MacBook-Air:~ chenluheng$ brew link python
Warning: Already linked: /usr/local/Cellar/python/3.7.7
To relink:
  brew unlink python && brew link python
Gong-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
Gong-MacBook-Air:~ chenluheng$ rm /usr/local/bin/python
Gong-MacBook-Air:~ chenluheng$ ln -s /usr/local/bin/python3 /usr/local/bin/python
Gong-MacBook-Air:~ chenluheng$ 
Gong-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
Gong-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
好，一步步来，第一步应该是成了，现在我们来解决第二步。

执行下面的诊断命令（一个个运行），把结果告诉我：

```shell
echo $PATH

which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by Jackgong1** [comment]
> 好，一步步来，第一步应该是成了，现在我们来解决第二步。
> 
> 执行下面的诊断命令（一个个运行），把结果告诉我：
> 
> ```shell
> echo $PATH
> 
> which python
> which python3
> python -V
> python3 -V
> pip -V
> pip3 -V
> ```
如下
Last login: Fri Jul  3 22:11:39 on ttys000
Gong-MacBook-Air:~ chenluheng$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
Gong-MacBook-Air:~ chenluheng$ which python
/usr/bin/python
Gong-MacBook-Air:~ chenluheng$ which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
Gong-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
Gong-MacBook-Air:~ chenluheng$ python3 -V
Python 3.8.1
Gong-MacBook-Air:~ chenluheng$ pip -V
-bash: pip: command not found
Gong-MacBook-Air:~ chenluheng$ pip -V
-bash: pip: command not found
Gong-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
你上面又有一个命令执行错了，最后一个命令应该是 `pip3 -V`——需要多练练自己的专注力啊。

然后再多执行一个命令看看：`echo $SHELL`。

**Comment by Jackgong1** [comment]
如下：
Last login: Fri Jul  3 22:22:01 on ttys000
Gong-MacBook-Air:~ chenluheng$ 
Gong-MacBook-Air:~ chenluheng$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
Gong-MacBook-Air:~ chenluheng$ which python
/usr/bin/python
Gong-MacBook-Air:~ chenluheng$ which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
Gong-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
Gong-MacBook-Air:~ chenluheng$ python3 -V
Python 3.8.1
Gong-MacBook-Air:~ chenluheng$ pip -V
-bash: pip: command not found
Gong-MacBook-Air:~ chenluheng$ pip3 -V
pip 19.2.3 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
Gong-MacBook-Air:~ chenluheng$ echo $SHELL
/bin/bash
Gong-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
好，信息够了，有两个问题：

1. 你用别的方法安装过一个 Python 3.8（位置在 `/Library/Frameworks/Python.framework/Versions/3.8/`），这个是我们不会用的版本，虽然可以不管它，但是不确定你还装过别的什么东西，是个小的隐患。

2. 你虽然装好了 Homebrew，但是没有把 Homebrew 的路径加到 $PATH 这个环境配置里去，这一步 Homebrew 安装程序如果没问题是会自动做的，但不知道为啥你这里没有做好。要解决这个问题可以手工操作：

* 先下载和装好 Visual Studio Code（本来就要装的，附录一的指南里有），并按照指南里的方法安装好 code 这个命令；
* 在命令行执行 `code ~/.bash_profile`，这会打开你的命令行配置文件，不管里面有啥，在最后添加：
```shell
export PATH="/usr/local/bin:$PATH"
```
* 保存 `.bash_profile` 文件，退出 Visual Studio Code；
* 回到命令行执行 `exit` 退出当前窗口，然后新开一个命令行窗口。

做完上面的所有操作之后，在新打开的命令行窗口里再执行一遍前面的诊断：

```shell
echo $PATH

which python
which python3
python -V
python3 -V
pip3 -V
```

你可以自己比较下两次的结果——然后把结果给我看。

**Comment by Jackgong1** [comment]
李老师，现在变成了3.7.如下。 



Last login: Sat Jul  4 10:48:14 on ttys000
Gong-MacBook-Air:~ chenluheng$ echo $PATH
/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
Gong-MacBook-Air:~ chenluheng$ which python
/usr/bin/python
Gong-MacBook-Air:~ chenluheng$ which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
Gong-MacBook-Air:~ chenluheng$ python -V
Python 2.7.10
Gong-MacBook-Air:~ chenluheng$ python3 -V
Python 3.8.1
Gong-MacBook-Air:~ chenluheng$ pip3 -V
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Gong-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
你这没变 3.7 啊，`python3 -V` 还是 `/Library/Frameworks/Python.framework/Versions/3.8/` 下面那个 3.8 的啊。

这说明在 Homebrew 的地盘里（`/usr/local/bin` 目录下）没有 python3 这个程序。你确定你 `brew install python` 和 `brew link python` 都成功了？之前我给你的三件事，你说第一件已经做了，但一直没给我看截图或者相关返回信息。

必要时重新 link 下：`brew unlink python && brew link python` 然后 `/usr/local/bin/python3 -V`

**Comment by Jackgong1** [comment]
![Screen Shot 2020-07-04 at 12 30 17 PM](https://user-images.githubusercontent.com/40572207/86505014-2e9d0880-bdf2-11ea-8d43-caa2c26624ce.png)

**Comment by neolee** [comment]
你最后一个命令还没执行 `/usr/local/bin/python3 -V`，这个返回啥？

以及现在那几个诊断命令的返回是啥？

```shell
which python
which python3
python -V
python3 -V
pip3 -V
```

p.s. `brew unlink python && brew link python` 这个命令你执行时 `&&` 后面少了一个空格，虽然这一次不影响结果，但是在调问题的时候一定要非常细心，严格按照我给你的去执行。

**Comment by Jackgong1** [comment]
![Screen Shot 2020-07-04 at 12 45 27 PM](https://user-images.githubusercontent.com/40572207/86505193-44133200-bdf4-11ea-9a6b-c80095ab101e.png)

**Comment by neolee** [comment]
噢，所以你觉得有啥变化了？

**Comment by Jackgong1** [comment]
现在应该算是安装成功了，3.7.7 吧？
python -V 一直是2.7.10

**Comment by neolee** [comment]
现在你的 python 和 python3 这两个命令都是指向你安装的 Python 3.7.7 了，pip3 也指向这个 Python 环境，所以基本上都对了。

你可以用下面的命令给 pip3 建立一个别名，以后用起来方便：

```shell
ln -s /usr/local/bin/pip3 /usr/local/bin/pip
```

然后就可以继续去安装 JupyterLab 了，这次应该没啥问题了。

**Comment by Jackgong1** [comment]
如下，请问是否说明已经安装成功Jupyterlab 了?

Gong-MacBook-Air:~ chenluheng$ pip install jupyterlab
-bash: pip: command not found
Gong-MacBook-Air:~ chenluheng$ pip3 install jupyterlab
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.7/site-packages (2.1.5)
Requirement already satisfied: notebook>=4.3.1 in /usr/local/lib/python3.7/site-packages (from jupyterlab) (6.0.3)
Requirement already satisfied: jupyterlab-server<2.0,>=1.1.0 in /usr/local/lib/python3.7/site-packages (from jupyterlab) (1.1.5)
Requirement already satisfied: jinja2>=2.10 in /usr/local/lib/python3.7/site-packages (from jupyterlab) (2.11.2)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /usr/local/lib/python3.7/site-packages (from jupyterlab) (6.0.4)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (0.8.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (4.6.3)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (4.3.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (5.6.1)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (5.3.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (0.2.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (19.0.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (0.8.3)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (1.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (5.0.7)
Requirement already satisfied: jupyter-client>=5.3.4 in /usr/local/lib/python3.7/site-packages (from notebook>=4.3.1->jupyterlab) (6.1.5)
Requirement already satisfied: jsonschema>=3.0.1 in /usr/local/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.0->jupyterlab) (3.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.0->jupyterlab) (2.24.0)
Requirement already satisfied: json5 in /usr/local/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.0->jupyterlab) (0.9.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from jinja2>=2.10->jupyterlab) (1.1.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (4.4.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (1.15.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (1.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (3.1.5)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.4.4)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (2.6.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.6.0)
Requirement already satisfied: appnope; platform_system == "Darwin" in /usr/local/lib/python3.7/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.7/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (7.16.1)
Requirement already satisfied: ptyprocess; os_name != "nt" in /usr/local/lib/python3.7/site-packages (from terminado>=0.8.1->notebook>=4.3.1->jupyterlab) (0.6.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyterlab) (2.8.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (1.7.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (0.16.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (19.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (46.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (3.0.4)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab) (0.5.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab) (20.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (3.0.5)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.17.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.0->jupyterlab) (3.1.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyterlab) (2.4.7)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /usr/local/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.7.0)
Gong-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
创建一个目录，进入这个目录，然后执行 `jupyter lab`，成功的话就说明装好了。

另外，前面不是告诉你怎么创建一个 pip 别名，这样就可以用 `pip install xxx` 了，为啥不做呢……

我觉得对这个帖，你可以深入总结一下，有哪些地方可以提升解决问题的效率……

**Comment by Jackgong1** [comment]
> 创建一个目录，进入这个目录，然后执行 `jupyter lab`，成功的话就说明装好了。
> 
> 另外，前面不是告诉你怎么创建一个 pip 别名，这样就可以用 `pip install xxx` 了，为啥不做呢……
> 
> 我觉得对这个帖，你可以深入总结一下，有哪些地方可以提升解决问题的效率……


输入以下 command ，跳出了如截图所示，请问是否表明成功了安装jupyter lab ?

Gong-MacBook-Air:~ chenluheng$ /Users/chenluheng/Code 
-bash: /Users/chenluheng/Code: is a directory
Gong-MacBook-Air:~ chenluheng$ jupyter lab


![Screen Shot 2020-07-04 at 1 29 47 PM](https://user-images.githubusercontent.com/40572207/86505679-85a6db80-bdfa-11ea-8241-76e41aca3306.png)

**Comment by neolee** [comment]
这样就可以了。建议你抽时间看一下支线课程，尤其是命令行、JupyterLab、Markdown 那几个。

**Comment by Jackgong1** [comment]
谢谢您的耐心指导。 
今天下午看一下。 
还有个问题是，请问怎样用电脑打开这个网课？

我试了copy 链接不可以。
网页版微信也不可以。 
苹果的微信程序也不可以。

**Comment by neolee** [comment]
用桌面版的微信是可以的，安装桌面版微信，用手机微信授权登录。为了方便，你可以在手机打开课程主页，把这个主页加入收藏，然后在桌面版微信里从收藏里进去，这是最简单的办法。

**Comment by Jackgong1** [comment]
> 用桌面版的微信是可以的，安装桌面版微信，用手机微信授权登录。为了方便，你可以在手机打开课程主页，把这个主页加入收藏，然后在桌面版微信里从收藏里进去，这是最简单的办法。

好的，看到了。谢谢李老师。
