### ISSUE TITLE
函数 id 每台计算机是不同的吗？

### ISSUE THREAD

**Issue by zanglei-80** [neolee/wop-community#190]
在写第七课作业时看到您说函数的id都是唯一的，但为什么在我电脑上显示的和你作业中给的数字不一样？
![捕获3](https://user-images.githubusercontent.com/60951614/88929964-6b530700-d2ad-11ea-953f-5df4f558b00d.PNG)
![捕获4](https://user-images.githubusercontent.com/60951614/88929975-6db56100-d2ad-11ea-9f8c-a78cba7edea6.PNG)

**Comment by zanglei-80** [comment]
图片上传成功了吗

**Comment by neolee** [comment]
这个上课我说了，id 是每次运行自动生成的，不是确定的数字。

**Comment by zanglei-80** [comment]
听漏了
