### ISSUE TITLE
怎样保存 myutil.py 文件

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#191]
在“模块”这一章中提到，把写好的函数保存为一个叫做myutil.py的文件。
我把那一段两个函数写完后，直接摁了Ctrl+Enter，也没见到保存的提示，这样是不是根本没有保存呢？因为之后引用模块的时候也报错了，提示：No module named 'myutil'
请问怎样保存myutil.py文件？

**Comment by xuzhengfu** [comment]
1. 打开 VSCode，新建一个文件，命名为 `myutil.py`；

2. 把代码复制到这个文件当中，而后 Ctrl + S 保存。

**Comment by yuexiangming** [comment]
谢谢正福同学，谢谢李老师，问题解决了。我把 myutil.py 文件保存在  \\Users\\86134\\code\\my-student-book' ，没有添加目录，直接 import 就可以。
