### ISSUE TITLE
Windows 下有没有办法表示日期的压缩格式呢？

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#194]
print("压缩版日期：", t.strftime("%Y-%-m-%-d")) # 压缩格式 %-m 和 %-d 不被 Windows 支持，所以这一句在 Windows 环境下会出错，那么，Windows 下有没有办法表示日期的压缩格式呢？

**Comment by neolee** [comment]
没有直接的办法，MSDN 的文档有列出 Windows 下 strftime 支持的格式码：

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2019
