### ISSUE TITLE
scoop 卸载

### ISSUE THREAD

**Issue by blueeyezhy** [neolee/wop-community#195]
我原来用的anaconda安装的python和jupyterlab，运行在虚拟环境下，powersell的路径也默认在这个虚拟环境之下。
今天安装scoop准备用，scoop管理安装包，没注意环境，安装在anaconda的虚拟环境下了。途中我又把anaconda卸载了。

结果，系统不识别 scoop，卸载不了。
![image](https://user-images.githubusercontent.com/33739411/89028636-5cc52800-d35f-11ea-9381-440912eb1653.png)

重新安装时显示已安装。
![image](https://user-images.githubusercontent.com/33739411/89028703-7e261400-d35f-11ea-845b-fc357d547f4b.png)

该怎么卸载呢？

原powershell启动ps文件是：
![image](https://user-images.githubusercontent.com/33739411/89028825-a6ae0e00-d35f-11ea-90d5-a2d0c1e55b2d.png)

scoop启动ps文件是：
![image](https://user-images.githubusercontent.com/33739411/89028878-c5140980-d35f-11ea-8322-8bd2be201d80.png)

**Comment by neolee** [comment]
点这个页面上方的 Wiki 链接，按照 “重装 Scoop” 提示操作。

**Comment by blueeyezhy** [comment]
谢谢老师
