### ISSUE TITLE
jupyter-lab 与 jupyter lab

### ISSUE THREAD

**Issue by blueeyezhy** [neolee/wop-community#197]
我原来安装的是anaconda，可以通过jupyter lab启动jupyter lab的编辑器；卸载anaconda，通过scoop安装 python和 jupyter
 lab后，jupyter 命令就无法识别了；
![image](https://user-images.githubusercontent.com/33739411/89078296-b7d63980-d3b6-11ea-9af2-db87367d053e.png)

我将scoop里 python script添加到环境变量里，可以通过 jupyter-lab 启动jupyter lab的编辑器
![image](https://user-images.githubusercontent.com/33739411/89078453-0c79b480-d3b7-11ea-8e17-5b62bf6ddbd7.png)

虽然解决了 学习，使用的问题，但是我想知道为什么 jupyter lab 命令不行，怎么让他行？
感觉上是 jupyter 命令的注册问题，怎解决这一类的问题？

**Comment by neolee** [comment]
感觉是你的 Jupyter Lab 没有装好，你看下你的 `C:\Users\<username>\scoop\apps\python37\current\Scripts` 目录下有些啥，应该有 `jupyter` 和一大串 `jupyter-xxxx` 的可执行文件或脚本。

你上面的出错截图是说找不到 `jupyter` 这个程序，所以应该不是“命令注册”的问题，事实上 `jupyter` 的命令处理也很简单，就是你执行 `jupyter xxx` 的话 `jupyter` 就去找 `jupyter-xxx` 的程序来运行而已。

**Comment by blueeyezhy** [comment]
![image](https://user-images.githubusercontent.com/33739411/89096607-7c655a80-d40a-11ea-9657-129f61b19bb0.png)
这些文件和脚本，还缺什么吗？

**Comment by neolee** [comment]
缺个 `jupyter.exe`。

应该是Jupyter Lab 没装好。

**Comment by blueeyezhy** [comment]
anaconda 在 appdata/roaming里面有残留，jupyter.exe等文件都在，anaconda文件夹全部删除。然后重新 pip install jupyterlab安装就好了。
![image](https://user-images.githubusercontent.com/33739411/89098397-d91c4180-d419-11ea-906c-49ce17f893ea.png)

但是还有报错 Error loading server extension jupyter_nbextensions_configurator 。
百度了一下，安装 ` pip install jupyter_contrib_nbextensions` 后就好了。
![image](https://user-images.githubusercontent.com/33739411/89098500-d9690c80-d41a-11ea-8287-8eed2bb5c757.png)

**Comment by xuzhengfu** [comment]
你是用官网上的方法彻底卸载 anaconda 的吗？

https://docs.anaconda.com/anaconda/install/uninstall/

**Comment by blueeyezhy** [comment]
没有，用win的安装与卸载卸载的，后来发现roaming里面有残留，就把roaming里的anaconda文件夹一起删了。

**Comment by neolee** [comment]
我猜大致是这样的：以前你用的是 Anaconda 的一整套，删掉 Anaconda 之后 Python 和 Jupyter 都是 Scoop 体系了，但是 Jupyter 老的配置信息还在，还在试图加载一些原来的扩展比如这个 jupyter_nbextensions_configurator——其实这东西并不是必需的。

你的 Jupyter 配置文件应该在 `~/.jupyter` 这个目录下，你可以看看是不是有一些遗留的老配置。

**Comment by blueeyezhy** [comment]
嗯，有道理。
总之问题解决了。

发自我的华为手机


-------- 原始邮件 --------
发件人： Neo Lee <notifications@github.com>
日期： 2020年8月1日周六 18:24
收件人： neolee/wop-community <wop-community@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, State change <state_change@noreply.github.com>
主 题： Re: [neolee/wop-community] jupyter-lab 与 jupyter lab (#197)

我猜大致是这样的：以前你用的是 Anaconda 的一整套，删掉 Anaconda 之后 Python 和 Jupyter 都是 Scoop 体系了，但是 Jupyter 老的配置信息还在，还在视图加载一些原来的扩展比如这个 jupyter_nbextensions_configurator――其实这东西主要是兼容老的 nbextensions 用的，并不是必须的。

―

**Comment by xuzhengfu** [comment]
现在启动 jupyter lab 没有报错了么？

**Comment by blueeyezhy** [comment]
没有了，已经解决了。

发自我的华为手机


-------- 原始邮件 --------
发件人： zhengfu <notifications@github.com>
日期： 2020年8月1日周六 19:10
收件人： neolee/wop-community <wop-community@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, State change <state_change@noreply.github.com>
主 题： Re: [neolee/wop-community] jupyter-lab 与 jupyter lab (#197)

现在启动 jupyter lab 没有报错了么？

―

**Comment by xuzhengfu** [comment]
感谢，受益良多！

**Comment by blueeyezhy** [comment]
老师，我吧原来的`~/.jupyter` 也删除了。现在都是8/1号新文件了。

**Comment by neolee** [comment]
> 老师，我吧原来的`~/.jupyter` 也删除了。现在都是8/1号新文件了。

嗯嗯，这样应该更加干净，隐患少一些。
