### ISSUE TITLE
Iterable 与 Iterator 举例问题

### ISSUE THREAD

**Issue by lgqbee** [neolee/wop-community#198]
## Iterable 与 Iterator这一章节教材中提到：
X 可以同时支持 __iter__() 和 __next__()，这样 X 既是 iterable 也是自己的 iterator，可以省略取迭代器的步骤，直接用 __next__() 开始，list，tuple，dictionary，set 几种 iterable 的内置数据容器都是这么做的。
1. 能不能举例一个不是它自己的例子？2. 是不是iterable也是自己的 iterator是常见现象？那八股文：
```
def__iter__(self):
    return self 
```
这句是不是不用写了。

**Comment by neolee** [comment]
首先，如果你要把你的对象用在 `for...in` 里面，就必须实现 `__iter__` 和 `__next__` 两个方法，原因课上讲了。

如果你不用 `for...in` 迭代循环，自己用 `next()` 来取数，那只要实现 `__next__` 方法就行了。

另外，在很少的情况下，可能会在不同对象中复用一个 iterator，那么就会出现不是 `return self` 的情况了。
