### ISSUE TITLE
关于写程序时会面对的问题之问题的定义

### ISSUE THREAD

**Issue by learningtowritecode** [neolee/wop-community#199]
老师在第一讲中讲到写程序一定会碰到定义的问题。计算机是无法处理定义不确定的问题。所以必须把不确定的东西变成确定的东西，计算机才能处理。面对问题，这种把不确定的东西变成确定的东西。是否包括概念的定义和规则的定义两个方面？
比如我们写一个让计算机从申请者中选出若干高个子男性参加篮球队的程序，首先，我们必须给计算机一个“高个子男性”这个概念的确定的定义，即此处是把概念的定义确定。其次，在“高个子男性”这个概念确定后，在“高个子男性”这个人群中选出若干参加篮球队的规则并不确定，因此计算机无法处理，所以，应该确定选拔的规则，比如这个规则可以是随机选拔，也可以是规定BMI在22-24之间，总之，这是对规则的定义。
所以，我对问题的定义的理解是包括两个方面：1.概念的定义 2.规则的定义。不知我理解的是否正确。

此外老师说问题的定义包括了一些边界和特殊情况。
“一些边界”是否指一个概念被定义之后，这个概念就有了清晰的边界，比如对“高个子男性”的定义是高于等于一米八。那么“高个子男性”这个概念就有了边界。不到一米八的男性就不算高个子。
“特殊情况”是否指一些非常规的情况，比如数字相同的卡片利用第二属性排序。

**Comment by neolee** [comment]
> 所以，我对问题的定义的理解是包括两个方面：1.概念的定义 2.规则的定义。

基本正确，但还要加上一个： 3. 目标的定义。基本概念、规则和目标，就定义了一个问题，其他的比如边界之类的是在此基础上的细节补充（边界条件其实是规则的一种）。
