### ISSUE TITLE
Homebrew 无法安装

### ISSUE THREAD

**Issue by TurtleNinja42** [neolee/wop-community#2]

**Comment by runningscott** [comment]
我已经按照您的链接安装了国内镜像版本了，应该是成功了，是不是可以直接用了？
<img width="1048" alt="截屏2020-06-24 15 23 22" src="https://user-images.githubusercontent.com/42107780/85515365-9d7aa480-b62f-11ea-92d3-af7efe9130f5.png">
<img width="989" alt="截屏2020-06-24 15 25 42" src="https://user-images.githubusercontent.com/42107780/85515375-a0759500-b62f-11ea-93fc-e6f2b67c9a0e.png">

之后想换成原版的话应该也有方法吧？

**Comment by runningscott** [comment]
Xcode我从APP Store下载过的，网络问题是指命令行没有翻墙吗？

**Comment by neolee** [comment]
？？？

**Comment by TurtleNinja42** [comment]
> ？？？

李老师，您好，我下载了您提供的 Homebrew 国内镜像版本就可以用了，然后也通过它下载了Python等软件，Xcode Command Line Tools下载不了我从网上搜到了解决方法 https://www.xiebruce.top/593.html ， 从官网上下载成功了 https://developer.apple.com/download/more/  。这是相关问题链接 #1 ，跟我有类似问题的朋友也可以试试。

**Comment by TurtleNinja42** [comment]
<img width="989" alt="截屏2020-06-24 15 25 42" src="https://user-images.githubusercontent.com/42107780/85924169-088fd980-b8c3-11ea-8309-8bcdf60aab12.png">
抱歉我在这里的发帖和评论用的不熟，附上安装成功截图

**Comment by neolee** [comment]
没关系，会越用越熟的。
