### ISSUE TITLE
Homebrew 安装 python 异常

### ISSUE THREAD

**Issue by Jackgong1** [neolee/wop-community#20]
李老师您好，已经用Brew 安装了Python, 显示以下warning
我安装不了jupyterlab. 

Last login: Fri Jul  3 14:21:58 on ttys000
chens-MacBook-Air:~ chenluheng$ brew install python
Updating Homebrew...
Warning: python 3.7.7 is already installed, it's just not linked
You can use `brew link python` to link this version.
chens-MacBook-Air:~ chenluheng$

**Comment by neolee** [comment]
你为啥关了 #19 问题然后又开这个一样的问题啊？继续在那边解决吧，我已经重新打开了。

**Comment by neolee** [comment]
Duplicate of #19
