### ISSUE TITLE
git add 无法跟踪文件

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#200]
使用MAC 10.15.5 
相关课程：支线 git和github

成功建立learn-git文件夹，并建立README.md文件
输入git add .\README.md 后，提示“fatal: 路径规格 '.README.md' 未匹配任何文件”

另外，不知道自动出现一个”package.json“文件是啥意思？

<img width="544" alt="截屏2020-08-01 下午11 46 21" src="https://user-images.githubusercontent.com/55272650/89105248-1ac8de80-d452-11ea-8300-fb2efad3026f.png">

**Comment by neolee** [comment]
你的文件名没写对，应该是 `git add README.md` 或者 `git add ./README.md` 都可以，但你写的正好错成了另外两个样子。
