### ISSUE TITLE
Python 安装问题

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#201]
由于重装系统，编程环境需要重新配置，在安装python时遇到问题：
1.使用命令 scoop install python37@3.7.4 安装问题，报错如下：

![error1](https://user-images.githubusercontent.com/53089964/89105220-e05f4180-d451-11ea-9810-ee78d5618a7c.PNG)

2.使用安装包安装，在默认路径安装，安装界面 Add to path 选项也勾选，安装成功，但是在命令行界面使用命令 python -V 查看版本的时候报错：

![error2](https://user-images.githubusercontent.com/53089964/89105271-421fab80-d452-11ea-9656-6378bbd20bd1.PNG)

老师给提示一下。

**Comment by neolee** [comment]
没有正确按照指南操作，没有成功 `scoop bucket add versions` 和 `scoop update`。
