### ISSUE TITLE
课程大练习二 - 集中区

### ISSUE THREAD

**Issue by neolee** [neolee/wop-community#202]
希望参与大练习二的 _社交化大作业_ 活动的同学，请把你提交的 gist 链接回复到这个贴。请注意：

1. 本帖回复只需要贴出 gist 链接，**不要**写任何其他东西；
2. 要对某个 gist 进行评论的请在该 gist 下面回复，**不要**写在这里。

**Comment by xuzhengfu** [comment]
https://gist.github.com/Xuzhengfu/075c8121b1f1410e5fb4f4f3e0382e6c

**Comment by jiaobufan** [comment]
https://gist.github.com/jiaobufan/9868551a89a0dc02574826e502f8dc21

**Comment by Createitv** [comment]
https://github.com/Createitv/LongTermCode/commit/b13848172c6557579e6300cfd27209bf2d59f7df

**Comment by Createitv** [comment]
https://github.com/Createitv/LongTermCode/blob/master/WoP/assignment2.py

**Comment by blueeyezhy** [comment]
https://gist.github.com/blueeyezhy/677033e8461bc30b0d9e940417702526

**Comment by Createitv** [comment]
> https://gist.github.com/blueeyezhy/677033e8461bc30b0d9e940417702526

Beautiful code

**Comment by hendasheng** [comment]
https://gist.github.com/N1U/3de70d0f633357e130ba88056a5466d0

**Comment by Rick-Zo** [comment]
https://gist.github.com/DerickZo/41688bb02ff81a5e53661ddf4a580db8

**Comment by lgqbee** [comment]
https://gist.github.com/lgqbee/c385b329793b55783e22963ba3753ce7

**Comment by gaoteng-pro** [comment]
https://gist.github.com/gaoteng-pro/0d5138c9fca256663e91dc8fdebf663b

**Comment by doriawq** [comment]
https://gist.github.com/doriawq/7e1ff4087a3d7fac32822ed0f70c9eac

**Comment by 1043-nw** [comment]
https://gist.github.com/1043-nw/381651fda19af87fff5bb1c55bfade70

**Comment by zhangSen1987** [comment]
https://gist.github.com/zhangSen1987/99514d60262edb27e57c74b63134ca42

**Comment by Liujiale02** [comment]
https://gist.github.com/Liujiale02/905d0841cafa7c9714ce824da1133ca2

**Comment by HSChloe** [comment]
https://gist.github.com/HSChloe/ce3dbedd83945d5fd7d268073f21dae1

**Comment by tyler1zhang** [comment]
https://gist.github.com/tyler1zhang/254d9e20f6fa1ccdc715d91fbd302c34

**Comment by blackoutwhb** [comment]
https://gist.github.com/blackoutwhb/6901dd5821f044cdd29469b10a11807d

**Comment by Amy20191** [comment]
https://gist.github.com/Amy20191/2122e8c99d1a336c0a77a0d547bd24cf

**Comment by sujuxiaoren** [comment]
https://gist.github.com/sujuxiaoren/cd398a7e7e258e6f58886cd3559c2cbc

**Comment by muyuzhu** [comment]
https://github.com/neolee/wop-community/issues/202

**Comment by muyuzhu** [comment]
https://gist.github.com/muyuzhu/2616b6dfd673ca3aadd38eca1aa4338b

**Comment by neolee** [comment]
https://github.com/neolee/python-primes

**Comment by girlfriendandme** [comment]
https://gist.github.com/girlfriendandme/3a80bdad48bc8dd1c69d48dc41385774
