### ISSUE TITLE
在 Github 上 fork 的文件没有 issues 的选项

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#203]
使用的是mac系统。

我尝试fork了老师的文件，在我的账户下也显示了。但是发现没有issues这个选项。在Code后面直接就是Pull request.这个是什么原因呢？我尝试fork了其他账户下的文件，发现也是一样的没有显示issues. 

<img width="1233" alt="截屏2020-08-02 上午1 05 45" src="https://user-images.githubusercontent.com/55272650/89106541-51582680-d45d-11ea-8d08-dc1fe353c916.png">

**Comment by xuzhengfu** [comment]
看到 Pull requests 那一栏最右边的 Settings 了吗？

点击它。

然后在 Features 部分将 Issues 勾选即可。

**Comment by jomi0820** [comment]
> 看到 Pull requests 那一栏最右边的 Settings 了吗？
> 
> 点击它。
> 
> 然后在 Features 部分将 Issues 勾选即可。

Settings里没有Features的部分啊？

<img width="895" alt="截屏2020-08-04 上午3 10 57" src="https://user-images.githubusercontent.com/55272650/89218283-599c9700-d600-11ea-86bf-bdf5d5d8f298.png">

**Comment by xuzhengfu** [comment]
emmmm……  向下滚动页面试试？

另，在 issue 底部直接回复即可，不必引用他人的回复 —— 这样更为清晰。

**Comment by jomi0820** [comment]
额......有滚动，真的有找没找到。这个问题意义好像不大，我关闭了以后自己再搜一搜吧

**Comment by xuzhengfu** [comment]
<img width="1401" alt="Screen Shot 2020-08-04 at 17 49 19" src="https://user-images.githubusercontent.com/39576401/89280299-03206e80-d67b-11ea-901d-4003c10360a9.png">
