### ISSUE TITLE
VS Code 报错

### ISSUE THREAD

**Issue by hqq922** [neolee/wop-community#205]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/67837404/89122042-b14edb80-d4f6-11ea-9940-6600d1ef32ee.png">
vscode中代码如下：
<img width="675" alt="image" src="https://user-images.githubusercontent.com/67837404/89122069-fecb4880-d4f6-11ea-904d-c8b157b9e230.png">
<img width="838" alt="image" src="https://user-images.githubusercontent.com/67837404/89122075-0985dd80-d4f7-11ea-9acf-cfd8ce3dd4dd.png">

**Comment by neolee** [comment]
看上去是代码里有不合法的字符（比如全角空格或者标点），看截图不太好确定，你可以：1. 检查下 `class HelloBot...` 中 `class` 后面的空格是不是中文全角空格；2. 把你的这个文件直接作为附件发到下面。

**Comment by hqq922** [comment]
gist:366604abeda77116f0a8bdf60c2dbb12

**Comment by xuzhengfu** [comment]
https://gist.github.com/hqq922/366604abeda77116f0a8bdf60c2dbb12

还得猜……

**Comment by hqq922** [comment]
额，传不来附件哒，拖过来说格式不对

**Comment by Xuzhengfu** [comment]
我也看不出来咋回事……

**Comment by Xuzhengfu** [comment]
Bot 类的 run 方法的最后一句，少了一个括号……

**Comment by neolee** [comment]
第 22 行：`self._say(self._think(self.a)` 最后缺一个反括号 `)`。
