### ISSUE TITLE
什么时候可以用多个 if 或者 elif

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#208]
1. 下面代码里同时出现了多个if, 什么时候可以用多个if，又什么时候用elif?
2. 最后一行return True，是隶属于上面 for...in循环？还是类似于else语句？亦或是独立出来的？

```
def is_prime(n):
  
    if n < 2:
        return False
    
    if n in (2, 3):
        return True

    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            return False
   
    return True
```

**Comment by neolee** [comment]
1. `elif ...` 的意思是 `else if ...`，所以，如果条件判断是递进式的，一般都应该使用 `if ... elif ...` 这样的——上面的代码之所以没用到这个，是因为前面的 `if` 如果成立直接就 `return` 了，所以无所谓了，上面的写法更加简单清晰。

2. 从缩进看显然最后一个 `return True` 是独立的，意思是“如果最后那个 for 循环玩成了都没有触发 `return False` 那句的话就 `return True` 吧”，最后那段写成下面这样也可以，但上面的写法更简洁：

```python
for i in range(2, int(sqrt(n)) + 1):
    if n % i == 0:
        return False
else:   
    return True
```

p.s. 我看你问的好几个问题都似乎有个倾向，就是试图从代码中找出一些普适规律，但要注意的是，对代码逻辑流程的理解是具体情况具体分析的，并没有一概而论的标准，要切实理解条件分支和循环结构之后根据具体代码去分析和理解，很多情况下多种写法都可以完成任务，只要其逻辑是对的就行。所以你要做的是：1. 理解示例代码的执行逻辑；2. 如果有“我换个写法行不行”的疑问，最好的办法是动手去试，如果可以，说明你的逻辑也对，如果不行，说明你的逻辑有问题。写程序并不是文字转写练习。

**Comment by Liujiale02** [comment]
收到
