### ISSUE TITLE
有关想法变成计算机语言的信心

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#209]
>所有的程序都只需要顺序，条件，循环就能解决。

当知道自己的程序一定能被这三种结构写出来，那么在写程序的时候，信心是很足的，**这就好比做数学难题知道它是有解的，虽然暂时自己求不出来。**

那是不是意味着，只要我有一个想法，就一定可以被写成程序。紧接着，就一定可以被写出来，只是时间问题。

任何程序（想法）都可以被三种基本结构解决，那限制计算机做事情的边界是啥？毕竟在边界内做事情，至少知道自己不是在造永动机，可以更勇往直前。

**Comment by neolee** [comment]
如果你的想法可以被用清晰的文字 step by step 的写出来，就肯定可以程序化——所以我一直建议你们写程序前先写下解决问题的 ste by step 的文字表述。

**Comment by gaoteng-pro** [comment]
明白些了
