### ISSUE TITLE
macOS 环境准备，brew doctor 报错问题

### ISSUE THREAD

**Issue by hendasheng** [neolee/wop-community#21]
<img width="719" alt="截屏2020-07-03 18 29 09" src="https://user-images.githubusercontent.com/20842136/86460506-17f7a280-bd5b-11ea-8bc1-15c5ccb23e31.png">

_前提：有一点点编程经验，brew 以前就安装过的。_

跟着 “macOS 下的编程环境准备” 步骤，前面都没问题，到 brew doctor 出现这样的报错。
大家又遇到过类似问题吗？请问如何解决？
感谢

**Comment by hendasheng** [comment]
`brew link gettext`
根据提示解决了第一个警告，后面两个还没有解决方案。

**Comment by hendasheng** [comment]
https://github.com/Homebrew/legacy-homebrew/issues/30180
在这里找到第二个警告的答案，现在还剩最后一个了。
<img width="727" alt="截屏2020-07-03 19 18 16" src="https://user-images.githubusercontent.com/20842136/86464370-f817ad00-bd61-11ea-8d6b-73f634c9c036.png">

**Comment by hendasheng** [comment]
执行 `brew cleanup` 解决了第三个问题。
但是又出现了新的问题。
<img width="698" alt="截屏2020-07-03 19 26 54" src="https://user-images.githubusercontent.com/20842136/86465059-6c068500-bd63-11ea-9b67-3b0f004935d7.png">

**Comment by neolee** [comment]
第一个 warning 是提示你有更新版本的 Command Line Tools，这个一般系统软件升级那里会提示你的，如果没有可以按照这里它提示的操作——其实也可以不理，99.9% 的情况下都是无所谓的。

第二个 warning 是说你的 /usr/local/include 下面有非 Homebrew 安装的头文件，可能你用别的方法安装过别的软件包，如果你不太清楚到底该如何处理，可以不理。

**Comment by hendasheng** [comment]
> 第一个 warning 是提示你有更新版本的 Command Line Tools，这个一般系统软件升级那里会提示你的，如果没有可以按照这里它提示的操作——其实也可以不理，99.9% 的情况下都是无所谓的。
> 
> 第二个 warning 是说你的 /usr/local/include 下面有非 Homebrew 安装的头文件，可能你用别的方法安装过别的软件包，如果你不太清楚到底该如何处理，可以不理。

非常感谢：）
