### ISSUE TITLE
关于模块问题

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#210]
![image](https://user-images.githubusercontent.com/49615335/89125178-1d3d3e00-d50f-11ea-90a5-71bb2fdbaa36.png)
ju具体什么情况就不清楚了

**Comment by neolee** [comment]
1. 你的这个 notebook 文件放在哪里？
2. 你的 `myutil.py` 文件放在那里？
3. `myutil.py` 文件是不是放在 notebook 文件所在目录下的 `assets` 子目录下？如果是，上面的操作才有意义。

如果对 module 的引入有疑问，除了仔细看教材的相关章节，重新仔细听一听我在直播第八讲开头对这个的解释吧。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/89126417-1535cc00-d518-11ea-8368-18cf693b0054.png)
我把这个文件保存C盘如上图，我的Notebook文件在D盘，然后我就把这个代码文件复制到D盘手动建立了个assets 子目录下，然后再来操作，还是上面那个错误

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/89126569-17e4f100-d519-11ea-9133-2743b2cb01e2.png)

**Comment by neolee** [comment]
所以你的 notebook 文件和 myutil.py 到底在哪里还是没说啊，你只说了 C 盘 D 盘，盘很大，下面有无数的目录，我怎么知道你放在哪里，以及是不是放对了呢？你上面的截图里的 `myutil.py` 显示已经删除，估计是被你搬到别的地方去了，到底哪里，我还是不知道……

另外建议你先看看支线课程第一讲，了解文件和目录的基本概念。

**Comment by WGL1** [comment]
没有删，刚刚被我改名了，
![image](https://user-images.githubusercontent.com/49615335/89127162-339ec600-d51e-11ea-88bc-22b9e397325c.png)这是C盘

**Comment by WGL1** [comment]
现在的操作是我把C盘这里的myutil.py文件复制到D盘nteract文件夹下，我自己建了个根目录assets下面

**Comment by neolee** [comment]
你的截图和你标记的箭头并不能说明你的文件具体在什么位置。

你打开系统的文件管理器，找到 D 盘，然后在 D 盘里找到你的 `myutil.py` 文件，选中它，然后在文件管理器的上面会有个类似下面这样的路径显示：

<img width="400" alt="Path" src="https://user-images.githubusercontent.com/24796/89127490-65b12780-d520-11ea-8155-7dc52b56eb60.png">

例如我的这个截图里，说明我的文件放在 `C:\Users\trust\Code\learn-python` 这个目录下。我需要你用这样的方式告诉我你的那个 notebook（后缀为 ipynb 的文件）和 `myutil.py` 文件分别在哪里。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/89127791-191b1b80-d523-11ea-9f7a-ad8644d7df56.png)

**Comment by neolee** [comment]
那么你的那个 notebook 文件在哪里呢（就是你下载后双击用 nteract 打开的那个作业本文件）？

**Comment by WGL1** [comment]
是说的这个吗？
![image](https://user-images.githubusercontent.com/49615335/89128071-9051af00-d525-11ea-97bc-bf271d66198b.png)

**Comment by neolee** [comment]
你这个是 nteract.exe 可执行文件，你打开的那个 xxx.ipynb 文件在哪里呀？从课程的作业页面下载的那个……

**Comment by WGL1** [comment]
在桌面的

**Comment by WGL1** [comment]
难道要和他们放在一起吗

**Comment by neolee** [comment]
上次上课我说过了，你有两个办法：

1. 把 `.ipynb` 文件和 `.py` 文件放在同一个目录下，那么不需要执行 `sys.path.append()` 就可以直接 `import`；

2. 两个文件不在一起，那么需要用 `sys.path.append()` 把 `.py` 文件所在的目录加到搜索路径中，加路径的时候可以用“绝对路径”也可以用“相对路径”——这俩概念支线课程第一讲里说了，我好早以前在你的某个问题里就让你去看过了。

假设你的 `.ipynb` 文件在桌面上（桌面其实对应的是 `C:\Users\86188\Desktop` 这个目录），

* 你在桌面创建了一个子目录叫 `assets` 然后把 `myutil.py` 放进去，那么你可以执行 `sys.path.append("./assets/")`，这就是”相对路径“的方法。
* 你的 `myutil.py` 在别的地方，比如 `D:\Program Files\nteract\assets` 下面，那么你可以执行 `sys.path.append("D:\Program Files\nteract\assets")`，这就是”绝对路径“的方法。

本质其实一样，都是让 Python 运行时能找到你的 `myutil.py` 文件。


> 难道要和他们放在一起吗

为啥要”难道“，这不是我课上说过的方法么……

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/89202629-d53d1a80-d5e5-11ea-9805-fce0775d94f4.png)
老师按你说的来，还是显示错误

**Comment by neolee** [comment]
假定你的 notebook 文件还在桌面没移动。

首先，把你的 `myutil.py` 放到桌面上，和你的 notebook 文件放一起，不需要执行 `sys.path.append`，这个一定不会有问题，你试了吗？

第二，在桌面建一个子目录 `assets`，把 `myutil.py` 放进去，然后执行 `sys.path.append('./assets/')`，这样也不会有问题，你试了吗？

最后，如果 `myutil.py` 文件在 `D:\Program Files\nteract\assets` 目录下，用 `sys.path.append("D:/Program Files/nteract/assets")` 也是可以的，但注意在 Windows 下加入目录的时候，目录里的 `\` 都要写成 `\\` 或者 `/`，否则会被看做转义符，就会出错。

p.s. 看你的截图，你的 notebook 文件并不在桌面目录（`C:\Users\86188\Desktop`），而是在 `C:\Users\86188\Desktop\作业\作业6` 这个目录下，那么上面描述的方法一和二也需要随之调整——你老是提供错误的信息给我，或者不理会我的一些问题，这个沟通效率很低啊！当然我猜你不是故意的，而是对目录的概念还是不太理解，这个就很麻烦了，建议你好好看第一讲支线课程，然后上网搜一些 Windows 下关于目录和文件的基础知识先补补课，否则很难继续。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/90331798-ffc9a300-dfe9-11ea-8d48-8f3a02544f28.png)
耽搁了hao'jiu好久，今天又来了，老师，现在错误是这样

**Comment by neolee** [comment]
这个错误提示不是很清晰吗？这是你的 myutil.py 里的程序没写对，`say_hi` 函数的参数名 name 应为 names。

提问之前先自己努力研究下错误信息。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/90357212-bf6b3300-e084-11ea-8b7a-ab8f8101a5bd.png)
![image](https://user-images.githubusercontent.com/49615335/90357214-c4c87d80-e084-11ea-8689-244d44146da0.png)
这个程序我复制了课本上的也一样，老师求助
