### ISSUE TITLE
类定义中的 self 问题

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#212]
使用mac 10.5
问题相关章节：第一部分第十一章 作业

我对这个章节中def下面对self.a='' 这个描述不能理解

我自己对理解，这个a应该对应对是answer，也就是用户输入对内容。
但是下面的_think(self, s): 的部分，有好像是s才是用户输入的内容。
比方说用户输入peter, 则计算机回答的是Hello Peter.

怎么看都跟a没有什么关系啊？

那为什么不应该是：
      def__init__S(self):
           self.q = ' '
           self.a = ' '

self.s = input()

我看不这个a定义的在这里的用途是什么？

-------------------------------------

import time

class Bot:

    wait = 1

    def __init__(self):
        self.q = ''
        self.a = ''

    def _think(self, s):
        return s

    def run(self):
        time.sleep(Bot.wait)
        print(self.q)
        self.a = input()
        time.sleep(Bot.wait)
        print(self._think(self.a))

class HelloBot(Bot):
    def __init__(self):
        self.q = "Hi, what is your name?"

    def _think(self, s):
        return f"Hello {s}"

**Comment by neolee** [comment]
先去 https://github.com/neolee/wop-community 学会如何贴代码，不然看看你自己贴的代码，是不是有点脑壳疼？

具体到问题本身，在 `run()` 方法中我们需要一个变量来放用户输入的内容，这个变量可以是一个仅在函数 `run()` 内有效的”局部变量（local var）“，也可以设计为一个在对象所有方法内可以共享的”对象属性（property）“，都是可以的。关于这两者的区别可以参考 #185 我最后的一个回复。

在最初的课上讲解时我用了后一种设计（作为对象属性 `self.a`），但完成整个系统搭建后那你会发现其实这个变量好像就在 `run()` 方法里用到，所以其实是可以改为局部变量的，在之后回顾时也说过这是我留下的一个伏笔，希望有同学发现并优化，在直播课第七讲的开头部分，你没有听到么？

p.s. 聊天机器人的一个优化版本： https://github.com/neolee/garfield
