### ISSUE TITLE
在 Visual Studio Code 中保存 .py 文件后在 python3 中无法运行

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#213]
使用mac 10.15

使用jupyter lab中完成第一阶段的大作业，运行正确。

拷贝到Visual Studio Code中，并保存为自己的名字“emilyhw.py”.

在terminal中以python3 emilyhw.py运行，系统提示：EmilydeMacBook:Code emily$ python3 emilyhw.py
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'emilyhw.py': [Errno 2] No such file or directory

以python3 hello.py运行，正确显示Hello World!
检查文件保存路径正确，为什么为显示no such file呢？

在Visual Studio Code中直接运行，显示以下内容：
<img width="984" alt="截屏2020-08-04 上午3 18 55" src="https://user-images.githubusercontent.com/55272650/89218875-5eae1600-d601-11ea-9f01-aaafaa92814e.png">

**Comment by neolee** [comment]
先去认真学习下支线课程第一讲，搞清楚”当前工作目录“的概念，自己检查当前工作目录下有哪些文件，有没有你要运行的那个 `emilyhw.py` 文件。

然后认真学习下支线课程关于 Visual Studio Code 那一章，了解如何在 VSCode 中运行和调试 Python 源程序。

p.s. 你的 Python 系统似乎不是按照课程指南安装的。
