### ISSUE TITLE
第九次作业 generator 下面的代码作业

### ISSUE THREAD

**Issue by zanglei-80** [neolee/wop-community#214]
为什么不可以把list（）换成print（）
![迭代器](https://user-images.githubusercontent.com/60951614/89264808-21c83a80-d666-11ea-8d07-d5dbe78aff00.PNG)

**Comment by neolee** [comment]
因为 `islice` 返回的是一个 *iterable object* 而不是列表，所以打印出来是一个 object 的标准描述；你用 `list(islice(...))` 可以把这个 *iterable object* 变成一个列表，打印出来才是列表的样子。
