### ISSUE TITLE
运行聊天程序无任何显示

### ISSUE THREAD

**Issue by LuoDaXiang** [neolee/wop-community#219]
课堂练习里的代码copy下来可以执行。
<img width="871" alt="截屏2020-08-06 上午7 24 02" src="https://user-images.githubusercontent.com/37765016/89473580-cf962f00-d7b5-11ea-8c59-9d614dd4cee7.png">

下面是我照抄的程序，反复对照，找不出原因，不能执行，没有提示。
<img width="951" alt="截屏2020-08-06 上午7 25 46" src="https://user-images.githubusercontent.com/37765016/89473668-0cfabc80-d7b6-11ea-9cc0-1355b14fed4d.png">
<img width="889" alt="截屏2020-08-06 上午7 26 06" src="https://user-images.githubusercontent.com/37765016/89473688-184de800-d7b6-11ea-8337-d8b1ac6e00f1.png">

**Comment by neolee** [comment]
把你的代码直接贴上来，我来试试。

**Comment by LuoDaXiang** [comment]
'''python
import time
import random

class Bot:
    
    wait = 1
    
    def __init__(self):
        self.q = ''
        self.a = ''
        
    def _think(self, s):
        return s
        
    def gogogo(self):
        time.sleep(Bot.wait)
        print(self.q)
        self.a = input()
        time.sleep(Bot.wait)
        print(self._think(self.a))


class HelloBot(Bot):

    def __init__(self):
        self.q = "Hi, what's your name?"
        
    def _think(self,s):
        return f"Hello {s}"


class GreetingBot(Bot):

    def __init__(self):
        self.q = "How are you today?"
        
    def _think(self,s):
        if 'good' in s.lower() or 'fine' in s.lower():
            return "I'm feeling good too."
        else:
            return "Sorry to hear that."


class FavoriteColorBot(Bot):

    def __init__(self):
        self.q = "What's your favorite color?"
        
    def _think(self,s):
        colors = ['rae','orange','yellow','green','blue','indigo','purple']
        return f"You like {s.lower()}? That's a beautiful color! My favorite color is {random.choice(colors)}."


class Elephant:
    
    def __init__(self,wait=1):
        Bot.wait = wait
        self.bots = []
        
    def add(self,bot):
        self.bots.append(bot)
        
    def _prompt(self,s):
        print(s)
        print()
    
    def gogogo(self):
        self._prompt("This is Elephant dialog system.Let's talk.")
        for bot in self.bots:
            bot.gogogo()


elephant = Elephant(1)
elephant.add(HelloBot())
elephant.add(GreetingBot())
elephant.add(FavoriteColorBot())
elephant.gogogo()
'''

**Comment by neolee** [comment]
贴代码的标签用错了，不是引号，是键盘左上角那个 backquote 字符。

然后我把你的代码拷贝保存到一个叫 `elephant.py` 的文件里，然后用 `python elephant.py` 运行，完全没有问题。

**Comment by tyler1zhang** [comment]
@LuoDaXiang 找到原因了么？
