### ISSUE TITLE
Scoop update

### ISSUE THREAD

**Issue by Denny-Huang** [neolee/wop-community#22]
蓝灯科学上网后Scoop安装成功，按时但是scoop
update不行，应该不是浏览器问题吧？
![企业微信截图_15937828888073](https://user-images.githubusercontent.com/58538336/86473825-34540900-bd74-11ea-8a24-ce917afa7b8c.png)

**Comment by Denny-Huang** [comment]
多打了“按时”两个字

**Comment by neolee** [comment]
Scoop 没装好，需要删了重装，点这个页面上方的 Wiki 链接，里面有。

**Comment by Denny-Huang** [comment]
好的谢谢！

**Comment by neolee** [comment]
补充一下：你用的代理服务，通常需要在命令行做一些配置才会生效，可以咨询下服务商。

**Comment by Denny-Huang** [comment]
好的，谢谢老师！昨晚安装git不成功，有个别文件invalid，换到今早卸载重装，发现能下载但不能加压，原来因为之前scoop有过不成功重装，7zip是failed，卸载重装，成功之后一步步来，终于配置好环境。虽然小成绩，但是很值得一提！这个过程对环境、管理包及层级、先后有了一些感性认识。还有个小问题我自己来解决吧，我都不知道怎么把administrator改为我的用户名，难道跟我的版本有关，正版家庭版。
相信这次真的能入门编程世界！感谢李骏老师！
![2323](https://user-images.githubusercontent.com/58538336/86500474-df3fe380-bdc3-11ea-944a-48c7f1f0fe67.png)

**Comment by neolee** [comment]
恭喜，gogogo！

用户名那个问题不大，只要不是中文用户名就行。

**Comment by Denny-Huang** [comment]
ok，gogogo!

**Comment by mixinboy** [comment]
> 恭喜，gogogo！
> 用户名那个问题不大，只要不是中文用户名就行。

中文用户名会怎么样？

**Comment by neolee** [comment]
@mixinboy 某些软件会出现兼容性问题，nodejs 和 VS Code 的某些插件都遇到过。

**Comment by Denny-Huang** [comment]
Done
