### ISSUE TITLE
运行周三课堂上讲的代码，报错

### ISSUE THREAD

**Issue by kekeyumuku** [neolee/wop-community#220]
代码如下：
```
from itertools import islice

class primes:
    def __init__(self, nlimit):
        self.nlimit = nlimit
        self.is_prime = [True] * nlimit
        self._sieve()
        self.next = 1

    def _sieve(self):
        self.is_prime[0] = False
        self.is_prime[1] = False
        for i in range(2, int(self.nlimit**0.5)+1):
            if self.is_prime[i]:
                for j in range(i*i, self.nlimit, i):
                    self.is_prime[j] = False
    
    def __next__(self):
        n = self.next + 1

        while True:
            if n > self.nlimit:
                raise StopIteration
            elif self.is_prime[n]:
                self.next = n
                return self.next
            else:
                n += 1


if __name__ == "__main__":

    print(list(primes(100)))

```

在命令行运行此文件，报错信息如下：
Traceback (most recent call last):
  File "primes1.py", line 32, in <module>
    print(list(primes(100)))
TypeError: 'primes' object is not iterable

**Comment by neolee** [comment]
我上课的时候说了，因为空间原因我没展示 `__iter__()` 这个八股方法，但你们还是要写的啊！

**Comment by kekeyumuku** [comment]
> 我上课的时候说了，因为空间原因我没展示 `__iter__()` 这个八股方法，但你们还是要写的啊！

哈哈，谢谢李骏老师，听课不够认真

**Comment by kekeyumuku** [comment]
加上`__iter__()`方法，之后的报错信息如下：
Traceback (most recent call last):
  File "primes1.py", line 36, in <module>
    print(list(primes(1000)))
  File "primes1.py", line 27, in __next__
    elif self.is_prime[n]:
IndexError: list index out of range

**Comment by neolee** [comment]
因为你抄写代码出错了呀，我已经把课上讲的几个实现都开源出来了，在这里：

https://github.com/neolee/python-primes

你可以对照里面的 mk2.py，练练眼力……（友情提示：出错信息是重要的线索）

**Comment by kekeyumuku** [comment]
我找到出错的地方了 
` if n > self.nlimit:`改成` if n >= self.nlimit:`就可以了。
但是我理解不了，从nlimit里面筛素数，为啥n=nlimit，就要raise StopIteration，为啥不是n > self.nlimit呢？这个边界值为啥这么严格

**Comment by neolee** [comment]
1. 列表的下标从 0 开始，一个包含 nlimit 个元素的列表，下标就是 0 ~ nlimit-1。

2. 一个下标是 0 ~ nlimit-1 的列表，你要去访问其下标为 nlimit 的元素？这就好比你去商店说要买一个人家没有的商品，店员说没有，你还反问“你们为啥这么严格啊”……

**Comment by kekeyumuku** [comment]
> 1. 列表的下标从 0 开始，一个包含 nlimit 个元素的列表，下标就是 0 ~ nlimit-1。
> 2. 一个下标是 0 ~ nlimit-1 的列表，你要去访问其下标为 nlimit 的元素？这就好比你去商店说要买一个人家没有的商品，店员说没有，你还反问“你们为啥这么严格啊”……

嘿嘿
