### ISSUE TITLE
dict 数据通过 list() 函数转换列表顺序问题 

### ISSUE THREAD

**Issue by lgqbee** [neolee/wop-community#221]
dict：后面我们会介绍的一种数据容器，里面每个元素都是一个 key-value 对，就是一个值（value）和它的名字（key），list() 会把其中所有的 keys 取出来组成一个列表，顺序是不可预期的（因为 dictionary 中的元素是没有顺序概念的）。
但实验如下语句时：
```
print(list({'a', 'e', 'i', 'o', 'u'}))
print(list({'a': 1, 'e': 2, 'i': 3, 'o': 4, 'u': 5}))
```
set那句经常变换，dict那句一直按顺序返回的原因：
![1](https://user-images.githubusercontent.com/57405578/89530466-1c631f80-d821-11ea-87b2-34a7e68636b2.png)

**Comment by neolee** [comment]
这说明在你这个程序里这个 dict 的元素顺序没有改变而已。
