### ISSUE TITLE
用 Python 做一个小工具

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/wop-community#222]
我有一个需求，在Mac平台实现在特定时间自动按下组合键 shift+command+2。请问李老师实现这个功能难吗？

**Comment by neolee** [comment]
具体一点呢，什么情况下自动按下？

用程序模拟按键不难，但要自动，这个就要看怎么个自动法了……

**Comment by Royhowtohack** [comment]
比如到了8点，自动按一次shift+command+2。以时间来触发。

**Comment by neolee** [comment]
这个不难，有很多解决方案。

比如：keyboard 这个包可以让你的 Python 程序模拟按键；schedule 这个包可以让你定时执行。

**Comment by Royhowtohack** [comment]
好的，多谢李老师，我试试。
