### ISSUE TITLE
关于 is_prime() 的写法

### ISSUE THREAD

**Issue by Yongheng2020** [neolee/wop-community#223]
```python

def is_prime(n):
    
    if n < 2:
        
        return False
    
    # 若n<2,返回False
    
    for i in range(2,int(sqrt(n))+1):
        
    # n>=2 时，做判断
        if n % i == 0:
            
            return False
        
    # 若n可以被其平方根以内的整数整除，那返回False
        
        else:
            
            return True 
        
    # 若n不可以被其平方根以内的整数整除，则返回True
老师，我知道我的这种写法不正确，正确的代码有两点我理解不了：
1、为什么要单独加上if n in （2，3）这句，感觉它包含在后面的循环语句中
2、最后的ruturn True,为什么不是放在循环语句内（表示：若有数能整除它，就返回False，没有，就返回True),而是放在了循环语句之外。（我测试了我写的这段代码，的确是不正确，是没想明白原因）

**Comment by neolee** [comment]
1. 那一句确实可以不加，我之所以写了，是因为这样思路比较清晰；

2. 因为返回 True 的逻辑是 n 要“被**所有**比自己平方根小的整数除都除不尽”，而不是“被**某个**整数除不尽”，体会下这两句话的区别，再对照代码看看，你的版本是不是相当于后一句话的逻辑？

**Comment by Yongheng2020** [comment]
老师，我想了半天还是没懂：
1、那 i 已经是在所有比N的平方根小的整数中的遍历了，也就是所有的比自己小的整数都试过一边，怎么能说是被某个整数除不尽呢？
2、我这样理解对不对：这个class其实是在用排除法确定是不是素数，首先排除了<2的，然后在>=2的数中，排除了合数，最后剩下的跳循环，返回了True,这样想貌似能通一些

**Comment by neolee** [comment]
1. 你的实现里，只要有一个 i 不能整除 n 就 `return True` 了，并没有确认“所有 i 都不能整除 n”，这个能理解么？

2. 我们不是在讨论 `is_prime()` 函数么？你说的 “class” 是指啥？

**Comment by Yongheng2020** [comment]
奥奥，对对，这样明白多了。class写错了，是这个函数
