### ISSUE TITLE
命令行输入Jupyter lab不能自动打开网址

### ISSUE THREAD

**Issue by HSChloe** [neolee/wop-community#224]
**Win10，之前在命令行输入Jupyter lab可以在360浏览器中打开，最近卸载了360及其浏览器，再在命令行输入Jupyter lab时，打开的是IE浏览器（我的默认浏览器是Microsoft Edge），但是页面是空白的**：
![image](https://user-images.githubusercontent.com/48611079/89704732-1daf5c00-d989-11ea-886b-5f69c50840c4.png)
**命令行显示如下**：
PS C:\Users\Chloe> Jupyter lab
[I 14:44:54.118 LabApp] JupyterLab extension loaded from c:\users\chloe\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 14:44:54.127 LabApp] JupyterLab application directory is c:\users\chloe\scoop\apps\python37\current\share\jupyter\lab
[I 14:44:54.681 LabApp] Serving notebooks from local directory: C:\Users\Chloe
[I 14:44:54.689 LabApp] The Jupyter Notebook is running at:
[I 14:44:54.689 LabApp] http://localhost:8888/?token=e7d80aac4fd6ed9cc9a3b3edba793837127c719041cb1541
[I 14:44:54.690 LabApp]  or http://127.0.0.1:8888/?token=e7d80aac4fd6ed9cc9a3b3edba793837127c719041cb1541
[I 14:44:54.690 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:44:54.961 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Chloe/AppData/Roaming/jupyter/runtime/nbserver-16508-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e7d80aac4fd6ed9cc9a3b3edba793837127c719041cb1541
     or http://127.0.0.1:8888/?token=e7d80aac4fd6ed9cc9a3b3edba793837127c719041cb1541                                                                         
  
**尝试过以下操作**：
1.    查找这个文件file:///C:/Users/Chloe/AppData/Roaming/jupyter/runtime/nbserver-16508-open.html ，发现Chloe下面没有AppData这个文件夹
2.    复制   http://localhost:8888/?token=e7d80aac4fd6ed9cc9a3b3edba793837127c719041cb1541到Microsoft Edge 可以正常打开Jupyter lab

**问题**：怎样才能在命令行输入Jupyter lab后可自动在指定浏览器中打开Jupyter lab？

**Comment by HSChloe** [comment]
**尝试操作补充：**
3.关闭所有浏览器， Ctrl+C，命令行重新输入Jupter lab，打开的仍然是IE浏览器，页面是空白

**Comment by neolee** [comment]
这个在指南里有说明。

1. Jupyter Lab 不支持 IE；
2. Jupyter Lab 会尝试打开系统缺省浏览器。

所以，你需要把系统缺省浏览器设为其他浏览器（具体方法请自行探索或者搜索）。

**Comment by HSChloe** [comment]
不好意思，我一直以为我的默认浏览器已经是Mircosoft Edge了......
现在可以了，谢谢老师。
