### ISSUE TITLE
关于列表切片元素是如何替换的问题

### ISSUE THREAD

**Issue by zanglei-80** [neolee/wop-community#226]
作业中nums[2:4] = [10, 11, 12, 13]是如何被分配到第三和第四里面的？是平均分配吗？如果用五个元素进行替换那怎么被分到原来两个元素的位置上？还有不是不会改变原来的列表吗？为什么再做下一步nums[2:4] = [2]是却是在新的列表里进行替换而不是在原来[0, 1, 2, 3, 4, 5, 6]中替换？如果是按新的列表那怎么nums[8] = 20 又会报错，被替换了以后明明已经有了八个元素了？

**Comment by neolee** [comment]
提问题要一个一个来，把每个问题分开表述清晰，很多问题自己就解决了。

* `nums[2:4]` 代表原列表中的第 3 和第 4 个元素，所以 `nums[2:4] = [10, 11, 12, 13]` 就代表用 `10, 11, 12, 13` 这四个元素替换掉原来的第 3 和第 4 个元素。所以这里没有什么“分配”的问题，就是拿掉原来的俩元素，在那个位置加上等号右边列表里的所有元素。

* 上课我明确说了，当切片放在赋值语句右边时就是改变列表内容的，这个行为和切片放在等号右边是不同的。

* 最后一个问题已经无法理解了，你自己想想在问的是什么……

**Comment by tyler1zhang** [comment]
@zanglei-80 问题最好一个个的来，而且配上相应的代码和出错信息。不然让我们去猜，很难帮到你。老师真耐心，你写的三行字，真的有点像猫玩过的毛线团，好乱啊。

**Comment by zanglei-80** [comment]
我又看了一遍回放，问题已经解决了。问的有点乱，抱歉
