### ISSUE TITLE
datetime locale 问题

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#227]
1.刚开始写这段代码报错：
```Python
print(t.strftime("%Y年%m月%d日 %H时%M分%S秒"))
```
![error3](https://user-images.githubusercontent.com/53089964/89733803-934f2100-da8a-11ea-9c86-e88ec2a60d83.PNG)

通过设置locale解决：
```Python
import locale

locale.setlocale(locale.LC_ALL, "chinese")

print(t.strftime("%Y年%m月%d日 %H时%M分%S秒"))
```
2.之后运行这段代码又报错：
```Python
s1 = "2020-08-09 Sun 20:44:36"
t1 = datetime.strptime(s1, "%Y-%m-%d %a %H:%M:%S")
print(type(t1), t1)
```
![error4](https://user-images.githubusercontent.com/53089964/89733875-0d7fa580-da8b-11ea-94e6-fdaab153376e.PNG)

通过设置locale解决：
```Python
import locale

locale.setlocale(locale.LC_ALL, "english")

s1 = "2020-08-09 Sun 20:44:36"
t1 = datetime.strptime(s1, "%Y-%m-%d %a %H:%M:%S")
print(type(t1), t1)
```

我的问题：老师，有没有什么设置或者指令可以实现不用来回切换locale?

**Comment by neolee** [comment]
第一个问题目前只有靠设置中文 locale 来解决，因为要保证 Python 环境和你的操作系统的语言设定一致。

第二个问题就另外一码事了，你应该先问自己，在中文环境下，为啥需要去识别 `Sun` 这样的星期表示？

**Comment by wangcong-creator** [comment]
老师，我明白你的意思了，作业里的练习导致的这种问题，正常情况下，一种语言环境下不会出现切换locale的问题。

中文环境下，处理这样的时间表示是合乎逻辑的：
```Python
s2 = "2020年08月09日 周日 20时44分36秒"
t2 = datetime.strptime(s2, "%Y年%m月%d日 %a %H时%M分%S秒")
print(type(t2), t2)
```
英文环境下，处理这样的时间表示是合乎逻辑的：
```Python
s1 = "2020-08-09 Sun 20:44:36"
t1 = datetime.strptime(s1, "%Y-%m-%d %a %H:%M:%S")
print(type(t1), t1)
```

我这么理解对吗？

**Comment by neolee** [comment]
是的！
