### ISSUE TITLE
第十讲 数据容器 作业中遇到的问题

### ISSUE THREAD

**Issue by Amanda-6789** [neolee/wop-community#228]
<img width="1119" alt="截屏2020-08-10 下午3 59 06" src="https://user-images.githubusercontent.com/53425091/89762279-b200f680-db22-11ea-8d57-3f819b16d1fb.png">

*增加、删除元素和其他列表操作*

完成该部分作业过程中，出现错误提示，不知道发生错误的原因，请问如何解决？

**Comment by xuzhengfu** [comment]
计算机说：`str` 对象没有 `pop` 属性

所以，`fruits.pop()` 这一句中的 `fruits` 基于种种操作已经不再是列表，而是一个字符串了……

**Comment by neolee** [comment]
一开始你的 `fruits` 应该是个列表，执行一次 `fruits = fruits.pop()` 之后 `fruits` 变成了 `fruits.pop()` 的返回值，也就是原先列表的最后一个元素的值（是个字符串）；如果你再次执行 `fruits = fruits.pop()` 的话，就会出现你截图里的错误，也就是上面同学说的，你的 `fruits` 这时候已经是个字符串了，而字符串没有 `pop()` 方法。

**Comment by Amanda-6789** [comment]
重新执行了命令行，返回 ：NameError: name 'fruit' is not defined

**Comment by Amanda-6789** [comment]
<img width="776" alt="截屏2020-08-11 上午9 22 06" src="https://user-images.githubusercontent.com/53425091/89846676-70209080-dbb4-11ea-8b9e-db57f2a37e23.png">

重新尝试，执行一次命令行，返回新的错误。
NameError: name 'fruit' is not defined

**Comment by xuzhengfu** [comment]
你是想要 `fruit = fruits.pop()` 而不是 `fruits = fruits.pop()` 吧？
