### ISSUE TITLE
关于筛子的问题

### ISSUE THREAD

**Issue by Yongheng2020** [neolee/wop-community#229]
```python
def _sieve(self):

        self.is_prime[0] = False
        self.is_prime[1] = False
        for i in range(2,int(self.nlimit**0.5) + 1):
            if self.is_prime[i]:
                for j in range(i*i, self.nlimit, i):
                    self.is_prime[j] =  False
```
老师，这个筛子我有个问题始终没想明白：

      初始化时，我们初始化了一个属性，名字叫做is_prime ，这个属性是一个长度为nlimit，所有元素都是True的列表。
而在上面这个我们称其为筛子的函数，if self.is_prime[i]这句我理解不了,
这句的意思是，“如果下标为 i 的元素对应的列表内是素数”或者说“如果下标为 i 的元素对应的列表内的值是True”。问题是，初始化的时候，所有元素都是True，而这句，在没有任何对于素数的判定函数的情况下，对于列表中每个元素True还是False是怎么判定的.

**Comment by neolee** [comment]
初始化时 `self.is_prime` 这个列表里全是 `True`，但是调用 `_sieve()` 函数之后，其中所有下标为合数的元素就变成了 False。

这样 `self.is_prime[i]` 就变成了 `i` 是不是素数的标志（`True` or `False`）。

**Comment by Yongheng2020** [comment]
这个_sieve()函数的实现，其中 if self.is_prime[i]: 这句可以解释为，如果这个元素是素数；我疑惑的是，这个元素是素数是怎么判断出来的？
比如，我在100以内做筛子，我们首先要在1—10范围内做判断，那我是通过哪个语句判断3，5，7这三个数是素数的

**Comment by neolee** [comment]
因为 `_sieve()` 方法实现了筛法的逻辑，把所有合数都打上 `False` 标志了啊。
