### ISSUE TITLE
安装 fastnumbers 模块后，在 jupyter lab 引用时报错

### ISSUE THREAD

**Issue by jomi0820** [neolee/wop-community#230]
使用mac 10.15
相关课程：一切都是字符串

在终端使用pip install安装fastnumbers模块，显示成功。

随后在jupyter lab中进行引用时，仍然提示No module named 'fastnumbers'
<img width="867" alt="截屏2020-08-10 下午7 17 04" src="https://user-images.githubusercontent.com/55272650/89777668-b1765900-db3e-11ea-9268-f60be334d2df.png">

**Comment by neolee** [comment]
这个问题的根源一般都是你的 Jupyter 用的 Python 环境和你命令行环境里缺省 Python 环境不一致。

**Comment by jomi0820** [comment]
老师，我检查了下：
1. 我的mac里的确是有python 和python3, 我是使用pip3 install安装的jupyterlab, 也是使用pip3 install安装的fastnumbers。
2.从jupyter lab截图可以看出fastnumber应该是装在python3.7这里的。我的理解应该是一样的呀？

应该怎么看命令行里缺省的环境，如何保持为一致呢？

**Comment by neolee** [comment]
尝试下面的诊断命令：

```shell
echo $PATH
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
which jupyter
```

**Comment by jomi0820** [comment]
输入后显示如下内容，没看出什么问题？
'''
emily@EmilydeMacBook ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
emily@EmilydeMacBook ~ % which python
/usr/bin/python
emily@EmilydeMacBook ~ % which python3
/usr/local/bin/python3
emily@EmilydeMacBook ~ % python -V
Python 2.7.16
emily@EmilydeMacBook ~ % python3 -V
Python 3.7.4
emily@EmilydeMacBook ~ % pip -V
zsh: command not found: pip
emily@EmilydeMacBook ~ % pip3 -V
pip 20.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
emily@EmilydeMacBook ~ % which jupyter
/usr/local/bin/jupyter
'''

**Comment by jomi0820** [comment]
‘’‘emily@EmilydeMacBook ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
emily@EmilydeMacBook ~ % which python
/usr/bin/python
emily@EmilydeMacBook ~ % which python3
/usr/local/bin/python3
emily@EmilydeMacBook ~ % python -V
Python 2.7.16
emily@EmilydeMacBook ~ % python3 -V
Python 3.7.4
emily@EmilydeMacBook ~ % pip -V
zsh: command not found: pip
emily@EmilydeMacBook ~ % pip3 -V
pip 20.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
emily@EmilydeMacBook ~ % which jupyter
/usr/local/bin/jupyter
emily@EmilydeMacBook ~ % ’‘’

**Comment by jomi0820** [comment]
诊断后显示如下：
```emily@EmilydeMacBook ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
emily@EmilydeMacBook ~ % which python
/usr/bin/python
emily@EmilydeMacBook ~ % which python3
/usr/local/bin/python3
emily@EmilydeMacBook ~ % python -V
Python 2.7.16
emily@EmilydeMacBook ~ % python3 -V
Python 3.7.4
emily@EmilydeMacBook ~ % pip -V
zsh: command not found: pip
emily@EmilydeMacBook ~ % pip3 -V
pip 20.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
emily@EmilydeMacBook ~ % which jupyter
/usr/local/bin/jupyter
emily@EmilydeMacBook ~ % ```


没有看出什么问题？

另外，我在下载文件检索时发现，下载的fastnumbers文件实际只有fastnumbers-3.0.0.dist-info一个文件夹，这个文件夹里面并没有任何py文件。我已经反复使用各种办法安装多次，结果都是这样的。
<img width="582" alt="截屏2020-08-10 下午11 56 01" src="https://user-images.githubusercontent.com/55272650/89803210-193f9a80-db65-11ea-9131-77c2abff03b3.png">

**Comment by jomi0820** [comment]
诊断后显示如下，没有发现什么问题？

```
emily@EmilydeMacBook ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
emily@EmilydeMacBook ~ % which python
/usr/bin/python
emily@EmilydeMacBook ~ % which python3
/usr/local/bin/python3
emily@EmilydeMacBook ~ % python -V
Python 2.7.16
emily@EmilydeMacBook ~ % python3 -V
Python 3.7.4
emily@EmilydeMacBook ~ % pip -V
zsh: command not found: pip
emily@EmilydeMacBook ~ % pip3 -V
pip 20.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
emily@EmilydeMacBook ~ % which jupyter
/usr/local/bin/jupyter
```


另外，我在下载文件检索时发现，下载的fastnumbers文件实际只有fastnumbers-3.0.0.dist-info一个文件夹，这个文件夹里面并没有任何py文件。我已经反复使用各种办法安装多次，结果都是这样的。
<img width="582" alt="截屏2020-08-10 下午11 56 01" src="https://user-images.githubusercontent.com/55272650/89803429-63c11700-db65-11ea-9ee9-7399e0adee91.png">

**Comment by neolee** [comment]
运行 `python3 -m pip -V` 呢？

**Comment by jomi0820** [comment]
显示为如下：
```
emily@EmilydeMacBook 3.7 % python3 -m pip -V
pip 19.0.3 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by neolee** [comment]
所以问题就出现了，根据诊断输出，你的 `pip3` 安装的包会放在 `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/` 下面，而你的 `python3` 环境使用的是 `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/` 下面的包——并且这俩都不是 Homebrew 安装和管理的。

我觉得你的系统里不知为啥安装了好几个 Python 环境，而且配置上有点乱。除了上述主要冲突以外， `/usr/local/bin/jupyter` 这个程序也不知道是属于哪个环境的。由于不知道你是怎么配置环境的，所以没法给出如何解决的建议。

你可以运行下面的命令，看看你目前在用的几个主要的程序都是来自哪里：

```shell
ls -l /usr/local/bin/pip* /usr/local/bin/python*
```

**Comment by jomi0820** [comment]
老师，经检查电脑中的确存在多个版本： python2, python3.7.3, python3.7.4, python3.8.5，而且安装的目录也很混乱。

1. 为什么会有这么多版本在不同目录下，我也搞不明白：因为这台电脑只有我用过，且我自己只安装过python3.7.4。 其他的是安装别的软件带的还是其他原因，暂时分辨不出来。

2.我尝试手动删除其他版本：如删除3.8.5，但是发现删除后还是在，尝试多次都是如此。

3. 我尝试在谷歌搜索了很久答案，没有找到可以解决的办法。现在网上发了问题，还没有人回复。

根据上述的情况，我感觉删除和更正为一致的比较困难。请问目前这个情况，是否有什么办法可以把之前这些混乱的东西全部删除，然后我再重新安装一遍呢？

**Comment by neolee** [comment]
如果你不知道它们在哪里那就很难清理。

我上面不是让你运行一个命令看看你现在启用的几个程序来自哪里吗？

```shell
ls -l /usr/local/bin/pip* /usr/local/bin/python*
```
