### ISSUE TITLE
两个 is_prime 方法为什么一个使用 while True 另一个却不用

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#232]
![WechatIMG11](https://user-images.githubusercontent.com/52586220/89791166-7d5a6280-db55-11ea-8d0d-d95680b9832b.jpeg)

有一个问题不好懂：
**为什么下面的方法中会使用到无限循环`while True`，而上面的方法却又不需要？**   这种差别不太好懂。

>上面两个next()方法都是为了实现寻找下一个素数并保存到`self.next`--每次给一个参数n，在`is_prime`中判断是否素数，是素数的话就保存并执行`return `结束当前循环，应该是一次就执行一个参数，实在想不通下面方法为什么会用`while True`？

**Comment by neolee** [comment]
继续仔细看，努力理解注释和代码结构。

**Comment by Liujiale02** [comment]
哦我明白了，在大脑中试运行多遍自然理解了，其实我自己的问题描述都有一部分是答案，谢谢老师指点
