### ISSUE TITLE
打印了两次列表，为什么第二次打印出来的为空列表？

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#233]
```
from itertools import islice

def fib():
    prev, curr = 0, 1
    while True:
        yield curr
        prev, curr = curr, prev + curr
        
f = fib()
obj = islice(f, 10)
print(list(obj))
print(list(obj))
```
执行的结果是下面的两行，为什么第二次打印出来的列表为空？
```
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[]
```

**Comment by xuzhengfu** [comment]
您对迭代器的理解还有一些欠缺，建议抽时间重新阅读一下教材：[Iterable 与 Iterator](https://nbviewer.jupyter.org/url/beidou-public.oss-cn-zhangjiakou.aliyuncs.com/qustions/2020/4/1589882621493.ipynb/%3Fsecurity-token%3DCAIS7AF1q6Ft5B2yfSjIr5b7f%252B3HrosT0bWEMWP5oXBjNNppuP39hzz2IHlEdHJgCekatvgymWpQ5%252Fcalrh%252BW4NIX0rNaY5t9ZlN9wqkbtISYFQHOPpW5qe%252BEE2%252FVjTZvqaLEcibIfrZfvCyESOm8gZ43br9cxi7QlWhKufnoJV7b9MRLGLaBHg8c7UwHAZ5r9IAPnb8LOukNgWQ4lDdF011oAFx%252BwgdgOadopbBtUqO1QSn8IJP%252BdSteKrDRtJ3IZJyX%252B2y2OFLbafb2EZSkUMTpPct3PwdpW%252Bb44zHWwgAuw%252FmKe3Q%252F5h0MBRp3WraYhqAAbMrO90G%252BrnC272Nohy8dbFaOg66eTOSs41FxANe1%252FHURHrgNu7OgTqOtBGeJT%252Fldk06tn0oSgfW1BMQ13V3YMzKNDiuMEXiYPN9rERr6A6kOGg0IKsVRBDbLOH5VHiTjvNRw0zxfi9PSowj47yFD41lXx4X9Ps1tJ6HVIku4BfT%26OSSAccessKeyId%3DSTS.NUN4WsCT2fwo3EHEp68UEW8Ve%26Expires%3D1597113113%26Signature%3DEUMrqlUbY5kaY6%252BC70L8moXy5WU%253D)。

**Comment by neolee** [comment]
因为第一次打印已经把迭代器里的数取完了，第二次打印自然取不出数了。
