### ISSUE TITLE
用函数写出筛子的算法，关于下标的问题

### ISSUE THREAD

**Issue by girlfriendandme** [neolee/wop-community#236]
![image](https://user-images.githubusercontent.com/48598963/89907818-b959fa00-dc1f-11ea-8ba9-51a602a8c88b.png)

这里我很想让他的输出结果是[2, 3, 5, 7]，结果他给我整了四个2.

我想不明白啊，你看这段代码：
![image](https://user-images.githubusercontent.com/48598963/89907930-d989b900-dc1f-11ea-96c7-4353bfcf46dc.png)
他就输出了相对应的下标。

为什么给我整四个2呢？

**Comment by neolee** [comment]
我觉得你可能没搞清楚 `index()` 这个方法是干嘛的吧。

`is_prime` 里面都是 `True` 或者 `False`，然后你的那个 `if a:` 在且仅在 `a = True` 的时候成立，然后 `is_prime.index(a)` 就是在 `is_prime` 里寻找第一个值为 `True` 的元素，返回其下标——这个下标必然是 2。

**Comment by girlfriendandme** [comment]
哎呀我勒个去，哈哈哈，老师还真是这样。

也就是说，对index()的理解应该是：
传给他一个列表元素，然后从列表的第一位开始找，永远只返回第一个相匹配的索引值。

**Comment by girlfriendandme** [comment]
用函数实现了筛子算法，能够输出nlimit范围内的素数

```python

def primes(nlimit):
    
    is_prime = [True] * nlimit
    
    is_prime[0] = False
    is_prime[1] = False
    for i in range(2, int(nlimit**0.5)+1):
        if is_prime[i]:
            for j in range(i*i, nlimit, i):
                is_prime[j] = False
             
    n = 0    
    lst = is_prime
    
    for a in lst:
        
        if a:
            lst[n] = n
            n += 1
        else:
            lst[n] = 0
            n += 1
            
    while 0 in lst:
        lst.remove(0)
    
    print(lst)
            
```

**Comment by girlfriendandme** [comment]
放这搁着了
