### ISSUE TITLE
课程大练习三 - 集中区

### ISSUE THREAD

**Issue by neolee** [neolee/wop-community#238]
* 初始源代码 - https://gist.github.com/neolee/a03b900853aadf3d95a3a7f25f4aa269

**Comment by xuzhengfu** [comment]
https://gist.github.com/Xuzhengfu/490dae340e6fddfa67b144f62390cb39

**Comment by muyuzhu** [comment]
https://gist.github.com/muyuzhu/97aa53e4925feb6c5377447ffeaf35eb

**Comment by yyd841122** [comment]
https://gist.github.com/yyd841122/44dfdc08a6d12df145a08a870bdca176

**Comment by jiaobufan** [comment]
https://gist.github.com/jiaobufan/2e84c8dcfbd8b77223be6a088a70024c

**Comment by shuimu0579** [comment]
https://gist.github.com/shuimu0579/a6b01d4105a22da62974ffb2f475a1ea

**Comment by zhangSen1987** [comment]
https://gist.github.com/zhangSen1987/36b8ba59937893f6f37fa2d17484c40c

**Comment by tyler1zhang** [comment]
https://gist.github.com/tyler1zhang/9dbccc971126d62a83334f10fdad522d

**Comment by Amy20191** [comment]
https://gist.github.com/Amy20191/b81a1f2c52d3964bb25c6dab7f84a7e4

**Comment by blackoutwhb** [comment]
https://gist.github.com/blackoutwhb/d0abdc7f14ed915bbbfe19afa494e1ad

**Comment by gaoteng-pro** [comment]
https://gist.github.com/gaoteng-pro/efe2264fec633254234aa881581835c1

**Comment by hendasheng** [comment]
https://gist.github.com/N1U/bfdd115c5679f6be8c803982a5e81917

**Comment by wangcong-creator** [comment]
https://gist.github.com/Wangbicong/70b11cc30916d66f09219cb8812832b0
