### ISSUE TITLE
如何才能创造一个列表的副本

### ISSUE THREAD

**Issue by girlfriendandme** [neolee/wop-community#239]
在操作列表的时候，发现不是创造一个列表的副本。

我运行如下代码：

![image](https://user-images.githubusercontent.com/48598963/89990378-dee51300-dcb4-11ea-9c95-34b90c3b082d.png)

然后我发现，当调用第一个函数的时候，原列表lst也被更改了。

其实有点搞蒙了。
a = lst
这个语句指的是什么意思呢？
他们应该都是指向[0, 1, 2, 3]这个对象的名字才对。
所以更改a的列表，应该是不会影响lst的。

难不成a = lst，是创造lst的别名吗？
所以可以理解成，内存中指向[0, 1, 2, 3]这个对象的，还是只有lst这个名字

那我如何才能创造一个列表的副本呢？老师！！

**Comment by neolee** [comment]
list 类型有个 `copy()` 方法，可用于创建副本。
