### ISSUE TITLE
nteract 安装和设置上遇到一些问题

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#24]
1、在配置 nteract 的 Python 环境时，在终端输入python -m ipykernel install，显示下图，不知道怎么回事？
<img width="471" alt="WeChat33a2ffc9879898483e5e6c09345f650b" src="https://user-images.githubusercontent.com/52586220/86503527-96972300-bde1-11ea-8b82-4585f6b35ff3.png">

2、我安装的nteract好像找不到runtime
<img width="800" alt="image" src="https://user-images.githubusercontent.com/52586220/86503571-073e3f80-bde2-11ea-8209-5dc258b4b6a5.png">

**Comment by neolee** [comment]
这个错说明没装好 ipykernel，你安装了么？当时有什么返回信息？

**Comment by Liujiale02** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/52586220/86506326-07016c80-be01-11ea-8cfa-ac9eb64f372b.png">
整个设置过程就这样，好像没什么问题。就是放第二个指令就不行了

**Comment by Liujiale02** [comment]
老师，其实我能用jupyter lab能打开作业文件,像下图那样。

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/52586220/86506389-9149d080-be01-11ea-9445-9a0a4da6c2e0.png">

用Jupiter lab写好作业后保存，也可以上传的吧

**Comment by neolee** [comment]
1. 用 Jupyter Lab 也没问题。

2. 我怀疑你的 python 和 pip 两个命令分别指向两个不一样的 Python 环境，这个问题还是要解决的。试试执行下面的诊断命令：

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by Liujiale02** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/52586220/86506515-7d529e80-be02-11ea-96e0-89f59dedce78.png">

结果如图。

我想起来一件事，最初的时候好像系统已经有python3.7.7版本，但是我看了教程视频，然后再重新下载一个3.7.4版本，不知道有没有影响？

**Comment by neolee** [comment]
除了 pip3 以外，都是指向你用 Homebrew 安装的 Python 3.7.4，而pip3 一般也不会用，没啥问题。

所以这很不科学啊，你再试试 `python -m ipykernel install`。

**Comment by Liujiale02** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/52586220/86506858-fb647480-be05-11ea-8769-4d8ce4ef25b6.png">

还是一样，费解

**Comment by neolee** [comment]
那你 `python -m pip install ipykernel` 呢？

**Comment by Liujiale02** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/52586220/86507574-e1c62b80-be0b-11ea-8267-e153f294f06a.png">

**好像成功了。**

打开nteract后，左下角显示idle。

<img width="785" alt="image" src="https://user-images.githubusercontent.com/52586220/86507611-2f429880-be0c-11ea-9905-8e17df1448f0.png">

**多谢老师耐心的指导！！**

**Comment by neolee** [comment]
我知道了，你的 `/usr/local/bin` 下面的 `python` 和 `python3` 都不太对，你执行下面的这个命令：

```shell
ls -l /usr/local/bin/python*
```

**Comment by Liujiale02** [comment]
不好意思，刚才有急事走开了。

我运行了一下指令了，如下图

>`Last login: Sat Jul  4 15:31:19 on ttys000
liujiale@LiujialedeMBP ~ % ls -l /usr/local/bin/python*
lrwxr-xr-x  1 liujiale  admin  22  6 27 21:27 /usr/local/bin/python -> /usr/local/bin/python3
lrwxr-xr-x  1 root      wheel  69  6 28 19:13 /usr/local/bin/python3 -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3
lrwxr-xr-x  1 root      wheel  76  6 28 19:13 /usr/local/bin/python3-config -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config
lrwxr-xr-x  1 root      wheel  71  6 28 19:13 /usr/local/bin/python3.7 -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
lrwxr-xr-x  1 root      wheel  78  6 28 19:13 /usr/local/bin/python3.7-config -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
lrwxr-xr-x  1 root      wheel  72  6 28 19:13 /usr/local/bin/python3.7m -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m
lrwxr-xr-x  1 root      wheel  79  6 28 19:13 /usr/local/bin/python3.7m-config -> ../../../Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
liujiale@LiujialedeMBP ~ % 
`

**Comment by neolee** [comment]
果然啊，你 `/usr/local/bin` 下面 `python` 和 `python3` 都指向另外一个 Python 而不是你用 Homebrew 安装的。

所以你现在 python 和 python3 指向一个 Python 环境，而 pip 指向的是另一个，这很容易把自己玩死。

最好用 Homebrew 覆盖一下： `brew link --force python`。

**Comment by Liujiale02** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/52586220/86512123-d4bc3300-be31-11ea-8173-bac10641d622.png">

试了两遍，得出这个结果。

**Comment by neolee** [comment]
不知道你是怎么装出这么一个奇葩的状态的。

试试这个： `brew unlink python && brew link --force python`

**Comment by Liujiale02** [comment]
`liujiale@LiujialedeMacBook-Pro ~ % brew unlink python && brew link --force python
Unlinking /usr/local/Cellar/python/3.7.7... 11 symlinks removed
Linking /usr/local/Cellar/python/3.7.7... 
**Error:** Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python
liujiale@LiujialedeMacBook-Pro ~ % 

`
这是运行的结果，好像要删除某些东西。

我也是很费解，配置环境这里水很深。我加问一句，macbook支持笔记本迁移的吗？假如我要更新笔记本，我还想把原笔记本的内容完全地照搬过去就好了。

**Comment by neolee** [comment]
那就试试 `brew link --overwrite python`

**Comment by Liujiale02** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/52586220/86514553-a0527200-be45-11ea-8c4c-58afda43b4c2.png">

我顺着上一条的提示，输入了`brew link --overwrite python`和`brew link --overwrite --dry-run python`

**Comment by neolee** [comment]
你执行 `brew link --overwrite python` 就可以了，后面那句不需要。

现在再来诊断套餐看看：

```shell
which python
which python3
python -V
python3 -V
python -m pip -V
pip -V
```

**Comment by Liujiale02** [comment]
```
liujiale@LiujialedeMBP ~ % which python
/usr/local/bin/python
liujiale@LiujialedeMBP ~ % which python3
/usr/local/bin/python3
liujiale@LiujialedeMBP ~ % python -V
Python 3.7.7
liujiale@LiujialedeMBP ~ % python3 -V
Python 3.7.7
liujiale@LiujialedeMBP ~ % python -m pip -V
pip 20.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
liujiale@LiujialedeMBP ~ % pip -V
pip 20.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
liujiale@LiujialedeMBP ~ % 
```

现在变成3.7.7了，

**Comment by neolee** [comment]
这就对啦，你用 Homebrew 装的就是 3.7.7，就这样吧，现在至少整套命令是一致的……

然后，你还要执行一遍：

```shell
pip install ipykernel
python -m ipykernel install
```

**Comment by Liujiale02** [comment]
```
liujiale@LiujialedeMBP ~ % pip install ipykernel
Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/site-packages (5.3.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/site-packages (from ipykernel) (6.1.3)
Requirement already satisfied: appnope; platform_system == "Darwin" in /usr/local/lib/python3.7/site-packages (from ipykernel) (0.1.0)
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.7/site-packages (from ipykernel) (7.16.1)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.7/site-packages (from ipykernel) (6.0.4)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.7/site-packages (from ipykernel) (4.3.3)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/site-packages (from jupyter-client->ipykernel) (19.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client->ipykernel) (2.8.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/site-packages (from jupyter-client->ipykernel) (4.6.3)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (0.7.5)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (4.8.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (2.6.1)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (0.17.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (46.0.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (3.0.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel) (0.2.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/site-packages (from traitlets>=4.1.0->ipykernel) (0.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from traitlets>=4.1.0->ipykernel) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.0.0->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /usr/local/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel) (0.2.5)
liujiale@LiujialedeMBP ~ % python -m ipykernel install
Installed kernelspec python3 in /usr/local/share/jupyter/kernels/python3
liujiale@LiujialedeMBP ~ % 
```

应该是成功了吗？

**Comment by neolee** [comment]
嗯，顺利成功，打开你的 nteract 试试吧。

**Comment by Liujiale02** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/52586220/86515278-53bd6580-be4a-11ea-8161-2108f01e35ef.png">


左下角显示not connected,也没找到哪里可以手动设置

**Comment by neolee** [comment]
菜单，Runtime 下面选一个。

**Comment by Liujiale02** [comment]
哦我看到了，在最顶那一栏，顺便搞懂了macbook的操作方式。

谢谢老师的指导，辛苦你了。太感谢
