### ISSUE TITLE
关于树定义

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#240]
```python
def add_child(self, node):
        assert isinstance(node, TreeNode)
        node.parent = self
        self.children.append(node)
```
类定义中，我们经常用`self.xx = `这种写法来对`self.xx`赋值，怎么`self`还可以放在等号右边（`node.parent = self`），这是什么操作？

**Comment by neolee** [comment]
`self` 是一个对象，就是类实例化出来的那个对象，我们写类定义的时候这个对象还没创建，所以用 `self` 这个特殊名字来提前引用，名字是特殊的，但本质上还是个对象，没啥特别。
