### ISSUE TITLE
时间数据格式不匹配

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#241]
![081301](https://user-images.githubusercontent.com/58320967/90099534-49f22080-dd6d-11ea-9d8d-37234abe66c9.PNG)
请问这是怎么回事？

**Comment by neolee** [comment]
参考 #227

**Comment by yuexiangming** [comment]
老师，我还是没弄明白。是因为我的系统和 Python 环境都是中文的，所以不能识别 “Wed” 这种英文表达吗？我把星期用中文表示，然后运行代码，怎么又不显示星期了呢？中文也不能识别了吗?
![081501](https://user-images.githubusercontent.com/58320967/90310115-10faad00-df21-11ea-99e1-8759b4b4b3b2.PNG)

**Comment by neolee** [comment]
> 是因为我的系统和 Python 环境都是中文的，所以不能识别 “Wed” 这种英文表达吗？

当然是啊。

> 我把星期用中文表示，然后运行代码，怎么又不显示星期了呢？

你 `print(t2)` 这个本来就不会显示星期啊，要显示星期你要用 `strftime` 啊。好好回去复习一遍吧。

**Comment by yuexiangming** [comment]
好的，老师。我时间投入确实不够。
