### ISSUE TITLE
mark 5 版本中的 if self.children: 判断是否可以去掉？

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#242]
```
def __str__(self):
        xs = [self.name]
        if self.children:
            for node in self.children[:-1]:
                node._to_strings(xs, _last=False)
            self.children[-1]._to_strings(xs, _last=True)
        return '\n'.join(xs)
```
mark 5 版本中的 str 方法，去掉 `if self.children:` 的判断，如果只有根节点的话，那么  `self.children:` 是空的，`for node in self.children[:-1]:` 就执行不下去了，所以直接执行 `return '\n'.join(xs)` 。是不是这样也可以？

```
def print_tree(root):
    print(root.name)
    for node in root.children[:-1]:
        _print_tree(node, _last=False)
    _print_tree(root.children[-1], _last=True)
```
mark 4 版本中是没有这个判断的。

**Comment by neolee** [comment]
因为我们在 `TreeNode` 的 `__init__()` 方法中写了 `self.children = []`，所以一般情况下 `self.children` 不会是 None；而如果 `self.children` 是空列表，`self.children[:-1]` 也会是空列表。

综上 `if self.children:` 这个判断去掉也没什么大问题，写着它也行——至少可以省下做一次切片的工作。

**Comment by Amy20191** [comment]
明白了
