### ISSUE TITLE
课程大练习三中 find(self, name) 函数的问题

### ISSUE THREAD

**Issue by muyuzhu** [neolee/wop-community#243]
最初写的函数是
```python
    def find(self, name):
        if self.name == name:
            print(self)
            return self
        if self.children and len(self.children):
            for node in self.children:
                node.find(name)
```
在老师给出的程序及测试代码的基础上，添加测试代码：
```python
root.find('A2')
```
执行程序，可以打印出A2，但是返回值打印结果却是 None

单步调试，看不懂
![微信图片_20200815115027](https://user-images.githubusercontent.com/57130025/90305082-3a034980-def1-11ea-8902-9730e06dfea6.png)
为什么执行到for循环 会返回None

![微信图片_20200815122045](https://user-images.githubusercontent.com/57130025/90305132-c9a8f800-def1-11ea-8ec4-f80d3085628b.png)
继续执行，到return语句 的返回值，为A2的结构

![微信图片_20200815123522](https://user-images.githubusercontent.com/57130025/90305318-d9c1d700-def3-11ea-8503-978616b40537.png)
继续执行，跳过了if 语句，到了for循环语句，返回值变为了A2

既然有返回值，为什么不跳出函数

不知道问题出在哪，找不到自己的盲点

**Comment by neolee** [comment]
你的第二个 `if` 语句下面就没有 `return` 了，所以只要进入到这个分支，你的 `find()` 函数就没有显式的返回值，那自然是返回 `None` 了。

在 `find()` 方法里使用递归调用是有点点 tricky 的，因为你不确定在递归到那一层能找到目标节点，找到了自然会返回这个节点，但上一层递归调用如果不写返回语句，那最后返回的还是个 `None`。

解决这个问题需要一些巧妙的逻辑设计，你先自己思考一下吧。

**Comment by muyuzhu** [comment]
第二个if，借一个变量return一下就行了，不知道这是不是老师说的巧妙的逻辑设计，等老师课上讲吧
