### ISSUE TITLE
符号

### ISSUE THREAD

**Issue by muse1171** [neolee/wop-community#244]
'└── ' 
'├── ',
     '│   ' 
这些符号是怎么打出来的？

**Comment by neolee** [comment]
这是 Unicode 字符里的一个分区，可以看这里：

https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by muse1171** [comment]
```python
输入  u'\u251C\u2500\u2500'

输出'├──'
```
是这样么？但是为什么老师的教材直接显示出此'├──'，如果直接显示？

**Comment by neolee** [comment]
直接 copy and paste 啊……
