### ISSUE TITLE
命令行界面安装 pip install pandas 不成功

### ISSUE THREAD

**Issue by brarcher214** [neolee/wop-community#245]
在命令行节目安装 pip install pandas 尝试多次（包括cmd）不成功，不知该如何安装pandas？求教
![Snipaste_2020-08-16_15-27-33](https://user-images.githubusercontent.com/24749111/90329236-61cbdd80-dfd5-11ea-8f1f-e0518d7f5ddd.png)

**Comment by neolee** [comment]
网络问题，考虑用清华的镜像站吧。

**Comment by Reecezhang** [comment]
老师，我的安装提示如下，要重新输入什么命令？
![截屏2020-08-16 17 13 48](https://user-images.githubusercontent.com/48814520/90330990-db6ac800-dfe3-11ea-8676-7cc541d04fb0.png)

**Comment by brarcher214** [comment]
多谢，已解决
