### ISSUE TITLE
关于树结构大作业

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#247]
1. 在`TreeNode`的外部写了一个函数，用于返回节点的**所有后代**，结果正确。代码如下：

```python
lst = []
def f(root):
    
    if root.children and len(root.children):
        lst.append(root.children)
        if root.children and len(root.children):
             for node in root.children:
                f(node)
    return lst
```

2. 我在`TreeNode`类里写`get_descendants`方法的时候，引用了这个返回节点后代的`f`函数。代码如下：
```python
def get_descendants(self, node):
        assert isinstance(node,TreeNode)
        assert self.node_in_tree(node)
        return f(node)
```

3. 树形图
>```python
>root
>├── A
>│   ├── A1
>│   └── A2
>│       ├── A21
>│       └── A22
>├── B
>└── C
>    ├── C1
>    └── C2
>        ├── C21
>        └── C22
>```

4. 调用`get_descendants`方法，代码如下：
```python
print(a.get_descendants(a1))
print(a.get_descendants(a2))
```
返回结果：
```python
[A, A1, A2, A21, A22]
[A, A1, A2, A21, A22, [A21, A22]]
```
---
5. `f`函数返回了所有的后代节点没问题；
`get_descendants`方法返回的是`f`函数的调用；
为什么上面`4`中的结果却不是返回`a1`或`a2`的所有后代？

**Comment by tyler1zhang** [comment]
猜测你之前尝试运行了 `f(a)` ， 所以 `lst` 已经被赋值为 `[A, A1, A2, A21, A22]` 。 所以当你运行 `4` 中的程序，第一行没有改变 `lst` ， 第二行加入了`[A21, A22]` 。 
如果以上猜测正确，给你如下建议：
1. 在 `f(root)` 初始化 `lst`
2. `lst.append(root.children)` 改为 `lst.extend(root.children)`

**Comment by neolee** [comment]
你这个实现用了外部函数，外部函数又使用了全局变量，每次调用 f 这个全局变量（`lst`）都带着前一次运行之后的内容，这个肯定是个严重的问题……

**Comment by gaoteng-pro** [comment]
昨天晚上，终于把树结构的递归作业做完，讲一下自己的体会。

当初我问本issue中问题的时候，其实是我自己对递归有一些认知上的错误。我简单地理解递归就是循环，所以我把列表写在函数的外面，因为我觉得如果把列表写在函数的里面，那每一次递归调用的时候，这个列表不就清零了吗？其实不是这样的，递归虽然也是一种循环，但是递归这种循环更像是**套娃**或者说是**镜中镜**，其实每次调用递归函数，那个列表是不同的列表，或者说作用域不同。

### 树具体难在哪呢？
我们也曾用类创建自己的对象，比如说以前的`Animal` `Dog` `Cat`，但这一次树结构的类确实难度有所提高，我个人觉得在以下三点：
**1. 类本身的`self`就是在创建一个未来的对象，`self`就需要一定适应的；
2. 递归是一种特殊的函数调用，调用函数自身。我们经常用到的函数调用是调用已经写好了的函数。而递归的调用，是在调用自己正在创建的函数，也就是你在调用这个函数的时候，它还没完全好，你在调用完之后，还需要完善才好。
3. 递归函数中列表的**作用域**是不一样的；
3. 树这种递归本身就比阶乘的递归要复杂一些，而且还要把递归写到类里面，有点`盗梦空间`的感觉，一不小心就绕乱了。**

### 那如何应对呢？
我又翻看了老师对递归讲解的那个视频，就是求阶乘的那个课程视频，视频中其实老师是给了答案的，奇怪的是，当初学那节课的时候，我可是一分钟都没落下，这次回头看，居然发现自己没有注意到的关键点。关于递归的特点，老师总结了三点：**降阶** **边界条件** **回溯**。而且老师在讲树案例的时候，也传授了写**递归函数的心法**，就是**把递归函数的调用当作是调用一个普通的函数**。那么如何写好递归函数呢？

1. **理解递归和循环的区别。** 递归函数是分两段的，首先是一直降阶，一直降到边界条件，然后再返回。并且它里面用到的列表的作用域是不一样的。
1. **先写首尾，再填中间。** 函数追求的是高内聚低耦合，那么我们就先把函数的输入输出写出来，尤其是输出。知道输出是啥，那么我们就知道了无论调用多少层递归，反正它的输出结果你是知道的。
2. **边界条件写好。** 递归函数的结束条件要写好，否则就是死循环了。
3. **至少搞清楚两层或三层关系。** 写递归函数，你至少要搞清楚调用的两层或三层关系，这样层数多了，就是简单的重复，你逻辑上也是完整的，不会丢了哪一步。
4. **在纸上写写画画。** 在纸上写写画画，当递归在运行的时候，发生了什么。

当初想描述树结构的难点在哪都无法说清楚，有种哑巴吃黄莲的感觉。以上是个人对于递归函数一些体会，希望对你有帮助。当然，递归函数我写起来还不是那么地顺手，但比一开始好多了，也认清了自己的认知错误。
