### ISSUE TITLE
macOS 安装 MySQL 遇到的问题

### ISSUE THREAD

**Issue by Reecezhang** [neolee/wop-community#249]

**Comment by Reecezhang** [comment]
不知道老师是否有推荐的，安装哪个？
![截屏2020-08-16 21 22 04](https://user-images.githubusercontent.com/48814520/90335369-2a762480-e007-11ea-9451-f0d1cf45d14b.png)
2.4.2里面有这些
![截屏2020-08-16 21 27 18](https://user-images.githubusercontent.com/48814520/90335397-5d201d00-e007-11ea-8a1a-0a7e3ad19889.png)

**Comment by tyler1zhang** [comment]
1, 2, 4 是一样的东西，只是格式不同。 3应该是test版本。

**Comment by neolee** [comment]
不要装 8 版本，应该装 5.7 的版本。

最好的办法是：`brew install mysql@5.7`

**Comment by Reecezhang** [comment]
已使用命令brew install mysql@5.7安装完，在命令行下输入 mysql -uroot后，命令行出现command not found。。。

![截屏2020-08-17 18 43 42](https://user-images.githubusercontent.com/48814520/90387902-94e79d00-e0b9-11ea-8c74-97a79a125f05.png)

**Comment by neolee** [comment]
你安装完之后有一段提示没看吧？你要把 `/usr/local/opt/mysql@5.7/bin` 加入 PATH 中。

```
If you need to have mysql@5.7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.zshrc
```

**Comment by Reecezhang** [comment]
是的，我重新装一次后看到了.然后进行到下面这一步，然后macOS是直接下载这个8.0.21的版本吗？

![截屏2020-08-18 10 31 39](https://user-images.githubusercontent.com/48814520/90463690-2698ee00-e13e-11ea-9a95-51ab9bef2b93.png)
![截屏2020-08-18 10 34 42](https://user-images.githubusercontent.com/48814520/90463814-6fe93d80-e13e-11ea-8d94-afd1f841d604.png)

**Comment by neolee** [comment]
上面不是说了么？都不看回帖的？

**Comment by neolee** [comment]
要不然呢？
