### ISSUE TITLE
scoop 没能成功安装

### ISSUE THREAD

**Issue by wangjunhuan** [neolee/wop-community#25]
PS C:\Windows\system32> iwr -useb get.scoop.sh | iex
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题。用网络代理可以彻底解决；或者试试我在这个仓库首页最下面写的方法：

https://github.com/neolee/wop-community

**Comment by wangjunhuan** [comment]
配置hosts,键入安装命令，报错如下：
iex : 使用“1”个参数调用“DownloadString”时发生异常:“操作已超时。”
所在位置 行:1 字符: 26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
