### ISSUE TITLE
'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/wop-community#251]
<img width="1680" alt="Screen Shot 2020-08-17 at 15 00 46" src="https://user-images.githubusercontent.com/52094557/90366889-7de58280-e09a-11ea-9051-eb656f1fca32.png">

是因为我少装了模块吗？

**Comment by Royhowtohack** [comment]
模块是module， 错误提示说的是attribute

**Comment by neolee** [comment]
看不到完整代码很难判断。

我猜问题出在你初始化 `User` 对象时，最后一个参数你写的是 `777-7777`，没加引号，这会被理解为一个算式，算出来结果是 `-7000`，这个是你的 mobile 属性的值，是个 int 类型的值，没有 `startswith` 这样的属性或者方法。

**Comment by Royhowtohack** [comment]
跪了，李老师说对了！
