### ISSUE TITLE
找不到 “assets/moma-artists.csv” 文件

### ISSUE THREAD

**Issue by wangjunhuan** [neolee/wop-community#252]
import pandas as pd 

data = pd.read_csv('assets/moma-artists.csv')
data.head(10)

执行后，报错：
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-3a5219c07255> in <module>
      1 import pandas
      2 
----> 3 data = pandas.read_csv('assets/moma-artists.csv')
      4 data.head(10)

C:\Python38\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    684     )
    685 
--> 686     return _read(filepath_or_buffer, kwds)
    687 
    688 

C:\Python38\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    450 
    451     # Create the parser.
--> 452     parser = TextFileReader(fp_or_buf, **kwds)
    453 
    454     if chunksize or iterator:

C:\Python38\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    934             self.options["has_index_names"] = kwds["has_index_names"]
    935 
--> 936         self._make_engine(self.engine)
    937 
    938     def close(self):

C:\Python38\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1166     def _make_engine(self, engine="c"):
   1167         if engine == "c":
-> 1168             self._engine = CParserWrapper(self.f, **self.options)
   1169         else:
   1170             if engine == "python":

C:\Python38\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1996         kwds["usecols"] = self.usecols
   1997 
-> 1998         self._reader = parsers.TextReader(src, **kwds)
   1999         self.unnamed_cols = self._reader.unnamed_cols
   2000 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'assets/moma-artists.csv'
Convert to Code Cell
Delete Cell
Add Cell Above
Add Cell Below

**Comment by neolee** [comment]
那就是……找不到呀。

支线课程第一讲学习过么？对于绝对路径和相对路径的概念是不是清晰？

然后在检查下你的 `moma-artists.csv` 文件是不是放在你运行的程序所在目录的 `assets` 子目录下？

**Comment by muyuzhu** [comment]
看#248

**Comment by wangjunhuan** [comment]
> 那就是……找不到呀。
> 
> 支线课程第一讲学习过么？对于绝对路径和相对路径的概念是不是清晰？
> 
> 然后在检查下你的 `moma-artists.csv` 文件是不是放在你运行的程序所在目录的 `assets` 子目录下？

哦

**Comment by wangjunhuan** [comment]
> 看#248

谢谢
