### ISSUE TITLE
Services 管理程序中 找不到 MySQL

### ISSUE THREAD

**Issue by muyuzhu** [neolee/wop-community#254]
按照指南的操作，执行 scoop install mysql57 命令，显示安装成功
![微信图片_20200817211341](https://user-images.githubusercontent.com/57130025/90403326-67a7e880-e0d3-11ea-8b92-fa2ab8474ff8.png)
过程中有个WARN,我不知道是否有影响

按照指南中的路径，找不到 my.ini 文件，我是在 scoop 目录下找到的，并且 my.ini 文件中的内容，也与指南中示范的不一样
![微信图片_20200817214123](https://user-images.githubusercontent.com/57130025/90403808-11877500-e0d4-11ea-8400-bb97c9d8b2a8.png)

运行 mysqld --install 命令后 会有其他显示吗？ 我这里没有
然后，打开Services 管理程序，找不到 MySQL

我按 Notes 中说的 用管理员身份运行 mysqld --install MySQL --defaults-file="C:\Users\wwj\scoop\apps\mysql57\current\my.ini"
仍然没有用
![微信图片_20200817220559](https://user-images.githubusercontent.com/57130025/90405089-e4d45d00-e0d5-11ea-8891-c7a6734bdae2.png)

不知道问题出在哪

**Comment by muyuzhu** [comment]
https://dev.mysql.com/doc/refman/5.7/en/windows-server-first-start.html
https://dev.mysql.com/doc/refman/5.7/en/windows-start-command-line.html
这里也找不到与我这个问题相关的信息

**Comment by neolee** [comment]
你运行 `mysqld --standalone` 可以不？看前面截图安装是失败的。

Windows 下安装 MySQL 是比较多坑的，自己多试试，不行就算了，不是关键问题。

**Comment by muyuzhu** [comment]
我用安装包装了，在workbench 里建了个 demo 的database 搞定了
