### ISSUE TITLE
Jupyter Lab 启动时要求用不同的 workspace 反复重启都无法解决

### ISSUE THREAD

**Issue by Yi-chenglong** [neolee/wop-community#255]
今天使用命令行执行jupyter lab命令启动的时候，浏览器显示以下界面：
<img width="1440" alt="截屏2020-08-17 下午11 44 25" src="https://user-images.githubusercontent.com/48592822/90415847-400d4c00-e0e4-11ea-85dc-258b180e509f.png">
终端里显示如下：
<img width="961" alt="截屏2020-08-17 下午11 43 04" src="https://user-images.githubusercontent.com/48592822/90416216-c590fc00-e0e4-11ea-82ab-35a80ed8b021.png">
然后我反复重启里浏览器、终端和电脑还是没有恢复，不知道该怎么解决这个问题了

**Comment by xuzhengfu** [comment]
把默认浏览器设置为 “Chrome" 试试。

same error in this issue : https://github.com/jupyterlab/jupyterlab/issues/8164#issuecomment-641675067
