### ISSUE TITLE
win10 redis 不能启动服务

### ISSUE THREAD

**Issue by sai2008** [neolee/wop-community#256]
![image](https://user-images.githubusercontent.com/57187730/90462679-cbfe9280-e13b-11ea-87df-b51f7c0c78b2.png)
![image](https://user-images.githubusercontent.com/57187730/90462741-e5074380-e13b-11ea-9fe3-9a8c93e039b4.png)
文件路径正确，是因为6379端口被占用了吗？

**Comment by xuzhengfu** [comment]
<img width="589" alt="Screen Shot 2020-08-18 at 10 50 01" src="https://user-images.githubusercontent.com/39576401/90464831-bc357d00-e140-11ea-92c6-0077bf6a71e7.png">

**Comment by sai2008** [comment]
谢谢，改成本地服务，问题已解决。
