### ISSUE TITLE
课程大练习三中增加函数后打印的数据变过了

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#257]
课程大练习三treenode.py 源文件中执行 `print(root)` ，结果如下图：
<img width="131" alt="1" src="https://user-images.githubusercontent.com/57065555/90478343-9ec3db80-e15f-11ea-946d-6767d03be95e.png">

然后，在源文件中增加了下面的代码：
```
def get_descendants(self, node):
        nodes = node.children
        for i in node.children:
            nodes.extend(self.get_descendants(i))
        return nodes
```
执行
```
print(root.get_descendants(a))
print(root)
```
结果如下图，A 下面多了A21 和A22，这是怎么回事呢？
<img width="163" alt="2" src="https://user-images.githubusercontent.com/57065555/90478816-44774a80-e160-11ea-8fa6-9799faffb589.png">

**Comment by neolee** [comment]
你用 `extend` 方法加进去的呀。

**Comment by Amy20191** [comment]
哦哦，明白了，自己一个人看了半天都没找出原因。
