### ISSUE TITLE
关于数据库连接与关闭的问题

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#260]
数据库这一节，在连接数据库后，用完需要及时关闭。那我在 .ipynb 文件里连接数据库后没关闭，而是直接把 .ipynb 文件关闭了，是不是也相当于执行了数据库的关闭操作 `cursor.close()` 和 `conn.close()` ，因为第二次再打开的时候，数据库已经不能用了，要重新连接。
另外，如果有程序调用了打开数据库的操作，而没有关闭，那么，程序关闭后是不是也相当于关闭了连接数据库的通道呢？下次重启程序的时候，要重新连接？
只不过是这两种方式，如果在 .ipynb 文件 或者 程序在运行时候，如果没有关闭，就不好。

**Comment by neolee** [comment]
理论上讲 Python 解释器退出时会自动关闭连接，即使它没有这么做，一段时间之后数据库管理系统也会关闭已经死掉的连接。

**Comment by Amy20191** [comment]
哦，好的。
