### ISSUE TITLE
无法启动 Jupyter Lab

### ISSUE THREAD

**Issue by YunHang1010** [neolee/wop-community#261]
今配置好mySQL数据库，却无法用命令行打开jupyter lab？?

<img width="572" alt="无法启动jupyter lab" src="https://user-images.githubusercontent.com/60560117/90750200-0ec09600-e307-11ea-9fc7-9d867204a963.png">

**Comment by neolee** [comment]
你的问题可能和 MySQL 无关，而是 Python 环境乱了。从截屏看你的 Python 安装很混乱，看上去似乎有系统自带的也有 Homebrew 安装的，Jupyter 装在了 `/usr/local/opt/python/bin` 下的那个 Python 环境下，而那个环境不知道为啥不在了。

由于环境复杂且不是按照课程指南配置的，暂时给不出什么建议。你可以根据上面说的自己尝试，或者恢复 `/usr/local/opt/python/bin` 下面的 Python 环境，或者在 `/usr/local/bin` 下的那个 Python 环境里重装 Jupyter Lab。
