### ISSUE TITLE
jupyterlab 无法安装

### ISSUE THREAD

**Issue by chenqi-chenqi** [neolee/wop-community#262]
命令行执行python -m pip install --upgrade pip没问题
执行pip install jupyterlab就大红一片
![1597929398(1)](https://user-images.githubusercontent.com/69389946/90775018-e21e7580-e32a-11ea-9c40-3ca8bb67818f.jpg)
![1597929431(1)](https://user-images.githubusercontent.com/69389946/90775025-e480cf80-e32a-11ea-93dd-cdc22dfcdb93.jpg)

**Comment by neolee** [comment]
网络问题，用国内的镜像吧，这问题被问过多次了，配置指南里也有说明。
