### ISSUE TITLE
输出的表格和老师课件不一样

### ISSUE THREAD

**Issue by muse1171** [neolee/wop-community#263]
![截屏2020-08-20 21 25 14](https://user-images.githubusercontent.com/26201194/90775794-d7181500-e32b-11ea-8647-441d82199ae1.png)

**Comment by tyler1zhang** [comment]
你想说的是格式不一样？

**Comment by muse1171** [comment]
对

**Comment by neolee** [comment]
哪儿不一样？你这是让大家猜谜呀！

**Comment by muse1171** [comment]
![截屏2020-08-25 19 03 11](https://user-images.githubusercontent.com/26201194/91167043-dbff0f00-e705-11ea-82d3-08a661a4bdf7.png)
输出的格式不一样，这是老师的输出。

**Comment by tyler1zhang** [comment]
亲，你还真的蛮惜字如金的，或者你可能需要学习如何说明白一个事情。 
你说的不一样是指什么呢？左右对齐？颜色？表格边框？
如果是这些，那它们很大几率是受jupyterlab的版本控制的。或者我们用jupyter lab, 你却用了nteract。
如果不是这些不一样，请详细说明吧。别让我们猜了。

**Comment by neolee** [comment]
如果你指的是文字的粗细、字体等格式，这个格式显示是可以用不同的样式表随便改的，你用的大概是 nteract，它有自己的样式表，和用 Jupyter Lab 的缺省样式表本来就不一样。
