### ISSUE TITLE
SQL 增加限制命令报错

### ISSUE THREAD

**Issue by YunHang1010** [neolee/wop-community#264]
增加对username列的限制：
```python
cursor.execute('ALTER TABLE users ADD CONSTRAINT constraint_username UNIQUE (username)')
conn.commit()
```
报错：
<img width="685" alt="image" src="https://user-images.githubusercontent.com/60560117/90951718-dbf5d980-e48f-11ea-9dd3-77a88bd40d42.png">

命令行中的操作：
<img width="387" alt="image" src="https://user-images.githubusercontent.com/60560117/90951385-14e07f00-e48d-11ea-9160-8bfff9daaf3b.png">

**Comment by neolee** [comment]
感觉是你已经执行过这个命令了。你在 mysql 环境下执行 `SHOW CREATE TABLE users` 看看。
