### ISSUE TITLE
安装好 jupyter lab 后按教程试运行卡住

### ISSUE THREAD

**Issue by chenqi-chenqi** [neolee/wop-community#265]
执行cd C:\Users\username\Code\my-student-book（本人安装的位置）
jupyter lab
命令行界面卡在这一个内容1个多小时了，不知道还要卡多久。请问可以关掉命令行界面吗？
![1598152613(1)](https://user-images.githubusercontent.com/69389946/90970158-b28e8980-e533-11ea-81d7-ce3aefd52c23.jpg)

**Comment by neolee** [comment]
你等了一个多小时？有这个时间为啥不把教程仔细读读呢？或者把命令行里的提示搞懂？

<img width="726" alt="jupyter" src="https://user-images.githubusercontent.com/24796/90970617-dc4aaf00-e539-11ea-9b35-a0dd5a275e16.png">

![cml](https://user-images.githubusercontent.com/24796/90970650-419ea000-e53a-11ea-96df-f185b552f3bd.png)

**Comment by chenqi-chenqi** [comment]
老师批评得对，是该好好运用“只字不差的阅读能力”
