### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#266]
这里有什么句法错误啊？找了很久没有找出来。
![082301](https://user-images.githubusercontent.com/58320967/90975406-74f72400-e566-11ea-96f3-061cf89e1942.PNG)

**Comment by neolee** [comment]
你仔细看你的代码的文字颜色，发现什么不寻常的地方么？

**Comment by yuexiangming** [comment]
错误代码的颜色变黑了，不是红色，而且还有三个单词加粗，意味着这是 python 自带函数。
这次我发现第二句和第三句后面漏了逗号，补上之后还是报错。
但是把 I' d 这里的单引号去掉之后就好了。这是什么原因呢？

**Comment by tyler1zhang** [comment]
再提示一下，单引号和双引号都是一对一对的。`I'd` 中的第二个字符，对于python来说，就是个单引号。
你想一下，怎么改，才能改对呢？

**Comment by yuexiangming** [comment]
中文输入模式下输入 I' d 中的第二个字符，就不报错了。就是不要让 python 把那个字符解读为单引号，这样理解对吗？
我完全没想到引号要成对出现才行，那各种括号应该也有成对出现的要求吧。
谢谢李老师和 Tyler1zhang 同学！

**Comment by tyler1zhang** [comment]
你用中文单引号代替英文单引号这种解决方式是不对的。你应该用双引号代替最外层那一对单引号。这样，双引号之内的部分就可以用单引号。或者你用转义字符 `\` 。 你查找一下怎么用转义字符吧。

>我完全没想到引号要成对出现才行，那各种括号应该也有成对出现的要求吧。

字符串就是一对英文单括号或者双引号括起来的字符。所以你的这段描述反应了你对字符串的定义理解不够。建议你好好看看相关的章节。

你可以通过 `ord()` 这个函数去看一下每个引号的 unicode 编码对应的数字。你会发现英文的单引号对应 39， 中文的左单引号是8216， 右单引号是8217。

**Comment by neolee** [comment]
> 中文输入模式下输入 I' d 中的第二个字符，就不报错了。就是不要让 python 把那个字符解读为单引号，这样理解对吗？

你这个解决方案思路不对啊，你写的是英文的字符串，里面怎么能用中文标点呢？必须用英文的单引号才对啊。为了在字符串里根据需要使用英文的单/双引号，而又不影响把字符串括起来的那对引号，有两种办法：
1. 如果你要在字符串里使用单引号，那外面就用双引号就好了，比如：`s = "I'd better go now."`；反之，如果你要在字符串里使用双引号，那外面用单引号就好了：`'I call it "consulting detective".'`。
2. 使用转义符，即在字符串里用反斜线来强制插入一个特殊字符，这不会和外面的引号搞混，比如：`s = 'I\'d better go now.'`，字符串中的 `\'` 强制插入了一个单引号。

顺便，这些知识教材里都有，请仔细学习/复习《字符与字符串》那一章。

> 我完全没想到引号要成对出现才行，那各种括号应该也有成对出现的要求吧。

你这个“完全没想到”有点奇怪，引号、括号、书名号等不都是必须成对出现的么？这个算基本常识吧，为啥你会觉得这个有点意外？这个需要自己好好思考一下，做一点元认知的训练。

**Comment by yuexiangming** [comment]
汗颜，还自以为是地认为自己把问题解决了！基础不牢，地动山摇啊！
感谢李老师和 tyler1zhang 同学不厌其烦地讲解。
我还有很多功课要做。
