### ISSUE TITLE
DataFrame 的 size 返回的应为数据集 cell 总数

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/wop-community#268]
找到教材中的一处错误。 在“数据和数据库”一章提到：
>DataFrame 还有很多好用的属性和方法，比如 size 返回数据集行数，columns 返回所有列的显示名称，apply() 可以对行或列执行一个指定的函数，等等。官方文档详细的介绍了所有这些属性和方法。

我尝试运行了 `size` 和 `shape` ，发现 size = number of rows * number of columns.

**Comment by neolee** [comment]
是的，已经改了下说法。

其实 DataFrame 就是个魔改的 numpy array，所以 numpy 那套都可用的。
