### ISSUE TITLE
Win 10 系统重装了环境要重新配置

### ISSUE THREAD

**Issue by yuxi1314** [neolee/wop-community#269]
![image](https://user-images.githubusercontent.com/70151157/91055924-e2cf4880-e657-11ea-85d1-31f9a3b5b87b.png)
hosts修改后下载速度还是很慢

**Comment by yuxi1314** [comment]
scoop git 软件包下载一直卡在百分之一

**Comment by neolee** [comment]
网络问题——你之前怎么成功配置的……

**Comment by yuxi1314** [comment]
就是修改hosts呀
![image](https://user-images.githubusercontent.com/70151157/91197578-14b2de80-e72e-11ea-9106-5e1c33824282.png)

**Comment by neolee** [comment]
改 hosts 只能解决 GitHub 访问的一些问题，包括 Scoop 本身的安装脚本的问题，但不能解决下载和安装具体某个软件包（比如 git）可能碰到的网络问题。

换个网络或者换个时间多试几次吧，还不行的话就试试用网络代理。
