### ISSUE TITLE
Mac 下载 nteract 打不开，显示无法识别映像？

### ISSUE THREAD

**Issue by baoyalu1994** [neolee/wop-community#27]
- [ ] ![image](https://user-images.githubusercontent.com/67821951/86508872-150db800-be16-11ea-987c-1947e4f13523.png)

**Comment by neolee** [comment]
下载的 dmg 文件不完整——通常是网络不好没下完整。

另外，你之前开了个 issue，但是直接关了，然后又开了这个新的。其实这是不需要的，所有 issue 的标题、内容等都可以编辑修改，不当心点了关闭也可以再重新打开。这些在本仓库的首页都有说，请认真阅读。

**Comment by baoyalu1994** [comment]
好的，非常感谢老师的耐心解答，我在试试，刚才发现打错字了，我下次就知道怎么问问题了
