### ISSUE TITLE
启动 Redis 拒绝访问

### ISSUE THREAD

**Issue by doriawq** [neolee/wop-community#270]
![image](https://user-images.githubusercontent.com/51192376/91063118-25951e80-e660-11ea-8779-9a68a0be22e0.png)

![image](https://user-images.githubusercontent.com/51192376/91062986-f8487080-e65f-11ea-9c80-97ceeeb5048e.png)

**Comment by neolee** [comment]
你这个看上去是服务没起来，去 Windows 的 服务管理 里看看你安装的 Redis 服务是什么状态。

**Comment by doriawq** [comment]
![image](https://user-images.githubusercontent.com/51192376/91115241-5d31b400-e6bc-11ea-9dc4-2f65bda517c7.png)

**Comment by neolee** [comment]
参考 #256
