### ISSUE TITLE
'NoneType'  object is not callable

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#271]
log( ) 怎么没有类型了呢？
![082501](https://user-images.githubusercontent.com/58320967/91162405-a0ad1200-e6fe-11ea-8a0b-9766a9f387b8.PNG)

**Comment by neolee** [comment]
你的 `log` 函数没有显式返回值。

仔细看你的实现，`log` 函数里面嵌套了好几层函数的定义以及调用，你的 `return` 少了一个，然后写错了位置。

**Comment by yuexiangming** [comment]
对不起，李老师！浪费你时间了！
