### ISSUE TITLE
macOS 下 MySQL 环境准备出现 command not found: mysql

### ISSUE THREAD

**Issue by muse1171** [neolee/wop-community#272]
macOS
在命 令行界面运行下面的命令即可：

brew install mysql@5.7
brew services start mysql@5.7 安装成功后执行mysql -uroot报错。
```python
==> Successfully started `mysql@5.7` (label: homebrew.mxcl.mysql@5.7)
baojuan@baojuandeMacBook-Pro Downloads % mysql -uroot
zsh: command not found: mysql
```

**Comment by neolee** [comment]
你用 Homebrew 安装好 mysql 之后是有一段提示的，如果要在命令行使用 `mysql`，需要添加一个路径到 PATH 变量里，然后重启命令行界面。

```
❯ brew info mysql@5.7
mysql@5.7: stable 5.7.31 (bottled) [keg-only]
Open source relational database management system
https://dev.mysql.com/doc/refman/5.7/en/
/usr/local/Cellar/mysql@5.7/5.7.31 (319 files, 232.4MB)
  Poured from bottle on 2020-07-18 at 13:43:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mysql@5.7.rb
License: GPL-2.0
==> Dependencies
Build: cmake ✔
Required: openssl@1.1 ✔
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

mysql@5.7 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have mysql@5.7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.zshrc

For compilers to find mysql@5.7 you may need to set:
  export LDFLAGS="-L/usr/local/opt/mysql@5.7/lib"
  export CPPFLAGS="-I/usr/local/opt/mysql@5.7/include"

For pkg-config to find mysql@5.7 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/mysql@5.7/lib/pkgconfig"


To have launchd start mysql@5.7 now and restart at login:
  brew services start mysql@5.7
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql@5.7/bin/mysql.server start
```

**Comment by muse1171** [comment]
根据安装后提示信息第一步配置环境变量：

家目录下，vim ~/.zshrc，将安装后提示的：

export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

export LDFLAGS="-L/usr/local/opt/mysql@5.7/lib"

export CPPFLAGS="-I/usr/local/opt/mysql@5.7/include"

Esc 退出编辑模式，输入以下命令： :wq 保存后退出vi，source ~/.zshrc 使之生效使配置到环境变量生效；

完成后使用:brew services start mysql@5.7或者你根据配置文件启动mysql数据库，服务启动后开始初始化配置；
运行：mysql_secure_installation

提示如下：

Securing the MySQL server deployment.

Connecting to MySQL using a blank password.

VALIDATE PASSWORD PLUGIN can be used to test passwords
and improve security. It checks the strength of password
and allows the users to set only those passwords which are
secure enough. Would you like to setup VALIDATE PASSWORD plugin?

Press y|Y for Yes, any other key for No: k  //是否采用mysql密码安全检测插件，我本地使用果断拒绝了，因为密码检查插件要求密码复杂程度高，大小写字母+数字+字符等
Please set the password for root here.      // 首次使用自带配置脚本，设置root密码
New password:                               

Re-enter new password: 
By default, a MySQL installation has an anonymous user,
allowing anyone to log into MySQL without having to have
a user account created for them. This is intended only for
testing, and to make the installation go a bit smoother.
You should remove them before moving into a production
environment.

Remove anonymous users? (Press y|Y for Yes, any other key for No) : y   //是否删除匿名用户
Success.


Normally, root should only be allowed to connect from
'localhost'. This ensures that someone cannot guess at
the root password from the network.

Disallow root login remotely? (Press y|Y for Yes, any other key for No) : y   //是否禁止远程登录
Success.

By default, MySQL comes with a database named 'test' that
anyone can access. This is also intended only for testing,
and should be removed before moving into a production
environment.


Remove test database and access to it? (Press y|Y for Yes, any other key for No) : y  //删除测试数据库，并登录
 - Dropping test database...
Success.

 - Removing privileges on test database...
Success.

Reloading the privilege tables will ensure that all changes
made so far will take effect immediately.

Reload privilege tables now? (Press y|Y for Yes, any other key for No) : y          //重新载入权限表
Success.

All done!
配置完成，使用mysql -uroot -p,然后输入配置到root密码登陆到mysql数据库；
