### ISSUE TITLE
scoop 更新出错

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#275]
我试过老师本页Wiki给出的重装方法了，一直挂在`Updating Scoop...`这。
![微信截图_20200827131751](https://user-images.githubusercontent.com/63906805/91387408-d02b5e00-e867-11ea-99b5-c3441b580fb9.png)
![微信截图_20200827141028](https://user-images.githubusercontent.com/63906805/91398670-1fc15800-e86f-11ea-9aef-9b08a649224a.png)

**Comment by Sincere-io** [comment]
> 我试过老师本页Wiki给出的重装方法了，依然出现同样的问题。
> 
> ![微信截图_20200827131751](https://user-images.githubusercontent.com/63906805/91387408-d02b5e00-e867-11ea-99b5-c3441b580fb9.png)

**Comment by neolee** [comment]
所以你的问题是第一个截屏还是第二个？

第二个没啥，就等呗，时间太久就关了重试，多半是网络问题。

**Comment by Sincere-io** [comment]
老师，如果关了重试，就会出现第一个截屏的问题。

**Comment by neolee** [comment]
那就是网络问题了。前一次 update 没成功留下了垃圾。
