### ISSUE TITLE
mysql 修改 root 密码操作失败

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#277]
**第一步、我在修改root密码之后，重新运行`mysql -uroot `之后，而输入密码那里显示了一个钥匙标签：**

<img width="1144" alt="WeChat0373ac769b3c7628fc34a48437ac0245" src="https://user-images.githubusercontent.com/52586220/91514193-bac23c80-e918-11ea-9d32-e96d872a74d2.png">
-
-
-
-
-

第二步、在我输入密码之后，却显示错误；另外在我输入密码的过程中并没有出现 Enter password: *******，一直都只显示一个钥匙的标签。
```
liujiale@LiujialedeMacBook-Pro ~ % mysql -uroot -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
liujiale@LiujialedeMacBook-Pro ~ % 

```

**Comment by Liujiale02** [comment]
要怎么操作可以退回重新设置密码那一步的？

**Comment by neolee** [comment]
输入密码的时候本来就不会显示任何东西，这样最安全，请仔细核对你输入的密码是不是正确。

如果实在输不对密码，也可以重置，方法类似下面这样：


https://support.rackspace.com/how-to/mysql-resetting-a-lost-mysql-root-password/

注意文中具体命令是针对 Linux 环境的，要换成你自己的环境对应的命令。

**Comment by Liujiale02** [comment]
还是比较难搞。

现在有一个底层的情况是： 每次在命令行界面输入`brew services start mysql@5.7`启动mysql时，都会显示以下的错误：
```
liujiale@LiujialedeMacBook-Pro ~ % mysql -uroot 
zsh: command not found: mysql
```

然后呢我就根据issues #272 中老师的回答，做以下动作：
```
输入brew info mysql@5.7
输入export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
```
做完上面两个动作之后，才能正常运行`mysql -uroot` ，但是每次重启命令行都要走一遍上述的动作。

问题：怎么一次性添加路径到 PATH 变量里，不至于每次启动sql都要做一遍上述动作？

**Comment by neolee** [comment]
把那句命令加到 .zshrc 里啊

**Comment by Liujiale02** [comment]
终于搞掂了，泪目啊老师！

这个帖子，也帮了我不少的忙
https://www.jb51.net/article/136696.htm
