### ISSUE TITLE
定义函数 对第二个参数赋值无法运行？

### ISSUE THREAD

**Issue by YunHang1010** [neolee/wop-community#278]
year = begin 运行
<img width="548" alt="image" src="https://user-images.githubusercontent.com/60560117/91536827-e7da1380-e947-11ea-9752-0961e5865341.png">

year = end / year = begin , year = end 无法运行
<img width="552" alt="image" src="https://user-images.githubusercontent.com/60560117/91536934-135cfe00-e948-11ea-8326-7ec4c0d574cf.png">

这是有什么规定么？

**Comment by neolee** [comment]
你理解 `year = end` 和 `while year < end:` 这两句是啥意思么？

**Comment by YunHang1010** [comment]
搞蒙了，现在理解了，麻烦老师了。
