### ISSUE TITLE
关于 partial

### ISSUE THREAD

**Issue by Yongheng2020** [neolee/wop-community#280]
![image](https://user-images.githubusercontent.com/67858621/91652661-fb15ec00-eacb-11ea-823a-a5dfc44fe120.png)

partial是用来对函数进行”降参“用的,教材中的这个函数，partial的第二个参数，若输入的是x=3，则会报错，这是什么原因？只能固定y？

**Comment by neolee** [comment]
`partial` 减参数的时候，对原函数里的 positional arguments 必须按顺序来，只能给后面的 positional arguments 设置值，不能给前面的设置；对 keyword arguments 倒是随意。

你的例子里，`power` 函数的两个参数都是 positional arguments，你只能对 y 进行设置。
