### ISSUE TITLE
MySQL 相关的问题

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#281]
已经按照指南安装和配置好了本地的MySQL数据库
![微信截图_20200831190604](https://user-images.githubusercontent.com/63906805/91713845-1b71a380-ebbd-11ea-956c-c80840e5a305.png)
在Jupyterlab里运行出现找不到mysql模块，想不明白所以来请教老师。
![微信截图_20200831183424](https://user-images.githubusercontent.com/63906805/91711659-cc297400-ebb8-11ea-9e50-1fd1058cbd3b.png)

**Comment by neolee** [comment]
有没有安装 `pip install mysql-connector-python`？

**Comment by Sincere-io** [comment]
没安装，原来是这样...
