### ISSUE TITLE
二手车爬虫

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#283]
跟着老师的案例二，自己想依葫芦画瓢做一个关于二手车的爬虫，然后做一些数据分析。

我找到了要爬取的表，但是我的`ul = soup.find('ul',class_='carlist clearfix js-top')`的结果是 `None` 。并且这个`ul`的父节点`div`，`ul = soup.find('div',class_='list-wrap js-post')`，`ul`的结果也是`None`。
<img width="1440" alt="截屏2020-09-05 下午10 31 23" src="https://user-images.githubusercontent.com/57254889/92316380-bb985400-f025-11ea-837b-d5959502aba6.png">
<img width="1440" alt="截屏2020-09-06 上午9 46 52" src="https://user-images.githubusercontent.com/57254889/92316408-1b8efa80-f026-11ea-8e39-bac88a3f0b8a.png">

**Comment by neolee** [comment]
你把 `response.content` 打出来就知道了，里面并没有你看到的页面内容，而是一大串加密的 JavaScript，这个页面是动态生成的（其中一个原因就是防爬）。

**Comment by gaoteng-pro** [comment]
##### 图1
<img width="1440" alt="截屏2020-09-06 下午5 47 39" src="https://user-images.githubusercontent.com/57254889/92323258-d8567b00-f069-11ea-9f37-46f7e9ecc689.png">

##### 图2
<img width="1440" alt="截屏2020-09-06 下午5 48 22" src="https://user-images.githubusercontent.com/57254889/92323273-f58b4980-f069-11ea-9e20-a7a3e1987022.png">

##### 图3
<img width="1440" alt="截屏2020-09-06 下午5 49 05" src="https://user-images.githubusercontent.com/57254889/92323275-050a9280-f06a-11ea-8b61-b9f387f5aa83.png">

三张截屏都是打印`response.content`的结果。

图一是`Restart and Clear Kernel`之后，运行了一遍`Kernel`之后的结果；图二是在图一运行一遍后，没有`Restart and Clear Kernel`，又重新运行了一遍所有的`Kernel`；图三是又一次`Restart and Clear Kernel`之后，运行了一遍`Kernel`之后的结果。

结果就是，这三张图的输出好像是一样的。

---

### 问题：
1. 动态生成页面的话，是不是每一次执行的结果是不一样的？
2. 如果想接着爬取，应该如何做？

**Comment by neolee** [comment]
你看到的是加密的 JavaScript 程序代码，真正的页面内容就是这些程序代码在浏览器里运行然后动态生成的。动态生成和“每次执行结果是否一样”没啥关系。

用实践案例里的方法无法处理这类页面，你可以找别的网页来试。等熟悉了基本技术之后再研究怎么对付这类页面。

**Comment by gaoteng-pro** [comment]
收到。

第一次上践行群编程课的时候，也是对二手车爬虫进行了尝试，那次失败了，死因不详；这是第二次对它尝试，比上次强，知道卡在哪里了。

先用其他的试手，慢慢获得经验，再对其进行进攻。
