### ISSUE TITLE
Services 中找不到 MySQL 一项

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#285]
按照指南安装 mysql57 成功
![090801](https://user-images.githubusercontent.com/58320967/92418662-3e8eeb00-f19b-11ea-89ab-f5287e6a9490.PNG)
但是找不到 my. ini 这个文件，只有一个文件名为 my 的文件，这个 my 文件里面的内容也跟指南上的不一样，所以我新建了一个
![090803](https://user-images.githubusercontent.com/58320967/92418748-b8bf6f80-f19b-11ea-9762-af891806de57.PNG)
我是用文本文档的格式新建的，这种格式是不是无效呢？应该用什么格式？
![090802](https://user-images.githubusercontent.com/58320967/92418801-1bb10680-f19c-11ea-8c58-b263fb762c07.PNG)
我还尝试了运行 mysqld --standalone, 显示如下：
![090804](https://user-images.githubusercontent.com/58320967/92418882-aa258800-f19c-11ea-89a7-29924ccaecf9.PNG)
请问如何解决这个问题？

**Comment by neolee** [comment]
你执行 `mysqld --install` 时返回的信息是告诉你这个操作没成功（“denied”），原因是权限不够，你需要以管理员权限执行这个命令才行。

**Comment by CHANCYstone** [comment]
老师我想问下，在修改my文件时，用什么方式打开都ok么？

**Comment by neolee** [comment]
@CHANCYstone 不太明白你的问题，你能把你遇到的具体问题表述清楚吗？

**Comment by CHANCYstone** [comment]
![image](https://user-images.githubusercontent.com/71212547/100542512-47b4c300-3285-11eb-8a96-f1c5f3806469.png)
当时遇到的问题是：
在current 文件夹中没有my.ini文件，但是有my这个文件，于是我就以为my文件就是老师所说的my.ini文件，并对my文件进行了改名，修改其中的内容等操作
但是问题没有得到解决，状态几乎没有得到改善。
于是以为自己是对文件的修改方式有问题，才导致修改的结果没有作用的。
我当时以为  vs  和  记事本  两种不同的方式打开文件，进行修改对结果会有影响。

**Comment by CHANCYstone** [comment]
白天的时候mysql 配置出现问题，在github中找issue，在Google中搜索等等，都无果
晚上打算放弃的时候，我在issue重新罗列了所有的相关issue 重新按照流程下载
经过一番努力最终成功配置好了环境。下面的经验仅供参考，希望对你有所帮助：

- 最开始下载失败后，我参考#254 希望自己配备MySQL57环境并用workbench配置，失败，再次卸载全部相关的

- 随后将所有相关issue整理：https://github.com/neolee/pilot/issues/646     https://github.com/neolee/pilot/issues/1150
以及 #254  和  #281 ，并没有开始做相关操作

- 并且惊讶的发现自己的有my 和 my.ini 两个文件 并在service中，找到了mysql.（也就是说，mysql在service 中出现可能与我下载后删除相关？？）
我也不太清楚，希望对你有帮助吧
