### ISSUE TITLE
Windows 无法启动 Redis 服务

### ISSUE THREAD

**Issue by yuexiangming** [neolee/wop-community#286]
在 Services 列表中可以找到 Redis, 但右键启动时提示 无法启动, 请问这是怎么回事？
![090805](https://user-images.githubusercontent.com/58320967/92419533-aeec3b00-f1a0-11ea-8cd4-7d6ca40f1d0c.PNG)

**Comment by neolee** [comment]
提问之前可以先搜索下，这个问题已经不止一次被问过了，参考 #256

**Comment by yuexiangming** [comment]
好的，老师。问题已解决。
