### ISSUE TITLE
MySQL 创建 conn 环境配置问题

### ISSUE THREAD

**Issue by Yongheng2020** [neolee/wop-community#287]
![image](https://user-images.githubusercontent.com/67858621/92424772-d1d61980-f1b7-11ea-9ee4-e3887c5d0678.png)
![image](https://user-images.githubusercontent.com/67858621/92424804-e4505300-f1b7-11ea-822e-199d98b07094.png)
老师：
   1、 我按照教材的步骤配置好了MySQL，但是做作业的过程中，代码运行不了，教材中说”配置 MySQL 连接时，host user passwd database 这四个参数对应 MySQL 服务的地址、用户名、密码和数据库名，根据你的环境设置即可“，是不是因为我这四个参数配置不对，请问应该在哪里查找这四个配置。
    2、教材中的这句”MySQL 中已创建用户 learn 拥有访问此 fifa19 数据库的权限“，这个已创建用户指的是什么？

**Comment by neolee** [comment]
看不到完整错误信息，没法判断。

关于创建用户等内容，在“课程配套资源”的附录中有“MySQL 配置指南”，仔细阅读，按照其中的指引操作，有详细说明。

**Comment by Yongheng2020** [comment]
![image](https://user-images.githubusercontent.com/67858621/92439810-11aff780-f1de-11ea-9bb6-5b31599a4418.png)

![image](https://user-images.githubusercontent.com/67858621/92439856-27252180-f1de-11ea-8e2f-2cd45d6cbaf6.png)
是按照配套资源的配置指南一步步做的

**Comment by neolee** [comment]
看错误信息最后一行，用给定用户访问相应数据库失败（权限问题）。

所以应该是没有正确配置用户（密码）以及访问权限。
