### ISSUE TITLE
安装 pandas 第三方库出错

### ISSUE THREAD

**Issue by Kuo-Ran** [neolee/wop-community#289]
麻烦老师同学帮忙看下。
被难住了，升级不成功，安装不上，实在是解决不了了，谢谢大家。
![Xnip2020-09-09_14-10-00](https://user-images.githubusercontent.com/68600053/92561288-8babb380-f2a6-11ea-84bc-936076b3c9ef.jpg)

**Comment by neolee** [comment]
你的 python 命令指向的是系统自带的 Python 2.7，用 python3 和 pip3 试试。

话说你这个情况，之前安装任何 Python 第三方库都会有问题，你为啥现在才遇到呢？

**Comment by Kuo-Ran** [comment]
谢谢老师，课程刚开始时出错过，用 pip3 解决了，后面学着学着就忘了，主要是没懂这次问题的根源是哪里，感谢老师解答。

疲于工作，回复较晚，望老师理解。
