### ISSUE TITLE
Python 安装失败

### ISSUE THREAD

**Issue by worldhuili** [neolee/wop-community#29]
老师，不知道为何Python每次都安装失败。

**Comment by hendasheng** [comment]
> 老师，不知道为何Python每次都安装失败。

大概写下前因后果吧，也方便老师定位问题。
什么系统，什么操作，什么反馈 ...

**Comment by tyler1zhang** [comment]
> 老师，不知道为何Python每次都安装失败。

贴一下照片，把信息贴全一点。特别是你最后一个命令，和所有的计算机反馈的信息。
还有你尝试了什么，遇到了什么error。

**Comment by neolee** [comment]
先按照今天上课说的把 https://github.com/neolee/wop-community 首页的 README 仔仔细细的读上两遍，然后把自己的问题说清楚吧。

其他重复的问题将被删除。
