### ISSUE TITLE
Pandas 读取 Excel 时间格式问题（案例学习之-自动化）

### ISSUE THREAD

**Issue by hendasheng** [neolee/wop-community#290]
课程示范中， dt 是 `Timestamp` 类型，执行 `to_pydatetime()` 后，dt 变成 `datetime` 类型。

![Snipaste_2020-09-09_22-48-57](https://user-images.githubusercontent.com/20842136/92615127-5bd4ce00-f2ef-11ea-85fe-57f46a00da7d.png)
![Snipaste_2020-09-09_22-49-42](https://user-images.githubusercontent.com/20842136/92615140-5f685500-f2ef-11ea-9ef5-180593d0ab7a.png)
---
为什么我的代码中， dt 一开始就是 `datetime` 类型？
系统：macOS
```Python
import pandas as pd
df = pd.read_excel('assets/expenses/01.xlsx',header=None)
dt = df.iloc[0, 1]
dt
# > datetime.datetime
```
<img width="550" alt="截屏2020-09-09 22 56 49" src="https://user-images.githubusercontent.com/20842136/92615500-c2f28280-f2ef-11ea-84f8-0b09a36f14e6.png">

**Comment by neolee** [comment]
嗯，我试了下，确实是你说的这样，这应该是最近 pandas 版本中的变化，我晚些时候做些更详细的测试后再更新教材，多谢你提供的反馈！

**Comment by hendasheng** [comment]
> 嗯，我试了下，确实是你说的这样，这应该是最近 pandas 版本中的变化，我晚些时候做些更详细的测试后再更新教材，多谢你提供的反馈！

谢谢老师：）
