### ISSUE TITLE
类型转换问题

### ISSUE THREAD

**Issue by ghost** [neolee/wop-community#292]
类型转换没有出现想要的结果。不知道为什么在我写的程序里运行int(float("3.14"))运算结果不是3而是3.14？而在命令行里运算结果却是3？
代码如下：
while True:
    number = input("Please enter a number:")
    if number == "q":
        break
    else:
        try:
            int(float(number))
        except:
            print("Please enter a number again!")
        else:
            print(number)
图片如下：
![454ea05d13da378a50783bdb8b6960b](https://user-images.githubusercontent.com/67884048/93101148-82727a80-f6dc-11ea-9770-e3bba6d26c9f.png)
![81d46ac97145f0392373aa6f3a51261](https://user-images.githubusercontent.com/67884048/93101156-843c3e00-f6dc-11ea-8d02-e6853b647d8d.png)
求助老师，同学们，多谢~

**Comment by neolee** [comment]
`int(float(number))` 是一个表达式，当你在 Python 解释器的交互界面里输入这个表达式后，解释器会求出它的结果并打印出来，这是解释器交互界面提供的一种方便的机制，并不是程序执行的效果——这一点在课上是解释过的。

当你把这些代码保存在 .py 文件中然后用 `python xxx.py` 运行时，上述功能就不存在了（因为它只是解释器交互界面提供的一种附加能力）。那么仔细看你的代码，到底做了什么呢？

首先你执行 `int(float(number))`，然后打印了 `number` 的结果 `print(number)`，这时候 `number` 里面是什么呢？思考下面的几个问题：
* 一开始 `number` 中放的是用户输入的内容，它是什么？
* `int(float(number))` 会改变 `number` 的内容吗？
* 所以最后打印出来的应该是什么？

**Comment by ghost** [comment]
不好意思现在才看到老师的回复。。。老师的意思是，int函数和float函数在文件内会失效是吗？如果是这样的话，假如我要在文件里做类型转换，那该怎么做呢？
