### ISSUE TITLE
关于树那一讲的疑问

### ISSUE THREAD

**Issue by ghost** [neolee/wop-community#294]
![image](https://user-images.githubusercontent.com/67884048/97433621-c18d2000-1958-11eb-9c75-70980b295934.png)
老师讲到树这一节第70分钟的时候有这张代码，我感觉if语句里的条件有点多余。因为如果有子节点的话，那么子节点的数量肯定是不为0的——我认为老师写的这两个条件是一回事。请问老师在这里为什么要这么写if语句的条件呢？

**Comment by ghost** [comment]
我试了一下，好像只有一个就可以了。。。。

**Comment by neolee** [comment]
是的，第一个就可以了，可以思考下为什么这样……
