### ISSUE TITLE
Scoop Git 安装问题

### ISSUE THREAD

**Issue by BensonHoll** [neolee/wop-community#295]
在安装Git时一直卡在图下红色这一段不动了，请问怎么处理? 谢谢

![image](https://user-images.githubusercontent.com/51362187/98188475-03682880-1f4e-11eb-88ca-9af701535b74.png)

**Comment by neolee** [comment]
等了多久？

**Comment by BensonHoll** [comment]
老师，现在卡在scoop更新这里一个多小时了。。

![image](https://user-images.githubusercontent.com/51362187/98206124-5bb22100-1f74-11eb-8198-701c9754fa13.png)

**Comment by BensonHoll** [comment]
> 等了多久？
老师，现在卡在scoop更新这里一个多小时了。。
![image](https://user-images.githubusercontent.com/51362187/98210180-1c3b0300-1f7b-11eb-9208-82dfd8021dec.png)

**Comment by neolee** [comment]
所以你的安装 git 那一步成功过了对吧？现在是 `scoop update` 卡住了？

这个一般都是网络方面的原因，可以换个时间或者换个网络再试试。

**Comment by BensonHoll** [comment]
> 所以你的安装 git 那一步成功过了对吧？现在是 `scoop update` 卡住了？
> 
> 这个一般都是网络方面的原因，可以换个时间或者换个网络再试试。

对的，git安装成功了，但是现在显示升级失败了
![image](https://user-images.githubusercontent.com/51362187/98215296-96bb5100-1f82-11eb-9800-50470123ec91.png)

**Comment by neolee** [comment]
这个提示就是网络问题，如我前面回复说的，可以换个时间或者换个网络再试试，或者使用网络代理。

**Comment by BensonHoll** [comment]
> 这个提示就是网络问题，如我前面回复说的，可以换个时间或者换个网络再试试，或者使用网络代理。

一般这个更新多久会有响应或者多久能完成更新？这个没有进度条可以看每次就傻等。。。

**Comment by BensonHoll** [comment]
> 这个提示就是网络问题，如我前面回复说的，可以换个时间或者换个网络再试试，或者使用网络代理。

老师  我已经试了两天了都不行，scoop update这一步是必须的吗，有没有替代方案?谢谢

**Comment by neolee** [comment]
如果网络没问题，这个很快的。所以我说可以试试网络代理。

实在搞不定的话，就不能用 Scoop 了，但可以去 Python 官网下载安装包然后自行安装：

https://www.python.org/downloads/release/python-374/

**Comment by BensonHoll** [comment]
> 如果网络没问题，这个很快的。所以我说可以试试网络代理。
> 
> 实在搞不定的话，就不能用 Scoop 了，但可以去 Python 官网下载安装包然后自行安装：
> 
> https://www.python.org/downloads/release/python-374/

老师，我把Python3.7.4安装到scoop的app目录下了，然后scoop list报python tool *failed*, VS code还没安装，这个问题不解决会有影响吗，谢谢

![image](https://user-images.githubusercontent.com/51362187/98437488-7247ac00-211d-11eb-8e99-f9d3b707cf72.png)
