### ISSUE TITLE
Scoop Git 安装问题

### ISSUE THREAD

**Issue by BensonHoll** [neolee/wop-community#296]
在安装Git时一直卡在图下红色这一段不动了，请问怎么处理? 谢谢
![image](https://user-images.githubusercontent.com/51362187/98189029-18918700-1f4f-11eb-81f7-afc1da02b534.png)

**Comment by neolee** [comment]
Duplicate of #295

**Comment by BensonHoll** [comment]
老师，这个updating等了一个多小时了都没反应。。
![image](https://user-images.githubusercontent.com/51362187/98205833-d3cc1700-1f73-11eb-97a7-61e4443de3b8.png)

**Comment by BensonHoll** [comment]
一直卡在updating scoop...
