### ISSUE TITLE
异常处理中，"Exception"是否是个特殊的关键词？

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/wop-community#298]
```python
try:
    5/0
except Exception as err:
    print(err)
```
`Exception` 并不在 `keyword.kwlist`里面，但是这里并不会报 `提前引用` 之类的错误。而且不能使用 `exception`. 请问 `python` 怎么定义 `Exception` 的呢？

**Comment by neolee** [comment]
Exception 是 Python built-in 的一个类，是所有运行时异常类的父类。

Python 有很多类、函数、对象等是 built-in 的，也就是说只要你能运行 `python` 解释器，这些东西就是可用的，不需要 `import`，这些东西都不算 `keyword`，自然也不会在 `keyword.kwlist` 中。
