### ISSUE TITLE
判断 itertools._grouper 长度的问题

### ISSUE THREAD

**Issue by iamjinlei0312** [neolee/wop-community#299]
老师好，

是这样的，有这么一个需求***识别列表中连续的数字***，因此我就写了以下的代码：

 ```python
from operator import itemgetter
from itertools import groupby
data = [2, 3, 4, 5, 12, 13, 14, 15, 16, 17]
for k, g in groupby(enumerate(data), lambda i_x: i_x[0]-i_x[1]):
    print(list(map(itemgetter(1),  g)))

```

输出符合预期：

 ```python
[2, 3, 4, 5]
[12, 13, 14, 15, 16, 17]
```

当 `data = [0, 2, 4, 7, 8]` 时，结果为

 ```python
[0]
[2]
[4]
[7, 8]
```
我想保留列表长度大于 `1` 的结果，因此就想用 `len(list(map(itemgetter(1),  g))) > 1` 来过滤，但却失败了。后来我发现问题所在，就是连续两次的 `list(map(itemgetter(1),  g))` ，第二次会失效。也就是连续两次使用 `g`，第二次失效了，`g` 的类型是 ：

 ```python
itertools._grouper
```

所以，老师，对于这种“只有在第一次使用的时候是正常”的现象，我懵了，我理解的迭代器是可以反复使用的呀。另外，对于以上现象的描述，用词方面可能我说的不够专业，😂😂😂。

连续两次使用 `list(map(itemgetter(1),  g))`

 ```python
from operator import itemgetter
from itertools import groupby
data = [2, 3, 4, 5, 12, 13, 14, 15, 16, 17]
for k, g in groupby(enumerate(data), lambda i_x: i_x[0]-i_x[1]):
    if len(list(map(itemgetter(1),  g))) > 1:
        print(list(map(itemgetter(1),  g)))

```

**Comment by iamjinlei0312** [comment]
对于以上问题的解决办法可以这样：

```python
from operator import itemgetter
from itertools import groupby
data = [0, 2, 4, 7, 8] 
for k, g in groupby(enumerate(data), lambda i_x: i_x[0]-i_x[1]):
    temp = list(map(itemgetter(1),  g))
    if len(temp) > 1:
        print(temp)
```

这样就可以得到想要的结果，但对于 “`g` 的第二次使用失效”的这个现象，我还不是很理解。

**Comment by neolee** [comment]
你最后的方案是对的，因为不这么做，而是 `len()` 的时候扫描一遍 `g`，`g` 是一个迭代器，它就迭代完了，停在最后没有元素可以迭代了，再要 `print()` 输出就不行了。

可迭代对象，每次 `next()`（有时候是隐藏的调用了这个，比如 `map()` 就会）都会取出一个数，对象里的数就少一个。

**Comment by iamjinlei0312** [comment]
明白了，我知道我哪里想错了，谢谢老师。问题中的 “g” 我也像老师一样 `g` 改过来格式了。
