### ISSUE TITLE
git commit 命令报错

### ISSUE THREAD

**Issue by sujuxiaoren** [neolee/wop-community#3]
老师您好，我通过**课程配套资源-附录-3.Git与GitHub入门**进行step by step学习的过程中，到了 git commit 这步命令时卡住了，出现了错误，在网上通过搜索后依然找不到解决办法。想问如何解决？谢谢。

以下是报错信息：
![微信图片_20200624164515](https://user-images.githubusercontent.com/48588846/85527800-c99d2200-b63d-11ea-87ac-68921b8ccdb0.png)

git的配置如下：
![微信图片_20200624164456](https://user-images.githubusercontent.com/48588846/85523921-272f6f80-b63a-11ea-979b-f349ad60cb98.png)

另外，这节文档里的图片全都裂了

**Comment by alphaho** [comment]
会不会是没有安装 VS Code 导致的报错？
你可以先试试通过命令 `git commit -m "<你的提交信息>"` 来提交 (需要把 `<你的提交信息>`  换成具体的内容，比如 `第一次提交`)

**Comment by sujuxiaoren** [comment]
> 会不会是没有安装 VS Code 导致的报错？
> 你可以先试试通过命令 `git commit -m "<你的提交信息>"` 来提交 (需要把 `<你的提交信息>` 换成具体的内容，比如 `第一次提交`)

已经安装 VS Code了的，并且前面已经执行过 `code README.md` 可以打开VS Code编辑并且保存了

**Comment by sujuxiaoren** [comment]
> 会不会是没有安装 VS Code 导致的报错？
> 你可以先试试通过命令 `git commit -m "<你的提交信息>"` 来提交 (需要把 `<你的提交信息>` 换成具体的内容，比如 `第一次提交`)

额，试了下，好像可以通过 `git commit README.md -m 'xxxxx'` 解决，为啥按照课程的，先 `git add `， 然后 `git commit` 不行呢？

**Comment by alphaho** [comment]
> 另外，这节文档里的图片全都裂了

这个应该是网络方面的问题，可能需要通过修改 `hosts` 文件来解决。

> 额，试了下，好像可以通过 git commit README.md -m 'xxxxx' 解决，为啥按照课程的，先 git add ， 然后 git commit 不行呢？

原来的 ` git commit ` 命令是通过调用 VS Code 来填写提交信息的。而通过 `git commit README.md -m 'xxxxx' ` 命令的话，是直接在这个命令里面填写提交信息，跳过了运行 VS Code（也就是产生错误的地方），所以可以成功。

**Comment by alphaho** [comment]
或者试试重装 VS Code 看看能不能解决你一开始 `git commit` 失败的问题？

**Comment by sujuxiaoren** [comment]
> 或者试试重装 VS Code 看看能不能解决你一开始 `git commit` 失败的问题？

感谢，我刚开始怀疑是不是我的用户名是中文啊，试了下，配置了绝对路径解决了。 `git config --global core.editor "'C:\Users\微软中国\AppData\Local\Programs\Microsoft VS Code\Code.exe' -w"`

至于图片裂那个，我开全局科学上网也不行，不过这个问题不重要了，哈哈哈。

再次感谢！

**Comment by neolee** [comment]
Notebook 内置图片这个问题了解了，正在看如何解决。

至于 core.editor 的问题你们已得到正解 👍

**Comment by neolee** [comment]
感谢技术团队的小伙伴加班处理，notebook 内置图片显示问题已解决，遇到问题的同学可以再试下。
