### ISSUE TITLE
w3school 中关于 HTML 的 id 语法是不是矛盾了？

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#300]
如图：
---
<img width="1440" alt="截屏2020-11-20 下午10 29 32" src="https://user-images.githubusercontent.com/57254889/99812017-e4d67400-2b80-11eb-8605-638e485de56e.png">

红框里的内容讲一个`id`名称只能由一个HTML元素使用，w3school例子如下图：

<img width="1440" alt="截屏2020-11-20 下午10 30 39" src="https://user-images.githubusercontent.com/57254889/99812368-58788100-2b81-11eb-8cb5-c5e6f4a83a3a.png">

但是，我在不同的HTML元素中使用了同一个`id`，发现居然是可以使用的，如下图：
<img width="1440" alt="截屏2020-11-20 下午10 33 16" src="https://user-images.githubusercontent.com/57254889/99812851-eb192000-2b81-11eb-9dc7-501bd2ed57ac.png">

我的`<p id="myHeader">me too</p>`使用了和`<h1 id="myHeader">my Header</h1>`一样的`id="myHeader"`，结果发现同一个`id`是可以被多个HTML元素使用的。

**Comment by neolee** [comment]
你“可以”把一个 id 用于不同的 elements，并不会导致你的浏览器或者电脑爆炸。

但这不好，也不对，因为 id 用于定位特定的 element，所以 w3school 说你“must”不这么用。

**Comment by gaoteng-pro** [comment]
嗯，我也知道不这么用（多个elements直接用`class`就好），所以感觉有点矛盾。
既然`id`目的是用于特定的element，那么在语法设计上是不是设计成：同一个`id`只能用于特定的element，用于不同的elements就会报错，会不会更严谨一些。

**Comment by neolee** [comment]
是会严谨一点，但是一般浏览器不会这么严格，第一是因为严格的检查比较耗时，第二是浏览器的主要责任是给普通用户展示内容，需要宽容一点。

在更严格的一些环境下，比如专门用于数据交换的 XML 格式解析里，是可以设置更严格的检查的。
