### ISSUE TITLE
第一章环境配置安装 scoop 问题

### ISSUE THREAD

**Issue by huangchangling800** [neolee/wop-community#301]
安装SCOOP是输入代码后，出现如下报错
![image](https://user-images.githubusercontent.com/61343620/99872018-a5a83180-2c19-11eb-8414-c33f2b5d31cb.png)

**Comment by neolee** [comment]
网络问题。

**Comment by huangchangling800** [comment]
> 网络问题。

那这种情况怎么解决呢？是不是需要翻墙？

**Comment by neolee** [comment]
换网络、换时间再试，或者试试网络代理。

另外，有没有仔细读过主页 https://github.com/neolee/wop-community/ 尤其是最下面的提示，有不少网络问题可以通过最下面那个指引操作来解决。
