### ISSUE TITLE
mysql 密码重置问题

### ISSUE THREAD

**Issue by wang-yulin** [neolee/wop-community#303]
mysql密码丢失。为了重置密码，我查找资料显示第一步需要关闭mysql服务，第二步是禁止安全密码验证（sudo /usr/local/mysql/bin/mysqld_safe --skip-grant-tables）。

但现在的情况是，第一步关闭服务就出现了问题。按照如下步骤成功操作后的10秒钟左右，又有新的进程运行。在连续kill两次过后，依然还是这个问题。

按照如下命令操作尝试停止mysql服务
`sudo /usr/local/opt/mysql@5.7/support-files/mysql.server stop`
出现如下错误：
` ERROR! MySQL server PID file could not be found!`
为解决这个问题，在命令行输入以下命令：
`ps -auaaron | grep -i mysql`
显示如下信息：
`  501  8269 ??         0:00.02 /bin/sh /usr/local/opt/mysql@5.7/bin/mysqld_safe --datadir=/usr/local/var/mysql
  501  8356 ??         0:00.30 /usr/local/opt/mysql@5.7/bin/mysqld --basedir=/usr/local/opt/mysql@5.7 --datadir=/usr/local/var/mysql --plugin-dir=/usr/local/opt/mysql@5.7/lib/plugin --log-error=AarondeMacBook-Pro.local.err --pid-file=AarondeMacBook-Pro.local.pid
  501  8377 ttys002    0:00.00 grep -i mysql`
为关闭这个进程，在命令行输入以下命令：
`kill -9 8269`
显示如下信息
` 501  8453 ttys002    0:00.00 grep -i mysql`

请问下运行的mysql进程要怎么样才能关闭呢？或者说是否还有更好的思路，在不需要关闭mysql进程的情况下也能重置密码？（我的电脑是macOS Catalina 版本10.15.7。mysql是按照课程教程进行安装配置的。）

**Comment by neolee** [comment]
如果是按照教程安装配置的，那么你的 mysql 应该是通过 Homebrew 安装的，那么停止服务的正确方式是：

```
brew services stop mysql@5.7
```

**Comment by wang-yulin** [comment]
谢谢老师，按照上面操作搞定了
