### ISSUE TITLE
iOS 开发

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#305]
看了老师在B站上的**移动开发之iOS篇**，老师讲这堂课主要是感性地认识一下。如果想真的开发一款iOS的app，老师从过来人的经验，有没有推荐的课程，或者适合初学者的具体学习路线。

**Comment by neolee** [comment]
Stanford 的课程：

https://cs193p.sites.stanford.edu/

**Comment by gaoteng-pro** [comment]
👍
