### ISSUE TITLE
SVM线性可分的疑问

### ISSUE THREAD

**Issue by wang-yulin** [neolee/wop-community#309]
SVM在处理非线性数据的时候，为什么一定升维去寻找线性的超平面呢？像下面这种数据直接找一个圆来做边界不行吗？我Google了一番几乎都没有找到好的答案，还请老师给点提示呢。
<img width="586" alt="截屏2021-01-18 下午9 18 50" src="https://user-images.githubusercontent.com/46066978/104920497-d4047c00-59d2-11eb-9b6f-2e312bd1cf3a.png">

**Comment by tyler1zhang** [comment]
线性是指平面中的直线。在上面的分类中，你无法通过一条直线将两类点分开。 假想一下，如果图中所有的点都是在一个三维空间，并且橙色的点的高度和蓝色的点的高度不同，这时候你是有机会通过一个`平面`分割两种点的。
