### ISSUE TITLE
无法进入 jupyter lab

### ISSUE THREAD

**Issue by cunzai2020** [neolee/wop-community#310]
![jupyter lab](https://user-images.githubusercontent.com/67787893/116184163-cee16680-a751-11eb-8ce8-b32085be3e3d.png)
jupyter lab在升级一次系统之后就不能运行了，也重新卸载和安装jupyter lab 程序，但依然不行。

**Comment by neolee** [comment]
从出错信息看是没装好，Jupyter Lab 是个大应用，需要好多 Python 包配合才能工作起来，只卸载重装 jupyterlab 这个包可能是不够的。

有个工具 `pip-autoremove` 可以简化这件事：
```shell
pip install pip-autoremove
pip-autoremove jupyterlab -y
pip install jupyterlab
```

注意，如果在执行这些操作的过程中有任何出错信息，要仔细看，可能暗含的问题。

**Comment by cunzai2020** [comment]
谢谢李老师，我尝试一下。
