### ISSUE TITLE
如何了解自己的电脑

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-community#311]
老师你好！

事情是这样的：昨天，我昨天在晚上在网页上搜索下载了wegame
下载的是一个包，我“正常”下载，因为知道注意下载的时候要注意它的对勾不能点，所以觉得应该没什么。
但随后，电脑就被流氓软件给劫持了：2345网站成了我的chrome首选的页面，然后还有奇奇怪怪的应用，什么贪玩蓝月，，，

我手机用的是ios的，感觉不存在这样子的软件，用起来很有把握。但是，电脑是windows就很没有把握，比如当初配置环境一节中，修改host来访问GitHub，我就觉得十分陌生，不敢相信：在这个文本文件中粘贴几个网站就能改变我的电脑访问某些网站的效果。
诸如这样的知识，在网上有看到过一些相关信息，但是还是想问问老师，有没有推荐的课程或者书籍可以对自己计算机更加，了解有把握。

**Comment by tyler1zhang** [comment]
首先你能登陆google，我假设你可以登陆所有的正常网站。那么你应该去官方网站下载wegame， `https://www.wegame.com.cn/store`
其次，你到了一个其他的网页，点了一个下载按钮，但是你并不清楚这个下载按钮对应下载和运行了什么。由于windows的市场占有率很高，所以大部分的恶意网页程序是写给windows的，Mac不容易中招。但是如果你去了一个Mac打开概率比较高的网站（cleanmymac盗版下载）那也会一样中招。 
其他的部分可能就需要老师回答了。
