### ISSUE TITLE
postgresql远程无法连接

### ISSUE THREAD

**Issue by wang-yulin** [neolee/wop-community#313]
操作系统：CentOS  7.6 64位
数据库版本：postgresql12

按照Google出来的信息，做了如下配置：
/var/lib/pgsql/12/data/pg_hba.conf
`host    all             all             0.0.0.0/0               md5`

/var/lib/pgsql/12/data/postgresql.conf
`#listen_addresses = '*'          `

执行命令：
`# sudo firewall-cmd --add-service=postgresql --permanent`
输出：
success
执行命令：
`# sudo firewall-cmd --reload`
输出：
success

确认数据库处于Active状态
执行命令：
`# systemctl status postgresql-12.service`
输出：
`● postgresql-12.service - PostgreSQL 12 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-12.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2021-06-25 20:43:16 CST; 13s ago`

确认服务器可以正常链接
执行命令：
`ping 182.92.74.231`
输出：
`PING 182.92.74.231 (182.92.74.231): 56 data bytes
64 bytes from 182.92.74.231: icmp_seq=0 ttl=53 time=31.831 ms
64 bytes from 182.92.74.231: icmp_seq=1 ttl=53 time=37.914 ms
64 bytes from 182.92.74.231: icmp_seq=2 ttl=53 time=31.057 ms
^C
--- 182.92.74.231 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 31.057/33.601/37.914/3.066 ms`

经过如上配置及检查，在本地terminal执行如下命令时，显示连接错误
执行命令：
`psql -U postgres -h 182.92.74.231`
输出：
`psql: error: could not connect to server: could not connect to server: Connection refused
	Is the server running on host "182.92.74.231" and accepting
	TCP/IP connections on port 5432?`

请问下如上配置是否还有遗漏的地方？接下来还需检查哪些地方并进行修改以确保能够远程连接数据库？

**Comment by neolee** [comment]
conf 里那句有删掉行首的 `#` 以启用设置吗？

**Comment by wang-yulin** [comment]
还真是，没有删除首行的`#`，删除后重新启动就连接上了，谢谢老师～
