### ISSUE TITLE
如何确定文件使用后，如何确认是否被合适的方式close

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/wop-community#314]
请问老师，我看到很多人写了下面的code
`pickle.dump(model, open(file_path, ‘wb’))`
程序运行完这一行之后，感觉这个file并没有被close。但是又不知道如何去确认。

如果改成如下方式，就可以确认了：
```python
f = open(file_path, 'wb')
pickle.dump(model, f)
print(f.closed)
# output is False, the file was not closed!

f.close()
print(f.closed)
# output is True
```

**Comment by iamjinlei0312** [comment]
你看这样写可以不
```python
with open(file_path, 'wb') as f:
       pickle.dump(model, f)
```

或这样：

```python

f = open('test.txt', 'w')
try:
    f.write('hello')
finally:
    f.close()

````

**Comment by tyler1zhang** [comment]
我没把问题写清楚：
如何确认一个file有没有被内存占用着，特别是当这个file没有对应的变量名字的时候。

**Comment by iamjinlei0312** [comment]
一些不错的参考资料：

1、[Memory Management in Python](https://realpython.com/python-memory-management/)

2、[Memory Management in Python](https://towardsdatascience.com/memory-management-in-python-6bea0c8aecc9)

3、[An Overview of Python Memory Management](https://www.analyticsvidhya.com/blog/2021/04/an-overview-of-python-memory-management/)

1和2是两篇不同的文章，只是标题相同，我这里是直接贴的原文的标题。

**Comment by neolee** [comment]
Python 会自动使用“引用计数”来管理打开的文件，如果打开的文件没有被任何变量引用，也没有正在被操作，Python 会自动关闭该文件。

不过对初学者来说最好自己手动关闭文件，楼上同学已有正确的例子。
