### ISSUE TITLE
实例化时提示无效的语法 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#316]
<img width="1440" alt="Screen Shot 2021-09-13 at 23 46 22" src="https://user-images.githubusercontent.com/63906805/133115545-4be75192-c4ea-4e3e-a076-17b583e82355.png">

**Comment by neolee** [comment]
这种一般都是出错的代码之前的代码有问题。

**Comment by Sincere-io** [comment]
是我没好好检查，谢谢李骏老师。
