### ISSUE TITLE
安装pandas遇到的问题

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#319]
<img width="990" alt="Screen Shot 2021-12-24 at 18 08 40" src="https://user-images.githubusercontent.com/63906805/147343530-51ccb48a-5810-4f74-820d-30786b9fbefe.png">

**Comment by neolee** [comment]
试试用国内的镜像，比如清华的开源镜像站，搜索下这里，以前贴过。

**Comment by Sincere-io** [comment]
好的，老师，我先去试

**Comment by Sincere-io** [comment]
> 试试用国内的镜像，比如清华的开源镜像站，搜索下这里，以前贴过。

好的，老师，我先去试。

**Comment by Sincere-io** [comment]
> 试试用国内的镜像，比如清华的开源镜像站，搜索下这里，以前贴过。

<img width="381" alt="Screen Shot 2021-12-24 at 21 46 36" src="https://user-images.githubusercontent.com/63906805/147356943-100f2ff8-72ec-4f8b-aa81-273f85020272.png">
<img width="546" alt="Screen Shot 2021-12-24 at 21 49 02" src="https://user-images.githubusercontent.com/63906805/147357072-6cd70216-f4a8-4ad5-8adc-8498335283a4.png">
老师，好像是没有权限，我不知道这里该怎么做了...

**Comment by neolee** [comment]
看这个啊：

https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

**Comment by Sincere-io** [comment]
> 看这个啊：
> 
> https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

<img width="567" alt="Screen Shot 2021-12-24 at 22 11 19" src="https://user-images.githubusercontent.com/63906805/147358240-d0264017-a09a-46c7-83f5-58fe65bb4d25.png">
老师，回到第一个截图的问题了...

**Comment by Sincere-io** [comment]
> 看这个啊：
> 
> https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

<img width="423" alt="Screen Shot 2021-12-24 at 23 10 00" src="https://user-images.githubusercontent.com/63906805/147361266-76fff508-8afc-42a2-8151-911f91c129ee.png">
成功了，谢谢老师！
