### ISSUE TITLE
是否需要使用 Conda？

### ISSUE THREAD

**Issue by shen-huang** [neolee/wop-community#320]
在课程里，JupyterLab 是直接用 pip 装在全局了，
而在笑来老师的手册里，他建议用 Conda 建立个虚拟环境再在里面用 JupterLab。
新手是否有必要使用 Conda？

**Comment by neolee** [comment]
建立虚拟环境用 virtualenv，这部分我课上没讲。

Conda 是 pip 的替代品，有自己的一套包管理体系，可以用，也可以不用，看你自己了。
