### ISSUE TITLE
mac os Mysql 数据导入出错

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#322]
<img width="732" alt="Screen Shot 2022-01-04 at 22 55 55" src="https://user-images.githubusercontent.com/63906805/148077921-db9710be-73a0-488f-bbd7-188e083a62a2.png">

<img width="530" alt="Screen Shot 2022-01-04 at 22 50 16" src="https://user-images.githubusercontent.com/63906805/148077261-908ffdde-3000-4675-b7db-6a16ea3bfabb.png">
按照Mysql配置指南，选择 Create new table，下拉框里选择数据库 demo，表名输入 players，点击 Next >；

**Comment by neolee** [comment]
从信息看是编码问题，你的 CSV 文件是 utf-8 编码，而数据库引擎是 ascii，这个有点奇怪，因为 MySQL 早就用 utf8 做缺省的引擎编码了，你可以搜一下如何改数据库的编码。

**Comment by Sincere-io** [comment]
<img width="632" alt="Screen Shot 2022-01-05 at 21 53 45" src="https://user-images.githubusercontent.com/63906805/148232423-5ab34750-1cad-44f4-a66f-0b26a8256c93.png">
老师，我查看了编码格式，不知道哪里出了问题。

**Comment by Sincere-io** [comment]
> 从信息看是编码问题，你的 CSV 文件是 utf-8 编码，而数据库引擎是 ascii，这个有点奇怪，因为 MySQL 早就用 utf8 做缺省的引擎编码了，你可以搜一下如何改数据库的编码。



> <img alt="Screen Shot 2022-01-05 at 21 53 45" width="632" src="https://user-images.githubusercontent.com/63906805/148232423-5ab34750-1cad-44f4-a66f-0b26a8256c93.png">
> 
> 老师，我查看了编码格式，不知道哪里出了问题。

**Comment by Sincere-io** [comment]
> 从信息看是编码问题，你的 CSV 文件是 utf-8 编码，而数据库引擎是 ascii，这个有点奇怪，因为 MySQL 早就用 utf8 做缺省的引擎编码了，你可以搜一下如何改数据库的编码。
<img width="1028" alt="Screen Shot 2022-01-13 at 21 05 33" src="https://user-images.githubusercontent.com/63906805/149522276-15274932-413e-40d1-ab06-0eceb7d96d09.png">
<img width="256" alt="Screen Shot 2022-01-13 at 21 16 28" src="https://user-images.githubusercontent.com/63906805/149522302-74d46190-ecaa-4b2a-8fed-ed5969ce2de7.png">

我尝试Google，依旧没有解决...

**Comment by neolee** [comment]
你至少要把你的 MySQL、MySQLWorkbench 版本、如何安装的、在 mysql 命令行上操作的情况、导入的是什么文件等信息说下吧，现在就这么点信息，想帮也帮不到哇……

**Comment by Sincere-io** [comment]
> 你至少要把你的 MySQL、MySQLWorkbench 版本、如何安装的、在 mysql 命令行上操作的情况、导入的是什么文件等信息说下吧，现在就这么点信息，想帮也帮不到哇……

抱歉老师，是这样的，我按照老师[仓库](https://github.com/neolee/pilot/blob/c89bab64df97045a02d4a63b875c0ab3a6f51762/x5-mysql-setup.ipynb)首页附录中MySQL配置指南进行配置，mysql 命令行上操作的情况与配置指南完全一致。
- MySQL版本：`mysql  Ver 14.14 Distrib 5.7.36, for osx10.16 (x86_64) using  EditLine wrapper`
-  MySQL 官方网站下载 [MySQLWorkbench](https://dev.mysql.com/downloads/workbench/)
<img width="820" alt="Screen Shot 2022-01-16 at 22 39 53" src="https://user-images.githubusercontent.com/63906805/149664753-a57e1a58-d02b-4604-a9bc-c8c2d51c2ac7.png">

<img width="867" alt="Screen Shot 2022-01-16 at 22 56 28" src="https://user-images.githubusercontent.com/63906805/149665363-cafec8fb-86fb-4f82-a58e-c9e4b2105c06.png">
<img width="406" alt="Screen Shot 2022-01-16 at 22 57 59" src="https://user-images.githubusercontent.com/63906805/149665372-34035d71-bc17-4693-bcf2-030b2b3d9643.png">

- 我的问题出在这里

<img width="534" alt="Screen Shot 2022-01-16 at 22 58 12" src="https://user-images.githubusercontent.com/63906805/149665382-7b310060-6fad-459e-8a3c-4e02455f92ec.png">

- 我尝试去更改数据库的编码格式，我的编码格式在下图；另外，我不知道是不是编码格式的问题，因为我在打开MySQLWorkbench时，出现过不支持操作系统的提示。
<img width="852" alt="Screen Shot 2022-01-16 at 23 34 48" src="https://user-images.githubusercontent.com/63906805/149666701-eaaebcb1-deed-45e4-8af7-163e4b7c6d49.png">


<img width="561" alt="Screen Shot 2022-01-16 at 22 48 17" src="https://user-images.githubusercontent.com/63906805/149664967-5f9d4f50-6d00-431b-ae28-0185d83ace0b.png">

**Comment by neolee** [comment]
看数据库配置没问题，你的 CSV 文件哪里下的？把链接或者直接把文件发这里，我看看文件本身是不是有问题。

还有你说 Workbench 启动有提示，是什么提示能发出来看看么？要解决问题最需要关注的就是软件给出的各种提示信息，只要看上去不是正常信息，都应该关注。

**Comment by Sincere-io** [comment]
> 看数据库配置没问题，你的 CSV 文件哪里下的？把链接或者直接把文件发这里，我看看文件本身是不是有问题。
> 
> 还有你说 Workbench 启动有提示，是什么提示能发出来看看么？要解决问题最需要关注的就是软件给出的各种提示信息，只要看上去不是正常信息，都应该关注。


[fifa19.csv](https://github.com/neolee/wop-community/files/7889236/fifa19.csv)

<img width="241" alt="Screen Shot 2022-01-18 at 21 06 24" src="https://user-images.githubusercontent.com/63906805/149942865-359eb09c-20fe-44cf-9fa3-ec1301ce7547.png">

**Comment by neolee** [comment]
我的 Mac 下没装 Workbench，所以在 Windows 下测试了你的文件，完全没问题，这个问题很奇怪……

**Comment by hope1324** [comment]
我也碰到这个问题，好几个月没有解决，今天解决了。我是win10系统，mysql-installer-community-8.0.29.0，用旧的版本mysql-workbench-community-8.0.19-winx64解决这个问题了。试了好几个版本，最后用旧版本8.0.19正常了。
