### ISSUE TITLE
html文件缩进错误

### ISSUE THREAD

**Issue by Sincere-io** [neolee/wop-community#324]
- 照着视频代码敲，提示html文件缩进错误，不明白缩进哪里有问题。

<img width="1440" alt="Screen Shot 2022-02-21 at 17 51 03" src="https://user-images.githubusercontent.com/63906805/154930610-302d9008-88a6-41f9-b34b-21e637fb6900.png">

- 点击保存。

<img width="486" alt="Screen Shot 2022-02-21 at 16 50 03" src="https://user-images.githubusercontent.com/63906805/154920152-a18c0fd4-6340-4633-b339-0c37dbe9711c.png">

- 命令行运行`python server.py.`

<img width="849" alt="Screen Shot 2022-02-22 at 17 37 29" src="https://user-images.githubusercontent.com/63906805/155104696-130e1e91-ad85-4686-a6f7-fa1f28c20deb.png">

**Comment by neolee** [comment]
是 Python 的缩进，不是 HTML 的问题，index.html 里 `$if` 后面的段落需要缩进。

**Comment by Sincere-io** [comment]
> 是 Python 的缩进，不是 HTML 的问题，index.html 里 `$if` 后面的段落需要缩进。

老师，我遇到的问题是`index.html`文件按`command + s` 保存之后自动缩进错误了，我没法儿控制...

**Comment by neolee** [comment]
> 老师，我遇到的问题是`index.html`文件按`command + s` 保存之后自动缩进错误了，我没法儿控制...

一般不应该，这应该是某些插件的问题。具体需要你自己研究下了。

**Comment by Sincere-io** [comment]
> > 老师，我遇到的问题是`index.html`文件按`command + s` 保存之后自动缩进错误了，我没法儿控制...
> 
> 一般不应该，这应该是某些插件的问题。具体需要你自己研究下了。

好的，谢谢老师。
