### ISSUE TITLE
应该怎么用python解这道题？

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#325]
![IMG_3123](https://user-images.githubusercontent.com/57254889/211460513-40c969b6-6d18-4fc7-88e7-1538ec4f5093.jpeg)

对这类题很感兴趣，想了很久，不知道如何解答，还希望老师给一下解答方法。

另外：还有类似的可以用python解答的益智类题目吗？从哪里可以找到？

**Comment by neolee** [comment]
这种不是益智题，是数学题。这道题是我的一位前辈也是朋友多年以前为某次小学生奥数比赛出的题 😃

这题用人脑来解比用程序更有趣，不妨多思考下。

**Comment by gaoteng-pro** [comment]
答案是：当第100秒的时候，在B一开始所在的这个位置，BAD三个小球第一次相遇，小球D一共运动了 **1360/3** 厘米吗？答案不零不整的，不知道对不对？竟然是小学生的奥数题，只能说小学生们太强大了。

**Comment by neolee** [comment]
https://github.com/neolee/mathvis-playground/blob/master/apmo.ipynb

我之前研究数学智能评测时做着玩的，亚太小学数学奥林匹克2016年第30题，下面有我写的解题思路。

**Comment by gaoteng-pro** [comment]
![4F99876B-7D22-4778-AE0D-C5CB160FB302](https://user-images.githubusercontent.com/57254889/212246478-83ef6353-6b4a-4c7a-bbc3-2156dcf2746a.jpeg)

对，是**1960/3**厘米。最终的算式（红圈部分）是三个200cm，再往下计算的时候丢了200cm，加上这个200cm就是这个答案。

之所以第一次是在100秒之后的B点三个小球相遇，是因为慢球运动到图中B点所在的这个位置刚好需要100秒，而这个100秒的时间恰巧也等于快慢球相遇时间的整数倍。即 **100 = 200/30 + 400/30 * N** ，这个N=7，也就是快慢球第八次的时候，三个小球相遇。

没有老师计算的简洁，一开始我是一次碰撞记录一次时间，撞了几次，找到点规律后，时间改成了快慢球一次相撞的时间。

根据这道题的启发，我发现用python来解奥数题是个很棒的做法，哈哈，真的用起来python了。

很好奇这道题用python咋解？怎样把这道题转化成计算机理解的语言，进而求解。

**Comment by neolee** [comment]
> 很好奇这道题用python咋解？怎样把这道题转化成计算机理解的语言，进而求解。

个人认为，这题用计算机求解还是需要理顺基本的思路（我上面发的链接里的解题思路第一段），这些理清后很快就可以解出来了，用计算机的意义不大。

另一个思路是直接把题目的表述字面上转换为程序，然后用一个程序模拟实际的运行状态，得到答案，这个方法也许也可行，是常见的计算机求解策略，但我没试过，不知道是不是比较麻烦。

**Comment by gaoteng-pro** [comment]
正在笨拙地尝试用思路二...
