### ISSUE TITLE
通过Visual Studio Code克隆时URL rejected: Bad hostname

### ISSUE THREAD

**Issue by Sirui-Ye** [neolee/wop-community#327]
<img width="440" alt="屏幕截图 2023-10-07 194706" src="https://github.com/neolee/wop-community/assets/147250808/0a58a151-34e7-475b-9811-ff956de7450d">

**Comment by andyhuang18** [comment]
是在输入 `git clone git@github.com:neolee/wop.git` 后报错了吗？首先看看你的ssh有没有配置好，然后检查一下地址有无输入错误，最后是网络状态，github有时候会被防火墙阻挡，可以多尝试几次。
