### ISSUE TITLE
关于init函数的问题

### ISSUE THREAD

**Issue by chunliuZhu** [neolee/wop-community#328]
class Person:
    def __init__(self):
        print("执行")
    def walk(self):
        print("走路")
    def run(self):
        print("跑步")

p=Person
有个帖子说init创建对象时就自动调用init，那为啥没有打印 执行 呢？

**Comment by andyhuang18** [comment]
你好～很感谢提出这个问题，这是一个很有趣的事情。你说的没错，当创建对象时，会自动调用init函数，但是你的init函数在命名上有误，应当用两个下划线包裹，即 `__init__` 。并且在你的代码中，还出现了一个问题，此处的 `p=Person` 仅仅是将Person这个类传递给了p，并非是新建了一个对象Person。正确创建对象应该是 `p=Person()`，你可以尝试修改了init后，在原代码下一行加入 `test=p()` 你会发现test是被新建的，可以触发init。所以，你的代码中 `p=Person` 是给 Person取了一个别称p。

你可以分别尝试以下代码：
```python
class Person:
    def __init__(self):
        print("执行")
    def walk(self):
        print("走路")
    def run(self):
        print("跑步")

p=Person()
```

和
```python
class Person:
    def __init__(self):
        print("执行")
    def walk(self):
        print("走路")
    def run(self):
        print("跑步")

p=Person
test=p()
```
另外，由于python是缩进敏感的，因此在贴出代码时，可以用\`\`\`包裹你的代码，这样子代码会呈现更细节的格式～

**Comment by chunliuZhu** [comment]
多谢，认识到自己的问题了，应该p=Person改成p=Person()。另，可能就是没用```包裹，所以原来缩进和下划线都有的，贴出来就没了，下回注意
