### ISSUE TITLE
类定义中下划线 `_` 开头的变量问题

### ISSUE THREAD

**Issue by xslikeyou** [neolee/wop-community#329]
老师，我们p1-9-oo-3课件里说：“将类定义中所有下划线 `_` 开头的变量和方法作为“内部”变量和方法来看待，也就是说这些变量和方法属于类的内部实现的一部分，随时可能改变，外部最好不要依赖于这些变量和方法。所以 Python 虽然没有提供强制受限的“私有成员”，但还是遵循了“接口与实现分离”的思维模式，我们在定义一个类的时候，如果有不希望外部直接使用的变量和方法，可以在其名字前加一个下划线 `_`”
我以为加了`_`的变量相当于C/C++里面的protected属性变量。但我写了下面的代码试验发现好像`_ name`在类外面无法直接访问，也不能通过类接口访问，而且课件说`_name`变量随时可能改变（怎么改变呢？）。难道只能在类里面直接改动`_name`的值？那`_name`这种`_`开头的变量还有什么用呢？
```
class Cat:
    _name='none_name'
    color='black'
    age=10
    
    def __init__(self,age) :
        self.age=age
    def getName():
        return self._name
    def setName(name):
        self._name=name


mimi=Cat(18)
print(f' age:{mimi.age}')
print(f' 直接访问name:{mini._name}')
print(f'通过类接口访问name:{mimi.getName()}')
mimi.setName('xiaomao')
```

**Comment by neolee** [comment]
教材中“随时可能改变”的意思是，这个变量的名字和含义和用途都可能变化，它不是这个类正式对外公布的 **接口**（*interface*），仅供类定义内部使用，简单说，就是外面别用它。
