### ISSUE TITLE
关于pip不能使用的问题

### ISSUE THREAD

**Issue by CYN-carol** [neolee/wop-community#330]
![issue-pip未见](https://github.com/neolee/wop-community/assets/147830917/e22514d6-4541-4a59-8693-b405f80e9765)

**Comment by CYN-carol** [comment]
https://blog.csdn.net/du_lollipop/article/details/105849470
尝试了以上方法可以解决

**Comment by neolee** [comment]
> https://blog.csdn.net/du_lollipop/article/details/105849470 尝试了以上方法可以解决

看来这是之前用Anaconda装过Python、后来又按照课程要求安装了官方Python包的环境容易出现的问题。

其他遇到类似问题的同学可以参考。

**Comment by TristanQian** [comment]
老师，我也遇到了相同的问题，试过重装python和VS Code，也没解决这个问题；按链接里的解决方法，未找到安装目录下的Scripts文件夹；想问下，还有其他方法吗？

**Comment by TristanQian** [comment]
已解决。
求教助教黄老师，判断是没把python添加到环境变量中。
以下链接是关于怎么把python添加到环境变量中：https://pythonjishu.com/path-add-python/
成功截图如下：
![Pip成功截图](https://github.com/neolee/wop-community/assets/105917992/4d1589f2-f454-4492-8ffb-c0324800b6d9)
