### ISSUE TITLE
关于pip不能使用的问题

### ISSUE THREAD

**Issue by qiyiyaz** [neolee/wop-community#332]
PS C:\Users\Lenovo\Desktop\微专业\Working> powershell
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS C:\Users\Lenovo\Desktop\微专业\Working> Get-Command python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         0.0.0.0    C:\Users\Lenovo\AppData\Local... 

PS C:\Users\Lenovo\Desktop\微专业\Working> Get-Command python3

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python3.exe                                        0.0.0.0    C:\Users\Lenovo\AppData\Local... 

PS C:\Users\Lenovo\Desktop\微专业\Working> Get-Command pip
Get-Command : 无法将“pip”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，
请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Get-Command pip
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

PS C:\Users\Lenovo\Desktop\微专业\Working> Get-Command pip3
Get-Command : 无法将“pip3”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径
，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Get-Command pip3
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pip3:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

PS C:\Users\Lenovo\Desktop\微专业\Working> python -V
PS C:\Users\Lenovo\Desktop\微专业\Working> python3 -V
PS C:\Users\Lenovo\Desktop\微专业\Working> pip -V
pip : 无法将“pip”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路
径正确，然后再试一次。
所在位置 行:1 字符: 1
+ pip -V
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Lenovo\Desktop\微专业\Working> pip3 -V
pip3 : 无法将“pip3”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保
路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ pip3 -V
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pip3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by andyhuang18** [comment]
这样的情况应该是pip 无效了，我觉得可以重新安装一下python
