### ISSUE TITLE
类定义中def 某函数(self, s)中s的作用

### ISSUE THREAD

**Issue by Sirui-Ye** [neolee/wop-community#333]
以此代码为例：
```python
def _format(self, s):
        return colored(s, 'blue')
```

如果我将它改为：
```python
def _format(self):
        return colored(self, 'blue')
```

在第一次运行的时候没有任何差别，但当第二次运行就会出现如下报错：
TypeError: Bot._format() takes 1 positional argument but 2 were given
经查询了解到是python认为我给def函数传了两个参数的意思（第二次运行的时候就是第二个参数）

所以我是否可以理解为s其实是self变量每一次运行的“临时变量”而并非是像name/age之类的参数？

**Comment by andyhuang18** [comment]
你说的对，对于第一个方法 _format(self, s)，s 不是类似于name 或 age 这样的实例属性，而是一个局部变量，它接受调用该方法时传递的字符串作为值。可以将其理解为一个临时变量，用于存储方法调用时传递的字符串。这样，可以在每次调用方法时传递不同的字符串，并对每个字符串进行蓝色渲染。

**Comment by neolee** [comment]
第三周的课程里有专门讲 `self` 的含义，以及 `self` 后面的参数如何使用的问题，你可以重读 [教材第四章](https://github.com/neolee/wop/blob/master/p1-9-oo-3.ipynb) 来尝试理解。

如果还有不明白的地方，今天下午早点到教室问我。
