### ISSUE TITLE
重装Python后VSCode中的源代码没有语法高亮显示

### ISSUE THREAD

**Issue by qiyiyaz** [neolee/wop-community#334]

**Comment by neolee** [comment]
你好歹多说两句或者给个截图啊？问问题之前先好好读读我们的 [指南](https://github.com/neolee/wop-community/blob/master/README.md) 吧！

**Comment by qiyiyaz** [comment]
不好意思老师，校外网站登录不上去无法发送图片。我邮件回复您可以嘛？图片已放在附件中

--------------原始邮件--------------
发件人："Neo&nbsp;Lee ***@***.***&gt;;
发送时间：2023年10月20日(星期五) 中午12:22
收件人："neolee/wop-community" ***@***.***&gt;;
抄送："高瑾 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [neolee/wop-community] visual studio code在我重装python后打开无颜色区分 (Issue #334)
-----------------------------------

 

 
你好歹多说两句或者给个截图啊？问问题之前先好好读读我们的 指南 吧！

**Comment by qiyiyaz** [comment]
<img width="464" alt="image" src="https://github.com/neolee/wop-community/assets/148410147/bcfd289c-088b-4965-9a31-5afe8033b991">

**Comment by qiyiyaz** [comment]
> 你好歹多说两句或者给个截图啊？问问题之前先好好读读我们的 [指南](https://github.com/neolee/wop-community/blob/master/README.md) 吧！

<img width="450" alt="mmexport1697776162819" src="https://github.com/neolee/wop-community/assets/148410147/c8b538c8-bb88-40e4-9e4f-e0c5767596cc">

**Comment by neolee** [comment]
没有语法高亮，检查下VSCode中 `Python` `Pylance` 和 `Jupyter` 三个插件是否正确安装，需要的话可以重装下这几个插件。

p.s. 截图要截全，整个VSCode窗口截下来，很多地方藏着你不知道的细节，但我能看到。

**Comment by qiyiyaz** [comment]
> 没有语法高亮，检查下VSCode中 `Python` `Pylance` 和 `Jupyter` 三个插件是否正确安装，需要的话可以重装下这几个插件。
> 
> p.s. 截图要截全，整个VSCode窗口截下来，很多地方藏着你不知道的细节，但我能看到。

<img width="960" alt="62aa37a3303e016cd8c7fc779ac95af" src="https://github.com/neolee/wop-community/assets/148410147/bcb56937-ebcc-4fad-8ffe-620cc1aa609a">
重装后还是原样

**Comment by qiyiyaz** [comment]
已解决，重装VScode
