### ISSUE TITLE
出现语法错误SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qiyiyaz** [neolee/wop-community#335]
运行的是老师的模版代码出现了以下报错。是因为开头的termcolor和simpleeval吗？但是不明白该怎么解决
<img width="959" alt="image" src="https://github.com/neolee/wop-community/assets/148410147/cb641207-dd26-4243-aa32-3fdefe335b98">

**Comment by neolee** [comment]
你需要在PowerShell的命令行运行 `python xxx.py` 命令，而不是在Python解释器中。

看你的命令行窗口右边那一排，选 `pwsh`，不要选其他那俩。
