### ISSUE TITLE
计算机输出值出现奇怪前缀与后缀

### ISSUE THREAD

**Issue by Crystina256** [neolee/wop-community#337]
使用.\文件名.py运行文件后，计算机输出部分在前面出现□36m，在后面出现□0m
![image](https://github.com/neolee/wop-community/assets/148602557/a61cada8-23b9-4cc0-a766-a1a556c62d03)

**Comment by neolee** [comment]
这些前后缀就是在命令行给文字上颜色的魔法，但你用的这个终端（Python自带那个吧）不支持该魔法，所以我不建议用这个，你应该安装PowerShell，并在PowerShell中运行程序。
