### ISSUE TITLE
在命令行执行 pip install jupyterlab 或 pip3 install jupyterlab 时报错

### ISSUE THREAD

**Issue by azheng526** [neolee/wop-community#34]
win10系统，已正常安装了scoop、git、python37（3.7.5）

提示是： 无法将“jupyter”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。
请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1

**Comment by azheng526** [comment]
问题会是python版本的问题吗？

**Comment by neolee** [comment]
你的标题里说 “在命令行执行 pip install jupyterlab 或 pip3 install jupyterlab 时报错”，报什么错？应该不是你正文里说的错误吧，那个错误和前述命令完全没关系。

**Comment by azheng526** [comment]
对不起，我的描述不准确。是在进行安装jupyterlab时输入pip install jupyterlab执行后出现的提示。

**Comment by neolee** [comment]
我确认下，你输入 `pip install jupyterlab` 然后出错是 `无法将“jupyter”项识别为 cmdlet、函数、脚本文件或可运行程序的名称`？

这不可能，最好截图给我看看。

**Comment by azheng526** [comment]
![批注 2020-07-04 233608](https://user-images.githubusercontent.com/50059311/86515977-a8afaa80-be4f-11ea-9df5-b11ae33fa2ae.png)

下面是我之前的安装情况
![批注 2020-07-04 233500](https://user-images.githubusercontent.com/50059311/86515995-bf560180-be4f-11ea-8de2-77646dbf7d60.png)

**Comment by neolee** [comment]
对嘛，所以说的是不认识 pip 这个命令，而非 jupyter。

但这个也很奇怪，理论上你装好 Python 就会有 python 和 pip 这些命令可用。

首先，先重启一次 Windows，然后再试试 `pip install jupyterlab`，如果还是有问题，运行下面这些诊断命令看看：

```powershell
$env:Path
which python
which pip
python -V
pip -V
```

**Comment by azheng526** [comment]
![win重启后](https://user-images.githubusercontent.com/50059311/86516252-9fbfd880-be51-11ea-8672-948a13785177.png)

重启后还是报那个错，按照老师给的步骤进行到pip-v又报错了。会是python版本的问题吗？

**Comment by neolee** [comment]
和 Python 版本关系不大，但你安装 Python 的时候很可能除了一些错误，导致 pip 没装上。

可以手动安装 pip，使用下面的命令：

```powershell
python -m ensurepip
```

**Comment by azheng526** [comment]
![批注 2020-07-05 024530](https://user-images.githubusercontent.com/50059311/86519119-457f4180-be6a-11ea-8ace-a4f6eeffb8f1.png)

**Comment by neolee** [comment]
使用 `python -m pip install jupyterlab` 如何呢？

**Comment by azheng526** [comment]
李老师早上好，我理解这样是安装好了，但我之后运行pip -V（检查pip版本时）又报无法识别pip了
![批注 2020-07-05 090031](https://user-images.githubusercontent.com/50059311/86523443-1505ca80-be9f-11ea-8163-716119dc2e88.png)

**Comment by zed-wong** [comment]
> 李老师早上好，我理解这样是安装好了，但我之后运行pip -V（检查pip版本时）又报无法识别pip了
> ![批注 2020-07-05 090031](https://user-images.githubusercontent.com/50059311/86523443-1505ca80-be9f-11ea-8163-716119dc2e88.png)
> 

这个是因为pip没有被加到环境变量中而导致的，直接用`python -m pip `是一样的效果。
如果你想解决，可以搜“如何添加环境变量”

**Comment by neolee** [comment]
由于某种原因，你的 pip 命令系统识别不出来（可能是上面同学说的 PATH 环境变量问题也可能有别的问题），用 `python -m pip install xxxx` 可以起到一样的效果，你就先用这个方式吧。

**Comment by azheng526** [comment]
![批注 2020-07-05 123631](https://user-images.githubusercontent.com/50059311/86525726-894f6680-bebd-11ea-8578-33aaac86db74.png)
老师，我试着按照搜来的方法 新增PATH环境变量，不知这个路径对不对？

**Comment by neolee** [comment]
你要看看你的 pip 在哪里啊，在我的 Windows 机器上，Path 里需要有这么个路径：`C:\Users\<你的用户名>\scoop\apps\python37\current\scripts`，你可以参考下。

**Comment by azheng526** [comment]
在系统中新增了一个Path变量并重启之后，这回好像真的成功了，请您帮我确认一下还有啥问题没？

![批注
![批注 2020-07-05 131206](https://user-images.githubusercontent.com/50059311/86526039-72ab0e80-bec1-11ea-8347-8b20620bc2d7.png)
 2020-07-05 130843](https://user-images.githubusercontent.com/50059311/86525999-e00a6f80-bec0-11ea-920b-5d9f2d814bd5.png)

**Comment by azheng526** [comment]
![批注 2020-07-05 131206](https://user-images.githubusercontent.com/50059311/86526190-324c9000-bec3-11ea-8051-6a5e19a3fc57.png)

**Comment by neolee** [comment]
看上去是没问题了。

**Comment by azheng526** [comment]
问题总结分析：系统中“pip”未被加入“path环境变量”导致以及有可能在安装python时有某些组件未被安装到位；
谢谢李老师和who3m1同学：）

**Comment by tyler1zhang** [comment]
> ![win重启后](https://user-images.githubusercontent.com/50059311/86516252-9fbfd880-be51-11ea-8672-948a13785177.png)
> 
> 重启后还是报那个错，按照老师给的步骤进行到pip-v又报错了。会是python版本的问题吗？

请问，为什么这位同学运行 `which python` 的时候出现的path是 `C:/Users/LZ/scoop/shims/python.exe`， 而问题最终解决所添加的path是 `C:/Users/LZ/scoop/apps/python37/current/scripts` (请忽略 `/` 和 `\`的不同）?

如果添加的是`C:/Users/LZ/scoop/shims` 可以解决问题么？

**Comment by neolee** [comment]
@tyler1zhang 因为他遇到的问题是 pip 找不到，pip 并不在 shims 那个目录下，而在 Python 自己的 scripts 目录下。
