### ISSUE TITLE
运行pip install Github出现报错

### ISSUE THREAD

**Issue by qiyiyaz** [neolee/wop-community#341]
<img width="960" alt="image" src="https://github.com/neolee/wop-community/assets/148410147/f41e5ce8-2f8e-443e-8517-0eabef962354">

**Comment by andyhuang18** [comment]
可以先执行`pip install --upgrade pip` 。这里的报错似乎是因为有一个子进程，所以可以重新关闭终端，保证没有别的进程的情况下，再试一试。

**Comment by qiyiyaz** [comment]
> pip install --upgrade pip

<img width="960" alt="image" src="https://github.com/neolee/wop-community/assets/148410147/57b16ff9-06eb-44cc-85be-0f53ade94ba3">
还是未能解决

**Comment by andyhuang18** [comment]
你用的是python3.12的版本，不确定github这个库是否兼容，可以考虑换一个版本，或者到计算机教室机器上试一下。

**Comment by qiyiyaz** [comment]
> 你用的是python3.12的版本，不确定github这个库是否兼容，可以考虑换一个版本，或者到计算机教室机器上试一下。

老师我解决了，运行的pip install PyGithub而不是pip install Github
