### ISSUE TITLE
Mac 无法打开 Visual Studio Code

### ISSUE THREAD

**Issue by hqq922** [neolee/wop-community#35]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/67837404/86517912-67bf9200-be5f-11ea-8b00-d156a4332007.png">

**Comment by neolee** [comment]
你做了什么出现这个画面？

**Comment by hqq922** [comment]
按照课程配套资源装完python3.7.7以后下载Visual Studio Code 拖到application然后出现这个界面无法进行下一步的安装动作

**Comment by hqq922** [comment]
很奇怪的是之前能打开vscode，现在无法打开了，之前是卡在了这一步#code.#，如下
<img width="791" alt="image" src="https://user-images.githubusercontent.com/67837404/86526249-4e046600-bec4-11ea-820b-74c9c1fa3d7c.png">
所以就不敢再往下完成学习环境的安装了

**Comment by neolee** [comment]
你下载了 Visual Studio Code.app，把它拖到 /Applications 下，然后在 /Applications 下面找到 Visual Studio Code，双击——然后出现什么？绝对不可能直接出你截图的东西。

**Comment by hqq922** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/67837404/86526901-303aff00-becc-11ea-902c-8b45891771e5.png">
这里总显示找不到code.

**Comment by neolee** [comment]
你后面这个问题是 `code` 和 `.` 之间需要个空格……去看看支线课程，理解 `code .` 是啥意思吧。

但这个问题和你主楼的问题不是一码事，那你现在从 /Applications 里能正常启动 Visual Studio Code 么？在里面配置安装了 code 命令么？

**Comment by hqq922** [comment]
好的，老师，mac无法打开Visual Studio Code的问题已经解决了，问题是出在我没有成功的把下载的Visual Studio Code拖到/Applications 下，目前已解决，今天去把支线课程看了恶补一下，谢谢老师。
