### ISSUE TITLE
Python 安装相关问题

### ISSUE THREAD

**Issue by SZZ0722** [neolee/wop-community#36]
![image](https://user-images.githubusercontent.com/67678671/86523151-b4748e80-be9a-11ea-9886-3c6e87f3a9ae.png)

![image](https://user-images.githubusercontent.com/67678671/86523168-06b5af80-be9b-11ea-8760-0f5aad37c7a7.png)
![image](https://user-images.githubusercontent.com/67678671/86523172-264cd800-be9b-11ea-89e6-c9b49b4b2c33.png)
按老师给的链接下载PYTHON安装包，安装好后，运行PYTHON-V命令出现以上情况
![image](https://user-images.githubusercontent.com/67678671/86523187-6ad87380-be9b-11ea-9f6c-d6bb6ad86580.png)
进入python,如上图
请问老师我的python 安装出了什么问题

**Comment by SZZ0722** [comment]
![image](https://user-images.githubusercontent.com/67678671/86523234-fd791280-be9b-11ea-8556-2e8df81fd8f4.png)
但是运行cmd,python能显示相关信息，

**Comment by neolee** [comment]
你应该在 Windows Terminal 中运行 `python -V` 命令，你前面出错的原因是命令输错了，中间漏了个空格！

好好想想我昨天讲课里说的……

**Comment by SZZ0722** [comment]
老师，你好，昨晚直播到后面就有点跟不上了，今早回看直播到106：16还是跟不上，直播讲到运行python代码有三种方法，第一种方法是直接进入解释器，上网百度了下，下图红色箭头所指即为解释器
![image](https://user-images.githubusercontent.com/67678671/86523835-f30f4680-bea4-11ea-87ee-356692ddb812.png)
![image](https://user-images.githubusercontent.com/67678671/86523872-83e62200-bea5-11ea-81d7-ab13fa0d5117.png)
![Uploading image.png…]()
与老师打
开页面显示不一样，且运行python -V后显示如上图
![Uploading image.png…]()

**Comment by SZZ0722** [comment]
老师，昨晚直播到后面就有点跟不上了，今早回看到106：15分时还是跟不上，文中讲到运行python代码有三种方法，第一种方法是直接进入解释器，上网百度了一下，图中红箭头所指即为解释器，但是打开的页面的与老师的不一样

**Comment by SZZ0722** [comment]
老师，昨晚直播到后面就有点跟不上了，今早回看到106：15分时还是跟不上，文中讲到运行python代码有三种方法，第一种方法是直接进入解释器，上网百度了一下，图中红箭头所指即为解释器，但是打开的页面的与老师的不一样
![Uploading image.png…]()

**Comment by SZZ0722** [comment]
老师，昨晚直播到后面就有点跟不上了，今早回看到106：15分时还是跟不上，文中讲到运行python代码有三种方法，第一种方法是直接进入解释器，上网百度了一下，图中红箭头所指即为解释器，但是打开的页面的与老师的不一样
![Uploading image.png…]()

**Comment by SZZ0722** [comment]
老师，昨晚直播到后面就有点跟不上了，今早回看到106：15分时还是跟不上，文中讲到运行python代码有三种方法，第一种方法是直接进入解释器，上网百度了一下，图中红箭头所指即为解释器，但是打开的页面的与老师的不一样

**Comment by SZZ0722** [comment]
![image](https://user-images.githubusercontent.com/67678671/86532159-42cc2d00-befa-11ea-8ee6-004312eccb37.png)
老师，你好，请问MAC OS系统下 的iTerm 对应WINDOWS 下的是不是Windows powershell,这点没弄清的话，您昨晚直播106：12秒我看不懂，运行PYTHON代码的三种方法，第一种是直接进入解释器。

**Comment by neolee** [comment]
macOS 下，iTerm 或 Terminal 相当于 Windows 下的 Windows Terminal 或者 ConEmu；zsh 或 bash 相当于 Windows 下的 PowerShell。

**Comment by SZZ0722** [comment]
谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 晚上8:05
收件人:&nbsp;"neolee/wop-community"<wop-community@noreply.github.com&gt;;
抄送:&nbsp;"天马行空"<308271077@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/wop-community] Python 安装相关问题 (#36)





 
macOS 下，iTerm 或 Terminal 相当于 Windows 下的 Windows Terminal 或者 ConEmu；zsh 或 bash 相当于 Windows 下的 PowerShell。
