### ISSUE TITLE
Scoop 安装报错

### ISSUE THREAD

**Issue by cx123456-cx** [neolee/wop-community#37]
![image](https://user-images.githubusercontent.com/57081376/86523529-7712ff80-bea0-11ea-926f-2ef09a0babdb.png)

**Comment by neolee** [comment]
首页的方法只能解决域名污染的问题，不能解决所有的网络问题，你这个似乎是连 scoop.sh 都无法访问，你可以试试能不能在浏览器里打开 get.scoop.sh 这个网站。

如果不能，可能你需要使用代理，或者暂时放弃 Scoop，直接去 Python 官网下载和安装 Python 3.7.4。

**Comment by zjh127** [comment]
我安装Scoop时也遇到同样问题，无法访问get.scoop.sh这个网站，怎么使用代理呢？
