### ISSUE TITLE
不能安装 Python 3.7.4 版本

### ISSUE THREAD

**Issue by ccaaxx77** [neolee/wop-community#38]
Scoop安装成功，安装python3.7.4版本，提示没有这个版本，在scoop里面搜索python软件包没有老师示范那么多，请问是哪里出了问题？
![图片](https://user-images.githubusercontent.com/67846779/86524009-6619bc80-bea7-11ea-83aa-644cac9a54cf.png)
![图片](https://user-images.githubusercontent.com/67846779/86524010-6c0f9d80-bea7-11ea-873a-4ea33ea0fa53.png)

**Comment by ccaaxx77** [comment]
手动安装的python3.7.4版本，解决问题。

**Comment by neolee** [comment]
虽然你自己解决了，但我要说，你没有认真的读配置指南。

<img width="572" alt="Install" src="https://user-images.githubusercontent.com/24796/86525164-1098dc00-beb6-11ea-81fe-51627239162e.png">
