### ISSUE TITLE
安装 Scoop 时遇到的问题

### ISSUE THREAD

**Issue by ly0721** [neolee/wop-community#39]
scoop安装时网络有问题按照老师的步骤已将hosts文件修改保存后，也更新了DNS缓存后安装scoopp命令后还是提示
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRe
   quest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft
   .PowerShell.Commands.InvokeWebRequestCommand

![微信图片_20200705115411](https://user-images.githubusercontent.com/67821088/86525213-d7ad3700-beb6-11ea-8649-5a8eb527fda6.jpg)
![微信图片_20200705115725](https://user-images.githubusercontent.com/67821088/86525215-e0057200-beb6-11ea-901d-26c815e18f9a.jpg)

**Comment by neolee** [comment]
你的 VS Code 里打开的 hosts 文件标签上有个小圆点，这就表示这个文件没保存呀。

**Comment by ly0721** [comment]
额，还是像昨天一样提示无法保存主机：用户未授权，我去官网直接下Python 3.7.4版本吧

**Comment by neolee** [comment]
嗯，你用 Plan B 吧，记住安装时，在开始安装的那个画面，最下面的 Add Python 3.7 to Path 一定记得勾选上，不然很容易装好之后无法在命令行里正常使用。

**Comment by ly0721** [comment]
用Plan B 的话，scoop install git和scoop update这两个不安装的话，会不会后面学习还是得用，不影响后续学习么？

**Comment by neolee** [comment]
不影响主线课程。

**Comment by ly0721** [comment]
好的知道了
