### ISSUE TITLE
Mac 系统安装 homebrew 失败

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#4]
李老师你好，最近在macbook配置环境，需要安装homebrew时遇到了下面这样一个问题：
>![1593090966384](https://user-images.githubusercontent.com/52586220/85756777-b1163000-b741-11ea-9cab-8c7a31d051bf.jpg)

我在网上搜索了一些答案，包括修改hosts和改手机热点下载之类，好像也不行。麻烦老师指导一下。

**Comment by neolee** [comment]
网络问题。用网络代理可以彻底解决；或者是是我在这个仓库首页最下面写的方法： https://github.com/neolee/wop-community

还可以参考之前其他同学问题里的一些答案： #1
