### ISSUE TITLE
用 Mac 下载 nteract 选哪个？

### ISSUE THREAD

**Issue by Reecezhang** [neolee/wop-community#40]
![截屏2020-07-05 13 36 59](https://user-images.githubusercontent.com/48814520/86526367-eea75580-bec5-11ea-8ecd-bbcdaf7fad5e.png)
![截屏2020-07-05 13 39 08](https://user-images.githubusercontent.com/48814520/86526418-72f9d880-bec6-11ea-97e3-4c094834ce58.png)

**Comment by who3m1** [comment]
> ![截屏2020-07-05 13 36 59](https://user-images.githubusercontent.com/48814520/86526367-eea75580-bec5-11ea-8ecd-bbcdaf7fad5e.png)
> ![截屏2020-07-05 13 39 08](https://user-images.githubusercontent.com/48814520/86526418-72f9d880-bec6-11ea-97e3-4c094834ce58.png)
> 
> 
> 
> 
> 
> 
> 
> 

第四个 mac-zip

**Comment by neolee** [comment]
`nteract-*.dmg` 这个。
