### ISSUE TITLE
无法安装 Scoop 影响以后上课吗？

### ISSUE THREAD

**Issue by zjh127** [neolee/wop-community#41]
![无法安装Scoop](https://user-images.githubusercontent.com/51049994/86526672-7e023800-bec9-11ea-86eb-c4fc7a59aa2c.png)
使用宽带是云南昆明的（中国移动宽带）

**Comment by neolee** [comment]
你昨天有听课么？你问的问题昨天都有讲。

首先仔仔细细的读一遍环境配置指南，一开始就说了你必须准备好什么：

<img width="687" alt="Guide" src="https://user-images.githubusercontent.com/24796/86526756-755e3180-beca-11ea-8647-e7b7f7d9185b.png">

然后仔仔细细的读这个仓库的首页：https://github.com/neolee/wop-community

里面也有你这个问题的答案。
