### ISSUE TITLE
在 Mac 上用 jupyter lab 打开学习用书有问题

### ISSUE THREAD

**Issue by Reecezhang** [neolee/wop-community#42]
![截屏2020-07-05 14 28 48](https://user-images.githubusercontent.com/48814520/86526879-eb16cd00-becb-11ea-8353-19bbdb9f6955.png)
请问在Mac上输入的命令是什么？

如果只在terminal上输入jupyter lab 后
![截屏2020-07-05 14 31 52](https://user-images.githubusercontent.com/48814520/86526927-7a23e500-becc-11ea-943d-fd4b66403b2e.png)

选用google打开后，是出错了吗？
![截屏2020-07-05 14 34 17](https://user-images.githubusercontent.com/48814520/86526946-a50e3900-becc-11ea-816f-08d766026643.png)

**Comment by neolee** [comment]
首先，你可以看看支线课程里的第一讲，了解一些基本的命令行操作。

然后，如果你按照配置指南装好了 Python 和 Jupyter Lab，那么可以照下面的操作来测试下（打开一个新的 Terminal 窗口执行操作）：

```shell
mkdir Code
cd Code
jupyter lab
```

如果没有错误的话，最后这个命令会运行 Jupyter Lab 的服务程序，然后自动打开你的缺省浏览器并加载 Jupyter Lab 页面，不需要你输入密码。

如果不是这样，那么你运行 `jupyter lab` 命令的那个命令行窗口里应该会有信息提示，可以截图发上来。

**Comment by Reecezhang** [comment]
用命令窗提示的地址在google里可以打开了
