### ISSUE TITLE
VSCode Terminal 无法输入

### ISSUE THREAD

**Issue by brarcher214** [neolee/wop-community#43]
模仿李骏老师B站在Windows编程环境准备中最后两分钟新建*.py文件后会自动提示安装扩展包（并未成功安装），尝试terminal一直无法输入任何字符，然后重新安装过多个版本（1.47.1/1.41/1.39），问题仍旧一直出现，而且不同版本尝试中先后弹出过Linter pylint is not installed和not enough space to split terminal等提示，从网上查询到的建议都依次尝试但terminal无法输入的问题始终没有解决，求助
![needhelp_2020-07-05_15-32-15](https://user-images.githubusercontent.com/24749111/86527814-04704700-bed5-11ea-979f-c54b6fdef7d1.png)

**Comment by neolee** [comment]
慢点来，一个问题一个问题解决，别蹦蹦跳跳地前进。

先排除简单且必须解决的问题，然后排除可以不管的一些问题，最后解决麻烦的问题。

1. 启动 VS Code，打开一个 .py 文件，会提示安装 Python 相关的核心插件——这个必须成功，不成功你以后会有很多麻烦。
2. pylint 可有可无，对你们目前学习意义不大，但要搞清楚哪里提示 pylint，具体什么问题，以及如何忽略掉该错误。
3. VS Code 自带的 Terminal 在 Windows 下有些时候会表现古怪，需要更相信的信息来确认问题。

按类似上面的思路整理下你的问题，一个个解决，一个个说清楚。

**Comment by brarcher214** [comment]
非常感谢李老师，核心插件已经安装好了
