### ISSUE TITLE
JupyterLab 安装问题

### ISSUE THREAD

**Issue by ly0721** [neolee/wop-community#46]
Jupyterlab 用清华镜像站那个命令安装后，升级了pip版本后还是不行。。。还是提示

9, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\龙禹\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\龙禹\AppData\Local\Programs\Python\Python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

![1](https://user-images.githubusercontent.com/67821088/86529961-55893680-bee7-11ea-9d02-9cf67be25ab2.png)
![2](https://user-images.githubusercontent.com/67821088/86529975-6d60ba80-bee7-11ea-959d-f4e04f57be05.png)

**Comment by neolee** [comment]
这个不需要新提一个 issue 啊，就在之前那个后面继续交互不好么？

你现在的问题是用了清华的镜像还是网络中断了，这就基本可以确定……是你自己的网络有问题，不稳定，换个时间或者换个网络再试吧。

另外，你安装 JupyterLab 成功之前不需要去试 `jupyter lab` 这个命令，因为你还没装好，当然没法用。

**Comment by ly0721** [comment]
知道了，老师

**Comment by neolee** [comment]
抱歉，我搞混了，原来刚才问这个问题的不是你，你这个后续的交互还是继续在这里进行吧。

**Comment by ly0721** [comment]
更换时间和网络运行命令后提示：
    100% |████████████████████████████████| 102kB 6.6MB/s
Installing collected packages: MarkupSafe, jinja2, ipython-genutils, entrypoints, pygments, decorator, six, traitlets, pyrsistent, attrs, zipp, importlib-metadata, jsonschema, pywin32, jupyter-core, nbformat, pyparsing, packaging, webencodings, bleach, testpath, defusedxml, pandocfilters, mistune, nbconvert, pywinpty, tornado, terminado, python-dateutil, pyzmq, jupyter-client, pickleshare, wcwidth, prompt-toolkit, colorama, backcall, parso, jedi, ipython, ipykernel, Send2Trash, prometheus-client, notebook, json5, urllib3, certifi, chardet, idna, requests, jupyterlab-server, jupyterlab
  Running setup.py install for pyrsistent ... done
  Running setup.py install for pandocfilters ... done
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 backcall-0.2.0 bleach-3.1.5 certifi-2020.6.20 chardet-3.0.4 colorama-0.4.3 decorator-4.4.2 defusedxml-0.6.0 entrypoints-0.3 idna-2.10 importlib-metadata-1.7.0 ipykernel-5.3.0 ipython-7.16.1 ipython-genutils-0.2.0 jedi-0.17.1 jinja2-2.11.2 json5-0.9.5 jsonschema-3.2.0 jupyter-client-6.1.5 jupyter-core-4.6.3 jupyterlab-2.1.5 jupyterlab-server-1.1.5 mistune-0.8.4 nbconvert-5.6.1 nbformat-5.0.7 notebook-6.0.3 packaging-20.4 pandocfilters-1.4.2 parso-0.7.0 pickleshare-0.7.5 prometheus-client-0.8.0 prompt-toolkit-3.0.5 pygments-2.6.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pywin32-228 pywinpty-0.5.7 pyzmq-19.0.1 requests-2.24.0 six-1.15.0 terminado-0.8.3 testpath-0.4.4 tornado-6.0.4 traitlets-4.3.3 urllib3-1.25.9 wcwidth-0.2.5 webencodings-0.5.1 zipp-3.1.0
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
![3](https://user-images.githubusercontent.com/67821088/86531016-61c5c180-bef0-11ea-9463-bfef68051fc4.png)
![4](https://user-images.githubusercontent.com/67821088/86531018-64c0b200-bef0-11ea-8130-5be14184b6d7.png)

**Comment by neolee** [comment]
这就是装好 JupyterLab 了呀。

不过你最好执行下 `python -m pip install --upgrade pip`，把 pip 自己升级到最新版本，也可以避免最后那几行黄字 warning。

**Comment by ly0721** [comment]
执行完 python -m pip install --upgrade pip命令后还是提示如下：
9, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\龙禹\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\龙禹\AppData\Local\Programs\Python\Python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by neolee** [comment]
还是网络的问题，用下面的命令（使用清华的镜像站）：

```shell
python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -U pip
```

**Comment by ly0721** [comment]
这下应该是成功了吧，感谢老师耐心解答
<img width="591" alt="6" src="https://user-images.githubusercontent.com/67821088/86531610-604ac800-bef5-11ea-931e-1fcc5dea0424.png">

**Comment by neolee** [comment]
恭喜，通过了第一道考验 👍
