### ISSUE TITLE
如何删除 Scoop 安装失败后残留的 git？

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#47]
已经安装 scoop，后安装 git，失败后，现在要先把 git 文件删了，才能安装，请问怎么去找 git 文件去删？

**Comment by neolee** [comment]
仔仔细细的读环境配置指南，里面有说明安装失败的残留怎么清楚，以便重试。

另外我改了你问题的标题和描述，一般来说标题请尽量精简，详细的描述放在正文中。所以最好也仔仔细细的读一下这个仓库首页的 README： https://github.com/neolee/wop-community

**Comment by WGL1** [comment]
好的
