### ISSUE TITLE
在 Mac mini 上无法安装 homebrew

### ISSUE THREAD

**Issue by zjutimes** [neolee/wop-community#48]
YmdeMac-mini:~ ymaa$ brew
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
YmdeMac-mini:~ ymaa$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by neolee** [comment]
你这不是已经有 brew 了么……试试 `brew update` 和 `brew doctor`。
