### ISSUE TITLE
提问上传图片失败

### ISSUE THREAD

**Issue by worldhuili** [neolee/wop-community#49]
老师，提问题上传图片一直失败，一直上传不了，这是
什么原因呢。上传图片显示Something went really wrong ,and we cant process that file.try again.

**Comment by neolee** [comment]
很像是网络问题。

**Comment by worldhuili** [comment]
换了个网，就可以上传了，并且速度很快，看来确实是网络问题，好用的网很重要。

**Comment by worldhuili** [comment]
> 很像是网络问题。
