### ISSUE TITLE
编程环境准备问题

### ISSUE THREAD

**Issue by K8K0** [neolee/wop-community#5]
# #1 按照教程准备输入到  iwr -useb get.scoop.sh | iex:   按回车   不能下载  
  下一行显示 iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题。用网络代理可以彻底解决；或者试试我在这个仓库首页最下面写的方法：

https://github.com/neolee/wop-community

**Comment by K8K0** [comment]
我刷新了 DNS 解析缓存，打开了网络加速，还是没有成功。为什么？？？求解答
:\Users\K8K0> ipconfig /flushdns                                         
Windows IP 配置

已成功刷新 DNS 解析缓存。
PS C:\Users\K8K0> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\K8K0>

**Comment by neolee** [comment]
这不是说成功了么，接下去运行 `scoop update`。

**Comment by K8K0** [comment]
PS C:\Users\K8K0> ipconfig /flushdns
Windows IP 配置

已成功刷新 DNS 解析缓存。
PS C:\Users\K8K0> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如
果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
不能运行。我不知道是哪个环节出了问题。

**Comment by neolee** [comment]
嗯，这是之前安装 Scoop 中断或者出了意外没完成，按照下面页面里“重装 Scoop”的提示操作，先完整删掉残留，再重新安装：


https://github.com/neolee/wop-community/wiki

注意仔细看每一个命令的返回结果，有告警或者错误提示可以截图发到下面给我看。

**Comment by K8K0** [comment]
PS C:\Users\K8K0> Scoop uninstall scoop
Scoop : 无法将“Scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正
确，然后再试一次。
所在位置 行:1 字符: 1
+ Scoop uninstall scoop
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\K8K0> cd
PS C:\Users\K8K0> del .\scoop -Force
del : 找不到路径“C:\Users\K8K0\scoop”，因为该路径不存在。
所在位置 行:1 字符: 1
+ del .\scoop -Force
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\K8K0\scoop:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by neolee** [comment]
你的 `C:\Users\K8K0\scoop` 已然不存在了，说明 Scoop 已经清掉了，这时候你运行：

```
iwr -useb get.scoop.sh | iex
```

是什么反应？最好截图给我看。

另外，从前面你的回复看，应该有些步骤你做了但是没有写出来，不然不会前面安装 Scoop 没开始就失败，后面却显示 Scoop 已安装（虽然未成功）；也不会显示 Scoop 已安装，但删除时却显示 `C:\Users\K8K0\scoop` 已经不存在。中间是不是你还尝试过其他操作？

**Comment by K8K0** [comment]
当时有一次应该是会成功，但好像网络出了问题没有成功。
有时候我会按错一些地方，出现一些和教程不一样的，我会再开一个重新来。
我暂时不会截图，我复制过来。
PS C:\Users\K8K0> Scoop uninstall scoop
Scoop : 无法将“Scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称
。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Scoop uninstall scoop
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Scoop:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\K8K0> cd
PS C:\Users\K8K0> del .\scoop.sh | iex
del : 找不到路径“C:\Users\K8K0\scoop.sh”，因为该路径不存在。
所在位置 行:1 字符: 1
+ del .\scoop.sh | iex
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\K8K0\scoop.sh:S
   tring) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Command
   s.RemoveItemCommand

PS C:\Users\K8K0> iwr -useb get.scoop.sh | iex
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequ
   est:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.P
   owerShell.Commands.InvokeWebRequestCommand

PS C:\Users\K8K0>

**Comment by neolee** [comment]
如果你按照这个仓库首页 https://github.com/neolee/wop-community 最下面的说明在 hosts 文件中加入了相关内容，并刷新了 DNS 缓存，那么应该可以访问 raw.githubusercontent.com 的，至少不会出现“未能解析”这个错误（有可能会出连接失败的错误）。所以确定上述操作都做成了么？你的 C:\Windows\System32\drivers\etc\hosts 这个文件的内容是啥样子？

你现在关键是安装 Scoop 的命令 `iwr -useb get.scoop.sh | iex` 如何能成功运行，别的暂时不用试了。

另外截图和贴图也在本仓库首页有说明，仔细看看那个页面所有内容吧。

**Comment by K8K0** [comment]
1.刷新DNS缓存   截图 
<img width="1080" alt="jietu1" src="https://user-images.githubusercontent.com/67420321/85886567-eb9ecc00-b818-11ea-9648-cf01e91172de.png">
2. 访问raw.githubusercontent.com 之后 代码贴图
‘’‘python
# PS C:\Users\K8K0> ipconfig /flushdns

Windows IP 配置

已成功刷新 DNS 解析缓存。
PS C:\Users\K8K0> raw.githubusercontent.com
raw.githubusercontent.com : 无法将“raw.githubusercontent.com”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ raw.githubusercontent.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (raw.githubusercontent.com:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\K8K0> raw.githubsercontent.com
raw.githubsercontent.com : 无法将“raw.githubsercontent.com”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查
名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ raw.githubsercontent.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (raw.githubsercontent.com:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\K8K0>
'''

**Comment by neolee** [comment]
你的 hosts 文件内容不对呀，仔细看下那个页面里的说明，看看哪里理解不了……如果不太明白，先不管 ipaddress.com，直接把我写的那一组 域名/IP 数据拷贝到 hosts 文件里看看。

**Comment by K8K0** [comment]
这是我查出来的ip，以及测试的结果。但我不知道是不是这是不是访问ip的时间。
![图片](https://user-images.githubusercontent.com/67420321/85918380-d7001980-b894-11ea-8836-5e16beeff8eb.png)
我使用你的 域名/IP 数据可以刷新 DNS 解析缓存，但下一个访问还是不行。
<img width="1080" alt="2020-06-27 (5)" src="https://user-images.githubusercontent.com/67420321/85919007-4b898700-b89a-11ea-9685-10f621042dec.png">

**Comment by neolee** [comment]
你这里有几个问题：

1. 那个系统配置文件的名字叫做 `hosts`，没有任何后缀名；从你上面的截图看，同个目录下你建立了好几个文件，第一个才是对的，后面两个是带有后缀名的，比如第三个实际上文件名是 `hosts.txt`（只是系统隐藏了后缀，看上去容易混淆）。你要确认你修改的是第一个那个没有后缀的文件 `hosts`。内容你截屏里的是对的，没问题。记得改完 `hosts` 执行下 `ipconfig /flushdns` 刷新缓存。

2. 你需要执行的命令还是 `iwr -useb get.scoop.sh | iex`，而不是 `raw.githubusercontent.com`，后者是你会用到的一个站点的域名而已，并不是一个可以执行的命令。当你改好了 `hosts` 文件之后，再尝试安装 Scoop 的命令 `iwr -useb get.scoop.sh | iex` 看看。

我一直说学编程就是和计算机交朋友，尝试各种命令和编写程序一样，都好比和计算机聊天，你对它说了什么，它回应你什么，最好每一句话都理解，不然很难谈下去，也就没法和计算机做朋友了。

**Comment by K8K0** [comment]
老师我把域名/IP复制到已存在的hosts里，但变得不能刷新 DNS 解析缓存。我是哪里错了？
<img width="1080" alt="2020-06-27 (8)" src="https://user-images.githubusercontent.com/67420321/85923006-1856f000-b8ba-11ea-99d3-195c87003c3c.png">

**Comment by neolee** [comment]
你的命令输入有误，是 `ipconfig /flushdns`，红色的出错信息已经告诉你为什么出错，就是它不认识你给的命令呀。

干这些活的时候要专注，注意力集中。以后写程序也是一样的。

**Comment by K8K0** [comment]
嗯 我知道了。    我安装好scoop后，下一步做什么。我做了一些尝试，但不太对。
‘’‘python
                                                                                                   PS C:\Users\K8K0> ipconfig /flushdns
Windows IP 配置

已成功刷新 DNS 解析缓存。
PS C:\Users\K8K0> iwr -useb get.scoop.sh | iex
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
'lastupdate' has been set to '2020-06-27T22:38:01.3813312+08:00'
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\Users\K8K0> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
couldn't find manifest for 'python37@3.7.4'
PS C:\Users\K8K0> scoop list
There aren't any apps installed.
PS C:\Users\K8K0> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\K8K0> scoop install git
Installing '7zip' (19.00) [64bit]
从传输流收到意外的 EOF 或 0 个字节。
PS C:\Users\K8K0> scoop help


alias       Manage scoop aliases
bucket      Manage Scoop buckets
cache       Show or clear the download cache
cleanup     Cleanup apps by removing old versions
config      Get or set configuration values
create      Create a custom app manifest
depends     List dependencies for an app
export      Exports (an importable) list of installed apps
help        Show help for a command
hold        Hold an app to disable updates
install     Install apps
list        List installed apps
prefix      Returns the path to the specified app
reset       Reset an app to resolve conflicts
search      Search available apps
status      Show status and check for new app versions
unhold      Unhold an app to enable updates
update      Update apps, or Scoop itself
virustotal  Look for app's hash on virustotal.com
which       Locate a shim/executable (similar to 'which' on Linux)


Type 'scoop help <command>' to get help for a specific command.
PS C:\Users\K8K0> scoop help <command>
+ scoop help <command>
+            ~
“<”运算符是为将来使用而保留的。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\Users\K8K0> scoop help command
scoop help: no such command 'command'
scoop help <command>
PS C:\Users\K8K0> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\K8K0> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
PS C:\Users\K8K0>
'''

**Comment by neolee** [comment]
按照“编程环境配置指南”一步步来啊，你有仔细看那个文档么……

p.s. 在开始安装 Python 之前，先确保 `scoop install git` 和 `scoop update` 都成功执行。

**Comment by K8K0** [comment]
我重新看了 编程环境配置指南  ，scoop 有问题，这个是哪里的问题？怎么解决。  老师。
‘’‘python
#PS C:\Users\K8K0> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:Stri
   ng) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Co
   mmands.SetItemPropertyCommand
'''

**Comment by neolee** [comment]
你执行的这个命令在有的系统里需要管理员权限，需要用管理员权限启动 Windows Terminal 再执行。

你现在已经装好了 Scoop，接下去最重要的是装 Python，为了装好 Python 需要先更新 Scoop 的数据，这可以通过下面的命令实现：

```powershell
scoop install git
scoop update
```

如果成功的话，就可以安装 Python 了：

```powershell
scoop bucket add versions
scoop update
scoop install python37@3.7.4
```

这才是你的主线目标。

上面这些在指南里都有，但不知道为啥你的路径非常跳跃，给人感觉是走到哪算哪，问题也发散得很，那就很难推进了。

**Comment by K8K0** [comment]
使用管理员权限后，他一直让我反复输入重复的命令。但还是不能安装 git.
'''python
#Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\K8K0> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.27.0.windows.1) [64bit]
无法连接到远程服务器
URL https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\K8K0> scoop update git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\K8K0>
'''
<img width="1080" alt="2020-06-29" src="https://user-images.githubusercontent.com/67420321/85974425-fb303780-ba07-11ea-8584-1a399528f183.png">

**Comment by neolee** [comment]
好，你现在前进了一步，面对 “安装 git” 这个任务，遇到的是网络问题：

```
Installing 'git' (2.27.0.windows.1) [64bit]
无法连接到远程服务器
URL https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z is not valid
```

先不要想别的问题，先把这个解决——你现在刚开始接触这些东西，千万不要同时想着解决两个问题，一个一个来。

这个问题有一些办法可以解决，你可以换个网络或者换个时间试试（是的，很多同学就是多试了几次就行了），也可以使用一个好用的网络代理（这个是最治本的），还可以搜索下我们的问答社区，其实已经有同学遇到一样的问题，并且自己想办法解决了，你可以参考其他同学的解决方案，点击这个问题链接： #11 。

**Comment by K8K0** [comment]
老师我安装不了git 是因为代理不支持命令行安装吗？ 
‘’‘python
#PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.27.0.windows.1) [64bit]
Loading PortableGit-2.27.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.27.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数
为 Null 或空。请提
供一个不为 Null 或空的参数，然后重试该命令。
所在位置 C:\Users\K8K0\scoop\apps\scoop\current\lib\decompress.ps1:81 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBi
    ndingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalComma
   nd

git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼
写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundExcep
   tion
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from C:\Users\K8K0\scoop\apps\git\2.27.0.windows.1\dl.7z.
Log file:
  ~\scoop\apps\git\2.27.0.windows.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
'''
如果是，我按照你给的问题链接中的解决办法，进行了第一步，第二步怎么操作？我尝试百度，但没找到方法。

**Comment by neolee** [comment]
Scoop 的 cache 目录在 `C:\Users\<你的用户名>\scoop\cache`，按照那位同学的方法，把你下载的 git 安装文件改名然后放到上述目录下，然后继续后面的步骤。

**Comment by K8K0** [comment]
我做完第二步，还是不能安装。 我第二步是对的吗？是哪里做错了？
![图片](https://user-images.githubusercontent.com/67420321/86504691-4d010500-bdee-11ea-8744-f82a0b6117c5.png)
‘’‘python
#'git' was uninstalled.
PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.27.0.windows.1) [64bit]
PortableGit-2.27.0-64-bit.7z.exe (41.8 MB) [================================================================================================] 100%
Checking hash of PortableGit-2.27.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试该命令。
所在位置 C:\Users\K8K0\scoop\apps\scoop\current\lib\decompress.ps1:81 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from C:\Users\K8K0\scoop\apps\git\2.27.0.windows.1\dl.7z.
Log file:
  ~\scoop\apps\git\2.27.0.windows.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
'''

**Comment by neolee** [comment]
你的 `C:\Users\K8K0\scoop\cache` 目录下有两个 git 的下载文件，只需要一个（另一个得删掉），所以哪个是你下载好放进去的？它的完整文件名是啥？从你的出错信息看，有可能是你的文件名没弄对。

另外还有一个可能，就是你的系统偏老，对长文件名的支持有问题，你可以尝试执行（注意这个命令需要管理员权限，也就是说你需要用管理员权限运行 Windows Terminal，然后执行这一句）：
```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

**Comment by K8K0** [comment]
我下载了一个，第三排的那个是我运行 scoop install git 之后自己出现的。图片是第四排我下载的文件全名。
![图片](https://user-images.githubusercontent.com/67420321/86505555-b0903000-bdf8-11ea-8392-69852907be14.png)

**Comment by neolee** [comment]
这个文件名不对呀，最后多了个 `;`，文件的后缀是 `7z`，不是 `7z;`。把名字改对，然后试试我前一个回复里那个命令，再尝试重新安装 git。

另外，你在文件浏览器里把文件名那一栏拉宽一点就能看到全名，不需要用记事本来打开呀。

**Comment by K8K0** [comment]
我改了
![图片](https://user-images.githubusercontent.com/67420321/86505949-1979a700-bdfd-11ea-92ee-2558f45134c6.png)
我运行了你给的命令，好像没什么反应。
'''python
#Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\K8K0> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1PS C:\Users\K8K0> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1                  scoop uninstall git
Uninstalling 'git' (2.27.0.windows.1).
'git' was uninstalled.
PS C:\Users\K8K0> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.27.0.windows.1) [64bit]
Loading PortableGit-2.27.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.27.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\Users\K8K0\scoop\apps\scoop\current\lib\decompress.ps1:81 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，
然后再试一次。
所在位置 行:1 字符: 1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from C:\Users\K8K0\scoop\apps\git\2.27.0.windows.1\dl.7z.
Log file:
  ~\scoop\apps\git\2.27.0.windows.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
PS C:\Users\K8K0>
'''
不好意思，我基本不使用电脑，平常的基本操作我不知道。

**Comment by neolee** [comment]
把 `C:\Users\K8K0\scoop\apps\git\2.27.0.windows.1\7zip.log` 文件作为附件发上来（把这个文件拖到这个页面的输入框里，等 Uploading... 那句话消失变成别的就好了）。

**Comment by K8K0** [comment]
很奇怪我从我的电脑可以打开那个文件，但是从输入框里的 try again  里找，这个文件显示不存在。或者直接复制文件，也复制不了。而且我没有\7zip.log
![图片](https://user-images.githubusercontent.com/67420321/86506251-5004f100-be00-11ea-8296-ece6a5f5bf76.png)

**Comment by neolee** [comment]
你这个问题比较复杂，而且你对系统也不太熟悉，咱们时间不多了，所以我们换替代方案吧。如果以后有时间有兴趣再来解决 Scoop 的问题。

一步步按照下面操作：

1. 去 https://www.python.org/downloads/release/python-374/ 这个页面下载 Python 安装包，就是页面下方文件列表里的 Windows x86-64 executable installer 那个文件；
2. 运行下载回来的 Python 安装文件，中间都用缺省设置，不用动；
3. 安装完毕之后打开命令行界面执行 `python -V` 应该返回 `3.7.4`；如果这时候返回信息是找不到/不认识 `python` 命令的话，就重启 Windows，然后再重试这一步；
4. 在命令行执行下面的命令：
```powershell
python -m pip install -U pip
pip install jupyterlab
python -m ipykernel install
```
5. 去 https://nteract.io/ 下载和安装最新版本的 nteract。

你现在应该可以用 nteract 打开我们的 ipynb 文件，完成作业并进行测试了。

如果中间任何一步出现问题，将出错的情况截图发过来，我下午都在这里，加快点速度。

当然 Visual Studio Code 还是要装的，参考安装指南装就行了，那个没难度。

**Comment by K8K0** [comment]
执行 python -V 后没给我回应，我重启电脑后，再试   以下
‘’‘python
#尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\K8K0> python -V
PS C:\Users\K8K0>

我需要用管理员权限执行吗？

**Comment by neolee** [comment]
这个 Python 安装到哪里了你记得吗？

以及执行 `$env:Path` 的结果是什么？

**Comment by K8K0** [comment]
是这个吗 ？   我重启后，还是这个状态。刚刚我忘记安装了。抱歉
![图片](https://user-images.githubusercontent.com/67420321/86507511-551b6d80-be0b-11ea-9beb-0b69379cd4ca.png)

**Comment by neolee** [comment]
你这个是直接运行了安装好的 python.exe，你现在需要打开 Windows Terminal，在里面运行 `python -V`，看看是什么结果。

**Comment by K8K0** [comment]
没有回应
<img width="1080" alt="2020-07-04 (7)" src="https://user-images.githubusercontent.com/67420321/86507712-02db4c00-be0d-11ea-8d4e-f5dd9b92e3ee.png">

**Comment by neolee** [comment]
OK. 你再运行一次你下载的那个 Python 安装程序，它会提示你 Modify、Repair 还是 Uninstall，先选择 Uninstall，彻底删掉安装的 Python。

然后再运行 Python 安装程序，这一次注意在开始安装的画面：
1. 在 Install Now 下面有安装到哪里去的一个目录，记下来；
2. 最下面的两个选项里，注意勾选 Add Python 3.7 to PATH 这一项；
3. 点击 Install Now 开始安装。

完成之后，再在命令行里执行：

```powershell
$env:Path

python -V
```

**Comment by K8K0** [comment]
老师，是在 Windows Terminal  里执行  $env:Pathpython -V吗？
‘’‘python
#PS C:\Users\K8K0> $env:Path
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\K8K0\scoop\shims;C:\Users\K8K0\AppData\Local\Microsoft\WindowsApps
PS C:\Users\K8K0> python -V
PS C:\Users\K8K0>
'''

**Comment by neolee** [comment]
看到了。

你按照我前面说的重新安装一次了么？

**Comment by K8K0** [comment]
可以了可以了  我重新安装卸载了两次，再重启。它现在返回 3.7.4了。
我现在继续
'''python
#python-m pip install-U pip
pip install jupyterlab
python-m ipykernel install
'''
？

**Comment by neolee** [comment]
哎呀，终于……

可以继续下面的步骤了：

> 4. 在命令行执行下面的命令：
> ```powershell
> python -m pip install -U pip
> pip install jupyterlab
> python -m ipykernel install
> ```
> 5. 去 https://nteract.io/ 下载和安装最新版本的 nteract。

**Comment by K8K0** [comment]
好     有个问题 我下载的 nteract  后面是     .exe    不是.ipynb  
<img width="1080" alt="2020-07-04 (9)" src="https://user-images.githubusercontent.com/67420321/86510585-961f7c00-be23-11ea-8dab-c4cf0bd78dbc.png">
这个没问题吗？

**Comment by neolee** [comment]
这个是 nteract 的安装程序，当然是 exe 啊，你运行它就会为你安装 nteract 这个程序，用 nteract 这个程序就能打开 .ipynb 类型的文档。

就好像你安装了 Microsoft Word 之后就可以用 Word 打开 .doc 文档一样。

**Comment by K8K0** [comment]
老师，我大概把编程环境搞定了。除了 scoop。
VSCode   在Terminal窗口可以运行 hello.py  ， 运行结果  Hello world。
nteract   下载完成，可以做作业。
Jupyter Lab   能打开  并上传作业。 
 抱拳 感谢

**Comment by Lormenli** [comment]
李老师，我在配置环境过程中，执行scoop install git，总是报错，出现：PS C:\Users\jh_l> scoop install git
Installing 'git' (2.30.1.windows.1) [64bit]
PortableGit-2.30.1-64-bit.7z.exe (43.1 MB) [====>               ]  27%
从传输流收到意外的 EOF 或 0 个字节。
URL https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/PortableGit-2.30.1-64-bit.7z.exe#/dl.7z is not valid。
请问这是什么问题？我该如何解决呢？

**Comment by Arthurcsy95** [comment]
如果出现下面的错误提示：
iwr : 请求被中止: 未能创建 SSL/TLS 安全通道。
需执行以下命令：
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
