### ISSUE TITLE
busybox 安装失败

### ISSUE THREAD

**Issue by worldhuili** [neolee/wop-community#50]
![批注 2020-07-05 194436](https://user-images.githubusercontent.com/67824722/86533213-0997bb00-bf02-11ea-93d0-e4e0bbe7833f.jpg)

**Comment by neolee** [comment]
没失败，就是网络不太顺畅，下载很慢（这个软件才几百K）。

**Comment by worldhuili** [comment]
好的，那我还是按之前的安就行是吗，输入 scoop install busybox?

**Comment by neolee** [comment]
是啊。

**Comment by worldhuili** [comment]
确实是网络问题，安上了，谢谢老师
