### ISSUE TITLE
安装 Scoop 下的 git 出现如下错误

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#51]
![99f30e7981b01af6f52e6e7ea695cb2](https://user-images.githubusercontent.com/49615335/86533358-31d3e980-bf03-11ea-821e-f4fe12ba53b6.png)

**Comment by neolee** [comment]
`scoop checkup` 有返回什么提示？

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86533724-ae67c780-bf05-11ea-9419-8683b1971c62.png)

**Comment by neolee** [comment]
按它说的做（其实这几个问题配置指南和这个站点的 Wiki 里也有）。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86533935-44502200-bf07-11ea-94d2-238298ada7eb.png)
不容易啊

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86534180-e6bcd500-bf08-11ea-9a95-a57da5fcf905.png)
啷个一直这种状态，hen很久了

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86535234-6ea6dd00-bf11-11ea-980e-e4d50aedd311.png)怎么更新不起

**Comment by neolee** [comment]
还是网络不太好，换个时间试试吧。

**Comment by WGL1** [comment]
好

**Comment by ly0721** [comment]
运行git相关命令都提示这个。。。
<img width="809" alt="7" src="https://user-images.githubusercontent.com/67821088/86551074-a8f69580-bf76-11ea-9acc-004080bc3089.png">

**Comment by ly0721** [comment]
运行Git和相关命令时都提示这个。。。
<img width="809" alt="7" src="https://user-images.githubusercontent.com/67821088/86551161-e3f8c900-bf76-11ea-8ac1-d823d5ff5943.png">

**Comment by neolee** [comment]
@ly0721 不要在别人的问题里问自己的问题。让仔细读的说明读了么？

https://github.com/neolee/wop-community

**Comment by ly0721** [comment]
抱歉老师，看了相关主题就直接问了，读了没记住刚又看了说明，我重新提一下。
