### ISSUE TITLE
关于安装 VS Code 不安装在 C 盘问题

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#53]
![image](https://user-images.githubusercontent.com/49615335/86534396-bbd38080-bf0a-11ea-89a5-8b628f8c4b01.png)
是要重新安装在C盘吗？

**Comment by neolee** [comment]
我昨天还在课上讲了和你这个几乎一样的例子，你仔细看你的命令错在哪儿……

提示：和 VS Code 放哪里没关系。

**Comment by WGL1** [comment]
![5038f05febd3a4e2c452ca8f3f1fd92](https://user-images.githubusercontent.com/49615335/86534676-b37c4500-bf0c-11ea-8e6f-9823eeb3af84.png)
命令该过了还是一样的提醒

**Comment by zed-wong** [comment]
> ![5038f05febd3a4e2c452ca8f3f1fd92](https://user-images.githubusercontent.com/49615335/86534676-b37c4500-bf0c-11ea-8e6f-9823eeb3af84.png)
> 命令该过了还是一样的提醒

这个还是我来回答吧🤣
`cd code`的意思是 切换当前目录到code文件夹下
根据你第二张图片的显示，你已经在code目录下了，而这个目录里面没有Code目录，所以会报错 ..

**Comment by neolee** [comment]
@WGL1 建议先去学习支线课程第一讲，了解命令行和工作目录的基本概念

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86535144-b416da80-bf10-11ea-8b5c-10f1152a838a.png)
咋还是这样

**Comment by neolee** [comment]
你的 Visual Studio Code 转好了么？单独可以运行么？

**Comment by WGL1** [comment]
可以单独运行

**Comment by WGL1** [comment]
我安装在D盘的，这个Windows PowerShell工作是在C盘

**Comment by neolee** [comment]
已经说过了，和在哪个盘没关系。

执行 `$env:Path` 结果是啥？

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86535788-79637100-bf15-11ea-9e96-8fa32a96c388.png)

**Comment by neolee** [comment]
这里面并没有你安装 VS Code 的地方，这不太正常，VS Code 的安装程序会自动把自己的安装目录加入 Path 中。

所以你是怎么安装 VS Code 的？

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86535991-d6135b80-bf16-11ea-9a1f-b51ed8eec89c.png)
这里的C盘改为Dpan盘

**Comment by WGL1** [comment]
我是直接把C改为D

**Comment by neolee** [comment]
无法判断为啥你这里没有自动配置好 code 命令所在的目录，不过也可以自己手动来做，只要把 code.exe 文件所在的目录加到系统 PATH 变量里就可以了，你的 code.exe 很可能在 `D:\Users\86188\AppData\Local\Programs\Microsoft VS Code\bin` 下，你可以先确认一下。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86536331-428f5a00-bf19-11ea-9fa4-5be285d8678a.png)
难道因为这个

**Comment by neolee** [comment]
可以重启下看看。

**Comment by WGL1** [comment]
行啦
