### ISSUE TITLE
iMac 安装 homebrew 失败

### ISSUE THREAD

**Issue by jiangminghe** [neolee/wop-community#54]
jiangminghe@jiangmihedeimac ~ % bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
zsh: no such file or directory: bin/bash
jiangminghe@jiangmihedeimac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
jiangminghe@jiangmihedeimac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
jiangminghe@jiangmihedeimac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
jiangminghe@jiangmihedeimac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
jiangminghe@jiangmihedeimac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
jiangminghe@jiangmihedeimac ~ % brew update
zsh: command not found: brew
jiangminghe@jiangmihedeimac ~ %

**Comment by zed-wong** [comment]
这个属于网络问题，需要使用代理，或者换个时间再试试

**Comment by neolee** [comment]
或者像我昨天说了好多遍的那样，仔细看看 https://github.com/neolee/wop-community 这个页面，在下面就有一个解决方案。

**Comment by jiangminghe** [comment]
谢谢
