### ISSUE TITLE
Scoop 安装 Git 出错

### ISSUE THREAD

**Issue by yyd841122** [neolee/wop-community#55]
在一周前，本机已经配置好环境，今天由于自己误操作导致，之前的环境被破坏，现在二次重新搭建环境。在支行scoop install git,命令时，
![1](https://user-images.githubusercontent.com/67271134/86535599-09a0b680-bf14-11ea-8239-581204dc2770.png)
一直卡在这个地方，不动，我理解可能是网络问题。现在我在github,已经下载好了PortableGit-2.27.0-64-bit.7z.exe
![2](https://user-images.githubusercontent.com/67271134/86535618-263cee80-bf14-11ea-95eb-950e80d11c67.png)

**Comment by yyd841122** [comment]
现在如何在命令行调用，我下载的PortableGit-2.27.0-64-bit.7z.exe，而不要去网上再下载。请指教！

**Comment by neolee** [comment]
请参考 #11 中的方法。
