### ISSUE TITLE
三种方式运行 python 第二种遇到问题

### ISSUE THREAD

**Issue by Jackgong1** [neolee/wop-community#56]
![Screen Shot 2020-07-05 at 11 01 45 PM](https://user-images.githubusercontent.com/40572207/86535609-1c1af000-bf14-11ea-90df-b499ef569702.png)
如图所示，为什么没有出现像老师视频演示画面的窗口？单击，双击都不行。

**Comment by neolee** [comment]
你双击左边的 test.ipynb 没有打开？确定么？

你运行 jupyter lab 命令的那个命令行窗口里有什么出错提示么？

**Comment by Jackgong1** [comment]
![3](https://user-images.githubusercontent.com/40572207/86535868-e840ca00-bf15-11ea-8d1c-399ed7396965.png)
第三种运行方法也遇到问题。
按照老师的步骤，在terminal run  python hello.py 为什么结果？

**Comment by Jackgong1** [comment]
> 你双击左边的 test.ipynb 没有打开？确定么？
> 
> 你运行 jupyter lab 命令的那个命令行窗口里有什么出错提示么？

这是在terminal 运行jupyter lab的结果。 
左键双击，窗口会出现闪一下，然后就消失。 

Last login: Sun Jul  5 23:14:39 on ttys000
Gong-MacBook-Air:~ chenluheng$ jupyter lab
[I 23:21:23.191 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.7/site-packages/jupyterlab
[I 23:21:23.191 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 23:21:23.195 LabApp] Serving notebooks from local directory: /Users/chenluheng
[I 23:21:23.195 LabApp] The Jupyter Notebook is running at:
[I 23:21:23.195 LabApp] http://localhost:8888/?token=ec4e5589443e929eba13d50eabfdd268d3dc6dfae1dfc9dd
[I 23:21:23.195 LabApp]  or http://127.0.0.1:8888/?token=ec4e5589443e929eba13d50eabfdd268d3dc6dfae1dfc9dd
[I 23:21:23.196 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:21:23.206 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/chenluheng/Library/Jupyter/runtime/nbserver-5595-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ec4e5589443e929eba13d50eabfdd268d3dc6dfae1dfc9dd
     or http://127.0.0.1:8888/?token=ec4e5589443e929eba13d50eabfdd268d3dc6dfae1dfc9dd
[I 23:21:28.755 LabApp] 301 GET /lab/workspaces/auto-r/?clone (::1) 1.80ms
[W 23:21:29.461 LabApp] Could not determine jupyterlab build status without nodejs

**Comment by neolee** [comment]
不是说了问题要一个个来么？一个问题没解决就去搞第二个问题，你以为是玩星际多线操作吗？！

首先，去好好学一学支线课程第一讲，搞清楚什么叫目录什么叫文件，什么叫当前工作目录，后一个问题就自然解决了。

Jupyter Lab 那个不知道为啥，你确定你双击了打开不了也没任何出错信息？这基本不太可能发生。

**Comment by Jackgong1** [comment]
> 不是说了问题要一个个来么？一个问题没解决就去搞第二个问题，你以为是玩星际多线操作吗？！
> 
> 首先，去好好学一学支线课程第一讲，搞清楚什么叫目录什么叫文件，什么叫当前工作目录，后一个问题就自然解决了。
> 
> Jupyter Lab 那个不知道为啥，你确定你双击了打开不了也没任何出错信息？这基本不太可能发生。

有没有可能是Run jupyter lab 最下面这行字的问题：   Could not determine jupyterlab build status without nodejs

![Screen Shot 2020-07-05 at 11 27 43 PM](https://user-images.githubusercontent.com/40572207/86536070-47530e80-bf17-11ea-8b57-b356d0e45cb5.png)

**Comment by neolee** [comment]
那个一般是没啥关系的，尤其是你的 Jupyter Lab 刚装好。

**Comment by Jackgong1** [comment]
> 那个一般是没啥关系的，尤其是你的 Jupyter Lab 刚装好。
左键双击以后， 画黑圈的窗口会出现 大概1秒，马上闪退 消失掉。

**Comment by neolee** [comment]
这个过程中命令行窗口里有什么信息么？

你可以直接回复，不需要引用我的回复，这样看着更加干净。

**Comment by Jackgong1** [comment]
![Screen Shot 2020-07-06 at 12 21 22 AM](https://user-images.githubusercontent.com/40572207/86537015-af592300-bf1e-11ea-83b1-8ba9c405c545.png)
出现闪退时候，Terminal 里面没有出现其他的。 
刚才google 了下，貌似也有其他人遇到notebook 闪退问题。 

但是我还没找到解决办法。

**Comment by neolee** [comment]
你点右边 Launcher 窗口里那个 Python 的大图标，会怎样？

**Comment by Jackgong1** [comment]
![Screen Shot 2020-07-06 at 1 02 29 PM](https://user-images.githubusercontent.com/40572207/86557607-3cd15d00-bf89-11ea-9022-ab6fc655e81c.png)
点这个Python 的大图标，每点一次，左边会出现一个 .ipynb file

**Comment by neolee** [comment]
但是没有打开这个 notebook 对吧？你这个确实奇怪，就是无法正常打开 notebook。暂时还没有头绪。

**Comment by Jackgong1** [comment]
![Screen Shot 2020-07-06 at 1 54 58 PM](https://user-images.githubusercontent.com/40572207/86560313-95582880-bf90-11ea-933e-619b7dc13d72.png)

Console 和 terminal 都可以打开另外一个窗口。 

Notebook,Markdown,Text File，都出现闪退。

**Comment by tyler1zhang** [comment]
请问可否提供下面的一些信息
1. 你的python 和jupyter lab的版本是什么
2. 你用的应该是Safari，如果用Chrome 或者 firefox 是不是也有这种问题
3. 你安装好jupyter lab之后，有没有添加其他的插件，比如TOC之类。

**Comment by Jackgong1** [comment]
太感谢了， 换成Chrome 这个问题解决了。
谢谢。

**Comment by tyler1zhang** [comment]
那你就关掉这个issue吧。 有开有关，这样可以让李骏老师或者来帮忙的同学可以知道哪些是**还需要被回答的问题**。

**Comment by Jackgong1** [comment]
好的。
