### ISSUE TITLE
运行 hello.py 出现 SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by cunzai2020** [neolee/wop-community#57]
写了一个hello.py文件，内容如下：
![1](https://user-images.githubusercontent.com/67787893/86536230-82a20d00-bf18-11ea-90aa-da98d4a630af.png)
用python运行正格文件，提示如下：
![2](https://user-images.githubusercontent.com/67787893/86536243-977ea080-bf18-11ea-9c08-40ab3b4a741c.png)
不知是何原因，求教。

**Comment by neolee** [comment]
因为你用了中文括号呀！

**Comment by cunzai2020** [comment]
明白了，谢谢李老师。
