### ISSUE TITLE
关于 scoop update 更新问题

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#58]
![image](https://user-images.githubusercontent.com/49615335/86536823-41602c00-bf1d-11ea-802a-6ab9e1610843.png)
属于scoop update 后自检后的问题

**Comment by neolee** [comment]
一个个来。

第一个错误是，你需要用管理员权限运行那个命令，以管理员身份运行 Windows Terminal，然后执行命令。

第二个还是网络问题。

**Comment by WGL1** [comment]
![image](https://user-images.githubusercontent.com/49615335/86536920-fc88c500-bf1d-11ea-89ef-742ea0fed657.png)
这样对吧

**Comment by neolee** [comment]
是的。

**Comment by WGL1** [comment]
又来啦
![image](https://user-images.githubusercontent.com/49615335/86537952-550f9080-bf25-11ea-95dc-89a114f085aa.png)

**Comment by neolee** [comment]
网络问题。

**Comment by WGL1** [comment]
好吧，老师早点睡

**Comment by kevinliu168** [comment]
> 相同的问题我也遇到过。
可以参考这页面的处理方法。
https://blog.csdn.net/qq_34121797/article/details/79561110?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare
