### ISSUE TITLE
作业命名格式

### ISSUE THREAD

**Issue by xuzhengfu** [neolee/wop-community#59]
通过「下载附件」下载下来的作业，其名称是一串数字。

是否需将该名称改成相应的章节名称？比如：将 `1590402800963.ipynb` 改为 `理解编程语言`。

**Comment by neolee** [comment]
名称是无所谓的，你可以随便改，但上传的时候主要不要传错，一定要对应上。

**Comment by xuzhengfu** [comment]
谢谢老师！
