### ISSUE TITLE
正则表达式的问题

### ISSUE THREAD

**Issue by aosjiabei** [neolee/wop-community#6]
因为   +  代表前面的原子必须至少出现一次，即：出现次数 ≧ 1 ；  `(er)` 是一个原子，'er'

所以 `(er)`+ 代表'er' 这个原子至少出现一次
![image](https://user-images.githubusercontent.com/48588326/85817540-d423fc80-b7a0-11ea-9f91-fb7bef6d8eff.png)

为什么返回值不是 ['er', 'erer', 'er']？

我找到这句话：A repeated capturing group will only capture the last iteration.重复的捕获组将仅捕获最后一次迭代。但还是不太明白

**Comment by neolee** [comment]
第二个匹配确实是 `erer`，但是因为你的 pattern 里使用了 group（`(er)`），所以返回里是 group 捕获的部分。

具体可以参考以前有同学问过的这个问题： https://github.com/neolee/pilot/issues/819
