### ISSUE TITLE
命令行进入 my-student-book 显示该路径不存在

### ISSUE THREAD

**Issue by worldhuili** [neolee/wop-community#62]
**关于“如何使用配套学习用书“的”这部分内容**
![image](https://user-images.githubusercontent.com/67824722/86549328-ea387680-bf71-11ea-843d-a11e2f403820.png)

**在命令行里执行失败，显示该路径不存在**
![image](https://user-images.githubusercontent.com/67824722/86549370-09cf9f00-bf72-11ea-9ea1-56c466bb4e25.png)

**又试了几次依然失败**
![image](https://user-images.githubusercontent.com/67824722/86549395-1c49d880-bf72-11ea-9526-40cbacec51b3.png)

**我的my-student-book保存在以下位置**
![image](https://user-images.githubusercontent.com/67824722/86549547-82cef680-bf72-11ea-9c3e-08780fedfe7c.png)

**麻烦老师解惑。**

**Comment by neolee** [comment]
没问题呀，你要进的目录确实不存在嘛。

你要自己建立那个目录，然后把下载回来的 zip 文件解压到哪个目录里去。

建议先去看看支线课程第一讲，了解目录文件和命令行的基本概念。
