### ISSUE TITLE
系统管理员权限怎么设置

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#63]
Windows 10 家庭版的系统管理员权限怎么设置？

**Comment by neolee** [comment]
什么叫“怎么设置”，能把你的目标说的更清晰一点吗？

如果是“以管理员权限运行某个软件（比如 Windows Terminal）”的话，那就是右键点击该应用软件的图标，选择 Run as Administrator（以管理员身份运行）就可以了。

**Comment by Amy20191** [comment]
我把  199.232.68.133 raw.githubusercontent.com  拷贝到Windows：C:\Windows\System32\drivers\etc\hosts里面保存的时候，跳出来说需要联系管理员获得相应的权限，这个是需要开通管理员权限吗？但我看了一下，我的用户名已经是管理员权限了。
![image](https://user-images.githubusercontent.com/57065555/86560255-76599680-bf90-11ea-8528-bd3285419d07.png)
![image](https://user-images.githubusercontent.com/57065555/86560603-465ec300-bf91-11ea-8028-3e8c5f9e31d1.png)

**Comment by neolee** [comment]
首先，不要去动你的用户账户设定，那个没问题。

然后最重要的，不要用记事本来修改这种系统文件，用我们装好的 Visual Studio Code。可以用管理员身份启动 VS Code，然后用 File - Open File... 来找到 hosts 文件打开编辑。

**Comment by Amy20191** [comment]
谢谢，这个问题解决了，现在有个相关的问题，假如我的Windows：C:\Windows\System32\drivers\etc\hosts，没有hosts这个文件，我要新建一个名为 hosts 的空文本文件，但我在桌面上点右键新建的时候，只有记事本，word格式的，建不了没有后缀的空文本文件。这个没有后缀的空文本文件怎么能建出来？

**Comment by neolee** [comment]
用命令行可以，或者用 VS Code 也可以。

**Comment by Amy20191** [comment]
好的，谢谢！
