### ISSUE TITLE
安装 git 过程中遇到的问题

### ISSUE THREAD

**Issue by ly0721** [neolee/wop-community#64]
用scoop 安装git 过程中输入安装命令后提示：
<img width="809" alt="7" src="https://user-images.githubusercontent.com/67821088/86553482-6b493b00-bf7d-11ea-9ae2-6262b812e9fe.png">

**Comment by neolee** [comment]
你这个是 scoop 没装好啊，需要卸掉重装，具体方法点这个页面上面的 Wiki 链接，里面有。

你之前不是 Scoop 搞好了么？如果实在不行，建议用 Plan B，直接从 Python 官网下载 3.7.4 安装包安装，先别管 Scoop 了。

**Comment by ly0721** [comment]
哦，B计划已经搞好了，这是怕影响到以后支线课程学习所以想把它弄好

**Comment by neolee** [comment]
噢噢，那就试试吧，重装的时候遇到任何问题截图发上来给我看看。

**Comment by ly0721** [comment]
![Uploading 22.png…]()

**Comment by ly0721** [comment]
<img width="779" alt="22" src="https://user-images.githubusercontent.com/67821088/86792390-0422a800-c09d-11ea-9201-7b2198841fc3.png">
