### ISSUE TITLE
Windows Terminal 的安装问题

### ISSUE THREAD

**Issue by dingtouall** [neolee/wop-community#65]
用践行群里的编程课配置的环境，可以顺利的学完本课程吗？ 
我的电脑是win10企业版 没有应用商店，安装不了Windows Terminal，后面折腾出来了应用商店还是安装不了Windows Terminal...... 要是不影响后续的学习，暂时不想浪费时间在这上面了

**Comment by neolee** [comment]
之前的环境也可以的，只要命令行、Python 3.7 和 Jupyter 三大件齐备就可以。

不过没有应用商店并不是问题，在这里也可以下载 Windows Terminal（你自己随便搜索下也能找到）：

https://github.com/microsoft/terminal/releases

**Comment by dingtouall** [comment]
之前的环境都按照步骤配齐了，用起来没问题
这个之前试过好几次都没成功，后来也试了一些网上的方法也没弄好，现在再次下载试了还是不行...
所以我还是暂时把时间放在课程上吧，基础较差相对的就需要付出更多的时间和精力，以后有需要再直接换个系统重新配置好了
谢谢老师的解答！
