### ISSUE TITLE
安装 Homebrew 时找不到 RETURN

### ISSUE THREAD

**Issue by jiangminghe** [neolee/wop-community#67]
<img width="570" alt="截屏2020-07-06 下午8 48 15" src="https://user-images.githubusercontent.com/67852126/86594666-06680200-bfca-11ea-9c66-7b6353b8d717.png">

**Comment by neolee** [comment]
你为啥提了两个一样的问题，然后还都关掉了？如果是误操作，很容易可以编辑自己的问题，还可以重新打开。

RETURN 就是回车键，你的键盘右侧中间那个大大的键。
