### ISSUE TITLE
Jupyter Lab 安装好后执行到 C 盘出现问题

### ISSUE THREAD

**Issue by WGL1** [neolee/wop-community#68]
![image](https://user-images.githubusercontent.com/49615335/86609157-1b4e9080-bfde-11ea-8850-d036b9959846.png)

**Comment by neolee** [comment]
那个目录只是我打的一个比方，不是真的有那么个目录啊……

你要自己准备好这个目录，然后才能进去。

你先看看支线课程 1、3、4、5 吧。
