### ISSUE TITLE
运行 nteract 显示需要更新

### ISSUE THREAD

**Issue by jiangminghe** [neolee/wop-community#69]
<img width="421" alt="截屏2020-07-06 下午11 12 35" src="https://user-images.githubusercontent.com/67852126/86609206-315c5100-bfde-11ea-8b66-5903755abfb9.png">

**Comment by jiangminghe** [comment]
nteract版本0.24.0

**Comment by neolee** [comment]
这个应该是 macOS 的运行安全措施，打开 macOS 的系统设置，在安全设置里看看有没有显示说刚组织了 nteract 运行，点允许运行就可以了。

**Comment by jiangminghe** [comment]
解决问题，感谢neolee老师。
