### ISSUE TITLE
作业填写是否需要和教材完全一样？

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/wop-community#70]
比如一个cell，教材中的内容是 `g = f` ， 如果我在作业中写成如下内容，自动作业批改系统会怎么判断
```python
g = f
f = True
g
```

而且，如果有几个连续的cell，内容顺序颠倒了，自动作业系统又会怎么判断呢？

**Comment by neolee** [comment]
不要增加单元格也不要删除单元格，顺序也不能错，代码运行不能出错，运行结果可以有小差异。

**Comment by gaoteng-pro** [comment]
你这个运行会报错吧，第一句等式右边的f没有被定义。

**Comment by tyler1zhang** [comment]
> 你这个运行会报错吧，第一句等式右边的f没有被定义。

不会，这个是其中的一个cell。之前的 `f` 已经被赋值为 `False`.
