### ISSUE TITLE
先 print 后 return 和先 return 后 print 结果为什么不同？

### ISSUE THREAD

**Issue by aosjiabei** [neolee/wop-community#71]
![image](https://user-images.githubusercontent.com/48588326/86623703-93c04c00-bff4-11ea-9ccd-0d3f231d20ef.png)
**为什么先return后print ，return值不输出到屏幕上？**

**Comment by gaoteng-pro** [comment]
解释器在看到`return`关键字后，就会结束整个函数，所以第二个函数的`print(1)`不会被执行。
