### ISSUE TITLE
which touch 这两个命令要装一个什么软件才能用？

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#72]
在支线课程，目录，文件和命令行里，李骏老师说到，which，touch这两个命令，在Windows下都是没有到，要安装一个什么软件才能用，我听了好几遍，都没有听清楚是什么软件，有没有哪位同学知道的？谢谢！

**Comment by neolee** [comment]
为啥不仔细看环境配置指南呢……

<img width="570" alt="busybox" src="https://user-images.githubusercontent.com/24796/86707656-c39a3e80-c04a-11ea-85e6-a9c7d35ec4bb.png">

**Comment by Amy20191** [comment]
李骏老师，根据环境配置指南里的内容，环境是配置好了，我电脑上which touch 是能用的，但是不知道是因为装了哪个软件以后可以用的，视频课程里没听清楚，所以这里问一下。是装了Windows Terminal后才能用的吗？

**Comment by Amy20191** [comment]
我把busybox也装一下。

**Comment by Amy20191** [comment]
明白了，是因为装了busybox，所以能用which touch 的命令了。

**Comment by neolee** [comment]
你是不是看不到我贴的图呀？如果是的话，可以考虑按照这个仓库首页最下面的方案配置下 hosts 文件： https://github.com/neolee/wop-community

**Comment by Amy20191** [comment]
嗯嗯，好的。
