### ISSUE TITLE
关于 isinstance 函数得出错误答案的问题

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#73]
练习学习用书上的一个题，关于自己实现一个type()函数，但是我发现有一处该输出bool值的地方，居然输出int（无论输入Fal se 还是 True都一样），是不是软件出问题了？求老师解答。
<img width="765" alt="image" src="https://user-images.githubusercontent.com/52586220/86722400-6eb1f480-c059-11ea-9748-5baa33abcb87.png">

**Comment by neolee** [comment]
恭喜发现本课程的第一个彩蛋。

实际上，Python 里的 [bool 类型是继承自 int 类型](https://docs.python.org/3/library/functions.html#bool) 的，等我们学了面向对象的概念就知道这可以表述为“bool 是 int 的子类”，所以一个 bool 类型的值确实是 int 类型的实例。至于为啥这么设计，我猜测是为了兼容 C 语言代码，因为 Python 底层实现高度依赖于 C 语言，数据类型更是直接从 C 拿来的。

p.s. 在你的函数实现中，通过简单的代码调整可以解决这个问题，你试试？

**Comment by aosjiabei** [comment]
![image](https://user-images.githubusercontent.com/48588326/86771224-6f13b500-c084-11ea-8282-df3fbea0cd0f.png)
**哈哈，从上面代码的执行结果来看，bool值（Ture and False）既是int型，又是bool型。
python文档里说：The bool class is a subclass of int.(bool是int的子类)，get it！**

**Comment by Liujiale02** [comment]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/52586220/86788249-88bef780-c098-11ea-922a-2c4a60711e81.png">

把验证bool类型的调到前面就可以了，学到了！
