### ISSUE TITLE
jupyterlab 上的输出显示问题

### ISSUE THREAD

**Issue by aosjiabei** [neolee/wop-community#74]
![IMG_202062_038_1458359775](https://user-images.githubusercontent.com/48588326/86766374-08d76400-c07d-11ea-8f13-cd57eb44ea86.png)
**为什么第2个type()不输出结果**

**Comment by neolee** [comment]
这是个常见的问题，明天上课会讲。

**Comment by tyler1zhang** [comment]
只有`print()`命令一定会输出结果，其他的命令如果不在最后一行，jupyter lab不会在这个cell下面输出结果。 比如你的`type(2)`，你只是告诉计算机让它计算这个命令，**把结果保存在内存中**， 并没有通知它要输出。 
这里jupyter lab 为了方便用户使用，所以才默认print最后一行的结果。但这个并不是程序的真正的输出。你可以尝试一下把下面的代码写成一个`test.py`然后在命令行运行`python test.py` 或 `python3 tets.py`。你在Terminal中得不到任何输出

```python
type(2)
f = False

```
