### ISSUE TITLE
Please enter a number 对话框问题

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#75]
![error](https://user-images.githubusercontent.com/53089964/86799748-db9eac00-c0a4-11ea-9077-2dd510121737.PNG)

请问出现对话框重复这种现象是对的吗？我的理解是一个对话框可以重复输入值，可以通过优化程序解决吗？

**Comment by neolee** [comment]
这个是 nteract 的实现模式，你可以试试用 Jupyter Lab，那个实现比这个好一点。

**Comment by wangcong-creator** [comment]
明白。谢谢老师。
