### ISSUE TITLE
关于 randrange

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/wop-community#76]
课程里`randrange(a,b)`函数的参数列表是两位，因为`randrange`和`range`有些相似，所以试了一下三个参数的情况，如下图：
<img width="356" alt="截屏2020-07-07 下午11 10 01" src="https://user-images.githubusercontent.com/57254889/86801879-0e49a400-c0a7-11ea-8289-38626c298476.png">
不知道那个缺省的值是啥意思，是步长吗？

另外，我们如何去看一个函数的源代码，比如`type` `range` `randrange`等等。

**Comment by neolee** [comment]
1. https://docs.python.org/3.7/library/random.html?highlight=randrange#random.randrange

2. Python 是个很大的体系，包括从语言核心到核心库、内置库和各种第三方库，所以要分情况考虑。核心部分在这里 https://github.com/python/cpython
