### ISSUE TITLE
input 执行结果

### ISSUE THREAD

**Issue by onthebus98** [neolee/wop-community#77]
请教:为什么这两段代码执行结果不同呢?第二段为什么没有输入框出现?
![1](https://user-images.githubusercontent.com/53966721/86804966-03444300-c0aa-11ea-899e-7a6935551f47.png)

**Comment by neolee** [comment]
你前一个单元格还没输入，也就么执行完，这个 notebook 背后的 Python 解释器引擎还在等你输入——后一个单元格还没轮到执行呢。

**Comment by onthebus98** [comment]
谢谢老师。
