### ISSUE TITLE
代码运行出错，好几行都是首字母未定义，is not defined

### ISSUE THREAD

**Issue by Denny-Huang** [neolee/wop-community#78]
jupyter打开P1-3作业，逻辑运算部分输入代码后运行怎么都是反馈第一个变量没有命名，多次尝试都不成功。在ConEmu命令行里试又是成功的，多次认真输入，格式应该无误，且其他段代码输入后运行又是正常的。isinstance有一部分也出现同样问题，该不会是P1-3-structure-2.ipynb文件的这些段落有错吧？
![2](https://user-images.githubusercontent.com/58538336/86844754-13284b00-c0db-11ea-8ca3-efa66bc71f42.png)
![3](https://user-images.githubusercontent.com/58538336/86844768-16bbd200-c0db-11ea-963c-6476b24c45dc.png)
![4](https://user-images.githubusercontent.com/58538336/86845248-cabd5d00-c0db-11ea-8b08-b492ba8ee760.png)
![1](https://user-images.githubusercontent.com/58538336/86844777-19b6c280-c0db-11ea-9411-41eca0ced426.png)
![5](https://user-images.githubusercontent.com/58538336/86845265-d14bd480-c0db-11ea-872a-83f348103759.png)

**Comment by neolee** [comment]
定义 t 和 f 那个单元格你没运行过啊，看前面的中括号里都是空着的。

另外，啥叫“首字母”啊？

**Comment by Denny-Huang** [comment]
哦，我也看到中括号是空着的了，原来是没有运行的意思。
我说的首字母是每行的第一个字母，不严谨，改过来。
谢谢老师！
