### ISSUE TITLE
为什么 touch hello.py 无法执行？

### ISSUE THREAD

**Issue by coolcoollc** [neolee/wop-community#79]
我换成ehco hellpo.py就可以了，这是为什么呢?
另外，python hello.py执行后也没有反应。换成py hello.py 就可以了。

PS C:\Users\Toefl> cd ~/code
PS C:\Users\Toefl\code> touch hello.py
touch : 无法将“touch”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ touch hello.py
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (touch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Toefl\code> echo hello.py
hello.py
PS C:\Users\Toefl\code> code hello.py
PS C:\Users\Toefl\code> python hello.py
PS C:\Users\Toefl\code> python3 hello.py
PS C:\Users\Toefl\code> py hello.py
4 + 9=13

**Comment by neolee** [comment]
大概是因为你没有装 busybox，所以没有 `touch` 这个命令。你直接 `code hello.py` 也可以打开一个名叫 hello.py 的空文件，但你需要手工保存下它才会真的写到硬盘上。

`echo` 命令其实啥也没干，就把你写在它后面的东西原样回显罢了。

**Comment by coolcoollc** [comment]
> 大概是因为你没有装 busybox，所以没有 `touch` 这个命令。你直接 `code hello.py` 也可以打开一个名叫 hello.py 的空文件，但你需要手工保存下它才会真的写到硬盘上。
> 
> `echo` 命令其实啥也没干，就把你写在它后面的东西原样回显罢了。

**Comment by coolcoollc** [comment]
> 大概是因为你没有装 busybox，所以没有 `touch` 这个命令。你直接 `code hello.py` 也可以打开一个名叫 hello.py 的空文件，但你需要手工保存下它才会真的写到硬盘上。
> 
> `echo` 命令其实啥也没干，就把你写在它后面的东西原样回显罢了。

busybox我一直没有装成功，显示的是：
PS C:\Users\Toefl> scoop install busybox
Couldn't find manifest for 'busybox'.

**Comment by neolee** [comment]
`scoop update` 应该没成功。

busybox 不装也没啥，就是图个方便，都有替代方案。

**Comment by coolcoollc** [comment]
谢谢老师，搞定了。重新安装了一下scoop，然后升级了。
install什么软件都没问题了。今天上课嗓子哑了，多休息多喝水，早日康复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 下午5:06
收件人:&nbsp;"neolee/wop-community"<wop-community@noreply.github.com&gt;;
抄送:&nbsp;"托福_刘畅"<22345431@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/wop-community] 为什么 touch hello.py 无法执行？ (#79)





 
scoop update 应该没成功。
 
busybox 不装也没啥，就是图个方便，都有替代方案。
