### ISSUE TITLE
Mac 自带 python 版本是 2.7 如何更新？

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#8]
老师你好，第一次用Mac系统，有很多问题需要请教你。

>我在终端那里安装了python 但是版本有点低2.7.16，要怎样更新到最新版本？
网上找了一些教程，操作起来好复杂，也失败了几次。

请老师指导，谢谢

**Comment by neolee** [comment]
系统自带的 Python 是没法手工更新的，也不要去动它。正确方法是另外安装一个我们需要的 3.7.4 版本，然后用这个版本就行了，具体操作请在课程目录里点开“课程配套资源”，然后点击“附录”下的第一个“编程环境指南”，按照里面 macOS 一节按部就班的操作，如有问题可以在这个问答空间里提出 issue。

我记得你已经安装过 Homebrew，可能也用 Homebrew 装了 Python 3.7.4，但有可能你运行 `python` 是指向系统内置的老版本，而 `python3` 才指向新装的那个，可以通过简单的几个命令让 `python` 命令指向你新装的版本，上述指南中就有说明如何操作。
