### ISSUE TITLE
支线课程 Markdown - VS Code 编辑器调出命令 Instant Markdown: Open Browser 执行报错

### ISSUE THREAD

**Issue by kekeyumuku** [neolee/wop-community#80]
错误提示为：Command 'Instant Markdown: Open Browser' resulted in an error (command 'instantmarkdown.openBrowser' not found)

此命令不存在？还需要为编辑器设置什么吗？
<img width="1624" alt="截屏2020-07-08 下午4 07 07" src="https://user-images.githubusercontent.com/25841942/86894210-58796680-c135-11ea-9665-d52304e8e510.png">

**Comment by jiaobufan** [comment]
1.查看一下instant markdown插件是否安装好了。
![image](https://user-images.githubusercontent.com/63732336/86896387-76949600-c138-11ea-87b4-24a57b6d0f2e.png)
2. 如果安装好了，打开一个markdown文档，按下ctrl + shift +p，如下图选择一下就会弹出个浏览器窗口了。
<img width="960" alt="1594197204(1)" src="https://user-images.githubusercontent.com/63732336/86896772-13efca00-c139-11ea-86d6-a760797cb59b.png">

**Comment by kekeyumuku** [comment]
已经安装了呀
<img width="766" alt="截屏2020-07-08 下午4 36 28" src="https://user-images.githubusercontent.com/25841942/86896981-67faae80-c139-11ea-8034-e822070c0b48.png">

**Comment by jiaobufan** [comment]
> 已经安装了呀
> <img alt="截屏2020-07-08 下午4 36 28" width="766" src="https://user-images.githubusercontent.com/25841942/86896981-67faae80-c139-11ea-8034-e822070c0b48.png">

那执行下第二步看看

**Comment by kekeyumuku** [comment]
> > 已经安装了呀
> > <img alt="截屏2020-07-08 下午4 36 28" width="766" src="https://user-images.githubusercontent.com/25841942/86896981-67faae80-c139-11ea-8034-e822070c0b48.png">
> 
> 那执行下第二步看看

<img width="1113" alt="截屏2020-07-08 下午4 41 58" src="https://user-images.githubusercontent.com/25841942/86897752-6a113d00-c13a-11ea-9aaa-db3f3058f3a5.png">
![Uploading 截屏2020-07-08 下午4.42.12.png…]()

**Comment by kekeyumuku** [comment]
> > 已经安装了呀
> > <img alt="截屏2020-07-08 下午4 36 28" width="766" src="https://user-images.githubusercontent.com/25841942/86896981-67faae80-c139-11ea-8034-e822070c0b48.png">
> 
> 那执行下第二步看看

<img width="1113" alt="截屏2020-07-08 下午4 41 58" src="https://user-images.githubusercontent.com/25841942/86897850-8c0abf80-c13a-11ea-99b7-686ca4f38970.png">
<img width="1133" alt="截屏2020-07-08 下午4 42 12" src="https://user-images.githubusercontent.com/25841942/86897858-8e6d1980-c13a-11ea-9f9c-f4bc9b22dd29.png">

**Comment by kekeyumuku** [comment]
重新启动编辑器，再继续步骤2，可以调出浏览器了。
但是新问题又出现了，在文件里写得字符串，在浏览器页面不显示。

http://localhost:8090 这个是浏览器页面地址

**Comment by jiaobufan** [comment]
> 重新启动编辑器，再继续步骤2，可以调出浏览器了。
> 但是新问题又出现了，在文件里写得字符串，在浏览器页面不显示。
> 
> http://localhost:8090 这个是浏览器页面地址

😄，那就只能终极大法了，卸载重装~

**Comment by kekeyumuku** [comment]
> > 重新启动编辑器，再继续步骤2，可以调出浏览器了。
> > 但是新问题又出现了，在文件里写得字符串，在浏览器页面不显示。
> > http://localhost:8090 这个是浏览器页面地址
> 
> 😄，那就只能终极大法了，卸载重装~

哈哈，牛逼。我再试试，不行就这么办

**Comment by jiaobufan** [comment]
卸载插件，不是卸载vscode哦

**Comment by neolee** [comment]
你有没有在运行什么防病毒工具之类的？

**Comment by kekeyumuku** [comment]
> 卸载插件，不是卸载vscode哦

我试试

> 你有没有在运行什么防病毒工具之类的？

我装了php环境，会不会有影响呢？

**Comment by kekeyumuku** [comment]
> 你有没有在运行什么防病毒工具之类的？

我装了php环境，会不会有影响呢？

**Comment by kekeyumuku** [comment]
> 卸载插件，不是卸载vscode哦

明白，刚试过了，还是不行

**Comment by jiaobufan** [comment]
> > 卸载插件，不是卸载vscode哦
> 
> 明白，刚试过了，还是不行

那你发现bug了，重启一下机器试试了。。。

**Comment by jiaobufan** [comment]
再就最后的方法了，google下看有没有什么答案，这问题还真是没有遇见过。

**Comment by jiaobufan** [comment]
还有个可能是浏览器的问题，你是chrome吗？

**Comment by neolee** [comment]
其实 VS Code 里关于 Markdown 的插件不少，要是这个实在太妖，可以试试别的，比如最近很受好评的 Markdown All in One。

**Comment by jiaobufan** [comment]
> 其实 VS Code 里关于 Markdown 的插件不少，要是这个实在太妖，可以试试别的，比如最近很受好评的 Markdown All in One。

😄，嗯嗯，我一般编辑markdown不用其他工具，习惯了用Typora，开发工具一般只用来敲代码。

**Comment by kekeyumuku** [comment]
> 其实 VS Code 里关于 Markdown 的插件不少，要是这个实在太妖，可以试试别的，比如最近很受好评的 Markdown All in One。

默认是mac自带的浏览器打开的，我把地址复制到chrome,看到报错信息了
![Uploading 222.png…]()

**Comment by kekeyumuku** [comment]
> 其实 VS Code 里关于 Markdown 的插件不少，要是这个实在太妖，可以试试别的，比如最近很受好评的 Markdown All in One。

默认是在mac自带浏览器打开的，我用chrome复制这个地址打开，出现报错信息了
<img width="1170" alt="222" src="https://user-images.githubusercontent.com/25841942/86904067-be201f80-c142-11ea-81ca-7bda21c88b72.png">

**Comment by kekeyumuku** [comment]
> > 其实 VS Code 里关于 Markdown 的插件不少，要是这个实在太妖，可以试试别的，比如最近很受好评的 Markdown All in One。
> 
> 😄，嗯嗯，我一般编辑markdown不用其他工具，习惯了用Typora，开发工具一般只用来敲代码。

恩呢，我研究下
