### ISSUE TITLE
nteract 软件无法打开

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/wop-community#83]
Windows系统，下载网址：https://nteract.io/
下载软件：

![图片](https://user-images.githubusercontent.com/57054269/86992963-55ce4e00-c1d5-11ea-82c5-e9e5f88df123.png)

安装后运行和使用快捷键两种方式打开，只是nteract的图像在转动，打不开软件，也没有任何错误提示，
![图片](https://user-images.githubusercontent.com/57054269/86993087-ad6cb980-c1d5-11ea-979a-ab3975633d8f.png)
![图片](https://user-images.githubusercontent.com/57054269/86993100-b5c4f480-c1d5-11ea-93e5-a3b70661de18.png)

**Comment by neolee** [comment]
你直接在文件管理器里找到一个 notebook（.ipynb 文件），右键，能用 nteract 打开它吗？

**Comment by wenwen-shan** [comment]
可以打开文件，后面配置正常，我之前的思路一直是从桌面的快捷键处打开。

**Comment by neolee** [comment]
据我所知你碰到的是 nteract 0.24 的一个 bug，但可以用我说的方法绕过——彻底解决等更新吧。

**Comment by wenwen-shan** [comment]
好的，谢谢老师。
