### ISSUE TITLE
关于 ValueError 的疑问

### ISSUE THREAD

**Issue by YunHang1010** [neolee/wop-community#84]
<img width="725" alt="iuuse-1" src="https://user-images.githubusercontent.com/60560117/86998076-2ffb7600-c1e2-11ea-9b66-85b10f74e63a.png">

怎样输入才能看出区别？

**Comment by neolee** [comment]
在这个例子里比较难看出差别，因为 try 的那段代码基本上只会出 ValueError。

你可以在 `break` 前补充一行代码，比如 `print(42 / x)`，然后运行时输入个 0，可能就能看出差异了。
