### ISSUE TITLE
作业本里代码运行后前面不是数字而是*

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#85]
![image](https://user-images.githubusercontent.com/57065555/87001624-7b198700-c1ea-11ea-8fde-433f06db7162.png)
这两段代码，第一次运行后前面是*，如果我在“请输入您的姓名”出来之后，输入了名字，回车，代码前会显示数字，而如果我在“请输入您的姓名”出来后，不输入东西，而是选中代码段，按shift+回车再次执行代码，代码段前面会一直是*，而且“请输入您的姓名”这行字也一直出不来了，这是什么原因？
如果前面是*，作业本这样保存后，提交，这个作业算是正确了吗？

**Comment by neolee** [comment]
当出现输入提示时，代码运行其实是停在 `input()` 这个函数调用，等你输入并回车之后才会返回——所以这时候这个单元格其实没执行完，自然也没有任何执行结果，其前面的 [] 里是 * 而不是执行完毕的数字序号。

更严重的是，每个 notebook 背后都是一个 Python 解释器，Python 解释器是单线式运行的，一行一行代码的解释和运行，由于前面的代码未执行（在等你交互），这个解释器就挂在那里了，之后什么事情也不会干。

所以如果你保存提交这个 notebook，所以 [*] 以后的单元格都处于“未运行”状态，即未完成的状态。

这个问题要解决也很容易：1. 不要在需要你输入的时候跳过；2. 出现这种挂起的情况，在菜单里选择 Kernel - Restart Kernel 就可以重启 kernel（即背后的 Python 解释器），恢复到原始状态——然后你需要从头运行每一个代码单元格。

**Comment by Amy20191** [comment]
好的，明白了。谢谢！
