### ISSUE TITLE
各种程序的关系问题

### ISSUE THREAD

**Issue by worldhuili** [neolee/wop-community#87]
老师，命令行和代码运行是什么关系呢，命令行的指令和运行代码是一回事？
命令行和python、Vs Code、Jupyter Lab、nteract之间有什么关系呢？这些之间的联系感觉比较混乱~
Vs Code是程序源代码编辑器，为何也可以运行代码呢，代码运行是靠什么？

**Comment by worldhuili** [comment]
运行代码是需要像命令行那样发布指令是吗，所以Vs Code、Jupyter Lab、nteract里是内嵌Python和命令行吗，是它们的结合体？是这样吗老师，我的猜想~

**Comment by neolee** [comment]
越是基本的问题越难回答……我尝试解释下。

1. 命令行那个窗口其实分成两层：一层是外面那个 Terminal 或者 Windows Terminal（或者有的同学用的 ConEmu），这叫“终端模拟器”，这一层的作用是模拟老实计算机终端，提供输入输出的文字界面，以及和计算机操作系统的交互；另一层是你在进入这个窗口时优先运行的一个环境程序，Windows 下是 PowerShell，macOS 下是 bash 或者 zsh，这些程序叫做“shell”，提供给你在命令行里输入各种命令的能力。

2. 一般来说各种 shell 都支持两种命令：一种是 shell 本身内置的命令，比如 ls 就是列出当前目录下的所有文件和目录，cd 是改变当前工作目录；另一种是 shell 也允许你执行其他程序，比如 python、brew、scoop 这些都不是 shell 内置的命令，而是你的计算机里安装好的其他程序，当你在命令行里输入这些程序的名字并回车时，shell 会找到这些程序并运行它们。

3. 无论是 shell 内置的命令还是外部程序如 python 等，它们运行时都支持你输入一些参数，这些参数可以改变它们运行时的行为表现。

4. 有些程序（以及参数）可以做很复杂的事情，比如 `python xxx.py` 可以运行 Python 程序（xxx.py），`python` 则会启动解释器，让你可以交互式的运行 Python 代码。

5. Jupyter Lab 是用 Python 和 JavaScript 写的一个程序，运行它会启动一个本地的网站服务，然后打开浏览器连到这个网站服务上显示出一个网页，这个网页就是我们看到的 Jupyter Lab 页面。

6. Visual Studio Code 和 nteract 都是独立的程序，它们有自己的图形化界面，启动后会打开自己的窗口完成各种复杂的任务。其中 Visual Studio Code 格外的复杂，搞清楚它的所有环节对目前的你来说几乎是不可能的，所以暂时不用纠结这个事情，但可以了解一点：Visual Studio Code 主窗口是个文本编辑器，但它也可以打开一个“终端模拟器（Terminal）”，其效果和你独立的打开一个 Terminal 或者 Windows Terminal 是类似的。

----

如果觉得太复杂，目前只需要了解以下要点：
* 命令行是命令行，程序代码是程序代码，不是一回事；
* Visual Studio Code 是代码编辑器，它本身并不能运行你的 Python 代码，它运行你的代码是在它自己的窗口里打开了一个命令行子窗口，然后运行了 `python xxx.py` 这样的命令，和你自己在命令行窗口运行这个命令没什么不一样。

**Comment by worldhuili** [comment]
谢谢老师耐心的解惑，真的很认真负责，因为是小白，提问的时候总会想自己的问题会不会很幼稚，会不会不值得提呢，看到老师的这么多回答觉得很感动，也给了自己继续好好学习编程的信心~我加油······

**Comment by aosjiabei** [comment]
想起来Vscode一开始配置的时候，需要select python interpreter，那么代码就是选择的python解释器执行的
