### ISSUE TITLE
无法在 macOS 的 Terminal 使用 python 指令调用 Python 3.7.x

### ISSUE THREAD

**Issue by shen-huang** [neolee/wop-community#88]
# 问题表现

无法在 macOS 的 Terminal 使用 `python` 指令调用 Python 3.7.x（调出的是系统自带的 Python 2.7），已建立软链接、已设置 PATH。

# 环境说明

- 硬件：MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) (Model A1706 EMC 3071)
- 系统：macOS Catalina (10.15.5)

# 问题描述

在《编程环境配置指南·macOS 篇·安装 Python》部分中提到：

> 在某些 macOS 系统中会内置一个老的 Python 2.7 的环境，而 `python` 命令会指向这个老的 Python 环境，这会给我们以后的操作带来不少麻烦，可以执行下面的命令来强制让 `python` 指向我们安装的 Python 3 的环境：
>
> ```bash
> rm /usr/local/bin/python
> ln -s /usr/local/bin/python3 /usr/local/bin/python
> ```

执行这部分中第一行的 `rm` 命令时，系统提示“No such file or directory”，由于这条命令的目的是为了删掉这个软链接，这种情况恰合其意。继续执行 `ln -s` 命令，顺利完成，软链接也成功建立了。

但在这个时候，运行
```bash
python -m pip install --upgrade pip
```
系统会提示：
> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip

这说明使用 `python` 调用的仍然是系统自带的 Python 2.7，版本检查命令也证实了这一情况：

<img alt="python -V" src="https://user-images.githubusercontent.com/53881314/87036259-1e838f80-c21d-11ea-85cf-358471fa2c98.png">

使用 `ls -l` 检查了软链接，确实是有的：

<img alt="ls -l python*" src="https://user-images.githubusercontent.com/53881314/87036966-21cb4b00-c21e-11ea-9331-161f9a4f5be6.png">

也检查了 PATH，`/usr/local/bin` 也是在最前面：

<img alt="PATH" src="https://user-images.githubusercontent.com/53881314/87037255-85ee0f00-c21e-11ea-892e-581c2e3dea93.png">

# 问题解决

在 @Xuzhengfu 的提醒下，我认真地读了一遍《[*How to set Python3 as a default python version on MacOS?*](https://dev.to/malwarebo/how-to-set-python3-as-a-default-python-version-on-mac-4jjf)》（[Irfan](https://dev.to/malwarebo)，2020 年 6 月 10 日），试着运行了一下：

```bash
ln -s -f /usr/local/bin/python3.7 /usr/local/bin/python
```

这个命令与最初的目的稍微有一点偏离，在我看来，这个命令实际上是强制建立了 `python` 到 `python3.7` 间的软链接，如果将来 Python 升级到了 3.8.x，这个链接就可能会失效，还得重新建。不过眼下如果它能解决问题，尝试一下也没什么坏处。

运行之后问题解决了。

我和 @neolee 老师进一步交流的时候，老师表示：

> 〔出现这种情况〕从逻辑推理来说只有一个可能，就是 /usr/local/bin/python 那个符号链接有问题。
> 我觉得你用
> ```bash
> rm /usr/local/bin/python
> ```
> 然后
> ```bash
> ln -s -f /usr/local/bin/python3 /usr/local/bin/python
> ```
> 应该也会好

我照做了一遍，发现确实好了。

对于这个故障，@neolee 老师分析说：

> 所以真相应该是，你最早创建那个符号链接的时候不知道发生了啥，虽然连接了，但是实际上没工作（因为现场难以考察，这个就成了谜团），所以 shell 认为那不是个可以执行的东西，于是跳过，找下一个 python，于是找到系统自带的 2.7。

另外关于 `ln` 的 `-f` 参数，@neolee 老师提醒：

> 我从来不用 `-f`，因为怕无意中覆盖掉已有的 link，如果已存在同名 link，`ln` 会报错，我就会去检查看是啥，如果确认可以覆盖就手工 rm 或者 unlink 掉，从来没问题，`-f` 参数不是问题所在。

最后 @neolee 老师总结：

> 就是那一次 `ln` 出了怪事，其他都是正常的。
> 当时到底发生了什么已不可考，**施主请放下吧**……

**Comment by xuzhengfu** [comment]
这篇文章可能对你有所帮助：

> https://dev.to/malwarebo/how-to-set-python3-as-a-default-python-version-on-mac-4jjf

但在[这篇文章](https://opensource.com/article/19/5/python-3-default-mac)中，作者旗帜鲜明的表达了自己的观点：

> "The basic premise of all Python development is to never use the system Python. You do not want the Mac OS X 'default Python' to be 'python3.' You want to never care about default Python."
> 
> ...... Moshe recommends using pyenv to manage Python environments.

**Comment by shen-huang** [comment]
@Xuzhengfu 我昨天看到过这篇文章了，他建议是用环境设置的方法来实现这个需求，我觉得在编程课的前期这样处理有点太折腾了，还不如直接用 `python3` 来调用 Python 3.7.x 处理 pip 的相关设置呢。

我是想知道建立软链接的方式为什么没起作用，是新版的 macOS 修改了什么策略，还是我哪里没做对。

**Comment by xuzhengfu** [comment]
你看看第一个链接…… （很多人遇到了和你一样的问题）

**Comment by shen-huang** [comment]
@Xuzhengfu 我也看过第一个链接，看的时候我没试，因为我觉得它建立的不是我想建的那个链接，你强调了一下之后我觉得试试也无妨，就运行了一下，发现问题解决了。

谢谢你！
