### ISSUE TITLE
Homebrew 更新后 pip3 和 jupyterlab 提示“bad interpreter: No such file or directory”

### ISSUE THREAD

**Issue by hendasheng** [neolee/wop-community#89]
## 系统
macOS Catalina 10.15.5
## 问题
用 Homebrew 安装其它工具，没想到 Homebrew 先把自己更新了一遍，现在 python 版本是 3.8.3.
但是 pip3 和 jupyterlab 都不能用了，提示：

<img width="683" alt="截屏2020-07-09 21 46 35" src="https://user-images.githubusercontent.com/20842136/87047903-abcee000-c22d-11ea-99f3-3e2ec2b76965.png">

在网上找到[解决方法](https://blog.csdn.net/toopoo/article/details/99956326)

<img width="997" alt="截屏2020-07-09 21 49 46" src="https://user-images.githubusercontent.com/20842136/87048327-2861be80-c22e-11ea-91c2-a9da08e1b0ec.png">

前两步都没问题。

<img width="684" alt="截屏2020-07-09 21 53 30" src="https://user-images.githubusercontent.com/20842136/87048736-b047c880-c22e-11ea-98d3-12190d33de9b.png">

但是最后一步

> “编辑/usr/local/bin/pip, 第一行更改为/usr/local/bin/python或者/usr/bin/env python”

实在想不明白该怎么操作，请问这个问题如何解决，非常感谢。

**Comment by neolee** [comment]
你先执行 `brew info python`，把结果给我看看。

**Comment by hendasheng** [comment]
> brew info python

<img width="701" alt="截屏2020-07-09 23 51 24" src="https://user-images.githubusercontent.com/20842136/87062048-1e948700-c23f-11ea-8ce6-7b139c7a8efc.png">

**Comment by neolee** [comment]
试试这个：`python -m pip install -U pip`

**Comment by hendasheng** [comment]
<img width="698" alt="截屏2020-07-09 23 55 59" src="https://user-images.githubusercontent.com/20842136/87062544-c01bd880-c23f-11ea-8efd-d602f5b2bd75.png">

**Comment by neolee** [comment]
哦，你没做 python 的别名，那么就 `python3 -m pip install -U pip`

**Comment by hendasheng** [comment]
<img width="701" alt="截屏2020-07-09 23 58 42" src="https://user-images.githubusercontent.com/20842136/87062810-21dc4280-c240-11ea-8dd8-29e6652b1f18.png">

**Comment by hendasheng** [comment]
<img width="746" alt="截屏2020-07-10 00 02 33" src="https://user-images.githubusercontent.com/20842136/87063238-ab8c1000-c240-11ea-985a-6dd6a36e795d.png">

这个应该是网络问题把？重新运行了一次，现在正在下载。

**Comment by neolee** [comment]
升级 pip 不成功，网络问题。我们先把这个放一边，先解决你的 pip 找不到正确的 python 解释器的问题。

执行下面的命令：

```shell
ls -l /usr/local/bin/python*
ls -l /usr/local/bin/pip*
```

**Comment by hendasheng** [comment]
<img width="697" alt="截屏2020-07-10 00 04 51" src="https://user-images.githubusercontent.com/20842136/87063459-fdcd3100-c240-11ea-9883-f9d009d8c304.png">

老师，这个装好啦

**Comment by hendasheng** [comment]
<img width="695" alt="截屏2020-07-10 00 05 48" src="https://user-images.githubusercontent.com/20842136/87063583-2523fe00-c241-11ea-9fa3-6d9fa12050a3.png">

<img width="693" alt="截屏2020-07-10 00 05 56" src="https://user-images.githubusercontent.com/20842136/87063590-281eee80-c241-11ea-96ac-e82229c026c0.png">

**Comment by neolee** [comment]
应该有两个办法可以解决你的问题。

方法一：执行 `brew switch python 3.7.7`。这会让 Homebrew 切换 Python 到 3.7.7 版本，而且理论上不会随便升级到 3.8 了。

方法二：执行 `code /usr/local/bin/pip3`，这会打开 pip3 命令的源程序，其中第一行是 pip3 使用的 Python 解释器的完整地址，将第一行改为下面这样就行了：

```python
#!/usr/local/opt/python@3.8/bin/python3.8
```

我比较推荐你用第一个方法。

**Comment by hendasheng** [comment]
<img width="690" alt="截屏2020-07-10 00 13 58" src="https://user-images.githubusercontent.com/20842136/87064411-4802e200-c242-11ea-9ccc-df74ba44cafe.png">

谢谢老师，我用了第一个方法。

**Comment by hendasheng** [comment]
<img width="688" alt="截屏2020-07-10 00 15 04" src="https://user-images.githubusercontent.com/20842136/87064507-6a94fb00-c242-11ea-9070-c1db81a6e366.png">

JupyterLab 也可以启动。

**Comment by hendasheng** [comment]
<img width="690" alt="截屏2020-07-10 00 13 58" src="https://user-images.githubusercontent.com/20842136/87064921-f1e26e80-c242-11ea-8407-182ac9caa303.png">

老师还有一个问题，这里应该执行哪一项？

**Comment by neolee** [comment]
执行 `brew link --overwrite python`

**Comment by hendasheng** [comment]
<img width="692" alt="截屏2020-07-10 00 35 48" src="https://user-images.githubusercontent.com/20842136/87066533-50105100-c245-11ea-90df-bdecd5aaf985.png">

**Comment by neolee** [comment]
现在 `pip -V` 和 `jupyter lab` 应该正常了吧？

**Comment by hendasheng** [comment]
<img width="703" alt="截屏2020-07-10 00 41 37" src="https://user-images.githubusercontent.com/20842136/87067070-23a90480-c246-11ea-9078-10d0d323d8b1.png">

jupyter lab 也正常了 🎉，谢谢老师 ：）
