### ISSUE TITLE
nteract 中图片无法显示

### ISSUE THREAD

**Issue by moonwmh** [neolee/wop-community#9]
下载了第一节的作业，跟课本对照后有这个问题：

课本：
![image](https://user-images.githubusercontent.com/48578043/85916171-9b5b5480-b880-11ea-8c4f-3fed8a9b224a.png)

作业本：
![image](https://user-images.githubusercontent.com/48578043/85916175-aa420700-b880-11ea-9140-3607f0940288.png)

请老师指教，谢谢！

**Comment by neolee** [comment]
是的，nteract 打开学习用书会有这个问题，不过影响不大，因为你是看着在线教材（会正确显示图片），然后在学习用书里填空完成作业。

如果希望在学习用书中也能够完整的显示所有图片，nteract 就比较麻烦，用“如何使用配套学习用书”中的 Jupyter Lab 的方式是可以的，但方便性就不如 nteract 了——所以做作业我还是推荐用 nteract。
