### ISSUE TITLE
关于幂次运算问题

### ISSUE THREAD

**Issue by yyd841122** [neolee/wop-community#90]
```python
x = 2
y = 3
z = x ** y
print(z)
z **= y
print(z)
print(f'x ** y ** y = {x} ** {y} ** {y} = {x ** y ** y}')
```
Value:
```python
z = 512
```
But Value:
```python
x ** y ** y = 2 ** 3 ** 3 = 134217728
```

Why not 512??

**Comment by neolee** [comment]
哈哈，你找到了一个神级的有趣问题。

首先，在 Python 官方文档关于 power operator（幂操作符）的说明中有[这么一段话](https://docs.python.org/3/reference/expressions.html#the-power-operator)：

> …in an unparenthesized sequence of power and unary operators, the operators are evaluated from right to left (this does not constrain the evaluation order for the operands)…

也就是说，如果有多个幂操作符和正负号操作符连在一起，要从右往左计算求值。这可以解释你得到的结果了。

但是，你应该会有下一个问题：为啥会有这么个奇怪的规定啊？这也是有原因的。

如果从左向右计算，那么 2 ** 3 ** 3 就等于 (2 ** 3) ** 3，这实际上就等于 2 ** (3 * 3)，你就没必要用两个幂操作符了。非要用两个幂操作符才能表示的，恰恰是从右向左计算的 2 ** (3 ** 3)，这种情况下就可以省略掉括号。

**Comment by catynchyna** [comment]
`z **= y` 就给喵整懵一秒钟。还好昨天有认真听老师上课，立马联想到 `+=` 的意思可套用：`z = z ** y`
```
 z = x ** y
z **= y # aka z = z ** y 
```
数学运算：2 ** 3 ** 3 = (2 ** 3) ** 3 = 2 ** (3 * 3) 中学喵肯定是在睡觉中度过了。
服气了。**今天晚上涨见识了～开心！** *谢谢*

**Comment by yyd841122** [comment]
这个问题我是这么发现的
a = 2 
b = 3
c = 4

x = 1
y = 2
z = 3


x *= a + 2
y /= b - 1

z **= c + 1 

print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

----------------------------

x,y的值都是先算 *   / ,这两个运算，
当我求z值的时候，发现和我想的不对，然后我想到了要是连续几个这样**的运算，会是什么结果，后来发现和我想的不一样。我就提问来了。  
------
老师解释了，我也想通了，当时是总感觉不对。
