### ISSUE TITLE
异常处理一章的第2个例子

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#91]
![image](https://user-images.githubusercontent.com/57065555/87119671-37d61b80-c2b1-11ea-87cb-beb43182f16b.png)
教材中，异常处理那一章，第二个例子，如上截图，有点看不懂，定义的函数this_fails()，下面可以写1/0，赋值给x？
还有下面的err，也不懂。

**Comment by neolee** [comment]
这个例子演示了两个知识点。

1. 一个函数本身会出现运行时异常（runtime exception，或者叫 runtime error），如果把这个函数的调用放到 `try...except` 异常处理结构中，就可以捕获它内部的异常。至于 `1 / 0` 这种代码只是个例子，正常程序肯定不会这么写，写了倒也不违法，只是调用的时候会扔出异常来。

2. 当 `try` 后面的代码扔出异常的时候，Python 解释器会自动生成一个“异常对象”，这是一个特殊的值（我们后面会讲），里面包含了异常的具体信息，`except ZeroDivisionError as err` 的意思是：如果 `try` 后面出现了 `ZeroDivisionError` 类型的异常，就执行下面的代码块，并且把相关的异常信息赋值给 `err` 这个变量。于是在 `except` 后面的代码里就可以访问 `err` 这个变量来获取异常的具体信息。

**Comment by Amy20191** [comment]
嗯嗯，过程理解了。谢谢！

**Comment by gaoteng-pro** [comment]
> 如果 try 后面出现了 ZeroDivisionError 类型的异常，就执行下面的代码块，并且把相关的异常信息赋值给 err 这个变量。于是在 except 后面的代码里就可以访问 err 这个变量来获取异常的具体信息。

`except`那句，只能是出现`ZeroDivisionError`才会执行下面的`print`，所以`as err`虽然是赋值，其实`err`只能是`ZeroDivisionError`。

在这个例子中，`as err`中`err`其实是确定的，是吧？

**Comment by neolee** [comment]
@gaoteng-pro `err` 这个变量的名字随便你取，当异常发生时，因为这个 `except` 子句只捕获 `ZeroDivisionError`，所以你拿到的 `err` 必定是 `ZeroDivisionError` 类型的。

**Comment by gaoteng-pro** [comment]
嗯，直接写`except as err`又不能捕捉错误类型赋值给变量`err`，因为会报错。所以只能在`except`与`as err`之间，自己主动加上报错类型，然后从中选一个赋值给`err`。

就是我们要使用 `except X as err`这个句型，`X`必须不能省掉，且必须是我们提前知道，还必须要写在`except`和`as err`之间的，这样理解对吧？

**Comment by neolee** [comment]
@gaoteng-pro 是的，因为你要捕获一个运行时异常并装进一个变量里，必须要确定这个异常的类型。

**Comment by gaoteng-pro** [comment]
👌
