### ISSUE TITLE
Visual Studio Code 中填写 commit message 不成功

### ISSUE THREAD

**Issue by Amy20191** [neolee/wop-community#92]
![image](https://user-images.githubusercontent.com/57065555/87149298-8c45bf00-c2e2-11ea-933a-7bc03d6088bd.png)

刚在看Visual Studio Code的支线课程，根据里面的内容试了一下，有个文件更改了，然后commit的时候，要填写commit message， 我填写了change-1，然后跳出了上面的信息，是要填写用户名还是什么意思？看不懂。
另外，文件更改后，不是已经保存了吗？为什么还要commit 一次呢？

**Comment by neolee** [comment]
这你就需要看另一个关于 git 的支线课程啦……

**Comment by Amy20191** [comment]
好的，那先看完git的支线课程再说。
