### ISSUE TITLE
赋值，遇到两个问题

### ISSUE THREAD

**Issue by jiangminghe** [neolee/wop-community#93]
1，f=3.14，f=False,type(f)时显示布尔，
2，l={1,2,3},type(l)显示set。
<img width="841" alt="截屏2020-07-10 下午10 02 45" src="https://user-images.githubusercontent.com/67852126/87163227-99ba7380-c2f9-11ea-8479-076ac0f8dec4.png">

**Comment by xuzhengfu** [comment]
1. 变量可以多次赋值，它（变量）的值与类型由最后一次赋值决定。

2. set 和 list 都是 python 的数据容器，关于数据容器的概念，会在后面章节讲到。

3. 列表（list）用的是 **方括号** —— **[]**，集合（set）用的是 **花括号** —— **{}**。

**Comment by liushui0712** [comment]
> 1. 变量可以多次赋值，它（变量）的值与类型由最后一次赋值决定。
> 2. set 和 list 都是 python 的数据容器，关于数据容器的概念，会在后面章节讲到。
> 3. 列表（list）用的是 **方括号** —— **[]**，集合（set）用的是 **花括号** —— **{}**。

学到了，花括号是set～～
