### ISSUE TITLE
字典里嵌套集合问题

### ISSUE THREAD

**Issue by wangcong-creator** [neolee/wop-community#94]
![2](https://user-images.githubusercontent.com/53089964/87167325-5cf17b00-c2ff-11ea-9a96-8b84cbf5507f.PNG)

老师，第49段程序执行没有问题，第50段程序有问题，这个问题原因是什么呢？'id'放在集合'mobile'之前和之后有什么区别呢？

**Comment by neolee** [comment]
`'id'` 的前一行行尾缺一个逗号。
