### ISSUE TITLE
电脑软件闪退，无法使用

### ISSUE THREAD

**Issue by mikan1013** [neolee/wop-community#95]
电脑打开后，微信登陆闪退，开始菜单单击也闪退，右键单击有时候可以打开，重启后也还是无改善。搜索网页可以打开，但输入不进去任何文字。
是中毒了吗？只能重装系统了吗
视频不知道怎么上传过来

**Comment by neolee** [comment]
看上去系统处于不稳定的状态，一般来说可能是硬件问题也可能是操作系统问题，当然也可能是中毒，最好找有经验的朋友看看或者直接送修。
