### ISSUE TITLE
对于新手来说，关于计算机原理的学习时机

### ISSUE THREAD

**Issue by learningtowritecode** [neolee/wop-community#96]
老师好，对于新手来说，想要系统学习计算机原理是在WOP课程学习完成之后开始比较合适，还是同步进行更好？谢谢。

**Comment by neolee** [comment]
一般来说是学完 WoP 入门课程之后。

但同步看起来也没问题，我觉得可以试着读读，如果感觉是跳起来能够得着的状态，就值得继续，否则可以先放放。

**Comment by learningtowritecode** [comment]
谢谢老师
