### ISSUE TITLE
对象实例化后为什么有些方法后面加括号有些不用加？

### ISSUE THREAD

**Issue by Liujiale02** [neolee/wop-community#97]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/52586220/87217009-6f0f0000-c377-11ea-974d-cb20ed1ac2d0.png">

上面截图是类定义与对象创建的一个例子。我想问下：

**为什么实例化后有些方法后面接括号，有些方法可以不加？什么情况下需要加括号呢？
类变量也要加括号吗？如果要加会在什么情况下？**

**Comment by neolee** [comment]
对象的方法是一种“函数”，是附属于对象的函数，而所有的函数的调用都必须加上括号（即使没有输入参数也需要）。

你看到没有括号的那些都不是“方法（method）”，而是“属性（attribute 或者 property）”，属性是一种“值”，是附属于对象的变量，自然不能加括号。

当然，后面你会学到“函数”其实也是一种“值”，其唯一特殊之处就是后面有括号……

**Comment by Liujiale02** [comment]
明白
