### ISSUE TITLE
赋值操作符章节中 [29] c = a + b 后面为什么再加一行代码写个 c 运行后才会显示结果

### ISSUE THREAD

**Issue by blackoutwhb** [neolee/wop-community#99]
教材原文
![教材原文](https://user-images.githubusercontent.com/48622830/87219450-c3bd7580-c38d-11ea-8f8b-92c3a281e276.jpg)

在写作业中，尝试只写第一行代码:
c = a + b
运行后无结果，不显示36，是因为赋值语句结束后，不返回任何值么？必须另起一行额外写个c，运行才会显示当前c的值？

**Comment by neolee** [comment]
赋值语句 `c = a + b` 做的是“对 `a + b` 这个表达式求值并把求值结果赋给变量 c”，并没有任何输出显示的指令给到 Python 解释器。

如果你想显示出 c 的值，可以在后面加上 `print(c)`，这调用 Python 的内置函数 `print()` 来显示输出 c 的值。

至于直接写个 c 也显示了结果，这是 Jupyter Lab 提供的一种方便功能，就是显示出每个代码单元格最后一行代码的值（如果它可以被求值的话）。这个方法是偷懒的方法，而且这个偷懒仅限于 Jupyter Lab 或者在 Python 解释器的 REPL 里。如果你把这块代码保存到一个 .py 文件中，然后直接用 Python 去运行这个 .py 文件，你会发现没有显示输出。所以我在课上讲，如果你要显示什么，最好还是自己写 `print()`。

p.s. 标题不要那么长，详细的表述尽量写在正文里。

**Comment by blackoutwhb** [comment]
答复很清晰，明白了，谢谢。
